Repository Talend/ui, pull requests merged in 2018-06, with the labels that each got.

#1409 chore: downgrade react-jsonschema-form to not use ajv
  packages/forms/package.json
  packages/forms/src/__snapshots__/Form.test.js.snap
  packages/forms/src/fields/ArrayField.js
  packages/forms/src/fields/ObjectField.js
  version.js
  yarn.lock
Labels: frontend, need review

#1407 feat(components): support custom content in CollapsiblePanel
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.snapshot.test.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.test.js
Labels: easy review, need review

#1411 feat(components): Add 'warning' status to Status/CollapsiblePanel
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/src/Status/Status.component.js
  packages/components/src/Status/Status.scss
  packages/components/stories/CollapsiblePanel.js
  packages/components/stories/Status.js
Labels: easy review, need review

#1412 New icon for empty characters into grid
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/empty-char.svg
Labels: easy review, need review

#1394 fix(Component/List): component objects item actions
  .travis/after_success_e2e.sh
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/Item.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/BreadcrumbTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/TableTest.java
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/stories/Breadcrumbs.js
  packages/components/stories/HeaderBar.js
  packages/components/stories/List.js
Labels: need review

#1380 chores(doc): change proposal for ActionDropdown
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.md
Labels: need review

#1416 feat(cmf): add cmf.collection.includes expression
  packages/cmf/__tests__/expressions/index.test.js
  packages/cmf/src/expressions/includes.js
  packages/cmf/src/expressions/index.js
  packages/cmf/src/expressions/index.md
Labels: need review

#1400 chore: make travis fail on mvn e2e test fail
  .travis.yml
  packages/components/e2e/component-objects/src/main/java/org/talend/component/AppHeaderBar.java
Labels: easy review, frontend, need review

#1415 feat(containers): custom sort for List's column
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleList.js
  packages/containers/src/List/List.md
  packages/containers/src/List/selector.js
Labels: need review

#1378 feat(component): Allow to pass an order on the list's columns
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/TableTest.java
  packages/components/src/List/List.md
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.test.js
  packages/components/stories/List.js
Labels: need review

#1379 feat(components): allow to hide a column on the list
  packages/components/src/List/List.md
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.test.js
  packages/components/stories/List.js
Labels: need review

#1420 fix(components): Handle available in List's dropdown button
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.test.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
Labels: need review

#1414 fix(component/MultiSelectTag): support titleMap
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js
  packages/forms/stories-core/json/fields/core-multiSelectTag.json
Labels: need review

#1395 feat(components/container): custom renderer for List column headers
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/TableTest.java
  packages/components/src/List/List.md
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.test.js
  packages/components/src/VirtualizedList/HeaderIcon/HeaderIcon.component.js
  packages/components/src/VirtualizedList/HeaderIcon/HeaderIcon.component.test.js
  packages/components/src/VirtualizedList/HeaderIcon/HeaderIcon.scss
  packages/components/src/VirtualizedList/HeaderIcon/__snapshots__/HeaderIcon.component.test.js.snap
  packages/components/src/VirtualizedList/HeaderIcon/index.js
  packages/components/src/VirtualizedList/index.js
  packages/components/src/VirtualizedList/utils/dictionary.js
  packages/components/stories/List.js
  packages/containers/examples/ExampleList.js
  packages/containers/src/List/List.container.js
Labels: need review

#1421 chore(eslint): babel-eslint 8.0.1 (was 8.0.2)
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/logging/package.json
  packages/sagas/package.json
  packages/scripts/package.json
  packages/storybook-cmf/package.json
  version.js
  yarn.lock
Labels: easy review, need review

#1424 fix(a11y): Buttons get :hover styles on :focus
  packages/theme/src/theme/_visual-helpers.scss
Labels: easy review, need review

#1418 fix(theme): closed dropdown menu don't take space anymore
  .prettierrc
  packages/theme/src/theme/_button-groups.scss
Labels: easy review, frontend, need review

#1425 feat(components/list): disable sort on column header
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.test.js
  packages/components/stories/List.js
Labels: easy review, need review

#1333 feat(components): Table
  packages/components/.storybook/preview-head.html
  packages/components/package.json
  packages/components/src/Draggable/DraggableComponent.js
  packages/components/src/Draggable/DraggableComponent.test.js
  packages/components/src/Draggable/__snapshots__/DraggableComponent.test.js.snap
  packages/components/src/Draggable/index.js
  packages/components/src/Table/Body/TableBody.js
  packages/components/src/Table/Body/TableBody.scss
  packages/components/src/Table/Cell/TableCell.js
  packages/components/src/Table/Cell/TableCell.test.js
  packages/components/src/Table/Cell/__snapshots__/TableCell.test.js.snap
  packages/components/src/Table/Header/TableHeader.js
  packages/components/src/Table/Header/TableHeader.scss
  packages/components/src/Table/Header/TableHeaderCell.js
  packages/components/src/Table/Row/TableRow.js
  packages/components/src/Table/Row/TableRow.scss
  packages/components/src/Table/Row/TableRow.test.js
  packages/components/src/Table/Row/__snapshots__/TableRow.test.js.snap
  packages/components/src/Table/Table.js
  packages/components/src/Table/Table.scss
  packages/components/src/Table/Table.test.js
  packages/components/src/Table/TestData.js
  packages/components/src/Table/__snapshots__/Table.test.js.snap
  packages/components/src/Table/index.js
  packages/components/src/index.js
  packages/components/stories/Table.js
  packages/components/stories/index.js
  yarn.lock
Labels: need review

#1399 feat(Component/List): display 3 icons as title actions in Table display
  output/components.eslint.txt
  output/theme.sasslint.txt
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/Item.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/LargeTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/TableTest.java
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.test.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
  packages/components/stories/List.js
  packages/components/stories/VirtualizedList.js
  packages/theme/src/theme/_dropdowns.scss
  yarn.lock
Labels: need review

#1422 feat(cmf): extract i18n from many folders
  packages/cmf/scripts/cmf-settings.i18n.js
  packages/cmf/scripts/cmf-settings.i18n.test.js
  packages/cmf/scripts/cmf-settings.merge.js
  packages/cmf/scripts/index.md
Labels: enhancement, need review

#1427 fix(cmf/sagas): http response could not have headers
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
  test-setup.js
Labels: easy review, need review

#1430 fix(components/typeahead): add plain text classnames
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
Labels: easy review, enhancement, frontend, need review

#1435 feat(ObjectViewer): add support for injecting element next to item
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.test.js
  packages/components/stories/ObjectViewer.js
Labels: need review

#1432 fix(theme): remove dropdown max height
  packages/theme/src/theme/_navbar.dropdown.scss
Labels: easy review, need review

#1437 feat(datagrid): remove the global flag when using test
  packages/datagrid/src/components/DefaultCellRenderer/FormatValue.component.js
  packages/datagrid/src/components/DefaultCellRenderer/FormatValue.test.js
Labels: bug, need review

#1434 fix(HeaderBar): buttons and link content placement
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
  packages/components/src/Enumeration/Header/__snapshots__/header.snapshot.test.js.snap
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/theme/src/theme/_navbar.scss
Labels: easy review, frontend, need review

#1293 feat(cmf/TUI-113): make cmf a framework
  packages/cmf/__tests__/assert.test.js
  packages/cmf/__tests__/bootstrap.test.js
  packages/cmf/__tests__/register.test.js
  packages/cmf/package.json
  packages/cmf/src/assert.js
  packages/cmf/src/bootstrap.js
  packages/cmf/src/bootstrap.md
  packages/cmf/src/index.js
  packages/cmf/src/register.js
  packages/generator/generators/react-cmf/templates/src/app/actions/index.js
  packages/generator/generators/react-cmf/templates/src/app/components/App/App.container.test.js
  packages/generator/generators/react-cmf/templates/src/app/components/index.js
  packages/generator/generators/react-cmf/templates/src/app/configure.js
  packages/generator/generators/react-cmf/templates/src/app/index.js
  version.js
  yarn.lock
Labels: need review

#1443 fix(forms/ColumnsWidget): change how onColumnChange scope is handled
  output/forms.eslint.txt
  packages/forms/src/widgets/ColumnsWidget/ColumnsWidget.js
Labels: need review

#1438 fix(TUI-155/forms): add getComponent support
  packages/containers/examples/ExampleForm.js
  packages/containers/examples/index.js
  packages/containers/src/Form/Form.container.js
  packages/containers/src/Form/__snapshots__/Form.test.js.snap
  packages/forms/src/Form.js
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
  packages/forms/src/UIForm/fields/Button/Buttons.component.js
  packages/forms/src/UIForm/fields/Button/SingleButton.component.js
  packages/forms/src/UIForm/fields/Button/__snapshots__/Buttons.component.test.js.snap
Labels: need review

#1445 chore(travis): avoid 2 heavy yarn install
  .travis.yml
Labels: easy review, frontend, need review

#1439 fix(Component/SidePanel): use flex instead of inline-flex
  packages/components/src/SidePanel/SidePanel.scss
Labels: easy review, frontend, need review

#1447 chore(components/treeview): add story with noheader
  packages/components/stories/TreeView.js
Labels: easy review, enhancement, frontend, need review

#1436 feat(cmf): currying some functions where it is usefull
  packages/cmf/howto/how-to-manage-collections.md
  packages/cmf/src/actions/collectionsActions.js
  packages/cmf/src/actions/componentsActions.js
Labels: easy review, enhancement, need review

#1453 feat(icons): Talend API Tester and Designer logos
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/api-designer-colored.svg
  packages/icons/src/svg/api-designer-negative.svg
  packages/icons/src/svg/api-designer-positive.svg
  packages/icons/src/svg/api-tester-colored.svg
  packages/icons/src/svg/api-tester-negative.svg
  packages/icons/src/svg/api-tester-positive.svg
Labels: easy review, need review

#1456 chore: rename scripts to codemodes
  codemodes/cmf/README.md
  codemodes/cmf/api_to_index.js
  codemodes/cmf/componentState_to_cmfConnect.js
  codemodes/cmf/package.json
  codemodes/cmf/yarn.lock
  codemodes/migrate_actions_settings_expressions.js
  codemodes/talend-ui-imports/codemod.js
  codemodes/talend-ui-imports/replace-imports.sh
Labels: easy review, need review

#1452 fix(theme): a11y - dropdown outline
  output/theme.sasslint.txt
  packages/theme/src/theme/_dropdowns.scss
Labels: easy review, frontend, need review

#1457 fix(theme/navbar): buttons line-height
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/theme/example/index.html
  packages/theme/src/theme/_navbar.button.scss
  packages/theme/src/theme/_navbar.scss
Labels: easy review, need review

#1455 chore: fix versions
  packages/cmf-cqrs/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/icons/package.json
  packages/sagas/package.json
  packages/theme/package.json
  version.js
  yarn.lock
Labels: easy review, frontend, need review

#1458 feat(Checkbox): improve a11y with outline
  output/theme.sasslint.txt
  packages/components/stories/Checkbox.js
  packages/theme/src/theme/_forms.scss
Labels: easy review, frontend, need review

#1459 fix(forms): prevent error when quickly add values
  packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js
Labels: need review

#1376 fix(theme): align buttons height
  packages/components/src/ActionBar/__snapshots__/ActionBar.snapshot.test.js.snap
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/Badge/__snapshots__/Badge.snap.test.js.snap
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/Enumeration/Enumeration.scss
  packages/components/src/Enumeration/Items/Item/Item.scss
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/Header.snapshot.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/headerInput.snapshot.test.js.snap
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/Notification/__snapshots__/Notification.snap.test.js.snap
  packages/components/src/PieChartButton/PieChartButton.component.js
  packages/components/src/PieChartButton/__snapshots__/PieChartButton.test.js.snap
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss
  packages/components/src/TreeView/TreeView.scss
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.scss
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/components/src/VirtualizedList/CellTextIcon/CellWithIcon.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/VirtualizedList.scss
  packages/components/stories/ActionFile.js
  packages/components/stories/ActionIconToggle.js
  packages/containers/src/ActionFile/__snapshots__/ActionFile.test.js.snap
  packages/forms/src/UIForm/fields/ListView/__snapshots__/ListView.component.test.js.snap
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/theme/example/index.html
  packages/theme/src/theme/_breadcrumbs.scss
  packages/theme/src/theme/_buttons.scss
  packages/theme/src/theme/_navbar.button.scss
  packages/theme/src/theme/_navs.scss
  packages/theme/src/theme/_variables.scss
Labels: frontend, need review

#1419 feat(components): Drawer - manage footer according to the tab selected
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.test.js
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/components/stories/Drawer.js
Labels: need review

#1467 feat(JSONSchemaRenderer): improve a11y
  output/components.eslint.txt
  packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.component.js
  packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.scss
  packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.test.js
  packages/components/src/JSONSchemaRenderer/__snapshots__/JSONSchemaRenderer.test.js.snap
Labels: frontend, need review

#1464 feat(HeaderBar): improve a11y
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
Labels: easy review, frontend, need review

#1465 feat(components/Layout): add inject support
  packages/components/src/Inject/Inject.component.js
  packages/components/src/Inject/Inject.md
  packages/components/src/Inject/Inject.test.js
  packages/components/src/Layout/Layout.component.js
  packages/components/src/Layout/Layout.md
  packages/components/src/Layout/Layout.test.js
  packages/components/src/Layout/OneColumn/OneColumn.test.js
  packages/components/src/Layout/OneColumn/__snapshots__/OneColumn.test.js.snap
  packages/components/src/Layout/TwoColumns/TwoColumns.component.js
  packages/components/src/Layout/TwoColumns/TwoColumns.test.js
  packages/components/src/Layout/TwoColumns/__snapshots__/TwoColumns.test.js.snap
  packages/components/src/Layout/__snapshots__/Layout.test.js.snap
  packages/containers/examples/ExampleLayout.js
  packages/containers/examples/index.js
  packages/containers/src/index.js
  test-setup.js
Labels: need review

#1472 fix(theme): navbar buttons height
  packages/theme/src/theme/_navbar.button.scss
Labels: easy review, frontend, need review

#1473 fix(FilterBar): remove button height
  packages/components/src/FilterBar/FilterBar.scss
Labels: easy review, frontend, need review

#1477 test: fix Inject tests
  packages/components/src/Inject/Inject.component.js
  packages/components/src/Inject/Inject.md
  packages/components/src/Inject/Inject.test.js
Labels: need review

#1479 fix(datagrid): error when the value is null
  packages/datagrid/src/components/DefaultCellRenderer/FormatValue.component.js
  packages/datagrid/src/components/DefaultCellRenderer/FormatValue.test.js
Labels: bug, need review

#1480 fix(UIForms): propagate form-context to child widgets
  packages/forms/src/widgets/CodeWidget/CodeWidget.component.js
  packages/forms/src/widgets/CodeWidget/CodeWidget.test.js
  packages/forms/stories-core/json/fields/core-code.json
Labels: easy review, need review

#1474 fix(Pagination): align elements
  packages/components/src/List/Toolbar/Pagination/Pagination.component.js
  packages/components/src/List/Toolbar/Pagination/Pagination.scss
  packages/components/src/List/Toolbar/Pagination/__snapshots__/Pagination.snapshot.test.js.snap
  packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
Labels: easy review, frontend, need review

#1481 fix(theme): overflow wrap the tooltip
  packages/datagrid/stories/datagrid.component.js
  packages/theme/example/index.html
  packages/theme/src/theme/_tooltip.scss
  packages/theme/src/theme/theme.scss
Labels: bug, easy review, need review

#1461 chore(Enumeration): disabling enumeration
  packages/components/src/Enumeration/Header/Header.component.js
  packages/components/src/Enumeration/Header/HeaderInput.component.js
  packages/components/src/Enumeration/Header/HeaderSelected.component.js
  packages/components/src/Enumeration/Header/header.test.js
  packages/components/src/Enumeration/Header/headerInput.test.js
  packages/components/src/Enumeration/Header/headerSelected.test.js
  packages/components/src/Enumeration/Items/Item/Item.component.js
  packages/components/src/Enumeration/Items/Item/Item.test.js
  packages/components/stories/Enumeration.js
  packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js
  packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.test.js
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/stories/json/enumerationDisabled.json
Labels: easy review, need review

#1486 fix(cmf):handleDefaultHttpConfiguration
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
Labels: need review

#1482 chore: eslint config module
  packages/eslint-config/.eslintrc.json
  packages/eslint-config/README.md
  packages/eslint-config/api-app-angular.yaml
  packages/eslint-config/api-app-react.yaml
  packages/eslint-config/api-app.yaml
  packages/eslint-config/api-packaging.yaml
  packages/eslint-config/api-test-e2e.yaml
  packages/eslint-config/api-test.yaml
  packages/eslint-config/api/eslintrc.base.yaml
  packages/eslint-config/index.js
  packages/eslint-config/package.json
Labels: easy review, frontend, need review

#1463 feat(notification): notification list handled even if Notification component is not mounted
  packages/containers/src/Notification/Notification.test.js
  packages/containers/src/Notification/pushNotification.js
Labels: enhancement, need review

#1446 chore(components/treeview): remove deprecated code
  packages/components/src/TreeView/TreeView.component.js
  packages/components/stories/TreeView.js
Labels: easy review, frontend, need review

#1460 chores(version.js): add documation to help for future maintenance and rewrite
  version.js
Labels: need review

#1475 feat(icon): badge outline
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/badge-outline.svg
Labels: easy review, need review

#1451 feat(FilterBar): improve a11y
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/FilterBar/__snapshots__/FilterBar.snapshot.test.js.snap
  packages/components/stories/FilterBar.js
Labels: easy review, frontend, need review

#1476 feat(uiform) : add a customFormat for Git url and fix others
  packages/forms/src/UIForm/customFormats.js
  packages/forms/src/UIForm/customFormats.test.js
Labels: need review

#1478 feat(components): hide tooltip between mouseDown & mouseUp
  packages/components/src/TooltipTrigger/TooltipTrigger.component.js
  packages/components/src/TooltipTrigger/__snapshots__/TooltipTrigger.test.js.snap
Labels: frontend, need review

#1492 feat(configurations): add actor to codecept globals
  packages/eslint-config/README.md
  packages/eslint-config/api-test-e2e.yaml
  packages/eslint-config/api-test-jasmine.yaml
  packages/eslint-config/api-test.yaml
  packages/eslint-config/package.json
Labels: easy review, need review

#1498 fix(uiform): customFormat git for https and ssh url
  packages/forms/src/UIForm/customFormats.js
  packages/forms/src/UIForm/customFormats.test.js
Labels: need review
