Repository Talend/ui, pull requests merged in 2018-07, with the labels that each got.

#1501 feat(frontend): icon append to enumeration item
  packages/components/src/Enumeration/Items/Item/Item.component.js
  packages/components/src/Enumeration/Items/Item/Item.propTypes.js
  packages/components/src/Enumeration/Items/Item/Item.test.js
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/components/stories/Enumeration.js
  packages/icons/src/svg/badge-outline.svg
  packages/icons/src/svg/character.svg
  packages/icons/src/svg/word.svg
Labels: need review

#1489 feat(Containers): HeaderBar container
  packages/containers/examples/ExampleHeaderBar.js
  packages/containers/examples/index.js
  packages/containers/src/HeaderBar/HeaderBar.connect.js
  packages/containers/src/HeaderBar/HeaderBar.constant.js
  packages/containers/src/HeaderBar/HeaderBar.container.js
  packages/containers/src/HeaderBar/HeaderBar.md
  packages/containers/src/HeaderBar/HeaderBar.sagas.js
  packages/containers/src/HeaderBar/HeaderBar.sagas.test.js
  packages/containers/src/HeaderBar/HeaderBar.test.js
  packages/containers/src/HeaderBar/__snapshots__/HeaderBar.test.js.snap
  packages/containers/src/HeaderBar/index.js
  packages/containers/src/index.js
Labels: need review

#1506 feat(components/SubHeaderBar): make the title/left part extend to full width when no center/right actions
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss
  packages/components/src/SubHeaderBar/SubHeaderBar.scss
Labels: easy review, need review

#1507 fix(theme): align left the tooltip
  packages/theme/src/theme/_tooltip.scss
Labels: bug, need review

#1509 fix(forms): customFormat: make optional .git for all type of git url
  packages/forms/src/UIForm/customFormats.js
  packages/forms/src/UIForm/customFormats.test.js
Labels: need review

#1490 feat(Containers): Sandbox app
  packages/containers/.npmignore
  packages/containers/sandbox/.babelrc
  packages/containers/sandbox/.editorconfig
  packages/containers/sandbox/.gitignore
  packages/containers/sandbox/README.md
  packages/containers/sandbox/mockBackend/mock/header-bar/products-list.json
  packages/containers/sandbox/mockBackend/server.js
  packages/containers/sandbox/package.json
  packages/containers/sandbox/src/app/actions/index.js
  packages/containers/sandbox/src/app/actions/redirect.js
  packages/containers/sandbox/src/app/components/App/App.container.js
  packages/containers/sandbox/src/app/components/App/index.js
  packages/containers/sandbox/src/app/components/Showcase/EmptyShowcase/EmptyShowcase.component.js
  packages/containers/sandbox/src/app/components/Showcase/EmptyShowcase/EmptyShowcase.scss
  packages/containers/sandbox/src/app/components/Showcase/EmptyShowcase/index.js
  packages/containers/sandbox/src/app/components/Showcase/Showcase.container.js
  packages/containers/sandbox/src/app/components/Showcase/Showcase.scss
  packages/containers/sandbox/src/app/components/Showcase/index.js
  packages/containers/sandbox/src/app/components/index.js
  packages/containers/sandbox/src/app/index.html
  packages/containers/sandbox/src/app/index.js
  packages/containers/sandbox/src/assets/settings.json
  packages/containers/sandbox/talend-scripts.json
  packages/containers/sandbox/webpack.config.dev.js
Labels: need review

#1510 fix(containers): fix load recursive HeaderBar
  packages/containers/src/HeaderBar/HeaderBar.container.js
  packages/containers/src/HeaderBar/HeaderBar.test.js
  packages/containers/src/HeaderBar/__snapshots__/HeaderBar.test.js.snap
Labels: bug, need review

#1408 chore(TUI-142/cmf): remove deprecated getCollection
  packages/cmf/README.md
  packages/cmf/__tests__/__snapshots__/cmfConnect.test.js.snap
  packages/cmf/src/cmfConnect.js
  packages/containers/src/Action/__snapshots__/Action.test.js.snap
  packages/containers/src/ActionBar/__snapshots__/ActionBar.test.js.snap
  packages/containers/src/Actions/__snapshots__/Actions.test.js.snap
Labels: need review

#1503 fix(cmf): cancel one saga
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/__tests__/sagas/component.test.js
  packages/cmf/package.json
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/sagas/component.js
  yarn.lock
Labels: bug, need review

#1515 chore: npm task failure fix on Windows
  package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
Labels: easy review, need review

#1517 feat(cmf): pass componentId in forked saga
  packages/cmf/__tests__/actions/saga.test.js
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/__tests__/sagas/component.test.js
  packages/cmf/src/actions/saga.js
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/cmfConnect.md
  packages/cmf/src/sagas/component.js
  packages/cmf/src/sagas/index.md
Labels: need review

#1516 feat(component): overlay always visible
  packages/components/package.json
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/components/src/OverlayTrigger/OverlayTrigger.component.js
  packages/components/src/OverlayTrigger/OverlayTrigger.scss
  packages/components/src/OverlayTrigger/OverlayTrigger.test.js
  packages/components/src/OverlayTrigger/__snapshots__/OverlayTrigger.test.js.snap
  packages/components/src/OverlayTrigger/index.js
  packages/components/src/OverlayTrigger/overlay.js
  packages/components/src/OverlayTrigger/overlay.test.js
  packages/components/stories/Action.js
  packages/components/stories/Action.scss
  packages/components/stories/List.js
  packages/datagrid/package.json
  packages/generator/generators/react-cmf/templates/package.json
  version.js
  yarn.lock
Labels: enhancement, need review, work in progress

#1521 fix: make Talend/scripts use react 16 for tests
  packages/generator/generators/react-cmf/templates/package.json
  packages/scripts/package.json
  packages/scripts/preset/config/test/test-setup.js
Labels: easy review, frontend, need review

#1524 fix(cmf): Inject log error #1301
  packages/cmf/src/Inject.component.js
Labels: need review

#1526 feat(containers/treeview): unfold selected's parents
  packages/containers/examples/ExampleTreeView.js
  packages/containers/src/TreeView/TreeView.container.js
  packages/containers/src/TreeView/TreeView.test.js
  packages/containers/src/TreeView/__snapshots__/TreeView.test.js.snap
Labels: easy review, enhancement, need review

#1513 fix(sandbox): imports cleanup
  packages/containers/sandbox/package.json
  packages/containers/sandbox/src/app/components/Showcase/Showcase.container.js
  packages/containers/sandbox/src/app/index.js
  packages/containers/sandbox/src/assets/settings.json
  packages/containers/sandbox/webpack.config.dev.js
  packages/containers/src/HeaderBar/HeaderBar.container.js
Labels: bug, need review

#1527 feat(components): Allow rel prop
  packages/components/src/utils/getPropsFrom.js
  packages/components/src/utils/getPropsFrom.test.js
Labels: easy review, need review

#1519 fix(components): Show percentage when piechart value is at 0%
  packages/components/src/PieChartButton/PieChartButton.component.js
  packages/components/src/PieChartButton/PieChartButton.test.js
  packages/components/src/PieChartButton/__snapshots__/PieChartButton.test.js.snap
  packages/components/stories/PieChartButton.js
  packages/containers/src/PieChartButton/__snapshots__/PieChartButton.test.js.snap
Labels: need review

#1511 fix(datagrid): fix quality with the new payload
  packages/datagrid/src/components/DataGrid/DataGrid.test.js
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
Labels: easy review, need review

#1528 chore(Component/Typeahead): hide section header when there's no label/icon
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.test.js
  packages/components/stories/Typeahead.js
Labels: easy review, need review

#1536 feat(cmf/expressions): add oneOf expression
  packages/cmf/__tests__/expressions/index.test.js
  packages/cmf/src/expressions/index.js
  packages/cmf/src/expressions/index.md
  packages/cmf/src/expressions/oneOf.js
Labels: easy review, need review

#1535 feat(containers): allow AppLoader to call sagas
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleAppLoader.js
  packages/containers/src/AppLoader/AppLoader.md
  packages/containers/src/AppLoader/AppLoader.saga.js
  packages/containers/src/AppLoader/AppLoader.saga.test.js
Labels: need review

#1469 feat(theme): inverse buttons
  output/theme.sasslint.txt
  packages/components/src/Enumeration/Enumeration.scss
  packages/components/src/Enumeration/Items/Item/Item.component.js
  packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap
  packages/components/stories/Action.js
  packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.test.js
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/theme/example/index.html
  packages/theme/src/theme/_button-groups.scss
  packages/theme/src/theme/_buttons.scss
  packages/theme/src/theme/_dropdowns.scss
  packages/theme/src/theme/_guidelines.scss
  packages/theme/src/theme/_variables.scss
  packages/theme/src/theme/_visual-helpers.scss
Labels: frontend, need review

#1518 fix(containers/DeleteResource): fix redirect saga, etc
  packages/containers/src/DeleteResource/DeleteResource.connect.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/README.md
  packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap
  packages/containers/src/DeleteResource/sagas.js
  packages/containers/src/DeleteResource/sagas.test.js
Labels: need review

#1520 fix(components): support ActionButton with overlay in the list
  output/components.eslint.txt
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/ActionButton.test.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
  packages/components/src/OverlayTrigger/OverlayTrigger.component.js
  packages/components/src/OverlayTrigger/__snapshots__/OverlayTrigger.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitle.test.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.test.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitle.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/index.js
  packages/components/src/VirtualizedList/RowLarge/__snapshots__/RowLarge.test.js.snap
  packages/components/src/VirtualizedList/utils/gridrow.js
  packages/components/src/VirtualizedList/utils/gridrow.test.js
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleAction.js
  packages/containers/src/ActionButton/ActionButton.connect.js
  packages/containers/src/ActionButton/ActionButton.test.js
  packages/containers/src/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/containers/src/List/List.container.js
  packages/containers/src/List/List.test.js
  packages/containers/src/List/__snapshots__/List.test.js.snap
Labels: enhancement, need review

#1539 fix(kit): move react from deps to peer
  packages/components-kit/package.json
Labels: easy review, need review

#1533 feat(icon): chart
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/charts.svg
Labels: easy review, need review

#1531 feat(icons): tags
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/tags.svg
Labels: easy review, need review

#1532 feat(icons): update clock
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/clock.svg
Labels: easy review, need review

#1534 feat(UIForm): migrate Code widget
  packages/forms/src/UIForm/fields/Code/Code.component.js
  packages/forms/src/UIForm/fields/Code/Code.component.test.js
  packages/forms/src/UIForm/fields/Code/README.md
  packages/forms/src/UIForm/fields/Code/__snapshots__/Code.component.test.js.snap
  packages/forms/src/UIForm/fields/Code/index.js
  packages/forms/src/UIForm/fields/Code/screenshot.gif
  packages/forms/src/UIForm/utils/widgets.js
  packages/forms/stories-core/json/fields/core-code.json
Labels: frontend, need review

#1544 fix(cmf): cancel a saga on a component unmount
  packages/cmf/__tests__/sagas/component.test.js
  packages/cmf/src/sagas/component.js
Labels: need review

#1494 feat(Datalist): add loading and trigger support
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/src/Datalist/Datalist.scss
  packages/components/src/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.scss
  packages/components/src/Typeahead/Typeahead.snapshot.test.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/components/stories/Datalist.js
  packages/containers/src/Typeahead/__snapshots__/Typeahead.test.js.snap
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js
  packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap
  packages/forms/src/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
  packages/forms/stories-core/index.js
  packages/forms/stories-core/json/fields/core-datalist.json
  packages/forms/stories-core/jsonStories.js
Labels: need review

#1548 chore: remove surge from travis
  .travis.yml
Labels: easy review, need review

#1549 Revert "chore: remove surge from travis (#1548)"
  .travis.yml
Labels: easy review, frontend, need review

#1543 fix(theme): css caret
  output/theme.sasslint.txt
  packages/components/stories/Toggle.js
  packages/theme/src/theme/_button-groups.scss
  packages/theme/src/theme/_buttons.scss
  packages/theme/src/theme/_dropdowns.scss
  packages/theme/src/theme/_navbar.dropdown.scss
  packages/theme/src/theme/_navs.dropdown.scss
  packages/theme/src/theme/_variables.scss
  packages/theme/src/theme/_visual-helpers.scss
  packages/theme/src/theme/theme.scss
Labels: easy review, frontend, need review

#1522 feat(form): display UIForm in drawer
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.scss
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
  packages/forms/stories-core/index.js
  packages/forms/stories-core/layouts.js
Labels: need review

#1497 feat(Layout): improve a11y
  packages/components/src/Layout/OneColumn/OneColumn.component.js
  packages/components/src/Layout/OneColumn/__snapshots__/OneColumn.test.js.snap
  packages/components/src/Layout/TwoColumns/TwoColumns.component.js
  packages/components/src/Layout/TwoColumns/__snapshots__/TwoColumns.test.js.snap
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
Labels: easy review, frontend, need review

#1500 feat(List/Toolbar): improve a11y
  packages/components/src/List/Toolbar/Pagination/Pagination.component.js
  packages/components/src/List/Toolbar/Pagination/__snapshots__/Pagination.snapshot.test.js.snap
  packages/components/src/List/Toolbar/SelectDisplayMode/SelectDisplayMode.component.js
  packages/components/src/List/Toolbar/SelectDisplayMode/__snapshots__/SelectDisplayMode.test.js.snap
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js
  packages/components/src/List/Toolbar/SelectSortBy/__snapshots__/SelectSortBy.test.js.snap
  packages/components/src/List/Toolbar/Toolbar.component.js
  packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
Labels: easy review, frontend, need review

#1550 feat(forms): add loading skeleton
  packages/components-kit/src/components/ComponentForm/ComponentForm.component.js
  packages/components/src/Skeleton/Skeleton.component.js
  packages/components/src/Skeleton/Skeleton.scss
  packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
  packages/containers/src/Form/__snapshots__/Form.test.js.snap
  packages/forms/package.json
  packages/forms/src/Form.js
  packages/forms/src/Form.test.js
  packages/forms/src/FormSkeleton.js
  packages/forms/src/FormSkeleton.scss
  packages/forms/src/FormSwitcher.js
  packages/forms/src/FormSwitcher.test.js
  packages/forms/src/__snapshots__/Form.test.js.snap
  packages/forms/src/index.js
  packages/forms/stories-core/layouts.js
Labels: need review

#1540 feat(components/HttpError): add go back link
  packages/components/src/HttpError/HttpError.component.js
  packages/components/src/HttpError/HttpError.scss
  packages/components/src/HttpError/HttpError.snapshot.test.js
  packages/components/src/HttpError/__snapshots__/HttpError.snapshot.test.js.snap
  packages/components/stories/HttpError.js
Labels: need review

#1553 fix(components): Add actionFile shadow and hover effects
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/Actions/ActionFile/ActionFile.scss
  packages/components/src/Actions/ActionFile/__snapshots__/ActionFile.test.js.snap
  packages/containers/src/ActionFile/__snapshots__/ActionFile.test.js.snap
Labels: easy review, need review

#1542 feat(Components-kit): add async datalist case
  packages/components-kit/mock/asyncDatalist.json
  packages/components-kit/package.json
  packages/components-kit/src/assets/settings.json
  packages/components-kit/src/components/ComponentForm/ComponentForm.component.js
  packages/components-kit/src/components/ComponentForm/__snapshots__/ComponentForm.test.js.snap
  packages/components-kit/src/components/ComponentForm/fields/Datalist/Datalist.component.js
  packages/components-kit/src/components/ComponentForm/fields/Datalist/Datalist.component.test.js
  packages/components-kit/src/components/ComponentForm/fields/Datalist/index.js
  packages/components-kit/src/components/ComponentForm/fields/index.js
  packages/components-kit/webpack.config.dev.js
Labels: frontend, need review

#1547 feat(components): implement RichTooltip
  output/components.eslint.txt
  packages/components/src/HeaderTitle/HeaderTitle.component.js
  packages/components/src/HeaderTitle/HeaderTitle.component.test.js
  packages/components/src/HeaderTitle/HeaderTitle.scss
  packages/components/src/HeaderTitle/__snapshots__/HeaderTitle.component.test.js.snap
  packages/components/src/HeaderTitle/index.js
  packages/components/src/RichError/RichError.component.js
  packages/components/src/RichError/RichError.component.test.js
  packages/components/src/RichError/RichError.scss
  packages/components/src/RichError/__snapshots__/RichError.component.test.js.snap
  packages/components/src/RichError/index.js
  packages/components/src/RichTooltip/RichTooltip.component.js
  packages/components/src/RichTooltip/RichTooltip.scss
  packages/components/src/RichTooltip/RichTooltip.test.js
  packages/components/src/RichTooltip/__snapshots__/RichTooltip.test.js.snap
  packages/components/src/RichTooltip/index.js
  packages/components/src/index.js
  packages/components/stories/RichTooltip.js
  packages/components/stories/index.js
Labels: need review

#1557 fix(datagrid): restore storybook
  packages/datagrid/stories/sample.json
  packages/datagrid/stories/sample2.json
  packages/datagrid/stories/sample3.json
Labels: bug, easy review, need review

#1561 chore(components/breadcrumb): a11y
  packages/components/src/Breadcrumbs/Breadcrumbs.component.js
  packages/components/src/Breadcrumbs/__snapshots__/Breadcrumbs.snapshot.test.js.snap
Labels: easy review, enhancement, need review

#1562 fix(List): input size optimisation
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleInput.component.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleInput.test.js.snap
Labels: easy review, frontend, need review

#1566 fix(AppLoader): wrong a11y attributes
  packages/components/src/AppLoader/AppLoader.component.js
  packages/components/src/AppLoader/__snapshots__/AppLoader.test.js.snap
  packages/components/src/AppLoader/constant.js
Labels: easy review, frontend, need review

#1564 feat(ActionsButton/ActionIconToggle): add aria attributes
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
  packages/components/src/Actions/ActionIconToggle/__snapshots__/ActionIconToggle.component.test.js.snap
Labels: easy review, frontend, need review

#1568 feat(Dialog): improve a11y
  packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
  packages/components/src/Dialog/Dialog.component.js
  packages/components/src/Dialog/__snapshots__/Dialog.test.js.snap
Labels: easy review, frontend, need review

#1563 fix(quality): apply dove-gray on empty quality
  packages/components/src/PieChartButton/PieChartButton.component.js
  packages/components/src/PieChartButton/PieChartButton.scss
  packages/components/stories/PieChartButton.js
  packages/containers/examples/ExamplePieChartButton.js
  packages/theme/src/theme/_datagrid.scss
Labels: easy review, need review

#1556 fix(ui): Fix some warning in the console
  packages/cmf/src/cmfConnect.js
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/containers/src/AppLoader/AppLoader.connect.js
Labels: easy review, enhancement, need review

#1572 fix(datagrid): fix redrawsRows when the datagrid is not showed
  packages/datagrid/README.md
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js
  packages/datagrid/src/components/DataGrid/DataGrid.test.js
  packages/datagrid/stories/datagrid.component.js
Labels: bug, need review

#1569 feat(Search): improve a11y
  output/components.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/FilterBar/__snapshots__/FilterBar.snapshot.test.js.snap
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/Table/Filters/__snapshots__/FiltersBar.test.js.snap
  packages/components/src/Table/TitleBar/__snapshots__/TitleBar.test.js.snap
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.snapshot.test.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/components/stories/Typeahead.js
  packages/theme/src/theme/_navbar.scss
  packages/theme/src/theme/_navbar.search.scss
Labels: frontend, need review

#1570 feat(Progress): improve a11y
  packages/components/src/ConfirmDialog/ConfirmDialog.component.js
  packages/components/src/ConfirmDialog/ConfirmDialog.test.js
  packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
  packages/components/src/Progress/Progress.component.js
  packages/components/src/Progress/Progress.test.js
  packages/components/src/Progress/__snapshots__/Progress.test.js.snap
  packages/components/stories/Progress.js
Labels: easy review, frontend, need review

#1571 feat(Table): improve a11y
  packages/components/src/Table/Header/TableHeader.js
  packages/components/src/Table/Header/__snapshots__/TableHeader.test.js.snap
  packages/components/src/Table/Row/TableRow.js
  packages/components/src/Table/Row/__snapshots__/TableRow.test.js.snap
  packages/components/src/Table/Table.js
  packages/components/src/Table/TestData.js
  packages/components/src/Table/__snapshots__/Table.test.js.snap
  packages/components/stories/Table.js
Labels: easy review, frontend, need review

#1575 fix(List): cell title dropdown position
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
Labels: easy review, frontend, need review

#1555 feat(ComponentForm): add submit url + mv kit into containers
  output/containers.eslint.txt
  packages/cmf/src/sagas/http.js
  packages/components-kit/.babelrc
  packages/components-kit/.gitignore
  packages/components-kit/.npmignore
  packages/components-kit/README.md
  packages/components-kit/mock/basic.json
  packages/components-kit/mock/components.json
  packages/components-kit/mock/servicenow.json
  packages/components-kit/package.json
  packages/components-kit/src/app/index.html
  packages/components-kit/src/app/index.js
  packages/components-kit/src/app/index.scss
  packages/components-kit/src/assets/settings.json
  packages/components-kit/src/components/index.js
  packages/components-kit/talend-scripts.json
  packages/containers/package.json
  packages/containers/sandbox/README.md
  packages/containers/sandbox/mockBackend/jsonForward.js
  packages/containers/sandbox/mockBackend/kit.js
  packages/containers/sandbox/mockBackend/mock/kit/example.json
  packages/containers/sandbox/mockBackend/server.js
  packages/containers/sandbox/src/app/components/App/App.container.js
  packages/containers/sandbox/src/app/components/App/index.js
  packages/containers/sandbox/src/app/components/Showcase/EmptyShowcase/EmptyShowcase.component.js
  packages/containers/sandbox/src/app/components/Showcase/EmptyShowcase/EmptyShowcase.scss
  packages/containers/sandbox/src/app/components/Showcase/EmptyShowcase/index.js
  packages/containers/sandbox/src/app/components/Showcase/Showcase.container.js
  packages/containers/sandbox/src/app/components/Showcase/Showcase.scss
  packages/containers/sandbox/src/app/components/Showcase/index.js
  packages/containers/sandbox/src/app/components/index.js
  packages/containers/sandbox/src/app/index.js
  packages/containers/sandbox/src/assets/settings.json
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.md
  packages/containers/src/ComponentForm/ComponentForm.saga.test.js
  packages/containers/src/ComponentForm/ComponentForm.sagas.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
  packages/containers/src/ComponentForm/ComponentForm.test.schema.json
  packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap
  packages/containers/src/ComponentForm/fields/Datalist/Datalist.component.js
  packages/containers/src/ComponentForm/fields/Datalist/Datalist.component.test.js
  packages/containers/src/ComponentForm/fields/Datalist/index.js
  packages/containers/src/ComponentForm/fields/index.js
  packages/containers/src/ComponentForm/index.js
  packages/containers/src/ComponentForm/kit/createTriggers.js
  packages/containers/src/ComponentForm/kit/createTriggers.test.js
  packages/containers/src/ComponentForm/kit/defaultRegistry.js
  packages/containers/src/ComponentForm/kit/defaultRegistry.test.js
  packages/containers/src/ComponentForm/kit/flatten.js
  packages/containers/src/ComponentForm/kit/flatten.test.js
  packages/containers/src/ComponentForm/kit/index.js
  version.js
  yarn.lock
Labels: need review

#1577 fix(Forms): FormSwitcher has the same api as underlying forms
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap
  packages/containers/src/Form/Form.test.js
  packages/forms/src/FormSwitcher.js
  packages/forms/src/FormSwitcher.test.js
Labels: frontend, need review
