Repository Talend/ui, pull requests merged in 2018-10, with the labels that each got.

#1718 feat(icon): column chooser
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/column-chooser.svg
Labels: easy review, need review

#1722 fix(components): tabBar with no children
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/components/stories/TabBar.js
Labels: easy review, need review

#1730 chore: fix react 15 build
  .travis.yml
Labels: need review

#1727 feat(TUI-199): add rowRenderers to the VirtualizedList
  packages/components/src/List/List.component.js
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
  packages/components/src/VirtualizedList/PropTypes.js
  packages/components/src/VirtualizedList/RendererSelector.component.js
  packages/components/src/VirtualizedList/RendererSelector.test.js
  packages/components/src/VirtualizedList/VirtualizedList.component.js
  packages/components/src/VirtualizedList/__snapshots__/VirtualizedList.test.js.snap
  packages/components/stories/List.js
  packages/components/stories/VirtualizedList.js
Labels: need review

#1729 doc: add versions precision in readme files
  README.md
  packages/cmf-cqrs/README.md
  packages/cmf-webpack-plugin/README.md
  packages/cmf/README.md
  packages/components/README.md
  packages/containers/README.md
  packages/forms/README.md
  packages/generator/README.md
  packages/icons/README.md
  packages/logging/README.md
  packages/sagas/README.md
  packages/theme/README.md
Labels: easy review, frontend, need review

#1733 chore: disable e2e tests
  .travis.yml
Labels: easy review, frontend, need review

#1732 fix(ComponentForm): extract complex items in trigger parameters
  output/containers.eslint.txt
  packages/containers/src/ComponentForm/kit/createTriggers.js
  packages/containers/src/ComponentForm/kit/createTriggers.test.js
  packages/containers/src/ComponentForm/kit/flatten.js
  packages/containers/src/ComponentForm/kit/flatten.test.js
Labels: frontend, need review

#1736 feat(icon): send
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/send.svg
Labels: easy review, need review

#1688 fix(components): new list style
  packages/components/src/List/List.scss
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/ListTable/ListTable.component.js
  packages/components/src/VirtualizedList/ListTable/ListTable.scss
  packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
  packages/components/src/VirtualizedList/_colors.scss
Labels: need review

#1739 fix(ComponentForm): flatten use option to include objects
  output/containers.eslint.txt
  packages/containers/src/ComponentForm/kit/createTriggers.js
  packages/containers/src/ComponentForm/kit/flatten.js
  packages/containers/src/ComponentForm/kit/flatten.test.js
Labels: easy review, frontend, need review

#1738 fix(TabBar): children from item definition are displayed again
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.test.js
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
Labels: easy review, frontend, need review

#1719 update(collapsiblePanel/TPSVC-6044): update by frontify guideline
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/src/CollapsiblePanel/CollapsiblePanel.snapshot.test.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.test.js
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/stories/CollapsiblePanel.js
Labels: need review

#1743 chore: add raf dependency and set in test-setup
  packages/scripts/package.json
  packages/scripts/preset/config/test/test-setup.js
Labels: easy review, need review

#1744 fix(Theme): button info color
  packages/theme/src/theme/_variables.scss
Labels: easy review, frontend, need review

#1745 feat(development): add mainSrc field in package.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/jsfc/package.json
  packages/logging/package.json
  packages/sagas/package.json
  packages/theme/package.json
Labels: need review

#1740 fix(component/actionicontoggle): dont change color on focus
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/column-chooser.svg
  packages/icons/src/svg/send.svg
Labels: bug, easy review, frontend, need review

#1750 chore(components/Inject.getReactElement): remove key warning
  packages/components/src/Inject/Inject.component.js
  packages/components/src/Inject/Inject.md
  packages/components/src/Inject/Inject.test.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
Labels: easy review, need review

#1753 test(components): revert snapshot introduced by #1740
  packages/components/package.json
  packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
Labels: easy review, need review

#1752 fix(TUI-204): remove bad use Action bsStyle
  packages/components/src/AboutDialog/AboutDialog.component.js
  packages/components/src/AboutDialog/__snapshots__/AboutDialog.snapshot.test.js.snap
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/stories/Action.js
  packages/components/stories/ActionFile.js
  packages/components/stories/Layout.js
  packages/components/stories/RichTooltip.js
Labels: easy review, need review

#1734 fix(datagrid): header is not white while column is selected
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.scss
Labels: easy review, need review

#1754 fix(components): bad display on actions hover on title
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
Labels: easy review, need review

#1731 feat(Components/Slider): Implement Action Icon
  packages/components/src/Slider/Slider.component.js
  packages/components/src/Slider/Slider.scss
  packages/components/src/Slider/Slider.snap.test.js
  packages/components/src/Slider/Slider.test.js
  packages/components/src/Slider/__snapshots__/Slider.snap.test.js.snap
  packages/components/src/Slider/__snapshots__/Slider.test.js.snap
  packages/components/stories/Slider.js
  packages/containers/examples/ExampleSlider.js
Labels: need review

#1723 feat: add possibility to pass custom button label in collapsible fieldset widget
  output/forms.eslint.txt
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/README.md
  packages/forms/src/UIForm/utils/condition.test.js
  packages/forms/stories-core/json/fieldsets/core-arrays-with-custom-options.json
Labels: easy review, need review

#1757 feat(icons): update table and expanded
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
  packages/icons/src/svg/expanded.svg
  packages/icons/src/svg/table.svg
Labels: easy review, need review

#1747 feat(icon): add quotes for query
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/quotes.svg
Labels: easy review, need review

#1742 fix(components): align dialog with guidelines
  packages/components/src/Dialog/Dialog.scss
Labels: easy review, need review

#1737 fix(icon): update sharing-owner and sharing-user icons
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/sharing-owner.svg
  packages/icons/src/svg/sharing-user.svg
Labels: easy review, need review

#1735 feat(icon): shared folder by someone & folder shared with someone
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/folder-shared-owner.svg
  packages/icons/src/svg/folder-shared-user.svg
Labels: easy review, need review

#1756 fix(List): removing hover style on actions on selected/active items
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js
  packages/components/src/VirtualizedList/ListGrid/__snapshots__/ListGrid.test.js.snap
  packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
  packages/components/src/VirtualizedList/RowSelection/RowSelection.scss
Labels: easy review, need review

#1760 fix(components): fix action bar padding
  packages/components/src/Dialog/Dialog.scss
Labels: bug, easy review, need review

#1763 fix(components/list): actions background on large display
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
  packages/components/stories/List.js
Labels: bug, easy review, frontend, need review

#1761 chore(Travis): restore ci and remove useless configuration
  .travis.yml
  .travis/before_install.sh
  README.md
  output/components.sasslint.txt
  output/containers.eslint.txt
Labels: easy review, need review

#1767 fix(theme/buttons): fix alignment issues
  packages/theme/src/theme/_visual-helpers.scss
Labels: bug, easy review, frontend, need review

#1769 fix(datagrid): null value in cell
  packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultValueRenderer.test.js.snap
  packages/datagrid/stories/sample.json
Labels: bug, need review

#1772 fix(components/progress): decrease infinite progress speed
  packages/components/src/Progress/Progress.scss
Labels: bug, easy review, need review

#1768 fix(components/typeahead): icon style
  output/components.sasslint.txt
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.scss
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultValueRenderer.test.js.snap
Labels: need review

#1778 fix(Container) HeaderBar component update
  packages/containers/src/HeaderBar/HeaderBar.actions.js
  packages/containers/src/HeaderBar/HeaderBar.container.js
Labels: frontend, need review

#1777 feat: skip links
  packages/components/src/Layout/Layout.component.js
  packages/components/src/Layout/Layout.scss
  packages/components/src/Layout/OneColumn/OneColumn.component.js
  packages/components/src/Layout/OneColumn/__snapshots__/OneColumn.test.js.snap
  packages/components/src/Layout/SkipLinks/SkipLinks.component.js
  packages/components/src/Layout/SkipLinks/SkipLinks.scss
  packages/components/src/Layout/SkipLinks/SkipLinks.test.js
  packages/components/src/Layout/SkipLinks/__snapshots__/SkipLinks.test.js.snap
  packages/components/src/Layout/SkipLinks/index.js
  packages/components/src/Layout/TwoColumns/TwoColumns.component.js
  packages/components/src/Layout/TwoColumns/__snapshots__/TwoColumns.test.js.snap
  packages/components/src/Layout/__snapshots__/Layout.test.js.snap
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
Labels: frontend, need review

#1764 fix(components/List): remove border on checkbox & uppercase on title
  packages/components/src/VirtualizedList/ListTable/ListTable.scss
Labels: easy review, need review

#1782 chore(tests): cross env unit test fix
  packages/components/package.json
  yarn.lock
Labels: easy review, need review

#1783 fix(components/SubHeader): Button text-transform
  packages/components/src/SubHeaderBar/SubHeaderBar.scss
Labels: easy review, need review

#1786 fix(containers): PropTypes for app switcher
  packages/containers/src/HeaderBar/HeaderBar.container.js
Labels: easy review, enhancement, need review

#1787 fix(components): App switcher should not display no options
  packages/components/src/HeaderBar/HeaderBar.component.js
Labels: easy review, need review

#1781 fix(components/ConfirmDialog): onHide called only if provided
  packages/components/src/ConfirmDialog/ConfirmDialog.component.js
Labels: easy review, need review

#1789 fix(cmf): cmfConnect with no param
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/src/cmfConnect.js
Labels: easy review, need review

#1784 feat(generator): improve component generator
  packages/generator/generators/react-component/index.js
  packages/generator/generators/react-component/templates/src/actions.js
  packages/generator/generators/react-component/templates/src/component.js
  packages/generator/generators/react-component/templates/src/component.test.js
  packages/generator/generators/react-component/templates/src/connect.component.js
  packages/generator/generators/react-component/templates/src/connect.js
  packages/generator/generators/react-component/templates/src/connect.test.js
  packages/generator/generators/react-component/templates/src/container.js
  packages/generator/generators/react-component/templates/src/container.test.js
  packages/generator/generators/react-component/templates/src/es6.class.component.js
  packages/generator/generators/react-component/templates/src/expressions.js
  packages/generator/generators/react-component/templates/src/full.connect.js
  packages/generator/generators/react-component/templates/src/full.container.js
  packages/generator/generators/react-component/templates/src/full.index.js
  packages/generator/generators/react-component/templates/src/full.test.js
  packages/generator/generators/react-component/templates/src/index.js
  packages/generator/generators/react-component/templates/src/sagas.js
  packages/generator/generators/react-component/templates/src/stateless.component.js
  packages/generator/test/react-component.js
Labels: need review

#1596 feat(cmf/TUI-279): add cmf.bootstrap modules support
  output/containers.eslint.txt
  packages/cmf-cqrs/README.md
  packages/cmf-cqrs/src/index.js
  packages/cmf/__tests__/bootstrap.test.js
  packages/cmf/__tests__/cmfModule.merge.test.js
  packages/cmf/__tests__/cmfModule.test.js
  packages/cmf/src/assert.js
  packages/cmf/src/bootstrap.js
  packages/cmf/src/bootstrap.md
  packages/cmf/src/cmfModule.js
  packages/cmf/src/cmfModule.merge.js
  packages/cmf/src/registry.js
  packages/containers/README.md
  packages/containers/sandbox/src/app/index.js
  packages/containers/src/containers.js
  packages/containers/src/index.js
  packages/containers/src/register.js
  packages/containers/src/register.test.js
Labels: need review

#1774 fix(components/DatePicker) Widget error handling with UIForm - poc2
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.md
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/forms/src/UIForm/fields/InputDateTimePicker/InputDateTimePicker.component.js
  packages/forms/src/UIForm/fields/InputDateTimePicker/InputDateTimePicker.test.js
  packages/forms/src/UIForm/fields/InputDateTimePicker/README.md
  packages/forms/src/UIForm/fields/InputDateTimePicker/WrongTypeError.js
  packages/forms/src/UIForm/fields/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/forms/src/UIForm/utils/validation.js
  packages/forms/src/UIForm/utils/validation.test.js
Labels: need review

#1771 feat(icon): update sharing-owner icon
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/sharing-owner.svg
Labels: easy review, need review

#1759 doc(cmf): add some diagrams
  packages/cmf/README.md
  packages/cmf/assets/diagram-bootstrap.svg
  packages/cmf/assets/diagram-bootstrap.xml
  packages/cmf/assets/diagram-cmfConnect.svg
  packages/cmf/assets/diagram-cmfConnect.xml
  packages/cmf/assets/diagram-code-orga.svg
  packages/cmf/assets/diagram-code-orga.xml
  packages/cmf/assets/diagram-react-redux-saga-rendering.xml
  packages/cmf/assets/diagram-rendering-cycle.svg
  packages/cmf/assets/diagram-rendering-cycle.xml
Labels: easy review, need review

#1793 fix(ComponentForm): fix linked saga
  packages/containers/src/ComponentForm/ComponentForm.saga.test.js
  packages/containers/src/ComponentForm/ComponentForm.sagas.js
Labels: bug, need review

#1790 fix(Layout): all warnings in the story
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleLayout.js
  packages/containers/src/index.js
  packages/storybook-cmf/src/CMFStory/CMFStory.component.js
Labels: easy review, need review

#1797 chore(components/ConfirmDialog): Unrequired props declaration
  packages/components/src/ConfirmDialog/ConfirmDialog.component.js
Labels: easy review, need review

#1798 chore(forms/Code): react-ace fallback warning on constructor
  packages/forms/src/UIForm/fields/Code/Code.component.js
Labels: easy review, need review
