Repository Talend/ui, pull requests merged in 2018-08, with the labels that each got.

#1584 feat(Container): Add a Breadcrumbs Container
  packages/containers/examples/ExampleBreadcrumbs.js
  packages/containers/examples/index.js
  packages/containers/src/Breadcrumbs/Breadcrumbs.connect.js
  packages/containers/src/Breadcrumbs/Breadcrumbs.test.js
  packages/containers/src/Breadcrumbs/index.js
  packages/containers/src/index.js
Labels: need review

#1529 feat(containers/selectobject): allow to filter on everything
  packages/containers/examples/ExampleSelectObject.js
  packages/containers/src/SelectObject/SelectObject.container.js
  packages/containers/src/SelectObject/SelectObject.test.js
Labels: enhancement, frontend, need review

#1585 fix(forms): display in dialog
  packages/components/src/Dialog/Dialog.component.js
  packages/components/src/Dialog/Dialog.scss
  packages/components/src/Dialog/Dialog.test.js
  packages/components/src/Dialog/__snapshots__/Dialog.test.js.snap
  packages/forms/src/UIForm/UIForm.scss
  packages/forms/stories-core/layouts.js
Labels: need review

#1582 fix(components): support bsStyle on ActionFile component
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/stories/ActionFile.js
Labels: need review

#1586 doc(containers/ComponentForm): add some doc
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.md
  packages/containers/src/ComponentForm/ComponentForm.puml
Labels: need review

#1578 fix(Typeahead): icon size and color
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/components/src/Typeahead/Typeahead.scss
  packages/icons/src/svg/charts.svg
  packages/icons/src/svg/clock.svg
  packages/icons/src/svg/minus-circle.svg
  packages/icons/src/svg/plus-circle.svg
  packages/icons/src/svg/tags.svg
Labels: easy review, frontend, need review

#1579 feat(components/editabletext): create component
  packages/components/src/EditableText/EditableText.component.js
  packages/components/src/EditableText/EditableText.scss
  packages/components/src/EditableText/EditableText.test.js
  packages/components/src/EditableText/InlineForm.component.js
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/components/src/EditableText/index.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.component.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.test.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/__snapshots__/InputTitleSubHeader.test.js.snap
  packages/components/src/SubHeaderBar/InputTitleSubHeader/index.js
  packages/components/src/SubHeaderBar/SubHeaderBar.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js
  packages/components/src/SubHeaderBar/TitleSubHeader/__snapshots__/TitleSubHeader.test.js.snap
  packages/components/src/SubHeaderBar/TitleSubHeader/index.js
  packages/components/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap
  packages/components/src/index.js
  packages/components/stories/EditableText.js
  packages/components/stories/index.js
Labels: enhancement, frontend, need review

#1587 feat(icon): local-storage
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/local-storage.svg
Labels: easy review, need review

#1417 fix(Component/List): do not trigger double click on input/button double click
  packages/components/package.json
  packages/components/src/VirtualizedList/CellCheckbox/CellCheckbox.component.js
  packages/components/src/VirtualizedList/CellCheckbox/__snapshots__/CellCheckbox.test.js.snap
  packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js
  packages/components/src/VirtualizedList/ListTable/ListTable.component.js
  packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
  packages/components/src/VirtualizedList/event/rowclick.js
  packages/components/src/VirtualizedList/event/rowclick.test.js
  packages/components/stories/VirtualizedList.js
Labels: frontend, need review

#1583 fix(components): Set btn-inverse background to transparent
  packages/theme/src/theme/_visual-helpers.scss
Labels: easy review, need review

#1593 fix(DeleteResource): rename validate button DELETE => REMOVE
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap
Labels: easy review, need review

#1599 fix(containers): spread loading props to the component Form
  packages/containers/src/Form/Form.container.js
  packages/containers/src/Form/Form.test.js
  packages/containers/src/Form/__snapshots__/Form.test.js.snap
Labels: bug, easy review, need review

#1598 fix(components/dialog): design adjustements
  packages/components/src/ActionBar/ActionBar.scss
  packages/components/src/Dialog/Dialog.component.js
  packages/components/src/Dialog/Dialog.test.js
  packages/components/src/Dialog/__snapshots__/Dialog.test.js.snap
  packages/components/stories/Dialog.js
  packages/theme/src/theme/_modals.scss
  packages/theme/src/theme/_variables.scss
Labels: easy review, enhancement, need review

#1607 fix(forms): Add safeRenderCompletion for safe state change
  packages/forms/src/Form.js
Labels: need review

#1594 fix(components/treeview): design adjustements
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.scss
  packages/components/src/TreeView/TreeViewItem/__snapshots__/TreeViewItem.test.js.snap
  packages/containers/src/SelectObject/SelectObject.scss
Labels: easy review, need review

#1592 fix(Typeahead): caret shape and interaction
  output/forms.eslint.txt
  packages/components/src/Typeahead/Typeahead.scss
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.scss
  packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap
Labels: easy review, frontend, need review

#1580 fix(List): placement and outline shape
  output/components.eslint.txt
  packages/components/package.json
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.test.js
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/ListTable/ListTable.scss
  packages/theme/src/theme/_button-groups.scss
Labels: frontend, need review

#1495 feat(ListView): improve a11y
  package.json
  packages/components/.storybook/preview-head.html
  packages/components/src/ListView/Header/Header.scss
  packages/components/src/ListView/Items/Item/Item.component.js
  packages/components/src/ListView/Items/Item/Item.test.js
  packages/components/src/ListView/Items/Item/__snapshots__/item.snapshot.test.js.snap
  packages/components/src/ListView/Items/Item/item.snapshot.test.js
  packages/components/src/ListView/Items/Items.component.js
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/ListView/ListView.scss
  packages/components/stories/ListView.js
  packages/theme/src/theme/_forms.switch-nested.scss
Labels: frontend, need review

#1614 feat(Enumeration): add the id on header actions
  packages/components/src/Enumeration/Header/Header.component.js
  packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Labels: easy review, need review

#1601 feat(containers/editabletext): create container
  output/containers.eslint.txt
  packages/components/src/SubHeaderBar/SubHeaderBar.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap
  packages/components/stories/SubHeaderBar.js
  packages/containers/.storybook/config.js
  packages/containers/.storybook/editabletext.storybook.js
  packages/containers/examples/ExampleEditableText.js
  packages/containers/examples/index.js
  packages/containers/src/EditableText/EditableText.connect.js
  packages/containers/src/EditableText/EditableText.container.js
  packages/containers/src/EditableText/EditableText.selectors.js
  packages/containers/src/EditableText/EditableText.test.js
  packages/containers/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/containers/src/EditableText/index.js
  packages/containers/src/SubHeaderBar/SubHeaderBar.container.js
  packages/containers/src/SubHeaderBar/SubHeaderBar.selectors.js
  packages/containers/src/SubHeaderBar/SubHeaderBar.test.js
  packages/containers/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap
  packages/containers/src/index.js
Labels: enhancement, need review

#1595 fix(components/editabletext): design adjustments
  packages/components/src/EditableText/EditableText.scss
  packages/components/src/EditableText/EditableText.test.js
  packages/components/src/EditableText/InlineForm.component.js
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
Labels: easy review, need review

#1612 fix(Loader): remove extra aria attributes
  packages/components/src/Loader/Loader.component.js
  packages/components/src/Loader/__snapshots__/Loader.snapshot.test.js.snap
Labels: easy review, frontend, need review

#1608 feat(components/DatePicker): Add dropdown
  packages/components/package.json
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.scss
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  yarn.lock
Labels: enhancement, frontend, need review

#1619 feat(PieChart): improve a11y
  packages/components/src/PieChart/PieChartIcon.component.js
  packages/components/src/PieChart/PieChartIcon.test.js
  packages/components/src/PieChart/__snapshots__/PieChartIcon.test.js.snap
Labels: easy review, frontend, need review

#1623 fix(storybook): restore scroll
  packages/components/.storybook/preview-head.html
Labels: easy review, frontend, need review

#1618 feat(Datalist): add live change callback
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/stories/Datalist.js
Labels: easy review, frontend, need review

#1622 feat(SidePanel): improve a11y
  packages/components/src/SidePanel/SidePanel.component.js
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
Labels: easy review, frontend, need review

#1624 feat(EditableText): improve a11y
  packages/components/src/EditableText/EditableText.component.js
  packages/components/src/EditableText/EditableText.scss
  packages/components/src/Skeleton/Skeleton.component.js
  packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
Labels: easy review, frontend, need review

#1625 feat(Forms): text display mode
  packages/forms/.storybook/preview-head.html
  packages/forms/src/UIForm/FormTemplate/DefaultFormTemplate.component.js
  packages/forms/src/UIForm/FormTemplate/TextModeFormTemplate.component.js
  packages/forms/src/UIForm/FormTemplate/index.js
  packages/forms/src/UIForm/README.md
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.scss
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/Widget/Widget.component.test.js
  packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
  packages/forms/src/UIForm/fields/FieldTemplate/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/FieldTemplate/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/FieldTemplate/displayMode/__snapshots__/TextMode.component.test.js.snap
  packages/forms/src/UIForm/fields/FieldTemplate/index.js
  packages/forms/src/UIForm/fields/Text/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/Text/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/Text/displayMode/__snapshots__/TextMode.component.test.js.snap
  packages/forms/src/UIForm/fields/Text/index.js
  packages/forms/src/UIForm/fields/TextArea/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/TextArea/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/TextArea/displayMode/__snapshots__/TextMode.component.test.js.snap
  packages/forms/src/UIForm/fields/TextArea/index.js
  packages/forms/src/UIForm/utils/widgets.js
  packages/forms/stories-core/jsonStories.js
Labels: frontend, need review

#1613 feat(Notification): improve a11y
  packages/components/src/Notification/Notification.component.js
  packages/components/src/Notification/Notification.test.js
  packages/components/src/Notification/__snapshots__/Notification.snap.test.js.snap
  packages/components/src/Notification/__snapshots__/Notification.test.js.snap
Labels: easy review, frontend, need review

#1628 chore(cmf/middleware): passing headers to onActionresponse
  packages/cmf/__tests__/actions/http.test.js
  packages/cmf/__tests__/middlewares/__snapshots__/http.test.js.snap
  packages/cmf/__tests__/middlewares/http.test.js
  packages/cmf/src/actions/http.js
  packages/cmf/src/middlewares/http/middleware.js
Labels: need review

#1634 chore(Form) Simple linting error fixes
  output/forms.eslint.txt
  packages/forms/src/Form.test.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/utils/templates.js
  packages/forms/src/fields/CollapsibleFieldset.test.js
  packages/forms/src/widgets/ColumnsWidget/ColumnsWidget.js
Labels: easy review, need review

#1602 fix(components): highlight the list when the user hover the main title
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/IconsProvider/IconsProvider.component.js
  packages/components/src/IconsProvider/IconsProvider.scss
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitle.test.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitle.test.js.snap
  packages/components/stories/List.js
  packages/components/stories/RichTooltip.js
  packages/icons/.svgo-filters.yml
  packages/icons/.svgo-icons.yml
  packages/icons/README.md
  packages/icons/package.json
  packages/icons/scripts/docs.js
  packages/icons/scripts/react.js
  packages/icons/src/extract.js
  packages/icons/src/filters/colormapping.svg
  packages/icons/src/filters/grayscale.svg
  packages/icons/src/index.js
  packages/icons/src/svg/local-storage.svg
  packages/icons/src/svgs.js
Labels: bug, need review

#1627 feat(UIForms): fieldset text mode
  packages/forms/src/UIForm/UIForm.scss
  packages/forms/src/UIForm/fieldsets/Fieldset/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fieldsets/Fieldset/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fieldsets/Fieldset/displayMode/__snapshots__/TextMode.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Fieldset/index.js
  packages/forms/src/UIForm/utils/widgets.js
Labels: easy review, frontend, need review

#1635 fix(UIForms): column top margin
  packages/forms/src/UIForm/fieldsets/Columns/Columns.scss
Labels: easy review, frontend, need review

#1632 feat(UIForms): code in text mode
  packages/forms/src/UIForm/fields/Code/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/Code/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/Code/displayMode/__snapshots__/TextMode.component.test.js.snap
  packages/forms/src/UIForm/fields/Code/index.js
  packages/forms/src/UIForm/utils/widgets.js
Labels: easy review, frontend, need review

#1615 feat(UIForm): NestedListView widget
  packages/forms/src/UIForm/fields/NestedListView/NestedListView.component.js
  packages/forms/src/UIForm/fields/NestedListView/NestedListView.scss
  packages/forms/src/UIForm/fields/NestedListView/NestedListView.test.js
  packages/forms/src/UIForm/fields/NestedListView/NestedListView.utils.js
  packages/forms/src/UIForm/fields/NestedListView/README.md
  packages/forms/src/UIForm/fields/NestedListView/__snapshots__/NestedListView.test.js.snap
  packages/forms/src/UIForm/fields/NestedListView/index.js
  packages/forms/src/UIForm/fields/NestedListView/screenshot.gif
  packages/forms/src/UIForm/utils/widgets.js
  packages/forms/stories-core/json/fields/core-nestedListView.json
Labels: need review

#1631 fix(components/treeview): design adjustements
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.scss
  packages/components/src/TreeView/TreeViewItem/__snapshots__/TreeViewItem.test.js.snap
Labels: bug, easy review, need review

#1637 feat(uiforms): checkbox text mode
  packages/forms/src/UIForm/fields/CheckBox/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/CheckBox/displayMode/TextMode.scss
  packages/forms/src/UIForm/fields/CheckBox/displayMode/TextMode.test.js
  packages/forms/src/UIForm/fields/CheckBox/displayMode/__snapshots__/TextMode.test.js.snap
  packages/forms/src/UIForm/fields/CheckBox/index.js
  packages/forms/src/UIForm/fields/FieldTemplate/displayMode/TextMode.component.js
  packages/forms/src/UIForm/utils/widgets.js
Labels: frontend, need review

#1633 feat(UIForms): multiSelectTag text mode
  packages/components/src/Badge/Badge.component.js
  packages/components/src/Badge/Badge.snap.test.js
  packages/components/src/Badge/__snapshots__/Badge.snap.test.js.snap
  packages/forms/src/UIForm/fields/MultiSelectTag/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/displayMode/TextMode.scss
  packages/forms/src/UIForm/fields/MultiSelectTag/index.js
  packages/forms/src/UIForm/utils/widgets.js
Labels: frontend, need review

#1626 feat(UIForms): datalist text mode
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.trigger.js
  packages/forms/src/UIForm/fields/Datalist/constants.js
  packages/forms/src/UIForm/fields/Datalist/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/Datalist/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/Datalist/displayMode/TextMode.scss
  packages/forms/src/UIForm/fields/Datalist/displayMode/__snapshots__/TextMode.component.test.js.snap
  packages/forms/src/UIForm/fields/Datalist/index.js
  packages/forms/src/UIForm/utils/widgets.js
  packages/forms/stories-core/json/fields/core-datalist.json
Labels: frontend, need review

#1638 feat(components/aboutmodal): create component
  packages/components/src/AboutDialog/AboutDialog.component.js
  packages/components/src/AboutDialog/AboutDialog.scss
  packages/components/src/AboutDialog/AboutDialog.snapshot.test.js
  packages/components/src/AboutDialog/AboutDialog.test.js
  packages/components/src/AboutDialog/__snapshots__/AboutDialog.snapshot.test.js.snap
  packages/components/src/AboutDialog/index.js
  packages/components/src/Skeleton/Skeleton.scss
  packages/components/src/index.js
  packages/components/stories/AboutDialog.js
  packages/components/stories/index.js
Labels: enhancement, frontend, need review

#1640 feat(component-objects): Update selenium version to 3.6.0
  packages/components/e2e/component-objects/pom.xml
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/Item.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/ListTest.java
Labels: easy review, need review

#1649 fix(UIForms): hidden input don't have labels anymore
  packages/forms/src/UIForm/fields/Text/Text.component.js
  packages/forms/src/UIForm/fields/Text/Text.component.test.js
  packages/forms/src/UIForm/fields/Text/__snapshots__/Text.component.test.js.snap
Labels: easy review, frontend, need review

#1643 fix(components/collapsible-panel): fix uppercase label when panel title has onSelect listener
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/stories/CollapsiblePanel.js
Labels: easy review, need review

#1590 feat(containers/List): default saga for filters and sorting
  packages/containers/src/List/List.connect.js
  packages/containers/src/List/List.constant.js
  packages/containers/src/List/List.container.js
  packages/containers/src/List/List.md
  packages/containers/src/List/List.sagas.js
  packages/containers/src/List/List.sagas.test.js
  packages/containers/src/List/List.test.js
  packages/containers/src/List/index.js
  packages/containers/src/List/selector.js
Labels: easy review, need review

#1644 fix(components/modal): header style
  packages/components/src/Dialog/Dialog.scss
  packages/components/stories/Dialog.js
Labels: bug, easy review, need review

#1642 feat(frontend): add className prop to enumeration item
  packages/components/src/Enumeration/Enumeration.component.js
  packages/components/src/Enumeration/Items/Item/Item.component.js
  packages/components/src/Enumeration/Items/Item/Item.propTypes.js
  packages/components/src/Enumeration/Items/Item/Item.test.js
  packages/components/stories/Enumeration.js
  packages/components/stories/Enumeration.scss
Labels: easy review, need review

#1658 doc(UIForm): import error in the samples
  packages/forms/src/UIForm/README.md
Labels: easy review, need review

#1661 fix(UIForms/ComponentForm): form and async errors in the same state
  packages/containers/sandbox/mockBackend/kit.js
  packages/containers/sandbox/mockBackend/mock/kit/index.js
  packages/containers/sandbox/mockBackend/mock/kit/titleMap.json
  packages/containers/sandbox/mockBackend/mock/kit/validation.json
  packages/containers/sandbox/src/assets/settings.json
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
  packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
Labels: frontend, need review

#1659 feat(UIForm): multiSelectTag widget onFocus trigger with tcomp support
  packages/containers/sandbox/mockBackend/mock/kit/titleMap.json
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
  packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap
  packages/containers/src/ComponentForm/fields/Datalist/Datalist.component.js
  packages/containers/src/ComponentForm/fields/Datalist/index.js
  packages/containers/src/ComponentForm/fields/NameResolver/NameResolver.component.js
  packages/containers/src/ComponentForm/fields/NameResolver/NameResolver.component.test.js
  packages/containers/src/ComponentForm/fields/NameResolver/index.js
  packages/containers/src/ComponentForm/fields/index.js
  packages/forms/src/UIForm/FormTemplate/DefaultFormTemplate.component.js
  packages/forms/src/UIForm/FormTemplate/TextModeFormTemplate.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js
  packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap
  packages/forms/src/UIForm/trigger/index.js
  packages/forms/src/fields/ArrayField.js
  packages/forms/stories-core/json/fields/core-multiSelectTag.json
Labels: frontend, need review

#1647 feat(Table): improve a11y
  packages/components/src/Table/Filters/FiltersBar.js
  packages/components/src/Table/Filters/__snapshots__/FiltersBar.test.js.snap
  packages/components/src/Table/Header/TableHeader.js
  packages/components/src/Table/Header/__snapshots__/TableHeader.test.js.snap
  packages/components/src/Table/Table.js
  packages/components/src/Table/TitleBar/__snapshots__/TitleBar.test.js.snap
  packages/components/src/Table/__snapshots__/Table.test.js.snap
  packages/components/stories/Table.js
Labels: easy review, frontend, need review
