Repository Talend/ui, pull requests merged in 2018-02, with the labels that each got.

#954 fix(ObjectViewer): Fixes object viewer style
  output/components.eslint.txt
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/ObjectViewer/List/List.component.js
  packages/components/src/ObjectViewer/Table/Table.component.js
  packages/components/src/ObjectViewer/Table/Table.scss
  packages/components/src/ObjectViewer/Table/__snapshots__/Table.test.js.snap
  packages/components/stories/ObjectViewer.js
Labels: need review

#1059 chore(travis): try to split demo build with test:cov
  .surge/index.html
  .travis.yml
  .travis/after_success_coverage.sh
  .travis/after_success_demo.sh
  .travis/after_success_deploy.sh
  .travis/after_success_git.sh
  .travis/after_success_lint.sh
  .travis/after_success_prettier.sh
  .travis/after_success_screenshots.sh
  .travis/after_success_static.sh
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  package.json
  packages/cmf-cqrs/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/forms/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/logging/package.json
  packages/sagas/package.json
  packages/theme/package.json
Labels: easy review, need review

#1058 fix(components/SidePanel): fix inverse theme when T7 layout activated
  packages/components/src/SidePanel/SidePanel.component.js
  packages/components/src/SidePanel/SidePanel.scss
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
Labels: need review

#1063 fix(HeaderBar): fixed position of header bar item separator
  packages/components/src/HeaderBar/HeaderBar.scss
Labels: easy review, need review

#1066 chore(ci): Bump travis NodeJS version to latest LTS
  .travis.yml
Labels: easy review, need review

#1065 feat(icons): Data view switch
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/hierarchical-view.svg
  packages/icons/src/svg/raw-data.svg
Labels: need review

#1049 fix(Notifications): failSafe
  output/containers.eslint.txt
  packages/containers/src/Notification/Notification.test.js
  packages/containers/src/Notification/pushNotification.js
Labels: need review

#1053 fix(containers/DeleteRessource): fix behaviour when refreshing browser
  BREAKING_CHANGES_LOG.md
  packages/containers/src/DeleteResource/DeleteResource.connect.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/DeleteResource.test.js
  packages/containers/src/DeleteResource/README.md
  packages/containers/src/DeleteResource/deleteResource.sagas.js
  packages/containers/src/DeleteResource/deleteResource.sagas.test.js
Labels: need review

#1054 feat(icons): component-kit
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/component-kit-negative.svg
  packages/icons/src/svg/component-kit-positive.svg
Labels: need review

#1051 feat(forms/array): update look & feel
  output/forms.eslint.txt
  packages/forms/src/UIForm/fieldsets/Array/Array.scss
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.scss
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/ArrayItem.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
  packages/forms/src/fields/CollapsibleFieldset.js
  packages/forms/src/fields/__snapshots__/CollapsibleFieldset.test.js.snap
  packages/forms/src/templates/ArrayFieldTemplate.js
  packages/forms/src/templates/ArrayFieldTemplate.scss
  packages/forms/src/widgets/ColumnsWidget/ColumnsWidget.js
  packages/forms/src/widgets/ColumnsWidget/ColumnsWidget.scss
  packages/forms/stories-core/json/fieldsets/core-arrays-complex.json
  packages/forms/stories/index.js
Labels: need review

#1073 doc(cmf): review
  packages/cmf/README.md
  packages/cmf/howto/best-practices.md
  packages/cmf/howto/best-pratices.md
  packages/cmf/howto/getting-started.md
  packages/cmf/howto/how-to-add-a-new-page.md
  packages/cmf/howto/how-to-manage-collections.md
  packages/cmf/howto/index.md
  packages/cmf/src/App.md
  packages/cmf/src/Dispatcher.md
  packages/cmf/src/actionCreator.md
  packages/cmf/src/api.md
  packages/cmf/src/cmfConnect.md
  packages/cmf/src/settings.md
  packages/cmf/src/store.md
Labels: easy review, enhancement, need review

#1064 fix(TDS-3104/List): toolbar dropdown value should be in capitalize
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss
  packages/components/src/List/Toolbar/Toolbar.scss
Labels: easy review, need review

#1055 feat(cmf): add redux-saga integration at component level
  BREAKING_CHANGES_LOG.md
  output/cmf.eslint.txt
  packages/cmf/__tests__/actions/saga.test.js
  packages/cmf/__tests__/api.test.js
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/__tests__/sagas/component.test.js
  packages/cmf/__tests__/sagas/putActionCreator.test.js
  packages/cmf/__tests__/selectors/index.test.js
  packages/cmf/src/actions/index.js
  packages/cmf/src/actions/saga.js
  packages/cmf/src/api.js
  packages/cmf/src/api.md
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/constant.js
  packages/cmf/src/sagas/collection.js
  packages/cmf/src/sagas/component.js
  packages/cmf/src/sagas/index.js
  packages/cmf/src/sagas/putActionCreator.js
  packages/cmf/src/selectors/collections.js
  packages/cmf/src/selectors/index.js
  packages/containers/src/DeleteResource/deleteResource.sagas.js
Labels: need review

#1077 fix: deprecated warning
  packages/cmf/src/component.js
Labels: easy review, need review

#1081 feat(forms/templates) : add translation in ArrayFieldTemplate
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/forms/src/UIForm/fields/ListView/ListView.component.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.test.js
  packages/forms/src/templates/ArrayFieldTemplate.js
Labels: easy review, need review

#1062 chore(travis): move action check on top and clean comments
  .travis.yml
  .travis/after_success_demo.sh
  .travis/after_success_deploy.sh
  .travis/after_success_git.sh
  .travis/after_success_lint.sh
  .travis/after_success_prettier.sh
  .travis/after_success_static.sh
Labels: easy review, frontend, need review

#1074 fix(generator): update versions
  packages/generator/generators/react-cmf/templates/package.json
Labels: easy review, need review

#1061 fix(components): Subheader form title is required
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InlineFormSubHeader.component.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.test.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/__snapshots__/InputTitleSubHeader.test.js.snap
  packages/components/stories/SubHeaderBar.js
Labels: need review

#1075 chore(generator): rename views by props
  packages/generator/generators/react-cmf/templates/src/assets/settings.json
Labels: easy review, need review

#1080 feat(containers/list): dispatch on edit submit and edit cancel
  packages/containers/src/List/List.container.js
  packages/containers/src/List/List.test.js
  packages/containers/src/List/__snapshots__/List.test.js.snap
Labels: easy review, enhancement, need review

#1078 fix(cmf): pass default state on cmfConnect at first mount
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/src/cmfConnect.js
Labels: easy review, frontend, need review

#1057 feat(VirtualizedList): add a CellDatetimeRenderer
  .travis.yml
  packages/components/package.json
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.scss
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js
  packages/components/src/VirtualizedList/CellDatetime/index.js
  packages/components/src/VirtualizedList/utils/dictionary.js
  packages/components/stories/List.js
  packages/components/stories/VirtualizedList.js
  packages/containers/examples/ExampleList.js
  packages/containers/src/List/List.test.js
  yarn.lock
Labels: need review

#1082 feat(cmf): route onEnter/onLeave with dispatch
  BREAKING_CHANGES_LOG.md
  output/containers.eslint.txt
  packages/cmf/__tests__/route.test.js
  packages/cmf/src/UIRouter.js
  packages/cmf/src/registry.js
  packages/cmf/src/route.js
  packages/cmf/src/settings.md
  packages/containers/src/DeleteResource/deleteResource.sagas.js
Labels: frontend, need review

#1086 fix(cmf/sagas/collection/waitFor): add id to selector
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/cmf/__tests__/sagas/collection.test.js
  packages/cmf/src/sagas/collection.js
Labels: easy review, need review

#1083 fix(cmf): add console.error on http JSError
  output/cmf.eslint.txt
  packages/cmf/src/actions/http.js
  packages/cmf/src/cmfConnect.js
Labels: easy review, need review

#1069 feat(cmf): add common expressions
  packages/cmf/__tests__/expressions/index.test.js
  packages/cmf/src/api.js
  packages/cmf/src/api.md
  packages/cmf/src/expressions/getInState.js
  packages/cmf/src/expressions/index.js
  packages/cmf/src/expressions/index.md
Labels: need review

#1087 fix(confirm-dialog): putting button computing in mapStateToProps
  packages/containers/src/ConfirmDialog/ConfirmDialog.connect.js
  packages/containers/src/ConfirmDialog/ConfirmDialog.container.js
  packages/containers/src/ConfirmDialog/ConfirmDialog.test.js
Labels: easy review, need review

#1072 chore(icons): Update logo-square.svg
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/logo-square.svg
Labels: need review

#1071 chore(icons): Update logo.svg
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/logo.svg
Labels: need review

#1089 feat(theme): Talend logo
  output/theme.sasslint.txt
  packages/theme/src/theme/_navbar.scss
Labels: easy review, need review

#1090 feat(icons): mdm
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/mdm-colored.svg
  packages/icons/src/svg/mdm-negative.svg
  packages/icons/src/svg/mdm-positive.svg
Labels: need review

#1008 chore(List): update with Inject API
  packages/components/src/Inject/Inject.md
  packages/components/src/List/List.component.js
  packages/components/src/List/List.md
  packages/components/src/List/Toolbar/Toolbar.component.js
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/containers/src/List/List.connect.js
  packages/containers/src/List/List.container.js
  packages/containers/src/List/__snapshots__/List.test.js.snap
Labels: need review

#1085 fix(icons): tdc-colored
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/tdc-colored.svg
Labels: need review

#1091 chore(icons): Update bigquery.svg
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/bigquery.svg
Labels: need review

#1104 feat(containers/List): Only add displayMode when required
  packages/containers/src/List/List.container.js
  packages/containers/src/List/List.test.js
  packages/containers/src/List/__snapshots__/List.test.js.snap
Labels: easy review, need review

#1103 TPSVC-4551: Talend 7 Header for Portal pages
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/Layout/constants.js
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/stories/config/themes.scss
  packages/theme/src/theme/variations/_portal.scss
Labels: easy review, frontend, need review

#1102 chore: set date-fns as dep, not peer dep
  packages/components/package.json
Labels: easy review, frontend, need review

#1095 feat(components/actionlist): extract actionlist from sidepanel
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/ActionList/ActionList.component.js
  packages/components/src/ActionList/ActionList.scss
  packages/components/src/ActionList/ActionList.snapshot.test.js
  packages/components/src/ActionList/ActionList.test.js
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/src/ActionList/__snapshots__/config.js
  packages/components/src/ActionList/index.js
  packages/components/src/SidePanel/SidePanel.component.js
  packages/components/src/SidePanel/SidePanel.scss
  packages/components/src/SidePanel/SidePanel.test.js
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/src/index.js
  packages/components/stories/ActionList.js
  packages/components/stories/index.js
Labels: easy review, need review

#1098 chore: @talend/scripts module
  packages/scripts/README.md
  packages/scripts/config/webpack.config.js
  packages/scripts/package.json
  packages/scripts/preset/config/.babelrc.json
  packages/scripts/preset/config/webpack.config.dev.js
  packages/scripts/preset/config/webpack.config.js
  packages/scripts/preset/config/webpack.config.prod.js
  packages/scripts/preset/preset-talend-webpack.js
  packages/scripts/preset/preset-talend.js
  packages/scripts/scripts/build.js
  packages/scripts/scripts/start.js
  packages/scripts/scripts/utils/env.js
  packages/scripts/scripts/utils/log.js
  packages/scripts/scripts/utils/path-resolver.js
  packages/scripts/scripts/utils/preset.js
Labels: frontend, need review

#1092 chore(icons): update AWS-kinesis.svg
  BREAKING_CHANGES_LOG.md
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/AWS-kinesis.svg
  packages/icons/src/svg/aws-kinesis.svg
  yarn.lock
Labels: need review

#1106 fix(forms): add static class and dynamic class name to arrayField elements
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
  packages/forms/src/templates/ArrayFieldTemplate.js
Labels: need review
