Repository Talend/ui, pull requests merged in 2018-12, with the labels that each got.

#1865 fix(components/VirtualizedList): hide key/value pairs when there is no value
  packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
  packages/components/stories/VirtualizedList.js
Labels: easy review, enhancement, need review

#1867 feat(componentForm): dispatch failed event when submit is failed
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.md
  packages/containers/src/ComponentForm/ComponentForm.saga.test.js
  packages/containers/src/ComponentForm/ComponentForm.sagas.js
Labels: easy review, need review

#1853 fix(RichTooltip): fix css issues with richtooltip
  packages/components/src/HeaderTitle/HeaderTitle.scss
  packages/components/src/OverlayTrigger/OverlayTrigger.component.js
  packages/components/src/OverlayTrigger/__snapshots__/OverlayTrigger.test.js.snap
  packages/components/src/RichTooltip/RichTooltip.scss
  packages/components/stories/RichTooltip.js
  screenshots.js
  screenshots/components-richtooltip.json
Labels: bug, need review

#1801 feat(UIForms): date time
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/README.md
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.js
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.test.js
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
  packages/components/src/DateTimePickers/pickers/YearPicker/__snapshots__/YearPicker.test.js.snap
  packages/forms/package.json
  packages/forms/src/UIForm/customFormats.js
  packages/forms/src/UIForm/customFormats.test.js
  packages/forms/src/UIForm/fields/Date/Date.component.js
  packages/forms/src/UIForm/fields/Date/Date.component.test.js
  packages/forms/src/UIForm/fields/Date/DateTime.component.js
  packages/forms/src/UIForm/fields/Date/README.md
  packages/forms/src/UIForm/fields/Date/__snapshots__/Date.component.test.js.snap
  packages/forms/src/UIForm/fields/Date/index.js
  packages/forms/src/UIForm/utils/widgets.js
  packages/forms/stories-core/json/fields/core-date.json
Labels: frontend, need review

#1868 fix(UIForm): array template error and description linked with list
  packages/forms/src/UIForm/Message/Message.component.js
  packages/forms/src/UIForm/Message/Message.component.test.js
  packages/forms/src/UIForm/Message/__snapshots__/Message.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
Labels: easy review, frontend, need review

#1866 feat(DatePicker): add missing labels for a11y
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js
  packages/components/src/DateTimePickers/pickers/DatePicker/__snapshots__/DatePicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.component.js
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.test.js
  packages/components/src/DateTimePickers/pickers/MonthPicker/__snapshots__/MonthPicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
  packages/components/src/DateTimePickers/pickers/YearPicker/__snapshots__/YearPicker.test.js.snap
  packages/components/src/DateTimePickers/views/MonthYearView/MonthYearView.component.js
  packages/components/src/DateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
Labels: frontend, need review

#1872 chore(DatePicker): utc mode
  output/components.sasslint.txt
  packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/DateTimePicker/README.md
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/README.md
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.js
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.test.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.scss
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.test.js
  packages/components/src/DateTimePickers/pickers/TimePicker/__snapshots__/TimePicker.test.js.snap
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.component.js
  packages/components/stories/DatePicker.js
  packages/components/stories/List.js
  packages/components/stories/VirtualizedList.js
  packages/components/stories/index.js
  packages/forms/src/UIForm/fields/Date/Date.component.js
  packages/forms/src/UIForm/fields/Date/README.md
  packages/forms/src/UIForm/fields/Date/__snapshots__/Date.component.test.js.snap
  packages/forms/stories-core/json/fields/core-date.json
Labels: need review

#1877 fix(cmf/localstorage): empty local storage value
  packages/cmf/src/localStorage.js
Labels: easy review, enhancement, need review

#1879 chore(component): move RichTooltip to RichLayout
  packages/components/src/RichTooltip/RichError/RichError.component.js
  packages/components/src/RichTooltip/RichError/RichError.component.test.js
  packages/components/src/RichTooltip/RichError/RichError.scss
  packages/components/src/RichTooltip/RichError/__snapshots__/RichError.component.test.js.snap
  packages/components/src/RichTooltip/RichError/index.js
  packages/components/src/RichTooltip/RichLayout/RichLayout.component.js
  packages/components/src/RichTooltip/RichLayout/RichLayout.scss
  packages/components/src/RichTooltip/RichLayout/RichLayout.test.js
  packages/components/src/RichTooltip/RichLayout/__snapshots__/RichLayout.test.js.snap
  packages/components/src/RichTooltip/RichLayout/index.js
  packages/components/src/RichTooltip/index.js
  packages/components/src/index.js
  packages/components/stories/RichTooltip.js
Labels: enhancement, need review

#1871 fix(component): update HeaderTitle style with the guidelines
  packages/components/src/HeaderTitle/HeaderTitle.scss
  packages/components/stories/RichTooltip.js
Labels: enhancement, need review, work in progress

#1875 chore: enable e2e tests
  .travis.yml
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/LargeTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/TableTest.java
  packages/components/stories/List.js
Labels: easy review, frontend, need review

#1876 feat(components/virtualizedlist): upgrade react-virtualized for a11y
  npm-audit/package-lock.json
  npm-audit/package.json
  packages/components/package.json
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/VirtualizedList/ListGrid/__snapshots__/ListGrid.test.js.snap
  packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  versions/dependencies.js
  yarn.lock
Labels: easy review, frontend, need review

#1881 chore: upgrade rc-tooltip
  npm-audit/package-lock.json
  npm-audit/package.json
  packages/components/package.json
  versions/dependencies.js
  yarn.lock
Labels: easy review, frontend, need review

#1870 fix(cmf/http): don't stringify if not json type
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
Labels: bug, easy review, frontend, need review

#1880 chore: upgrade rc-slider
  npm-audit/package-lock.json
  npm-audit/package.json
  packages/components/package.json
  versions/dependencies.js
  yarn.lock
Labels: easy review, frontend, need review

#1883 fix(DatePicker): remove useUTC from input props
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
Labels: easy review, frontend, need review

#1884 fix(components/ActionIconToggle): provide a better scope to svg
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/icons/src/svg/contains.svg
  packages/icons/src/svg/equal.svg
  packages/icons/src/svg/less-than-equal.svg
  packages/icons/src/svg/less-than.svg
  packages/icons/src/svg/more-than-equal.svg
  packages/icons/src/svg/more-than.svg
  packages/icons/src/svg/not-equal.svg
Labels: bug, frontend, need review

#1864 fix(Containers/Action): resolve action props in Action component
  packages/containers/src/Action/Action.connect.js
  packages/containers/src/Action/Action.test.js
  packages/containers/src/Action/__snapshots__/Action.test.js.snap
Labels: bug, frontend, need review

#1885 fix(components/dialog): design adjustments
  packages/components/src/Dialog/Dialog.scss
Labels: bug, easy review, need review

#1887 fix(components/list): large display adjustments
  packages/components/src/VirtualizedList/ListGrid/ListGrid.test.js
  packages/components/src/VirtualizedList/RendererSelector.test.js
  packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
  packages/components/src/VirtualizedList/RowLarge/__snapshots__/RowLarge.test.js.snap
Labels: bug, easy review, frontend, need review

#1891 fix(components): apply dove-gray by default on actions on the list
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
Labels: bug, easy review, need review

#1889 feat(containers/HeaderBar): Provide callback products alteration callback
  packages/containers/src/HeaderBar/HeaderBar.container.js
  packages/containers/src/HeaderBar/HeaderBar.test.js
Labels: easy review, need review

#1873 fix(container/forms): dirty state on form reset
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
  packages/theme/src/theme/_visual-helpers.scss
Labels: need review

#1892 fix(DatePicker): guideline style
  output/components.sasslint.txt
  packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.scss
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.scss
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.scss
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.scss
  packages/components/src/DateTimePickers/pickers/TimePicker/__snapshots__/TimePicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.scss
  packages/components/src/DateTimePickers/shared/styles/mixins.scss
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.component.js
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.scss
  packages/components/src/DateTimePickers/views/MonthYearView/MonthYearView.scss
  packages/components/src/DateTimePickers/views/ViewLayout/ViewLayout.scss
Labels: frontend, need review

#1894 chore(css): Improve css @import
  output/theme.sasslint.txt
  packages/forms/src/UIForm/fields/File/File.scss
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.scss
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.scss
  packages/theme/src/theme/_forms.guideline.scss
  packages/theme/src/theme/_forms.scss
Labels: easy review, need review

#1897 chore: move current talend/scripts into a webapp folder
  packages/scripts/README.md
  packages/scripts/index.js
  packages/scripts/webapp/README.md
  packages/scripts/webapp/config/webpack.config.js
  packages/scripts/webapp/preset/README.md
  packages/scripts/webapp/preset/config/.babelrc.json
  packages/scripts/webapp/preset/config/.eslintrc
  packages/scripts/webapp/preset/config/jest.config.js
  packages/scripts/webapp/preset/config/licence.js
  packages/scripts/webapp/preset/config/test/jest-preprocess.js
  packages/scripts/webapp/preset/config/test/style-mock.js
  packages/scripts/webapp/preset/config/test/test-setup.js
  packages/scripts/webapp/preset/config/webpack.config.dev.js
  packages/scripts/webapp/preset/config/webpack.config.js
  packages/scripts/webapp/preset/config/webpack.config.prod.js
  packages/scripts/webapp/preset/preset-talend-eslint.js
  packages/scripts/webapp/preset/preset-talend-jest.js
  packages/scripts/webapp/preset/preset-talend-webpack.js
  packages/scripts/webapp/preset/preset-talend.js
  packages/scripts/webapp/scripts/build.js
  packages/scripts/webapp/scripts/lint-es.js
  packages/scripts/webapp/scripts/start.js
  packages/scripts/webapp/scripts/test.js
  packages/scripts/webapp/utils/env.js
  packages/scripts/webapp/utils/log.js
  packages/scripts/webapp/utils/path-resolver.js
  packages/scripts/webapp/utils/preset.js
Labels: frontend, need review

#1886 fix(components/subheaderbar): apply guideline on action icon
  README.md
  output/components.sasslint.txt
  packages/components/src/SubHeaderBar/SubHeaderBar.scss
  packages/components/stories/Action.js
  packages/components/stories/SubHeaderBar.js
  packages/theme/example/index.html
  packages/theme/src/theme/_buttons.scss
Labels: bug, need review

#1904 fix(containers/SubHeaderBar): remove undefined selector
  output/containers.eslint.txt
  packages/containers/src/SubHeaderBar/SubHeaderBar.selectors.js
  packages/containers/src/SubHeaderBar/index.js
Labels: need review

#1906 fix(scripts): update babel plugins
  packages/containers/sandbox/.babelrc
  packages/containers/sandbox/package.json
  packages/containers/sandbox/talend-scripts.json
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/.babelrc.json
Labels: need review

#1898 fix(cmf/http): do not stringify if it s a string
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
Labels: need review

#1901 feat: i18n scripts
  packages/scripts/README.md
  packages/scripts/common/log.js
  packages/scripts/index.js
  packages/scripts/internationalization/README.md
  packages/scripts/internationalization/common/error.js
  packages/scripts/internationalization/common/xtm.js
  packages/scripts/internationalization/index.js
  packages/scripts/internationalization/process.png
  packages/scripts/internationalization/scripts/download.js
  packages/scripts/internationalization/scripts/extract.js
  packages/scripts/internationalization/scripts/upload.js
  packages/scripts/package.json
  packages/scripts/webapp/index.js
Labels: frontend, need review

#1908 chore(scripts): upgrade lib to avoid security issue
  packages/scripts/package.json
Labels: easy review, frontend, need review

#1907 fix(scripts): do not include fonts in the bundle
  packages/containers/sandbox/package.json
  packages/scripts/webapp/config/webpack.config.js
  packages/scripts/webapp/preset/README.md
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: need review

#1903 fix(components): change sort proptype to avoid a warn
  packages/components/src/List/Toolbar/Toolbar.component.js
Labels: easy review, need review, proptypes warning

#1911 chore(container): remove componentForm events in redux payload
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
Labels: easy review, need review

#1913 fix(UIForm): Buttons wrapper rendered even if no actions
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
Labels: bug, easy review, frontend, need review

#1912 fix(Components): Missing possibility to have a 'form' prop on a ActionButton
  packages/components/src/utils/getPropsFrom.js
  packages/components/src/utils/getPropsFrom.test.js
Labels: bug, easy review, frontend, need review

#1909 feat(Scripts): i18n to github
  packages/scripts/index.js
  packages/scripts/internationalization/README.md
  packages/scripts/internationalization/common/error.js
  packages/scripts/internationalization/scripts/to-github.js
  packages/scripts/package.json
Labels: frontend, need review

#1914 fix(UIForm): Missing event object spread in callback
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
Labels: bug, easy review, frontend, need review

#1919 feat(container/list): parse expression nested in column data
  packages/cmf/src/expression.js
  packages/containers/src/List/List.container.js
Labels: easy review, need review

#1900 chore: add some screenshots story support
  packages/components/stories/ActionIconToggle.js
  screenshots/components-aboutdialog.json
  screenshots/components-actionlist.json
  screenshots/components-actions.json
  screenshots/components-badge.json
  screenshots/components-breadcrumbs.json
  screenshots/components-checkbox.json
  screenshots/components-collapsiblepanel.json
  screenshots/components-confirmdialog.json
  screenshots/components-drawer.json
  screenshots/components-editabletext.json
  screenshots/components-richtooltip.json
  screenshots/components-subheader.json
  screenshots/components-tabbar.json
  screenshots/components-virtualized-list.json
Labels: need review

#1922 fix(datagrid): add type button on the header
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/DefaultHeaderRenderer.test.js.snap
Labels: bug, need review

#1926 fix(datagrid): incorrect color after a horizontal scroll on the header
  packages/datagrid/src/components/DataGrid/DataGrid.scss
Labels: bug, easy review, need review

#1930 fix(ActionIconToggle): border on active state
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/Actions/ActionIconToggle/__snapshots__/ActionIconToggle.component.test.js.snap
Labels: easy review, frontend, need review

#1924 fix(theme/hyperlinks): adapt hyperlinks to guidelines
  packages/theme/src/theme/_hyperlinks.scss
  packages/theme/src/theme/_navbar.scss
  packages/theme/src/theme/theme.scss
Labels: bug, easy review, enhancement, frontend, need review

#1899 feat(icons): union
  packages/icons/src/svg/union.svg
Labels: easy review, need review

#1915 feat(Components): Give possibility to inject directly a component reference
  packages/components/src/Inject/Inject.component.js
  packages/components/src/Inject/Inject.test.js
Labels: enhancement, frontend, need review

#1921 feat(components): Add rounding label on PieChart
  packages/components/src/PieChart/PieChartIcon.component.js
  packages/components/src/PieChart/PieChartIcon.test.js
  packages/components/stories/PieChart.js
Labels: need review

#1927 fix(datagrid): update serialize to handle quality or not
  packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/stories/datagrid.component.js
  packages/datagrid/stories/sampleWithoutQuality.json
Labels: bug, need review

#1929 fix(ObjectViewer): perf
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.test.js
  packages/components/src/ObjectViewer/JSONLike/__snapshots__/JSONLike.test.js.snap
  packages/components/src/ObjectViewer/List/__snapshots__/List.test.js.snap
  packages/components/src/ObjectViewer/Table/__snapshots__/Table.test.js.snap
Labels: easy review

#1932 fix(component): ObjectViewer flat table mode head
  packages/components/src/ObjectViewer/Table/Table.component.js
  packages/components/src/ObjectViewer/Table/Table.test.js
  packages/components/src/ObjectViewer/Table/__snapshots__/Table.test.js.snap
  packages/components/stories/ObjectViewer.js
Labels: need review

#1918 fix(UIForm/Datalist): do not add empty value in title map
  output/components.sasslint.txt
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.scss
  packages/components/src/Typeahead/Typeahead.snapshot.test.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/components/stories/Datalist.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js
  packages/forms/src/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
  packages/forms/stories-core/json/concepts/aaa.json
Labels: breaking change, frontend, need review

#1890 chore: Upgrade react-bootstrap
  npm-audit/audit.json
  npm-audit/package-lock.json
  npm-audit/package.json
  packages/components/package.json
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/Status/Status.scss
  packages/components/stories/CollapsiblePanel.js
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/theme/src/theme/_variables.scss
  versions/dependencies.js
  yarn.lock
Labels: breaking change, frontend, need review

#1854 feat(CMF/TUI-305): omitCMFProps is the default now
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/cmfConnect.md
Labels: breaking change

#1851 feat(TUI-298): update headings font size
  packages/theme/example/index.html
  packages/theme/src/theme/_type.scss
  packages/theme/src/theme/_variables.scss
  packages/theme/src/theme/theme.scss
Labels: breaking change, need review

#1933 fix: SubHeader and Dialog headings
  packages/components/src/ConfirmDialog/ConfirmDialog.test.js
  packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
  packages/components/src/Dialog/Dialog.component.js
  packages/components/src/Dialog/Dialog.scss
  packages/components/src/Dialog/__snapshots__/Dialog.test.js.snap
  packages/components/src/EditableText/EditableText.component.js
  packages/components/src/EditableText/EditableText.scss
  packages/components/src/EditableText/EditableText.test.js
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
Labels: breaking change, frontend, need review
