Repository Talend/ui, pull requests merged in 2018-11, with the labels that each got.

#1800 fix(datagrid): remove the prefix data in the header
  packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/stories/sample.json
Labels: bug, need review

#1792 fix(UIForms): array with fieldseption validation
  output/forms.eslint.txt
  packages/forms/src/UIForm/fieldsets/Array/Array.component.js
  packages/forms/src/UIForm/utils/array.js
  packages/forms/src/UIForm/utils/array.test.js
  packages/forms/src/UIForm/utils/validation.js
Labels: frontend, need review

#1652 feat(DatePicker): prepare for UIForm
  mocks/dateMock.js
  packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.md
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.js
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.test.js
  packages/components/src/DateTimePickers/ReadMe.md
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.test.js
  packages/components/src/DateTimePickers/pickers/IncrementableScrollList/RowRenderer/RowRenderer.component.js
  packages/components/src/DateTimePickers/pickers/IncrementableScrollList/RowRenderer/RowRenderer.test.js
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.component.js
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.test.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.test.js
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.test.js
  packages/components/src/DateTimePickers/shared/components/PickerAction/PickerAction.component.js
  packages/components/src/DateTimePickers/shared/components/PickerAction/__snapshots__/PickerAction.test.js.snap
  packages/components/src/DateTimePickers/shared/utils/test/dateMocking.js
  packages/components/stories/DateTimePicker.js
  test-setup.js
  yarn.lock
Labels: frontend, need review

#1802 fix(components): hiding the tooltip when the button is disabled
  packages/components/src/TooltipTrigger/TooltipTrigger.component.js
  packages/components/src/TooltipTrigger/TooltipTrigger.test.js
  packages/components/src/TooltipTrigger/__snapshots__/TooltipTrigger.test.js.snap
  packages/components/stories/Action.js
  packages/components/stories/ActionIconToggle.js
Labels: bug, need review

#1804 fix(icons): Replace sharing
  npm-audit/audit.json
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/components/src/TooltipTrigger/TooltipTrigger.test.js
  packages/icons/src/svg/fieldglass.svg
  packages/icons/src/svg/folder-shared-owner.svg
  packages/icons/src/svg/sharing-owner.svg
Labels: easy review, need review

#1810 fix(ObjectViewer): Fix object viewer header style
  packages/components/src/ObjectViewer/Table/Table.scss
Labels: easy review, need review

#1803 feat(form): add form reset handlign on UIForm
  packages/forms/src/UIForm/README.md
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
  packages/forms/src/UIForm/__snapshots__/UIForm.container.test.js.snap
Labels: enhancement, need review

#1812 fix(components/Subheaderbar): padding action bar left
  npm-audit/audit.json
  packages/components/src/EditableText/EditableText.scss
  packages/components/src/SubHeaderBar/SubHeaderBar.scss
Labels: easy review, need review

#1816 doc: remove all breaking change log note
  packages/cmf-cqrs/README.md
  packages/components/README.md
  packages/containers/README.md
  packages/datagrid/README.md
  packages/forms/README.md
  packages/generator/README.md
  packages/icons/README.md
  packages/logging/README.md
  packages/sagas/README.md
  packages/theme/README.md
Labels: easy review, need review

#1779 fix(generator/cmf): make it work
  packages/generator/.babelrc
  packages/generator/generators/app/index.js
  packages/generator/generators/create-cell/index.js
  packages/generator/generators/dotfiles/index.js
  packages/generator/generators/react-cmf/index.js
  packages/generator/generators/react-cmf/templates/cmf.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/generator/generators/react-cmf/templates/src/app/actions/dataset.js
  packages/generator/generators/react-cmf/templates/src/app/actions/datastore.js
  packages/generator/generators/react-cmf/templates/src/app/actions/index.js
  packages/generator/generators/react-cmf/templates/src/app/actions/redirect.js
  packages/generator/generators/react-cmf/templates/src/app/actions/redirect.test.js
  packages/generator/generators/react-cmf/templates/src/app/constants/dataset.js
  packages/generator/generators/react-cmf/templates/src/app/constants/datastore.js
  packages/generator/generators/react-cmf/templates/src/app/constants/index.js
  packages/generator/generators/react-cmf/templates/src/app/expressions/index.js
  packages/generator/generators/react-cmf/templates/src/app/index.html
  packages/generator/generators/react-cmf/templates/src/app/index.js
  packages/generator/generators/react-cmf/templates/src/app/reducers/myExample.js
  packages/generator/generators/react-cmf/templates/src/app/reducers/reducers.md
  packages/generator/generators/react-cmf/templates/src/app/saga/index.js
  packages/generator/generators/react-cmf/templates/src/app/sagas/handleDatasets.js
  packages/generator/generators/react-cmf/templates/src/app/sagas/handleDatastores.js
  packages/generator/generators/react-cmf/templates/src/app/sagas/index.js
  packages/generator/generators/react-cmf/templates/src/app/selectors/index.js
  packages/generator/generators/react-cmf/templates/src/assets/settings.json
  packages/generator/generators/react-cmf/templates/src/settings/HeaderBar.json
  packages/generator/generators/react-cmf/templates/src/settings/HomeListView.json
  packages/generator/generators/react-cmf/templates/src/settings/SidePanel.json
  packages/generator/generators/react-cmf/templates/src/settings/router.json
  packages/generator/generators/react-cmf/templates/talend-scripts.json
  packages/generator/generators/react-component/index.js
  packages/generator/package.json
  yarn.lock
Labels: need review

#1807 fix(components): add tooltip on the subheaderbar
  packages/components/src/EditableText/EditableText.component.js
  packages/components/src/EditableText/EditableText.test.js
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/__snapshots__/TitleSubHeader.test.js.snap
Labels: bug, need review

#1766 feat(TUI-231/TUI-90/SidePanel): make the container work with link
  output/containers.eslint.txt
  packages/cmf/src/onEvent.js
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleSidePanel.js
  packages/containers/package.json
  packages/containers/src/HomeListView/__snapshots__/HomeListView.test.js.snap
  packages/containers/src/SidePanel/SidePanel.connect.js
  packages/containers/src/SidePanel/SidePanel.container.js
  packages/containers/src/SidePanel/SidePanel.md
  packages/containers/src/SidePanel/SidePanel.test.js
  packages/containers/src/SidePanel/constants.js
Labels: need review

#1751 chore(TUI-256): apply code mode omitCMFProps
  packages/containers/src/AboutDialog/AboutDialog.connect.js
  packages/containers/src/Action/Action.connect.js
  packages/containers/src/ActionBar/ActionBar.connect.js
  packages/containers/src/ActionButton/ActionButton.connect.js
  packages/containers/src/ActionDropdown/ActionDropdown.connect.js
  packages/containers/src/ActionFile/ActionFile.connect.js
  packages/containers/src/ActionIconToggle/ActionIconToggle.connect.js
  packages/containers/src/ActionSplitDropdown/ActionSplitDropdown.connect.js
  packages/containers/src/Actions/Actions.connect.js
  packages/containers/src/AppLoader/AppLoader.connect.js
  packages/containers/src/Badge/Badge.component.js
  packages/containers/src/Breadcrumbs/Breadcrumbs.connect.js
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ConfirmDialog/ConfirmDialog.connect.js
  packages/containers/src/DeleteResource/DeleteResource.connect.js
  packages/containers/src/EditableText/EditableText.connect.js
  packages/containers/src/FilterBar/FilterBar.connect.js
  packages/containers/src/Form/Form.connect.js
  packages/containers/src/HeaderBar/HeaderBar.connect.js
  packages/containers/src/HomeListView/HomeListView.connect.js
  packages/containers/src/List/List.connect.js
  packages/containers/src/List/List.container.js
  packages/containers/src/Notification/Notification.connect.js
  packages/containers/src/ObjectViewer/ObjectViewer.connect.js
  packages/containers/src/PieChartButton/PieChartButton.connect.js
  packages/containers/src/Redirect/Redirect.container.js
  packages/containers/src/SelectObject/SelectObject.connect.js
  packages/containers/src/ShortcutManager/ShortcutManager.connect.js
  packages/containers/src/SidePanel/SidePanel.connect.js
  packages/containers/src/Slider/Slider.connect.js
  packages/containers/src/SubHeaderBar/SubHeaderBar.connect.js
  packages/containers/src/TabBar/TabBar.connect.js
  packages/containers/src/TreeView/TreeView.container.js
  packages/containers/src/Typeahead/Typeahead.connect.js
  packages/containers/src/index.js
  packages/generator/generators/react-component/index.js
  yarn.lock
Labels: need review

#1820 fix(sidepanel): add withrouter
  packages/containers/package.json
  packages/containers/src/HomeListView/__snapshots__/HomeListView.test.js.snap
  packages/containers/src/SidePanel/SidePanel.connect.js
Labels: need review

#1821 fix(components): disable the css when ActionIconToggle is disabled
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
Labels: bug, easy review, need review

#1818 fix(forms): Exclude readonly fields from label focus style
  packages/forms/src/UIForm/__snapshots__/widgets.json
  packages/forms/stories/json/widgets.json
  packages/theme/src/theme/_forms.scss
Labels: easy review, need review

#1811 fix(form): remove warning messages
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/fields/Button/Button.component.js
  packages/forms/src/UIForm/fields/Button/__snapshots__/Button.component.test.js.snap
  packages/forms/src/UIForm/fields/File/File.component.js
  packages/forms/src/UIForm/fields/File/__snapshots__/File.component.test.js.snap
Labels: easy review, need review

#1822 fix(forms/TUI-93): required checkbox put * at the end
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.scss
Labels: easy review, need review

#1795 chore(theme): add svg-rg-size
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/theme/src/theme/_guidelines.scss
Labels: easy review, need review

#1806 fix(components/Slider): align icons with slider handler and add disabled props
  packages/components/src/Slider/Slider.component.js
  packages/components/src/Slider/Slider.scss
  packages/components/src/Slider/Slider.snap.test.js
  packages/components/src/Slider/Slider.test.js
  packages/components/src/Slider/__snapshots__/Slider.snap.test.js.snap
  packages/components/src/Slider/__snapshots__/Slider.test.js.snap
  packages/components/stories/Slider.js
  packages/containers/examples/ExampleSlider.js
Labels: need review

#1828 fix(Layout): do not touch the body style
  packages/components/src/Layout/Layout.scss
  packages/components/stories/Layout.js
Labels: easy review, frontend, need review

#1824 fix(cmf/#1808): add warning if no displayName
  packages/cmf/src/cmfConnect.js
  packages/containers/examples/ExampleActionIconToggle.js
  packages/containers/src/index.js
Labels: easy review, need review

#1829 chore(datagrid): make it cmfModule
  packages/datagrid/README.md
  packages/datagrid/package.json
  packages/datagrid/src/cmfModule.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.component.js
  packages/datagrid/src/components/DefaultIntCellRenderer/DefaultIntCellRenderer.component.js
  packages/datagrid/src/containers/DataGrid/DataGrid.connect.js
  packages/datagrid/src/register.js
  packages/datagrid/src/register.test.js
  packages/datagrid/stories/datagrid.component.js
  packages/datagrid/stories/datagrid.container.js
Labels: need review

#1830 fix(Containers/ActionButton): add missing registry props
  packages/containers/src/ActionButton/ActionButton.connect.js
Labels: easy review, need review

#1832 fix(ComponentForm): reset
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.saga.test.js
  packages/containers/src/ComponentForm/ComponentForm.sagas.js
  packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap
  packages/forms/src/UIForm/README.md
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
  yarn.lock
Labels: need review

#1755 fix(UIForm): collapsible items title in array
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap
  packages/forms/src/UIForm/utils/array.js
  packages/forms/src/UIForm/utils/array.test.js
  packages/forms/stories-core/json/fieldsets/core-arrays.json
Labels: need review

#1834 feat(datagrid): add story to simulate adding data
  packages/datagrid/stories/DynamicDataGrid.component.js
  packages/datagrid/stories/datagrid.component.js
Labels: enhancement, need review

#1843 feat(containers/HeaderBar): Static products, sort and products "onClick"
  packages/containers/sandbox/src/assets/settings.json
  packages/containers/src/HeaderBar/HeaderBar.container.js
  packages/containers/src/HeaderBar/HeaderBar.test.js
  packages/containers/src/HeaderBar/__snapshots__/HeaderBar.test.js.snap
Labels: easy review, need review

#1836 feat(icons): add Marketo and Netsuite
  .travis/after_success_git.sh
  packages/components/src/IconsProvider/IconsProvider.test.js
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/marketo.svg
  packages/icons/src/svg/netsuite.svg
Labels: easy review, need review

#1838 fix(CMF/TUI-101): improve error message when register an actionCreator
  packages/cmf/__tests__/actionCreator.test.js
  packages/cmf/src/actionCreator.js
Labels: need review

#1823 doc(forms): remove knob and put UIForm first
  packages/forms/.storybook/addons.js
  packages/forms/.storybook/config.js
  packages/forms/package.json
  packages/forms/stories-core/index.js
  packages/forms/stories-core/jsonStories.js
  packages/forms/stories/index.js
Labels: easy review, need review

#1819 fix(TUI-292/CMF): handle fetch Error
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
Labels: need review

#1845 feat(icon): versioning
  packages/icons/src/svg/versioning.svg
Labels: easy review, need review

#1841 chore(DatePicker): seconds management
  output/components.sasslint.txt
  packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/README.md
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.js
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.test.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.scss
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.component.js
  packages/components/src/DateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
  packages/components/stories/DateTimePicker.js
  yarn.lock
Labels: need review

#1831 feat(ActionFile): pass accept props
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/Actions/ActionFile/ActionFile.test.js
  packages/components/src/Actions/ActionFile/__snapshots__/ActionFile.test.js.snap
  packages/containers/src/ActionFile/__snapshots__/ActionFile.test.js.snap
Labels: easy review, need review

#1847 feat(DatePicker): date format as props
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.scss
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/README.md
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.js
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.test.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.test.js
  packages/components/src/DateTimePickers/pickers/TimePicker/__snapshots__/TimePicker.test.js.snap
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.test.js
  packages/components/src/DateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
  packages/components/stories/DateTimePicker.js
Labels: frontend, need review

#1833 fix(components/subheaderbar): design adjustments
  output/components.sasslint.txt
  packages/components/src/Actions/Action/Action.component.js
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/EditableText/EditableText.scss
  packages/components/src/SubHeaderBar/SubHeaderBar.scss
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  screenshots/components.editabletext.json
Labels: easy review, enhancement, need review

#1850 chore: remove watch and fix security issue
  npm-audit/audit.json
  npm-audit/package-lock.json
  npm-audit/package.json
  package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/icons/package.json
  packages/icons/webpack.config.js
  versions/dependencies.js
  yarn.lock
Labels: easy review, need review

#1848 chore(DatePicker): date only
  packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.js
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.test.js
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.component.js
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.test.js
  packages/components/src/DateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
  packages/components/stories/DateTimePicker.js
Labels: need review

#1621 feat(scripts): allow to use user's babelrc
  packages/scripts/preset/README.md
  packages/scripts/preset/config/webpack.config.js
Labels: easy review, need review

#1852 chore(DatePicker): refactor year picker
  packages/components/src/DateTimePickers/generator.js
  packages/components/src/DateTimePickers/generator.test.js
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.scss
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.md
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.scss
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.test.js
  packages/components/src/DateTimePickers/pickers/YearPicker/__snapshots__/YearPicker.test.js.snap
  packages/components/src/DateTimePickers/shared/components/IconButton/IconButton.component.js
  packages/components/src/DateTimePickers/shared/components/IconButton/IconButton.scss
  packages/components/src/DateTimePickers/shared/components/IconButton/IconButton.test.js
  packages/components/src/DateTimePickers/shared/components/IconButton/__snapshots__/IconButton.test.js.snap
  packages/components/src/DateTimePickers/shared/components/IconButton/index.js
  packages/components/src/DateTimePickers/shared/components/IncrementableScrollList/IncrementableScrollList.component.js
  packages/components/src/DateTimePickers/shared/components/IncrementableScrollList/IncrementableScrollList.scss
  packages/components/src/DateTimePickers/shared/components/IncrementableScrollList/IncrementableScrollList.test.js
  packages/components/src/DateTimePickers/shared/components/IncrementableScrollList/RowRenderer/RowRenderer.component.js
  packages/components/src/DateTimePickers/shared/components/IncrementableScrollList/RowRenderer/RowRenderer.test.js
  packages/components/src/DateTimePickers/shared/components/IncrementableScrollList/RowRenderer/__snapshots__/RowRenderer.test.js.snap
  packages/components/src/DateTimePickers/shared/components/IncrementableScrollList/RowRenderer/index.js
  packages/components/src/DateTimePickers/shared/components/IncrementableScrollList/__snapshots__/IncrementableScrollList.test.js.snap
  packages/components/src/DateTimePickers/shared/components/IncrementableScrollList/index.js
  packages/components/src/DateTimePickers/shared/components/PickerAction/PickerAction.component.js
  packages/components/src/DateTimePickers/shared/components/PickerAction/PickerAction.scss
  packages/components/src/DateTimePickers/shared/components/PickerAction/PickerAction.test.js
  packages/components/src/DateTimePickers/shared/components/PickerAction/__snapshots__/PickerAction.test.js.snap
  packages/components/src/DateTimePickers/shared/components/PickerAction/index.js
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.scss
  packages/components/src/DateTimePickers/views/MonthYearView/MonthYearView.scss
Labels: frontend, need review

#1855 chore(DatePicker): i18n on component part
  packages/components/src/DateFnsLocale/formatters.js
  packages/components/src/DateTimePickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/generator.js
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js
  packages/components/src/DateTimePickers/pickers/DatePicker/__snapshots__/DatePicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/DatePicker/index.js
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.component.js
  packages/components/src/DateTimePickers/pickers/MonthPicker/__snapshots__/MonthPicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/MonthPicker/index.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/index.js
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
  packages/components/src/DateTimePickers/pickers/YearPicker/index.js
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.component.js
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.test.js
  packages/components/src/DateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
  packages/components/src/DateTimePickers/views/DateTimeView/index.js
  packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.component.js
  packages/components/src/DateTimePickers/views/HeaderTitle/index.js
  packages/components/src/DateTimePickers/views/MonthYearView/MonthYearView.component.js
  packages/components/src/DateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
  packages/components/src/DateTimePickers/views/MonthYearView/index.js
  packages/components/src/Gesture/withCalendarGesture.js
Labels: need review

#1858 feat(DatePicker): year picker gestures
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.test.js
  packages/components/src/DateTimePickers/pickers/YearPicker/__snapshots__/YearPicker.test.js.snap
  packages/components/src/Gesture/withDynamicListGesture.js
  packages/components/src/Gesture/withDynamicListGesture.test.js
Labels: frontend, need review

#1859 feat(containers/list): add order argument to custom sort function
  packages/containers/src/List/selector.js
Labels: easy review, enhancement, frontend, need review

#1846 chore(TUI-307/CMF): DEPRECATED redux-storage
  packages/cmf/__tests__/localStorage.test.js
  packages/cmf/src/bootstrap.md
  packages/cmf/src/index.js
  packages/cmf/src/localStorage.js
  packages/cmf/src/localStorage.md
  packages/cmf/src/reduxstorage/redux-storage-decorator-immutablejs.js
  packages/cmf/src/reduxstorage/reduxLocalStorage.js
  test-setup.js
Labels: need review

#1857 fix(components/SubHeaderBar): data-feature on title edition button
  packages/components/src/EditableText/EditableText.component.js
  packages/components/src/EditableText/EditableText.test.js
  packages/components/src/EditableText/InlineForm.component.js
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js
Labels: easy review, enhancement, need review

#1860 feat(icons): operators
  packages/icons/src/svg/contains.svg
  packages/icons/src/svg/equal.svg
  packages/icons/src/svg/less-than-equal.svg
  packages/icons/src/svg/less-than.svg
  packages/icons/src/svg/more-than-equal.svg
  packages/icons/src/svg/more-than.svg
  packages/icons/src/svg/not-equal.svg
Labels: easy review, need review

#1813 fix(CMF/TUI-291): use spawn to not break all sagas
  packages/cmf/__tests__/sagas/component.test.js
  packages/cmf/src/bootstrap.js
  packages/cmf/src/cmfModule.merge.js
  packages/cmf/src/sagaRouter/index.md
  packages/cmf/src/sagaRouter/router.js
  packages/cmf/src/sagas/component.js
  packages/cmf/src/sagas/index.md
Labels: need review

#1839 fix(component): rework actions css in row large
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
Labels: easy review, need review
