Repository Talend/ui, pull requests merged in 2018-03, with the labels that each got.

#1107 chore(containers): register all components and containers
  output/containers.eslint.txt
  packages/containers/src/register.js
  packages/containers/src/register.test.js
  packages/containers/src/wrap.js
  packages/containers/src/wrap.test.js
Labels: need review

#1112 fix(component/objectviewer): preventdefault on button onClick handler
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.test.js
  packages/components/src/ObjectViewer/JSONLike/__snapshots__/JSONLike.test.js.snap
  packages/components/stories/ObjectViewer.js
Labels: easy review, need review

#1114 feat(Scripts): lint:es command
  packages/scripts/README.md
  packages/scripts/config/webpack.config.js
  packages/scripts/index.js
  packages/scripts/package.json
  packages/scripts/preset/config/.eslintrc
  packages/scripts/preset/preset-talend-eslint.js
  packages/scripts/preset/preset-talend.js
  packages/scripts/scripts/build.js
  packages/scripts/scripts/lint-es.js
  packages/scripts/scripts/start.js
  packages/scripts/scripts/utils/preset.js
  packages/scripts/utils/env.js
  packages/scripts/utils/log.js
  packages/scripts/utils/path-resolver.js
  packages/scripts/utils/preset.js
Labels: frontend, need review

#1115 feat(icons/field-selector): new icon
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/field-selector.svg
Labels: need review

#1111 feat(components/tabbar): rename selected to selectedKey
  BREAKING_CHANGES_LOG.md
  packages/components/src/Drawer/Drawer.test.js
  packages/components/src/Layout/Layout.test.js
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.test.js
  packages/components/stories/Drawer.js
  packages/components/stories/Layout.js
  packages/components/stories/TabBar.js
Labels: easy review, enhancement, need review

#1105 fix(HeaderBar): remove container, use new Inject
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.test.js
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.test.js.snap
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/containers/src/HeaderBar/HeaderBar.component.js
  packages/containers/src/HeaderBar/HeaderBar.test.js
  packages/containers/src/HeaderBar/__snapshots__/HeaderBar.test.js.snap
  packages/containers/src/HeaderBar/index.js
  packages/containers/src/HomeListView/HomeListView.component.js
  packages/containers/src/HomeListView/__snapshots__/HomeListView.test.js.snap
  packages/containers/src/index.js
Labels: easy review, need review

#1097 feat(cmf): add dispatch to props
  output/cmf.eslint.txt
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/cmfConnect.md
  packages/cmf/src/constant.js
Labels: need review

#1084 feat(cmf): add react-cmf-webpack-plugin
  .travis/after_success_lint.sh
  lerna.json
  output/cmf-webpack-plugin.eslint.txt
  package.json
  packages/cmf-webpack-plugin/.babelrc
  packages/cmf-webpack-plugin/.gitignore
  packages/cmf-webpack-plugin/.npmignore
  packages/cmf-webpack-plugin/LICENSE
  packages/cmf-webpack-plugin/README.md
  packages/cmf-webpack-plugin/package.json
  packages/cmf-webpack-plugin/src/index.js
  packages/cmf/package.json
  packages/cmf/scripts/cmf-settings.js
  packages/cmf/scripts/cmf-settings.merge.js
  packages/cmf/scripts/utils/index.js
  version.js
  yarn.lock
Labels: enhancement, need review

#1110 fix(e2e): List stories links
  packages/components/e2e/component-objects/src/test/java/org/talend/component/ListTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/table/TableTest.java
Labels: easy review, need review

#1109 feat(components/containers): PieChartButton
  packages/components/package.json
  packages/components/src/PieChartButton/PieChartButton.component.js
  packages/components/src/PieChartButton/PieChartButton.scss
  packages/components/src/PieChartButton/PieChartButton.test.js
  packages/components/src/PieChartButton/__snapshots__/PieChartButton.test.js.snap
  packages/components/src/PieChartButton/__snapshots__/config.js
  packages/components/src/PieChartButton/index.js
  packages/components/stories/PieChartButton.js
  packages/components/stories/index.js
  packages/containers/examples/ExamplePieChartButton.js
  packages/containers/examples/index.js
  packages/containers/src/PieChartButton/PieChartButton.connect.js
  packages/containers/src/PieChartButton/PieChartButton.test.js
  packages/containers/src/PieChartButton/__snapshots__/PieChartButton.test.js.snap
  packages/containers/src/PieChartButton/index.js
  version.js
  yarn.lock
Labels: need review

#1093 fix(Action): move from actionAPI to props
  BREAKING_CHANGES_LOG.md
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/cmf/src/action.js
  packages/components/src/ActionBar/ActionBar.component.js
  packages/components/src/ActionBar/ActionBar.test.js
  packages/components/src/ActionBar/__snapshots__/ActionBar.snapshot.test.js.snap
  packages/components/src/ActionBar/__snapshots__/ActionBar.test.js.snap
  packages/components/src/ActionList/ActionList.component.js
  packages/components/src/Actions/Action/Action.component.js
  packages/components/src/Actions/Action/Action.test.js
  packages/components/src/Actions/Actions.component.js
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleHeaderBar.js
  packages/containers/src/Action/Action.connect.js
  packages/containers/src/Action/Action.test.js
  packages/containers/src/Action/__snapshots__/Action.test.js.snap
  packages/containers/src/ActionButton/ActionButton.connect.js
  packages/containers/src/ActionDropdown/ActionDropdown.connect.js
  packages/containers/src/ActionFile/ActionFile.connect.js
  packages/containers/src/register.js
  packages/containers/src/wrap.js
  packages/containers/src/wrap.test.js
Labels: need review

#1121 feat(components): Skeleton loading component
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/PieChartButton/PieChartButton.component.js
  packages/components/src/PieChartButton/PieChartButton.scss
  packages/components/src/PieChartButton/__snapshots__/PieChartButton.test.js.snap
  packages/components/src/Skeleton/Skeleton.component.js
  packages/components/src/Skeleton/Skeleton.scss
  packages/components/src/Skeleton/Skeleton.test.js
  packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
  packages/components/src/Skeleton/__snapshots__/config.js
  packages/components/src/Skeleton/index.js
  packages/components/stories/Skeleton.js
  packages/components/stories/index.js
Labels: need review

#1119 fix: expose bootstrap components wrapped in HOC
  output/containers.eslint.txt
  packages/components/src/bootstrap.js
  packages/components/src/index.js
  packages/components/src/wrap.js
  packages/components/src/wrap.test.js
  packages/containers/src/register.js
Labels: need review

#1120 feat(cmf): support simple name in settings props
  packages/cmf/__tests__/settings.test.js
  packages/cmf/src/settings.js
Labels: need review

#1125 chore(components): change const in skeleton & add doc
  packages/components/src/PieChartButton/PieChartButton.component.js
  packages/components/src/Skeleton/Skeleton.component.js
  packages/components/src/Skeleton/Skeleton.md
  packages/components/src/Skeleton/index.js
  packages/components/stories/Skeleton.js
Labels: need review

#1128 fix(component/HeaderBar) :displayName
  output/components.eslint.txt
  packages/components/src/HeaderBar/HeaderBar.component.js
Labels: easy review, need review

#1132 fix(components/sidepanel): fix e2e tests
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/e2e/component-objects/pom.xml
  packages/components/e2e/component-objects/src/main/java/org/talend/component/SidePanel.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/SidePanelTest.java
Labels: need review

#1117 doc(containers/subheaderbar): fix storybook example
  packages/cmf-webpack-plugin/package.json
  packages/components/package.json
  packages/containers/examples/ExampleSubHeaderBar.js
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  version.js
  yarn.lock
Labels: need review

#1139 chore: improve e2e gotostory
  packages/components/e2e/component-objects/src/test/java/org/talend/component/StorybookTest.java
Labels: bug, easy review, enhancement, need review

#1129 fix(HeaderBar): remove useless tooltip, that hides menu
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
Labels: easy review, need review

#1141 fix(components/headerbar): search results container width
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/forms/src/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Labels: bug, easy review, need review

#1136 feat(datagrid): implement onVerticalScroll
  packages/datagrid/README.md
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js
  packages/datagrid/src/components/DataGrid/DataGrid.test.js
  packages/datagrid/src/containers/DataGrid/DataGrid.container.js
  packages/datagrid/src/containers/DataGrid/DataGrid.container.test.js
  packages/datagrid/src/containers/DataGrid/__snapshots__/DataGrid.container.test.js.snap
  packages/datagrid/stories/datagrid.component.js
  packages/datagrid/stories/datagrid.container.js
Labels: enhancement, need review

#1127 feat(datagrid): implement skeleton with the loading state
  BREAKING_CHANGES_LOG.md
  packages/cmf-cqrs/.npmignore
  packages/cmf-cqrs/README.md
  packages/cmf-webpack-plugin/README.md
  packages/cmf/.npmignore
  packages/cmf/README.md
  packages/components/README.md
  packages/components/src/PieChartButton/PieChartButton.component.js
  packages/components/src/PieChartButton/PieChartButton.test.js
  packages/components/src/PieChartButton/__snapshots__/PieChartButton.test.js.snap
  packages/components/src/PieChartButton/__snapshots__/config.js
  packages/components/src/Skeleton/Skeleton.scss
  packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
  packages/components/src/yarn.lock
  packages/components/stories/PieChartButton.js
  packages/components/stories/Skeleton.js
  packages/components/stories/Skeleton.scss
  packages/containers/README.md
  packages/datagrid/README.md
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js
  packages/datagrid/src/components/DataGrid/DataGrid.scss
  packages/datagrid/src/components/DataGrid/DataGrid.test.js
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  packages/datagrid/stories/datagrid.component.js
  packages/datagrid/stories/datagrid.container.js
  packages/forms/README.md
  packages/generator/README.md
  packages/icons/README.md
  packages/logging/README.md
  packages/sagas/README.md
  packages/theme/README.md
  yarn.lock
Labels: enhancement, need review

#1140 feat(cmf): handle params in saga on components
  packages/cmf/__tests__/actions/saga.test.js
  packages/cmf/__tests__/sagas/component.test.js
  packages/cmf/src/actions/saga.js
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/sagas/component.js
  packages/cmf/src/sagas/index.md
Labels: need review

#1135 chore(theme): TDS T7 svg logo
  packages/theme/src/theme/variations/_tds.scss
Labels: easy review, need review

#1142 feat(cmf/http): Add patch method to the api
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
Labels: need review

#1108 feat(components/HeaderBar): app switcher in brand section
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/e2e/component-objects/src/main/java/org/talend/component/AppHeaderBar.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/AppHeaderBarTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/SidePanelTest.java
  packages/components/src/Actions/ActionFile/ActionFile.scss
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/stories/HeaderBar.js
  packages/theme/src/theme/_visual-helpers.scss
  packages/theme/src/theme/variations/_portal.scss
  packages/theme/src/theme/variations/_tdc.scss
  packages/theme/src/theme/variations/_tdp.scss
  packages/theme/src/theme/variations/_tds.scss
  packages/theme/src/theme/variations/_tfd.scss
  packages/theme/src/theme/variations/_tic.scss
  packages/theme/src/theme/variations/_tmc.scss
Labels: need review

#1133 fix(components/ObjectViewer): headers generation
  packages/components/src/ObjectViewer/Table/Table.component.js
  packages/components/src/ObjectViewer/Table/Table.test.js
Labels: easy review, need review

#1150 fix(components/actions): handle undefined getcomponent
  packages/components/src/Actions/Action/Action.component.js
  packages/components/src/Actions/Action/Action.test.js
  packages/components/src/Inject/Inject.component.js
Labels: bug, easy review, enhancement, frontend, help wanted, need review

#1131 feat(forms): add validation check
  packages/forms/README.md
  packages/forms/package.json
  packages/forms/src/validate.js
  packages/forms/src/validate.test.js
  version.js
  yarn.lock
Labels: need review

#1143 chore(components/actionlist): e2e
  .gitignore
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/e2e/component-objects/src/main/java/org/talend/component/ActionList.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/ActionListTest.java
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/stories/ActionList.js
Labels: easy review, enhancement, need review

#1151 feat(cmf): call saga before the didMountActionCreator
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/src/cmfConnect.js
Labels: enhancement

#1153 chores(components/tabs): change the padding of first and last element
  packages/theme/src/theme/_navs.scss
Labels: easy review, need review

#1146 fix(container): change props to fit ActionCreator new api
  packages/containers/src/Slider/Slider.container.js
  packages/containers/src/Slider/Slider.test.js
Labels: need review

#1154 fix(container): change props on filterBar to fit ActionCreator new api
  packages/containers/src/FilterBar/FilterBar.container.js
  packages/containers/src/FilterBar/FilterBar.test.js
Labels: need review

#1157 fix(cmf): persist event when using dispatchActionCreator
  packages/cmf/src/cmfConnect.js
Labels: need review

#1155 chore(e2e): browserstack
  .travis.yml
  .travis/after_success_e2e.sh
  packages/components/e2e/component-objects/README.md
  packages/components/e2e/component-objects/pom.xml
  packages/components/e2e/component-objects/src/test/java/org/talend/component/StorybookTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/BrowserStackWebDriverTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/LocalWebDriverTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/WebDriverTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/WebDriverTestFactory.java
Labels: enhancement, need review

#1156 fix(modal): align with the guidelines
  output/components.sasslint.txt
  packages/components/src/ActionBar/ActionBar.scss
  packages/components/src/ConfirmDialog/ConfirmDialog.component.js
  packages/components/src/ConfirmDialog/ConfirmDialog.scss
  packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
  packages/components/src/Dialog/Dialog.component.js
  packages/components/src/Dialog/__snapshots__/Dialog.test.js.snap
  packages/components/src/Progress/Progress.scss
  packages/theme/example/index.html
  packages/theme/src/theme/_guidelines.scss
  packages/theme/src/theme/_modals.scss
Labels: need review

#1138 fix(forms/datalistwidget): render dropdown on click with an empty list
  packages/forms/src/widgets/DatalistWidget/DatalistWidget.js
  packages/forms/src/widgets/DatalistWidget/DatalistWidget.test.js
  packages/forms/src/widgets/DatalistWidget/__snapshots__/DatalistWidget.test.js.snap
  packages/forms/stories/index.js
Labels: need review

#1161 chore(e2e): browserstack
  .travis.yml
  .travis/after_success_e2e.sh
  packages/components/e2e/component-objects/README.md
  packages/components/e2e/component-objects/pom.xml
  packages/components/e2e/component-objects/src/test/java/org/talend/component/StorybookTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/BrowserStackWebDriverTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/LocalWebDriverTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/WebDriverTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/WebDriverTestFactory.java
Labels: enhancement, need review

#1060 fix(components/breadcrumb): e2e
  packages/components/e2e/component-objects/src/main/java/org/talend/component/Breadcrumb.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/BreadcrumbMaxReachedTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/BreadcrumbTest.java
  packages/components/e2e/component-objects/src/test/resources/log4j2.xml
  packages/components/src/Breadcrumbs/Breadcrumbs.component.js
  packages/components/src/Breadcrumbs/Breadcrumbs.scss
  packages/components/src/Breadcrumbs/__snapshots__/Breadcrumbs.snapshot.test.js.snap
  packages/theme/src/theme/_breadcrumbs.scss
Labels: enhancement, need review

#1158 fix(components/headerbar): search results title container width
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/stories/HeaderBar.js
Labels: bug, easy review, need review

#1162 fix(components/headerbar): remove onclick when app switcher has products
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/stories/HeaderBar.js
Labels: bug, easy review, need review

#1144 chore(e2e): accept id in e2e components constructors
  packages/components/e2e/component-objects/src/main/java/org/talend/component/ActionList.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/AppHeaderBar.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/Breadcrumb.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/ConfirmDialog.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/Drawer.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/List.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/SidePanel.java
Labels: easy review, enhancement, need review

#1163 fix(component/wrap): remove some attributes and explain why
  packages/components/src/wrap.js
  packages/components/src/wrap.test.js
  packages/generator/package.json
Labels: easy review, need review

#1160 fix(components/SidePanel): Adds top padding
  packages/components/src/SidePanel/SidePanel.scss
Labels: bug, easy review, enhancement, need review

#1134 chore(components/tabbar): e2e
  packages/components/e2e/component-objects/src/main/java/org/talend/component/TabBar.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/TabBarTest.java
Labels: easy review, enhancement, need review

#1168 feat(datagrid): allow to resize columns
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.scss
  packages/datagrid/src/containers/DataGrid/__snapshots__/DataGrid.container.test.js.snap
  packages/datagrid/stories/datagrid.component.js
Labels: need review

#1173 feat(datagrid): allow to customize the empty data message
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  packages/datagrid/stories/datagrid.component.js
Labels: easy review, need review

#1172 chore(cmf/httpmiddleware): adding additional headers
  packages/cmf/__tests__/middlewares/csrfHandling.test.js
  packages/cmf/__tests__/middlewares/http.test.js
  packages/cmf/src/middlewares/http/csrfHandling.js
  packages/cmf/src/middlewares/http/index.md
  packages/cmf/src/middlewares/http/middleware.js
  packages/cmf/src/sagas/http.js
Labels: need review

#1175 fix(datagrid): fix error when the schema change
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
  packages/datagrid/stories/datagrid.component.js
  packages/datagrid/stories/sample2.json
Labels: easy review, need review

#1174 feat(datagrid): add startindex for default serializer
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js
  packages/datagrid/src/components/DataGrid/DataGrid.test.js
  packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/src/containers/DataGrid/__snapshots__/DataGrid.container.test.js.snap
  packages/datagrid/stories/datagrid.component.js
Labels: easy review, need review

#1165 fix(CMF): Register internal expressions
  packages/cmf/__tests__/api.test.js
  packages/cmf/src/api.js
Labels: easy review, need review

#1177 fix(SidePanel/theme): side panel + nav-pills style, with anchors
  packages/components/src/ActionList/ActionList.scss
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/src/SidePanel/SidePanel.component.js
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/stories/ActionList.js
  packages/components/stories/SidePanel.js
  packages/theme/example/index.html
  packages/theme/src/theme/_navs.scss
  packages/theme/src/theme/_visual-helpers.scss
Labels: frontend, need review

#1167 feat(cmf): allow to register sagas on components
  packages/cmf/__tests__/component.test.js
  packages/cmf/src/component.js
Labels: need review

#1159 fix(components/Dialog): spread props [BR]
  packages/components/src/Dialog/Dialog.component.js
  packages/components/src/Dialog/Dialog.test.js
  packages/components/src/Dialog/DialogModalProps.test.js
  packages/components/src/Dialog/__snapshots__/Dialog.test.js.snap
  packages/components/src/Dialog/__snapshots__/DialogModalProps.test.js.snap
Labels: need review

#1130 chore(ui): update process to hightlight a breaking change
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, need review

#1180 feat(List): keep filter icon displayed when expanded
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/FilterBar/FilterBar.test.js
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/stories/FilterBar.js
  packages/containers/src/FilterBar/__snapshots__/FilterBar.test.js.snap
Labels: need review

#1094 fix(theme): form fields styling according to the guideline
  output/theme.sasslint.txt
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.scss
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.js
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.scss
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.test.js
  packages/forms/stories/json/multiSelectTag.json
  packages/theme/example/index.html
  packages/theme/src/theme/_forms.scss
Labels: need review

#1184 fix(forms/datalist): data lost after onblur the input
  packages/forms/src/widgets/DatalistWidget/DatalistWidget.js
  packages/forms/src/widgets/DatalistWidget/DatalistWidget.test.js
Labels: bug, need review

#1147 chore(e2e): headerbar + notifications + large display
  packages/components/e2e/component-objects/pom.xml
  packages/components/e2e/component-objects/src/main/java/org/talend/component/AppHeaderBar.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/Application.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/ConfirmDialog.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/List.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/Notification.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/Cell.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/Display.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/Item.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/ListDisplay.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/display/Large.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/display/Table.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/table/Table.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/AppHeaderBarTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/ListTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/NotificationTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/LargeTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/TableTest.java
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/stories/HeaderBar.js
Labels: need review

#1183 fix: add checking on instanceOf Array, and fix some prop-types
  packages/components/src/Enumeration/Items/Item/Item.component.js
  packages/components/src/Enumeration/Items/Item/Item.test.js
  packages/components/src/Enumeration/Items/Item/item.snapshot.test.js
  packages/containers/src/List/List.container.js
Labels: easy review, need review

#1185 feat(icons): Add credits-engine icons
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/credits-engine.svg
Labels: need review

#1169 fix(icons): update tmc-colored.svg
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/tmc-colored.svg
Labels: need review

#1187 fix(components/e2e): tabbar constructors should be public
  packages/components/e2e/component-objects/src/main/java/org/talend/component/TabBar.java
Labels: bug, easy review, need review

#1113 chore(component/datalist) : extracting the component from form
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/src/Datalist/Datalist.scss
  packages/components/src/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/components/src/Datalist/index.js
  packages/components/src/index.js
  packages/components/stories/Datalist.js
  packages/components/stories/index.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.scss
  packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
Labels: need review

#1170 fix(icons): update tic-colored.svg
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/tic-colored.svg
Labels: need review

#1190 fix(SidePanel): colors managed in the component
  packages/components/src/Layout/TwoColumns/TwoColumns.scss
  packages/components/src/SidePanel/SidePanel.scss
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/stories/SidePanel.js
  packages/containers/.storybook/preview-head.html
Labels: easy review, frontend, need review

#1189 feat(components/Actions): pass through all aria and data attributes
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/src/Actions/ActionButton/ActionButton.test.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/components/src/Actions/ActionDropdown/ActionDropdown.test.js
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.test.js.snap
  packages/components/src/Actions/ActionFile/ActionFile.test.js
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.test.js
  packages/components/src/Actions/ActionIconToggle/__snapshots__/ActionIconToggle.component.test.js.snap
  packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.test.js
  packages/components/src/Actions/ActionSplitDropdown/__snapshots__/ActionSplitDropdown.test.js.snap
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
  packages/components/src/utils/getPropsFrom.js
  packages/components/src/utils/getPropsFrom.test.js
  packages/components/stories/Action.js
  packages/components/stories/ActionBar.js
  packages/components/stories/ActionDropdown.js
  packages/components/stories/ActionFile.js
  packages/components/stories/ActionIconToggle.js
  packages/components/stories/ActionList.js
  packages/components/stories/ActionSplitDropdown.js
  packages/components/stories/Actions.js
  packages/components/stories/VirtualizedList.js
  packages/forms/stories-core/customActionsStory.js
  packages/forms/stories-core/json/fields/core-buttons.json
  packages/forms/stories/index.js
Labels: easy review, enhancement, need review

#1171 feat(theme/loader): css app loader for the application launch page
  packages/cmf/__tests__/App.test.js
  packages/cmf/src/App.js
  packages/cmf/src/App.md
  packages/cmf/src/UIRouter.js
  packages/components/src/AppLoader/AppLoader.component.js
  packages/components/src/AppLoader/AppLoader.md
  packages/components/src/AppLoader/AppLoader.test.js
  packages/components/src/AppLoader/__snapshots__/AppLoader.test.js.snap
  packages/components/src/AppLoader/constant.js
  packages/components/src/AppLoader/index.js
  packages/components/src/Loader/Loader.md
  packages/components/src/index.js
  packages/components/stories/AppLoader.js
  packages/components/stories/Loader.js
  packages/components/stories/index.js
  packages/theme/src/theme/_variables.scss
Labels: need review

#1193 feat(scripts): add screenshots compare CLI
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  packages/theme/screenshots.config.json
  packages/theme/screenshots/alerts.png
  packages/theme/screenshots/badges.png
  packages/theme/screenshots/breadcrumbs.png
  packages/theme/screenshots/btn-dropup-icons.png
  packages/theme/screenshots/btn-sizes-icons.png
  packages/theme/screenshots/button-groups.png
  packages/theme/screenshots/button-sizes.png
  packages/theme/screenshots/buttons-dropdowns-icons.png
  packages/theme/screenshots/buttons-left-icons.png
  packages/theme/screenshots/buttons-no-icons.png
  packages/theme/screenshots/buttons-right-icons.png
  packages/theme/screenshots/buttons.png
  packages/theme/screenshots/buttons_disabled.png
  packages/theme/screenshots/dropdowns.png
  packages/theme/screenshots/form-inputs.png
  packages/theme/screenshots/forms.png
  packages/theme/screenshots/jumbotron.png
  packages/theme/screenshots/labels.png
  packages/theme/screenshots/list-groups.png
  packages/theme/screenshots/modals.png
  packages/theme/screenshots/nav-tabs-justified.png
  packages/theme/screenshots/nav-tabs.png
  packages/theme/screenshots/nav_pills-default.png
  packages/theme/screenshots/nav_pills-inverse.png
  packages/theme/screenshots/nav_pills-nav_stacked-default.png
  packages/theme/screenshots/nav_pills-nav_stacked-inverse.png
  packages/theme/screenshots/navbar-default.png
  packages/theme/screenshots/navbar-inverse.png
  packages/theme/screenshots/pager.png
  packages/theme/screenshots/pagination.png
  packages/theme/screenshots/panels.png
  packages/theme/screenshots/popovers.png
  packages/theme/screenshots/progress-alternatives.png
  packages/theme/screenshots/progress-basic.png
  packages/theme/screenshots/progress-stacked.png
  packages/theme/screenshots/progress-striped.png
  packages/theme/screenshots/tables.png
  packages/theme/screenshots/tooltips.png
  packages/theme/screenshots/typography.png
  packages/theme/screenshots/wells.png
  screenshots.js
  screenshots.json
  screenshots.md
  yarn.lock
Labels: need review

#1191 fix(Inject): pass props from inject.all
  packages/components/src/Inject/Inject.component.js
  packages/components/src/Inject/Inject.md
  packages/components/src/Inject/Inject.test.js
Labels: bug, need review

#1197 fix(icons): fix aws-kinesis none-zero attribute value
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/aws-kinesis.svg
Labels: frontend, need review

#1192 fix(i18n-form) : add mapping for the prop language in form container
  output/containers.eslint.txt
  packages/containers/src/Form/Form.container.js
  packages/containers/src/Form/Form.test.js
  packages/containers/src/Form/__snapshots__/Form.test.js.snap
Labels: easy review, need review

#1198 fix(cmf): invariant condition for 'register undefined as component' error
  packages/cmf/src/component.js
  packages/cmf/src/sagas/component.js
Labels: bug, easy review, need review

#1186 feat(cmf): add onEventSetState
  output/cmf.eslint.txt
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/__tests__/onEvent.test.js
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/componentState.js
  packages/cmf/src/constant.js
  packages/cmf/src/onEvent.js
  packages/cmf/src/onEvent.md
Labels: need review

#1196 chore(icons): travis run svgo on PRs
  .travis/before_script_icons.sh
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/aws-kinesis.svg
  packages/icons/src/svg/bigquery.svg
  packages/icons/src/svg/campaigns.svg
  packages/icons/src/svg/component-kit-negative.svg
  packages/icons/src/svg/component-kit-positive.svg
  packages/icons/src/svg/credits-engine.svg
  packages/icons/src/svg/data-models.svg
  packages/icons/src/svg/datagrid.svg
  packages/icons/src/svg/eye-slash.svg
  packages/icons/src/svg/field-selector.svg
  packages/icons/src/svg/filter-column.svg
  packages/icons/src/svg/google-dataflow.svg
  packages/icons/src/svg/hierarchical-view.svg
  packages/icons/src/svg/info-circle.svg
  packages/icons/src/svg/logo-square.svg
  packages/icons/src/svg/logo.svg
  packages/icons/src/svg/mdm-colored.svg
  packages/icons/src/svg/mdm-negative.svg
  packages/icons/src/svg/mdm-positive.svg
  packages/icons/src/svg/panel-opener-bottom.svg
  packages/icons/src/svg/panel-opener-right.svg
  packages/icons/src/svg/question-circle.svg
  packages/icons/src/svg/raw-data.svg
  packages/icons/src/svg/sharing-default.svg
  packages/icons/src/svg/sharing-owner.svg
  packages/icons/src/svg/sharing-user.svg
Labels: frontend, need review

#1200 fix(icons): update sharing-owner, sharing-user icons
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/sharing-owner.svg
  packages/icons/src/svg/sharing-user.svg
  packages/icons/src/talendicons.css
Labels: bug, need review

#1203 fix(Datalist): remove form from component
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/__snapshots__/Datalist.component.test.js.snap
Labels: easy review, frontend, need review

#1148 feat(SubHeaderBar): add loading feedback
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/Layout/__snapshots__/Layout.test.js.snap
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.component.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.test.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/__snapshots__/InputTitleSubHeader.test.js.snap
  packages/components/src/SubHeaderBar/SubHeaderBar.component.js
  packages/components/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap
  packages/components/stories/SubHeaderBar.js
  packages/containers/examples/ExampleSubHeaderBar.js
  packages/containers/src/SubHeaderBar/SubHeaderBar.container.js
Labels: need review

#1208 fix(theme): fix filter bar styling in forms
  output/theme.sasslint.txt
  packages/theme/src/theme/_forms.scss
Labels: need review

#1199 chore(component/datalist): fixing display on ie and edge
  packages/components/src/Datalist/Datalist.scss
Labels: easy review

#1210 fix(cmf/httpMiddleware): override default headers
  packages/cmf/__tests__/middlewares/http.test.js
  packages/cmf/src/middlewares/http/middleware.js
Labels: easy review, need review

#1213 fix(HeaderBar): remove username text transformation
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
Labels: easy review, frontend, need review

#1215 fix(TFD-3270): Center InputTitleSubHeader icon in Edge
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss
Labels: need review

#1212 fix(forms): apply border styling for form input fields in focus
  output/theme.sasslint.txt
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.scss
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.scss
  packages/theme/src/theme/_forms.scss
Labels: need review

#1216 feat(datagrid): update ag-grid to 17.0.0
  packages/datagrid/package.json
  yarn.lock
Labels: easy review, enhancement, need review

#1221 chore(screenshots/test:nonreg): update CLI to use a folder of json
  screenshots.js
  screenshots.json
  screenshots/components.json
  screenshots/forms-core-concepts.json
  screenshots/forms-core-fields.json
  screenshots/forms-core-fieldsets.json
  screenshots/theme.json
Labels: need review

#1188 feat: add custom format to UIForm
  output/containers.eslint.txt
  packages/containers/src/Form/Form.container.js
  packages/containers/src/Form/Form.test.js
  packages/containers/src/Form/__snapshots__/Form.test.js.snap
  packages/forms/src/Form.js
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/__snapshots__/UIForm.container.test.js.snap
  packages/forms/src/UIForm/customFormats.js
  packages/forms/src/UIForm/customFormats.test.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/constants.js
  packages/forms/src/templates/ArrayFieldTemplate.js
  packages/forms/src/validate.js
  packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js
  packages/forms/src/widgets/ListViewWidget/ListViewWidget.js
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.js
  packages/forms/stories-core/json/concepts/core-format-validation.json
Labels: need review

#1209 feat(icons): tdp-colored
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/tdp-colored.svg
Labels: easy review, need review

#1222 chore(test:nonreg): add badge breadcrumb and collapsible
  packages/components/stories/Badge.js
  packages/components/stories/CollapsiblePanel.js
  screenshots.js
  screenshots/components-actions.json
  screenshots/components-badge.json
  screenshots/components-breadcrumbs.json
  screenshots/components-collapsiblepanel.json
  screenshots/components-subheader.json
Labels: need review

#1218 fix(component/datalist): checking if value exist on update
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/stories/Datalist.js
  packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
Labels: easy review, need review

#1220 fix(components): Action instead of Button from react-bootstrap
  packages/components/src/Breadcrumbs/Breadcrumbs.component.js
  packages/components/src/ListView/Items/Item/Item.component.js
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/ListView/Items/items.test.js
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitle.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleSelector.test.js.snap
  packages/components/src/VirtualizedList/RowLarge/__snapshots__/RowLarge.test.js.snap
  packages/components/stories/ListView.js
  screenshots/components-listview.json
Labels: easy review, need review

#1224 fix: translated skeleton type is extracted correctly
  packages/components/src/Skeleton/Skeleton.component.js
Labels: easy review, frontend, need review

#1219 feat(containers): Add TabBar container
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleTabBar.js
  packages/containers/examples/index.js
  packages/containers/src/TabBar/TabBar.connect.js
  packages/containers/src/TabBar/TabBar.container.js
  packages/containers/src/TabBar/TabBar.selectors.js
  packages/containers/src/TabBar/TabBar.test.js
  packages/containers/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/containers/src/TabBar/index.js
  packages/containers/src/index.js
Labels: need review

#1223 fix(components) : inputTitleSubHeader not visible on ie11
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss
Labels: easy review, need review
