Repository Talend/ui, pull requests merged in 2018-09, with the labels that each got.

#1656 fix(UIForms): datalist alignement
  output/theme.sasslint.txt
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.scss
  packages/components/src/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/forms/stories-core/json/fieldsets/core-columns.json
  packages/theme/src/theme/_forms.scss
Labels: easy review, frontend, need review

#1655 feat(theme): Add MDM application theme variation
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/Layout/constants.js
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/stories/config/themes.scss
  packages/theme/src/theme/variations/_mdm.scss
Labels: easy review, frontend, need review

#1651 feat: add skeleton loading for right actions in subheader
  packages/components/src/SubHeaderBar/SubHeaderBar.component.js
  packages/components/src/SubHeaderBar/SubHeaderBar.md
  packages/components/src/SubHeaderBar/SubHeaderBar.test.js
  packages/components/stories/SubHeaderBar.js
Labels: need review

#1666 fix(theme): MDM new application brand-secondary theme variation
  packages/theme/src/theme/variations/_mdm.scss
Labels: easy review, frontend, need review

#1668 fix(Storybook): forms listview
  packages/forms/stories/json/listView.json
Labels: easy review, frontend, need review

#1605 feat(containers/ComponentForm): add csrf token
  orga.md
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.md
  packages/containers/src/ComponentForm/ComponentForm.test.js
  packages/containers/src/ComponentForm/kit/createTriggers.js
  packages/containers/src/ComponentForm/kit/createTriggers.test.js
Labels: need review

#1670 chore(TUI-133): yarn start
  README.md
  package.json
Labels: easy review, need review

#1654 feat(UIForms): improve a11y
  output/forms.eslint.txt
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.snapshot.test.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/forms/package.json
  packages/forms/src/UIForm/Message/Message.component.js
  packages/forms/src/UIForm/Message/Message.component.test.js
  packages/forms/src/UIForm/Message/__snapshots__/Message.component.test.js.snap
  packages/forms/src/UIForm/Message/generateId.js
  packages/forms/src/UIForm/Message/generateId.test.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.component.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.test.js
  packages/forms/src/UIForm/fields/CheckBox/__snapshots__/CheckBox.test.js.snap
  packages/forms/src/UIForm/fields/CheckBox/__snapshots__/CheckBoxes.test.js.snap
  packages/forms/src/UIForm/fields/CheckBox/__snapshots__/SimpleCheckBox.test.js.snap
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js
  packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.js
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.test.js
  packages/forms/src/UIForm/fields/FieldTemplate/__snapshots__/FieldTemplate.component.test.js.snap
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js
  packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap
  packages/forms/src/UIForm/fields/Radios/Radios.component.js
  packages/forms/src/UIForm/fields/Radios/Radios.component.test.js
  packages/forms/src/UIForm/fields/Radios/__snapshots__/Radios.component.test.js.snap
  packages/forms/src/UIForm/fields/Select/Select.component.js
  packages/forms/src/UIForm/fields/Select/Select.component.test.js
  packages/forms/src/UIForm/fields/Select/__snapshots__/Select.component.test.js.snap
  packages/forms/src/UIForm/fields/Text/Text.component.js
  packages/forms/src/UIForm/fields/Text/Text.component.test.js
  packages/forms/src/UIForm/fields/Text/__snapshots__/Text.component.test.js.snap
  packages/forms/src/UIForm/fields/TextArea/TextArea.component.js
  packages/forms/src/UIForm/fields/TextArea/TextArea.component.test.js
  packages/forms/src/UIForm/fields/TextArea/__snapshots__/TextArea.component.test.js.snap
  packages/forms/src/UIForm/fields/Toggle/Toggle.component.js
  packages/forms/src/UIForm/fields/Toggle/Toggle.component.test.js
  packages/forms/src/UIForm/fields/Toggle/__snapshots__/Toggle.component.test.js.snap
Labels: frontend, need review

#1665 feat(components): new list style
  packages/components/src/List/List.scss
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/ListTable/ListTable.component.js
  packages/components/src/VirtualizedList/ListTable/ListTable.scss
  packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap
Labels: need review

#1673 Revert "feat(components): new list style (#1665)"
  packages/components/src/List/List.scss
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/ListTable/ListTable.component.js
  packages/components/src/VirtualizedList/ListTable/ListTable.scss
  packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap
Labels: easy review, frontend, need review

#1676 fix(ListView) Remove useless scrollbars
  packages/components/src/ListView/Items/Items.scss
Labels: easy review, need review

#1667 fix(UIForms/TUI-197): nested array items key has now the indexes
  packages/forms/src/UIForm/fieldsets/Array/Array.component.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js
Labels: easy review, frontend, need review

#1672 feat(ListView): improve a11y
  output/forms.eslint.txt
  packages/components/src/ListView/Items/Item/Item.component.js
  packages/components/src/ListView/Items/Item/Item.scss
  packages/components/src/ListView/Items/Item/__snapshots__/item.snapshot.test.js.snap
  packages/components/src/ListView/Items/Items.component.js
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/ListView/ListView.component.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.js
  packages/forms/src/UIForm/fields/ListView/__snapshots__/ListView.component.test.js.snap
Labels: frontend, need review

#1677 fix(Components/Slider): onFocus throw a onChange event
  packages/components/src/Slider/Slider.scss
Labels: need review

#1674 feat(containers/TUI-189): add trigger to update properties
  packages/containers/sandbox/mockBackend/kit.js
  packages/containers/sandbox/mockBackend/mock/kit/titleMap.json
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.md
  packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap
  packages/containers/src/ComponentForm/kit/defaultRegistry.js
  packages/containers/src/ComponentForm/kit/defaultRegistry.md
  packages/containers/src/ComponentForm/kit/defaultRegistry.test.js
Labels: need review

#1650 feat(Treeview): improve a11y
  packages/components/src/Badge/Badge.component.js
  packages/components/src/TreeView/TreeView.component.js
  packages/components/src/TreeView/TreeView.scss
  packages/components/src/TreeView/TreeView.test.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.scss
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.test.js
  packages/components/src/TreeView/TreeViewItem/__snapshots__/TreeViewItem.test.js.snap
  packages/components/src/TreeView/TreeViewItem/index.js
  packages/components/src/TreeView/__snapshots__/TreeView.test.js.snap
  packages/components/src/polyfills/element-closest.js
  packages/components/src/utils/getPropsFrom.js
  packages/components/src/utils/getPropsFrom.test.js
  packages/components/stories/TreeView.js
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleTreeView.js
  packages/containers/src/SelectObject/SelectObject.container.js
  packages/containers/src/TreeView/TreeView.container.js
  packages/containers/src/TreeView/TreeView.test.js
  packages/containers/src/TreeView/__snapshots__/TreeView.test.js.snap
  test-setup.js
  yarn.lock
Labels: frontend, need review

#1675 chore(components/containers): optimize lodash import
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.component.js
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.test.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/stories/List.js
  packages/containers/examples/ExampleList.js
Labels: need review

#1491 chore(TUI-81): add npm audit command
  .gitignore
  .npmignore
  .travis.yml
  .travis/after_success_git.sh
  npm-audit/audit.json
  npm-audit/package-lock.json
  npm-audit/package.json
  package.json
  versions/dependencies.js
  versions/generate-version-audit.js
  versions/version.js
Labels: frontend, need review

#1685 chore: fix CI react 15 job
  .travis.yml
  npm-audit/audit.json
Labels: easy review, frontend, need review

#1679 fix(components/virtualizedlist): Actions dropdowns
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/stories/VirtualizedList.js
Labels: easy review, need review

#1669 feat(containers/DeleteResource): Add `onCancelRedirectUrl` prop
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/README.md
  packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap
  packages/containers/src/DeleteResource/sagas.js
  packages/containers/src/DeleteResource/sagas.test.js
Labels: need review

#1684 fix(components/confirmdialog): call cancel onclick when hiding modal
  packages/components/src/AboutDialog/__snapshots__/AboutDialog.snapshot.test.js.snap
  packages/components/src/ConfirmDialog/ConfirmDialog.component.js
  packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
  packages/components/src/Dialog/Dialog.component.js
  packages/components/stories/Dialog.css
  packages/components/stories/Dialog.js
Labels: easy review, need review

#1687 fix(components/VirtualizedList): fix focus outline
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
Labels: need review

#1692 fix(component): remove two proptypes warnings
  packages/components/src/EditableText/EditableText.component.js
Labels: need review

#1694 fix(containers/DeleteResource): Add onHide handler
  packages/components/src/ConfirmDialog/ConfirmDialog.component.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap
Labels: easy review, need review

#1695 fix(ComponentKit): include objects and arrays in payload flatten
  packages/containers/src/ComponentForm/kit/flatten.js
  packages/containers/src/ComponentForm/kit/flatten.test.js
Labels: easy review, frontend, need review

#1641 feat(component/TabBar): improve a11y
  .travis.yml
  packages/components/e2e/component-objects/src/main/java/org/talend/component/TabBar.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/TabBarTest.java
  packages/components/src/Drawer/Drawer.test.js
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/Layout/Layout.test.js
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/src/TabBar/TabBar.snapshot.test.js
  packages/components/src/TabBar/TabBar.test.js
  packages/components/src/TabBar/__snapshots__/TabBar.snapshot.test.js.snap
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/components/src/TabBar/__snapshots__/config.js
  packages/components/stories/TabBar.js
  packages/theme/src/theme/_navs.scss
Labels: frontend, need review

#1660 feat(forms/conditions/TCOMP-1029): add jsonLogic condition [BREAKING CHANGE]
  packages/forms/package.json
  packages/forms/src/UIForm/README.md
  packages/forms/src/UIForm/Widget/Widget.component.test.js
  packages/forms/src/UIForm/Widget/condition.js
  packages/forms/src/UIForm/Widget/condition.test.js
  yarn.lock
Labels: need review

#1701 fix(components) Fix linting errors
  output/components.eslint.txt
  packages/components/src/ActionList/__snapshots__/config.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.test.js
  packages/components/src/HeaderBar/__snapshots__/config.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/RichTooltip/RichTooltip.test.js
  packages/components/src/SidePanel/__snapshots__/config.js
Labels: easy review, need review

#1686 feat(forms): UIForms-Datalist : manage multi section
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js
  packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/forms/stories-core/json/fields/core-datalist.json
Labels: need review

#1690 fix(components/List): flicking list
  packages/components/src/List/List.scss
Labels: easy review, need review

#1697 feat(UIForm): import Code widget a11y
  packages/forms/src/UIForm/Message/generateId.js
  packages/forms/src/UIForm/Message/generateId.test.js
  packages/forms/src/UIForm/fields/Code/Code.component.js
  packages/forms/src/UIForm/fields/Code/Code.component.test.js
  packages/forms/src/UIForm/fields/Code/__snapshots__/Code.component.test.js.snap
Labels: frontend, need review

#1699 feat(UIForm): improve tabs widget a11y
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.test.js
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/forms/src/UIForm/fieldsets/Tabs/Tabs.component.js
  packages/forms/src/UIForm/fieldsets/Tabs/Tabs.component.test.js
  packages/forms/src/UIForm/fieldsets/Tabs/Tabs.scss
  packages/forms/src/UIForm/fieldsets/Tabs/__snapshots__/Tabs.component.test.js.snap
Labels: frontend, need review

#1616 feat(ObjectViewer): improve a11y
  output/components.eslint.txt
  packages/components/__mocks__/tree.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.scss
  packages/components/src/ObjectViewer/JSONLike/JSONLike.test.js
  packages/components/src/ObjectViewer/JSONLike/__snapshots__/JSONLike.test.js.snap
  packages/components/src/ObjectViewer/List/List.component.js
  packages/components/src/ObjectViewer/List/List.test.js
  packages/components/src/ObjectViewer/List/__snapshots__/List.test.js.snap
  packages/components/src/ObjectViewer/ObjectViewer.test.js
  packages/components/src/ObjectViewer/Table/Table.component.js
  packages/components/src/ObjectViewer/Table/Table.test.js
  packages/components/src/ObjectViewer/Table/__snapshots__/Table.test.js.snap
  packages/components/src/Tree/index.js
  packages/components/src/Tree/withTreeGesture.js
  packages/components/src/Tree/withTreeGesture.test.js
  packages/components/src/TreeView/TreeView.component.js
  packages/components/src/TreeView/TreeView.test.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.test.js
  packages/components/src/TreeView/TreeViewItem/__snapshots__/TreeViewItem.test.js.snap
  packages/components/src/TreeView/__snapshots__/TreeView.test.js.snap
  packages/components/stories/ObjectViewer.js
  packages/components/stories/TreeView.js
  packages/containers/examples/ExampleTreeView.js
  packages/containers/src/ObjectViewer/ObjectViewer.container.js
  packages/containers/src/ObjectViewer/ObjectViewer.test.js
  packages/containers/src/TreeView/TreeView.container.js
  packages/containers/src/TreeView/TreeView.test.js
  packages/containers/src/TreeView/__snapshots__/TreeView.test.js.snap
  packages/theme/src/theme/_variables.scss
Labels: frontend, need review

#1706 fix(icons): remove hardcoded color
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/word.svg
Labels: easy review, need review

#1705 fix(cmf/TUI-222): remove propTypes spread in cmfConnect
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/src/cmfConnect.js
Labels: easy review, frontend, need review, proptypes warning

#1704 fix(cmf): missing namespace
  packages/cmf/scripts/cmf-settings.i18n.js
Labels: bug, need review

#1708 feat(uiform): skip validation for hidden field via condition
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/utils/condition.js
  packages/forms/src/UIForm/utils/condition.test.js
  packages/forms/src/UIForm/utils/validation.js
  packages/forms/src/UIForm/utils/validation.test.js
Labels: need review

#1709 feat(generators): add register in index + create settings json
  packages/generator/generators/react-component/index.js
  packages/generator/generators/react-component/parser.js
  packages/generator/generators/react-component/templates/src/connect.component.js
  packages/generator/generators/react-component/templates/src/connect.test.js
  packages/generator/generators/react-component/templates/src/es6.arrow.component.js
  packages/generator/generators/react-component/templates/src/es6.class.component.js
  packages/generator/generators/react-component/templates/src/full.connect.js
  packages/generator/generators/react-component/templates/src/settings.json
  packages/generator/generators/react-component/templates/src/stateless.component.js
  packages/generator/package.json
  packages/generator/test/react-component.js
  packages/generator/test/template_index_js.txt
  yarn.lock
Labels: need review

#1707 feat(datagrid): other type render like string
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/AvroRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/AvroRenderer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/AvroRenderer.test.js.snap
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultValueRenderer.test.js.snap
  packages/datagrid/src/constants/avro-type.constant.js
  packages/datagrid/src/constants/index.js
  packages/datagrid/stories/datagrid.component.js
  packages/datagrid/stories/sample.json
Labels: enhancement, need review

#1713 fix(ObjectViewer): select and toggle by click
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.test.js
  packages/components/src/ObjectViewer/JSONLike/__snapshots__/JSONLike.test.js.snap
  packages/components/src/Tree/withTreeGesture.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.test.js
  packages/components/src/TreeView/__snapshots__/TreeView.test.js.snap
Labels: frontend, need review

#1712 feat(ObjectViewer): improve a11y (#1616)
  output/components.eslint.txt
  packages/components/__mocks__/tree.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.scss
  packages/components/src/ObjectViewer/JSONLike/JSONLike.test.js
  packages/components/src/ObjectViewer/JSONLike/__snapshots__/JSONLike.test.js.snap
  packages/components/src/ObjectViewer/List/List.component.js
  packages/components/src/ObjectViewer/List/List.test.js
  packages/components/src/ObjectViewer/List/__snapshots__/List.test.js.snap
  packages/components/src/ObjectViewer/ObjectViewer.test.js
  packages/components/src/ObjectViewer/Table/Table.component.js
  packages/components/src/ObjectViewer/Table/Table.test.js
  packages/components/src/ObjectViewer/Table/__snapshots__/Table.test.js.snap
  packages/components/src/Tree/index.js
  packages/components/src/Tree/withTreeGesture.js
  packages/components/src/Tree/withTreeGesture.test.js
  packages/components/src/TreeView/TreeView.component.js
  packages/components/src/TreeView/TreeView.test.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.test.js
  packages/components/src/TreeView/TreeViewItem/__snapshots__/TreeViewItem.test.js.snap
  packages/components/src/TreeView/__snapshots__/TreeView.test.js.snap
  packages/components/stories/ObjectViewer.js
  packages/components/stories/TreeView.js
  packages/containers/examples/ExampleTreeView.js
  packages/containers/src/ObjectViewer/ObjectViewer.container.js
  packages/containers/src/ObjectViewer/ObjectViewer.test.js
  packages/containers/src/TreeView/TreeView.container.js
  packages/containers/src/TreeView/TreeView.test.js
  packages/containers/src/TreeView/__snapshots__/TreeView.test.js.snap
  packages/theme/src/theme/_variables.scss
Labels: frontend

#1636 fix(List): alignment issues
  packages/components/src/List/Toolbar/SelectAll/SelectAll.scss
  packages/theme/src/theme/_forms.checkbox.scss
Labels: easy review, need review

#1702 feat(List/Large): improve a11y
  output/components.eslint.txt
  packages/components/__mocks__/list.js
  packages/components/src/Gesture/index.js
  packages/components/src/Gesture/withListGesture.js
  packages/components/src/Gesture/withListGesture.test.js
  packages/components/src/Gesture/withTreeGesture.js
  packages/components/src/Gesture/withTreeGesture.test.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/Tree/index.js
  packages/components/src/TreeView/TreeView.component.js
  packages/components/src/TreeView/TreeViewItem/index.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.test.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
  packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js
  packages/components/src/VirtualizedList/ListGrid/ListGrid.test.js
  packages/components/src/VirtualizedList/ListGrid/__snapshots__/ListGrid.test.js.snap
  packages/components/src/VirtualizedList/RendererSelector.test.js
  packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
  packages/components/src/VirtualizedList/RowLarge/__snapshots__/RowLarge.test.js.snap
Labels: frontend, need review

#1716 feat(uiform): keep the errors provide by triggers during onSubmit
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
Labels: easy review, need review

#1715 feat(theme): new jaffa color
  packages/theme/src/theme/_colors.scss
Labels: easy review, frontend, need review

#1714 fix(TUI-233): ensure conditional rendering with array indices resolution
  npm-audit/audit.json
  output/forms.eslint.txt
  packages/cmf/__tests__/bootstrap.test.js
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/utils/condition.js
  packages/forms/src/UIForm/utils/condition.test.js
Labels: frontend, need review
