Repository Talend/ui, pull requests merged in 2018-04, with the labels that each got.

#1233 fix(components/action): title attribute
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/Actions/ActionButton/ActionButton.test.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/components/src/Breadcrumbs/Breadcrumbs.component.js
  packages/components/src/utils/getPropsFrom.js
Labels: easy review, need review

#1234 fix(components/virtualizedlist): override column attributes from cell
  packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
  packages/components/stories/VirtualizedList.js
Labels: easy review, need review

#1238 fix(components/virtualizedlist): force button type and remove any icon
  packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleSelector.test.js.snap
Labels: easy review, need review

#1237 i18n(components) : Add translation on ActionBar component
  packages/components/src/ActionBar/ActionBar.component.js
  packages/components/src/ActionBar/ActionBar.snapshot.test.js
  packages/components/src/ActionBar/__snapshots__/ActionBar.snapshot.test.js.snap
  packages/components/src/Layout/__snapshots__/Layout.test.js.snap
  packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
  packages/components/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap
Labels: need review

#1226 feat(datagrid): change label on the QualityBar and implement i18n
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/QualityBar.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/QualityBar.test.js
  packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/DefaultHeaderRenderer.test.js.snap
  packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/QualityBar.test.js.snap
  packages/datagrid/src/constant.js
  packages/datagrid/src/translate.js
  packages/datagrid/stories/config/i18n.js
  packages/datagrid/stories/datagrid.container.js
  packages/datagrid/stories/sample.json
  packages/datagrid/stories/sample2.json
Labels: need review

#1217 fix(container): fix deleteResource storybook
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/containers/examples/ExampleDeleteResource.js
Labels: need review

#1211 fix(datagrid): allow to mutate data in the grid
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCell.scss
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultCellRenderer.test.js.snap
  packages/datagrid/src/containers/DataGrid/__snapshots__/DataGrid.container.test.js.snap
  packages/datagrid/stories/datagrid.component.js
  packages/datagrid/stories/sample3.json
Labels: need review

#1230 feat(containers/TabBar): Rework TabBar container
  packages/containers/src/TabBar/TabBar.connect.js
  packages/containers/src/TabBar/TabBar.container.js
  packages/containers/src/TabBar/TabBar.selectors.js
  packages/containers/src/TabBar/TabBar.test.js
  packages/containers/src/TabBar/__snapshots__/TabBar.test.js.snap
Labels: need review

#1227 fix(cmf/onEventSetState): spreadCMFState
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/src/cmfConnect.js
Labels: easy review, need review

#1240 feat(datagrid): misc changes on QualityIndicator (i18n, display)
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/QualityIndicator.component.js
  packages/datagrid/src/components/DefaultCellRenderer/QualityIndicator.scss
  packages/datagrid/src/components/DefaultCellRenderer/QualityIndicator.test.js
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultCellRenderer.test.js.snap
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/QualityIndicator.test.js.snap
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.test.js
  packages/datagrid/src/constants/datagrid.constants.js
  packages/datagrid/src/constants/index.js
  packages/datagrid/stories/config/i18n.js
Labels: bug, need review

#1239 feat(datagrid): fix optional avro type
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/DefaultHeaderRenderer.test.js.snap
  packages/datagrid/stories/sample.json
Labels: bug, need review

#1242 chore(version): update keycode
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  version.js
  yarn.lock
Labels: need review

#1245 fix(forms/listview): update state when receive props
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/forms/src/widgets/ListViewWidget/ListViewWidget.js
  packages/forms/src/widgets/ListViewWidget/ListViewWidget.test.js
Labels: need review

#1244 feat: add @talend/html-webpack-plugin
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
  packages/components/src/AppLoader/constant.js
  packages/html-webpack-plugin/.editorconfig
  packages/html-webpack-plugin/.eslintrc
  packages/html-webpack-plugin/.gitignore
  packages/html-webpack-plugin/.npmignore
  packages/html-webpack-plugin/LICENSE
  packages/html-webpack-plugin/README.md
  packages/html-webpack-plugin/index.js
  packages/html-webpack-plugin/index.test.js
  packages/html-webpack-plugin/package.json
Labels: need review

#1231 feat(components/Drawer): use injected components in Drawer
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.test.js
Labels: easy review, need review

#1251 fix(components/HeaderBar): remove caret shadow
  packages/components/src/HeaderBar/HeaderBar.scss
Labels: easy review, frontend, need review

#1253 chore(ci): skip first line on lerna reports to avoid useless diff
  .travis/after_success_lint.sh
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/forms.sasslint.txt
  output/logging.eslint.txt
  output/sagas.eslint.txt
  output/theme.sasslint.txt
Labels: easy review, enhancement, need review

#1257 feat(color): add $lochmara
  packages/theme/src/theme/_colors.scss
Labels: easy review, frontend, need review

#1252 chore(ui): prettier format with json files
  .prettierrc
  .travis/after_success_git.sh
  .travis/after_success_prettier.sh
Labels: need review

#1248 chore(EnumerationWidget): pass data feature to action buttons and Toggle
  packages/components/src/Enumeration/Header/Header.component.js
  packages/components/src/Enumeration/Header/__snapshots__/header.snapshot.test.js.snap
  packages/components/src/Enumeration/Header/header.snapshot.test.js
  packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap
  packages/components/src/Toggle/Toggle.component.js
  packages/components/src/Toggle/Toggle.snapshot.test.js
  packages/components/src/Toggle/__snapshots__/Toggle.snapshot.test.js.snap
  packages/forms/src/fields/BooleanField.js
  packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js
  packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.test.js
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Labels: easy review, need review

#1258 fix(components/breadcrumbs): remove title case
  packages/components/src/Breadcrumbs/Breadcrumbs.scss
  packages/components/stories/Breadcrumbs.js
Labels: bug, easy review, need review

#1259 fix(containers/FilterBar): use props when passed
  packages/containers/src/FilterBar/FilterBar.container.js
  packages/containers/src/FilterBar/FilterBar.test.js
  packages/containers/src/FilterBar/__snapshots__/FilterBar.test.js.snap
Labels: easy review, need review

#1261 fix(components/virtualizedlist): add tooltip on the item's title
  packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleSelector.test.js.snap
Labels: easy review, enhancement, need review

#1256 feat(icons): tasks
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/tasks.svg
Labels: need review

#1250 fix(containers): redirect with wrong url
  packages/cmf/src/settings.md
  packages/containers/src/Redirect/Redirect.container.js
  packages/containers/src/Redirect/Redirect.test.js
Labels: easy review, need review

#1243 feat(DeleteResource): Add wording & i18n
  I18n.md
  package.json
  packages/containers/examples/ExampleDeleteResource.js
  packages/containers/examples/config/i18n.js
  packages/containers/package.json
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/DeleteResource.test.js
  packages/containers/src/DeleteResource/README.md
  packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap
  packages/containers/src/constant.js
  packages/containers/src/translate.js
Labels: need review

#1266 fix(html-webpack-plugin): change deps to peerDeps
  packages/html-webpack-plugin/package.json
Labels: easy review, need review

#1249 feat(components/icon): add name attr and spread props
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
  packages/components/src/Badge/__snapshots__/Badge.snap.test.js.snap
  packages/components/src/Breadcrumbs/__snapshots__/Breadcrumbs.snapshot.test.js.snap
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/Enumeration/Header/__snapshots__/header.snapshot.test.js.snap
  packages/components/src/Enumeration/Header/__snapshots__/headerInput.snapshot.test.js.snap
  packages/components/src/Enumeration/Header/__snapshots__/headerSelected.snapshot.test.js.snap
  packages/components/src/Enumeration/Items/__snapshots__/items.snapshot.test.js.snap
  packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/Icon/Icon.component.js
  packages/components/src/Icon/Icon.test.js
  packages/components/src/Icon/__snapshots__/Icon.test.js.snap
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/components/src/List/Toolbar/Pagination/__snapshots__/Pagination.snapshot.test.js.snap
  packages/components/src/List/Toolbar/SelectDisplayMode/__snapshots__/SelectDisplayMode.test.js.snap
  packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/Header.snapshot.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/headerInput.snapshot.test.js.snap
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/Notification/__snapshots__/Notification.snap.test.js.snap
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
  packages/forms/src/fields/__snapshots__/CollapsibleFieldset.test.js.snap
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/icons/src/svg/tasks.svg
Labels: easy review, need review

#1268 chore(html-webpack-plugin): set public package
  packages/html-webpack-plugin/package.json
Labels: easy review, need review

#1267 feat(cmf): silent generic http error on sagas
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
  packages/cmf/src/sagas/index.md
Labels: need review

#1269 chore(cmf-cqrs): Add prop-types package
  packages/cmf-cqrs/package.json
  packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.container.js
Labels: easy review, need review

#1272 fix(cmf): make cmf settings work with only one file
  packages/cmf/scripts/cmf-settings.merge.js
Labels: need review

#1270 chore(components): appLoader improving the spinner animation
  packages/components/src/AppLoader/constant.js
Labels: easy review, need review

#1262 feat(cmf): add router expressions
  packages/cmf/__tests__/expressions/index.test.js
  packages/cmf/__tests__/expressions/router.test.js
  packages/cmf/__tests__/selectors/router.test.js
  packages/cmf/src/api.js
  packages/cmf/src/constant.js
  packages/cmf/src/expressions/index.js
  packages/cmf/src/expressions/index.md
  packages/cmf/src/expressions/router.js
  packages/cmf/src/expressions/router.md
  packages/cmf/src/selectors/index.js
  packages/cmf/src/selectors/router.js
Labels: need review

#1265 fix(HomeListView): support drawers components
  packages/components/src/WithDrawer/WithDrawer.component.js
  packages/components/src/WithDrawer/withDrawer.test.js
  packages/containers/src/HomeListView/HomeListView.component.js
  packages/containers/src/HomeListView/HomeListView.test.js
  packages/containers/src/HomeListView/__snapshots__/HomeListView.test.js.snap
Labels: need review

#1274 fix(icon): remove double dot in tdp-colored.svg
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/.svgo.yml
  packages/icons/src/svg/tdp-colored.svg
Labels: easy review, need review

#1271 feat(icons): ellipsis
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/ellipsis.svg
Labels: easy review, need review

#1277 fix(cmf): sagas GET and DELETE fix
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
Labels: need review

#1275 fix(icons): missing dot in tdp-positive.svg
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/tdp-positive.svg
Labels: easy review, need review

#1246 feat(scripts): no config tests
  packages/scripts/README.md
  packages/scripts/index.js
  packages/scripts/package.json
  packages/scripts/preset/config/jest.config.js
  packages/scripts/preset/config/test/jest-preprocess.js
  packages/scripts/preset/config/test/style-mock.js
  packages/scripts/preset/config/test/test-setup.js
  packages/scripts/preset/preset-talend-jest.js
  packages/scripts/preset/preset-talend.js
  packages/scripts/scripts/test.js
Labels: frontend, need review

#1264 fix(components): fix font-weight in subheader
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss
Labels: need review, question

#1280 feat(cmf): parse setting to apply i18n
  packages/cmf/README.md
  packages/cmf/package.json
  packages/cmf/scripts/cmf-settings.i18n.js
  packages/cmf/scripts/cmf-settings.i18n.test.js
  packages/cmf/scripts/cmf-settings.js
  packages/cmf/scripts/cmf-settings.merge.js
  packages/cmf/scripts/cmf-settings.utils.js
  packages/cmf/scripts/getJSON.js
  packages/cmf/scripts/index.md
  yarn.lock
Labels: enhancement, need review

#1283 feat(cmf): add toJS memoized for expression / mapStateToProps
  packages/cmf/__tests__/selectors/collections.test.js
  packages/cmf/__tests__/selectors/index.test.js
  packages/cmf/__tests__/selectors/toJS.test.js
  packages/cmf/src/api.md
  packages/cmf/src/selectors/collections.js
  packages/cmf/src/selectors/collections.md
  packages/cmf/src/selectors/index.js
  packages/cmf/src/selectors/index.md
  packages/cmf/src/selectors/toJS.js
  packages/cmf/src/selectors/toJS.md
Labels: need review

#1282 fix(forms): switch to UIform if uischema is an array
  packages/containers/src/Form/Form.container.js
  packages/containers/src/Form/Form.test.js
  packages/containers/src/Form/__snapshots__/Form.test.js.snap
  packages/forms/src/Form.js
  packages/forms/src/Form.test.js
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/__snapshots__/Form.test.js.snap
Labels: need review

#1297 fix(cmf): fix typo
  packages/cmf/scripts/cmf-settings.merge.js
  packages/cmf/scripts/index.md
Labels: bug, easy review

#1292 fix(component/Datalist): display label, not the value
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/stories/Datalist.js
  packages/forms/stories-core/json/fields/core-datalist.json
Labels: need review

#1285 feat: delete deprecated logo-(dp|ic|mc).svg
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/components/stories/HeaderBar.js
  packages/icons/src/svg/logo-dp.svg
  packages/icons/src/svg/logo-ic.svg
  packages/icons/src/svg/logo-mc.svg
Labels: easy review, need review

#1295 feat(component): allow to pass classes to input file
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/Actions/ActionFile/ActionFile.test.js
  packages/components/src/Actions/ActionFile/__snapshots__/ActionFile.test.js.snap
Labels: easy review, need review

#1298 doc(cmf): Tweak misleading code and sentences
  packages/cmf/howto/how-to-add-a-new-page.md
  packages/cmf/src/cmfConnect.md
Labels: easy review, need review

#1299 chore(jsfc): upgrade from upstream
  packages/jsfc/.babelrc
  packages/jsfc/README.md
  packages/jsfc/lib/json-refs-standalone-min.js
  packages/jsfc/lib/json-refs-standalone.js
  packages/jsfc/package.json
  packages/jsfc/src/lib/merge.js
  packages/jsfc/src/lib/resolve.js
  packages/jsfc/src/lib/resolve.spec.js
  packages/jsfc/src/lib/validate.js
  packages/jsfc/src/lib/validate.spec.js
  packages/jsfc/src/module.js
  packages/jsfc/src/module.spec.js
Labels: frontend, need review

#1302 fix(cmf): use defaultValue when do translate settings
  packages/cmf/scripts/cmf-settings.i18n.js
Labels: easy review

#1289 doc(cmf): update README
  packages/cmf/README.md
  packages/cmf/scripts/index.md
  packages/cmf/src/cmfConnect.md
  packages/cmf/src/expression.md
  packages/cmf/src/registry.md
Labels: need review

#1288 Add icon data-fabric-colored.svg
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/data-fabric-colored.svg
Labels: easy review, need review

#1304 fix(components): put the class where it's usefull on actionFile
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/Actions/ActionFile/__snapshots__/ActionFile.test.js.snap
  packages/containers/src/ActionFile/__snapshots__/ActionFile.test.js.snap
Labels: easy review, enhancement, need review

#1307 chore: remove React.PropTypes in test or component
  packages/cmf/__tests__/cmfConnect.test.js
  packages/components/__mocks__/react-addons-css-transition-group.js
  packages/forms/stories/index.js
  packages/generator/generators/react-cmf/templates/src/app/components/App.container.js
Labels: easy review, enhancement, need review

#1305 feat(components/PieChartButton): add refs
  packages/components/src/PieChartButton/PieChartButton.component.js
  packages/components/src/PieChartButton/PieChartButton.test.js
Labels: need review

#1290 chore(components/appLoader): improve spinner animation
  packages/components/src/AppLoader/AppLoader.component.js
  packages/components/src/AppLoader/__snapshots__/AppLoader.test.js.snap
  packages/components/src/AppLoader/constant.js
Labels: easy review, need review

#1313 feat(theme): update rio-grande color
  packages/theme/src/theme/_colors.scss
Labels: easy review, frontend, need review

#1306 fix(html-webpack-plugin): change media for async loading
  packages/html-webpack-plugin/index.js
  packages/html-webpack-plugin/index.test.js
Labels: easy review, enhancement, need review

#1281 chore(Datalist): adding noResultText prop
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/src/Datalist/__snapshots__/Datalist.component.test.js.snap
Labels: easy review, need review

#1316 chore(cmf): remove alert from the settings reducer
  output/cmf.eslint.txt
  packages/cmf/__tests__/reducers/settingsReducers.js
  packages/cmf/src/reducers/settingsReducers.js
Labels: easy review, need review
