Repository Talend/ui, pull requests merged in 2018-05, with the labels that each got.

#1321 fix(components): app loader spinner styling
  packages/components/src/AppLoader/constant.js
Labels: easy review, need review

#1317 feat(cmf): option to sort the keys
  packages/cmf/scripts/cmf-settings.i18n.js
  packages/cmf/scripts/cmf-settings.i18n.test.js
  packages/cmf/scripts/cmf-settings.merge.js
  packages/cmf/scripts/cmf-settings.utils.js
  packages/cmf/scripts/cmf-settings.utils.test.js
  packages/cmf/scripts/index.md
Labels: enhancement, need review

#1303 chore(UIForms): upgrade jsfc
  packages/forms/package.json
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/merge.js
  packages/forms/src/UIForm/utils/validation.js
  version.js
  yarn.lock
Labels: frontend, need review

#1247 fix(forms): ListViewWidget selection
  packages/forms/src/widgets/ListViewWidget/ListViewWidget.js
  packages/forms/src/widgets/ListViewWidget/ListViewWidget.test.js
Labels: need review

#1319 chore(SidePanel): make side panel's width ajusted to its content
  packages/components/src/ActionList/ActionList.scss
  packages/components/src/SidePanel/SidePanel.scss
Labels: easy review, need review

#1324 chore(scripts): use version wildcards for babel
  packages/scripts/package.json
  version.js
Labels: easy review, frontend, need review

#1318 feat(generator): use talend/scripts
  packages/generator/generators/react-cmf/index.js
  packages/generator/generators/react-cmf/templates/env.js
  packages/generator/generators/react-cmf/templates/package.json
  packages/generator/generators/react-cmf/templates/src/app/components/App/App.container.js
  packages/generator/generators/react-cmf/templates/src/app/components/App/App.container.test.js
  packages/generator/generators/react-cmf/templates/src/app/components/App/index.js
  packages/generator/generators/react-cmf/templates/src/app/configure.js
  packages/generator/generators/react-cmf/templates/src/assets/settings.json
  packages/generator/generators/react-cmf/templates/src/test/styleMock.js
  packages/generator/generators/react-cmf/templates/webpack.config.dev.js
  packages/generator/generators/react-cmf/templates/webpack.config.js
  packages/generator/generators/react-cmf/templates/webpack.config.prod.js
  packages/generator/test/react-cmf.js
Labels: frontend, need review

#1331 fix(containers): update deprecated import
  packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.container.js
  packages/codeshift/README.md
  packages/codeshift/componentState_to_cmfConnect.js
  packages/codeshift/package.json
  packages/containers/src/ConfirmDialog/ConfirmDialog.container.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/FilterBar/FilterBar.container.js
  packages/containers/src/Form/Form.container.js
  packages/containers/src/Notification/Notification.container.js
  packages/containers/src/ObjectViewer/ObjectViewer.container.js
  packages/containers/src/PieChartButton/PieChartButton.connect.js
  packages/containers/src/SelectObject/SelectObject.container.js
  packages/containers/src/ShortcutManager/ShortcutManager.container.js
  packages/containers/src/Slider/Slider.container.js
  packages/containers/src/TreeView/TreeView.container.js
  packages/containers/src/state.js
Labels: need review

#1326 chore(icons): introduce deprecated folder
  packages/icons/pom.xml
  packages/icons/src/svg-deprecated/README.md
Labels: easy review, frontend, need review

#1337 feat(scripts): customisable app loader
  packages/scripts/README.md
  packages/scripts/package.json
  packages/scripts/preset/README.md
  packages/scripts/preset/config/webpack.config.js
Labels: enhancement, frontend, need review

#1339 feat(scripts): run eslint as pre-loader in dev mode
  packages/scripts/package.json
  packages/scripts/preset/config/webpack.config.dev.js
Labels: easy review, frontend, need review

#1322 fix(cmf/scripts/settings): manage case of undefined namespace or not define in the cmf.json file
  packages/cmf/scripts/cmf-settings.i18n.js
  packages/cmf/scripts/cmf-settings.i18n.test.js
  packages/cmf/scripts/index.md
Labels: need review

#1338 feat(scripts): insert licence banner in bundles
  packages/scripts/preset/config/licence.js
  packages/scripts/preset/config/webpack.config.js
Labels: easy review, frontend, need review

#1334 fix(container): fix the props for the PieChartButton
  packages/components/src/PieChartButton/PieChartButton.component.js
  packages/components/src/PieChartButton/PieChartButton.test.js
  packages/containers/src/PieChartButton/PieChartButton.connect.js
  packages/containers/src/PieChartButton/PieChartButton.test.js
  packages/containers/src/PieChartButton/__snapshots__/PieChartButton.test.js.snap
Labels: need review

#1294 feat(cmf): allow to pass componentId in routes
  packages/cmf/__tests__/route.test.js
  packages/cmf/src/route.js
  packages/cmf/src/route.md
Labels: need review

#1312 chore: update browserlist to >0.25% + IE11
  .babelrc
  packages/scripts/preset/config/.babelrc.json
  packages/scripts/preset/config/webpack.config.js
  packages/theme/webpack.config.js
Labels: easy review, frontend, need review

#1279 fix(components/ActionDropdown): proptypes on items
  packages/components/package.json
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/containers/src/ActionDropdown/ActionDropdown.connect.js
Labels: easy review, need review

#1344 chore(react-i18n): update react-i18next
  I18n.md
  packages/components/package.json
  packages/components/src/ActionBar/ActionBar.component.js
  packages/components/src/ActionBar/ActionBar.snapshot.test.js
  packages/components/src/ActionBar/__snapshots__/ActionBar.snapshot.test.js.snap
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.component.js
  packages/components/src/Actions/ActionSplitDropdown/__snapshots__/ActionSplitDropdown.test.js.snap
  packages/components/src/Badge/Badge.component.js
  packages/components/src/Enumeration/Enumeration.component.js
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/List/Toolbar/SelectAll/SelectAll.component.js
  packages/components/src/List/Toolbar/SelectDisplayMode/SelectDisplayMode.component.js
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js
  packages/components/src/List/Toolbar/Toolbar.component.js
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/ListView/Header/Header.component.js
  packages/components/src/ListView/Header/HeaderInput.component.js
  packages/components/src/ListView/Items/Items.component.js
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/ListView/Items/items.test.js
  packages/components/src/ListView/ListView.component.js
  packages/components/src/SidePanel/SidePanel.component.js
  packages/components/src/Skeleton/Skeleton.component.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InlineFormSubHeader.component.js
  packages/components/src/SubHeaderBar/InputTitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/SubHeaderBar.component.js
  packages/components/src/VirtualizedList/NoRows/NoRows.component.js
  packages/components/src/VirtualizedList/NoRows/NoRows.test.js
  packages/components/src/VirtualizedList/NoRows/__snapshots__/NoRows.test.js.snap
  packages/components/src/translate.js
  packages/containers/package.json
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap
  packages/containers/src/translate.js
  packages/datagrid/package.json
  packages/datagrid/src/components/DefaultCellRenderer/QualityIndicator.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/QualityBar.component.js
  packages/datagrid/src/translate.js
  packages/forms/package.json
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.test.js
  packages/forms/src/UIForm/fields/ListView/__snapshots__/ListView.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/__snapshots__/Form.test.js.snap
  packages/forms/src/templates/ArrayFieldTemplate.js
  packages/forms/src/translate.js
  packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/src/widgets/ListViewWidget/ListViewWidget.js
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.js
  packages/generator/generators/react-cmf/templates/package.json
  version.js
  yarn.lock
Labels: enhancement, need review

#1347 fix(Component/SubHeaderBar): edition button color
  packages/components/src/SubHeaderBar/InputTitleSubHeader/InputTitleSubHeader.scss
Labels: easy review, need review

#1327 chore(Containers/List): multi selection on list container
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleList.js
  packages/containers/src/List/List.container.js
  packages/containers/src/List/List.test.js
  packages/containers/src/List/__snapshots__/List.test.js.snap
Labels: easy review, need review

#1328 chore(datagrid): remove warnings console in datagrid
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
Labels: bug, easy review, need review

#1354 fix: small fix in cmf settings scripts
  packages/cmf/scripts/cmf-settings.merge.js
Labels: easy review, need review

#1349 chore: move codemod and mutualize test setup
  packages/cmf-cqrs/env__tests.js
  packages/cmf-cqrs/package.json
  packages/cmf-cqrs/test-setup.js
  packages/cmf/package.json
  packages/cmf/test-setup.js
  packages/components/package.json
  packages/components/test-setup.js
  packages/containers/env__tests.js
  packages/containers/package.json
  packages/containers/test-setup.js
  packages/datagrid/env__tests.js
  packages/datagrid/package.json
  packages/datagrid/test-setup.js
  packages/forms/package.json
  packages/forms/test-setup.js
  packages/logging/env__tests.js
  packages/logging/package.json
  packages/sagas/env__tests.js
  packages/sagas/package.json
  packages/scripts/preset/config/test/test-setup.js
  scripts/cmf-componentState-deprecation/README.md
  scripts/cmf-componentState-deprecation/componentState_to_cmfConnect.js
  scripts/cmf-componentState-deprecation/package.json
  test-setup.js
Labels: easy review, need review

#1353 fix(Component/Badge): disabled button style
  packages/components/src/Badge/Badge.scss
Labels: easy review, frontend, need review

#1352 fix(Container/Dropdown): pass onclick to the component
  packages/containers/src/ActionDropdown/ActionDropdown.connect.js
  packages/containers/src/ActionDropdown/__snapshots__/ActionDropdown.test.js.snap
Labels: bug, easy review, need review

#1348 feat(icons): Promotion Pipelines
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/data-fabric-colored.svg
  packages/icons/src/svg/promotion-pipelines.svg
Labels: easy review, need review

#1345 feat(scripts): cmf plugin
  output/cmf-webpack-plugin.eslint.txt
  packages/cmf-webpack-plugin/package.json
  packages/cmf-webpack-plugin/src/index.js
  packages/cmf/scripts/cmf-settings.merge.js
  packages/html-webpack-plugin/package.json
  packages/scripts/package.json
  packages/scripts/preset/README.md
  packages/scripts/preset/config/webpack.config.dev.js
  packages/scripts/preset/config/webpack.config.js
  packages/scripts/preset/config/webpack.config.prod.js
  packages/scripts/scripts/build.js
Labels: frontend, need review

#986 chore: upgrade react-jsonschema-form
  output/cmf-webpack-plugin.eslint.txt
  packages/forms/package.json
  packages/forms/src/Form.test.js
  packages/forms/src/UIForm/Widget/Widget.component.test.js
  packages/forms/src/__snapshots__/Form.test.js.snap
  packages/forms/src/fields/ArrayField.js
  packages/forms/src/fields/BooleanField.js
  packages/forms/src/fields/ObjectField.js
  packages/forms/src/fields/StringField.js
  packages/forms/src/fields/__snapshots__/CollapsibleFieldset.test.js.snap
  packages/forms/src/widgets/KeyValueWidget/KeyValueWidget.js
  packages/forms/stories/index.js
  version.js
  yarn.lock
Labels: frontend, need review

#1361 fix(components/HeaderBar): missing bootstrap classNames
  output/theme.sasslint.txt
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/stories/HeaderBar.js
  packages/components/stories/Skeleton.js
  packages/components/stories/Typeahead.js
  packages/theme/src/theme/_navbar.scss
Labels: easy review, need review

#1360 doc(cmf): expression order
  packages/cmf/src/expression.md
Labels: easy review, enhancement, need review

#1194 feat(containers): add AppLoader container
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleAppLoader.js
  packages/containers/examples/index.js
  packages/containers/package.json
  packages/containers/src/AppLoader/AppLoader.connect.js
  packages/containers/src/AppLoader/AppLoader.connect.test.js
  packages/containers/src/AppLoader/AppLoader.md
  packages/containers/src/AppLoader/AppLoader.saga.js
  packages/containers/src/AppLoader/AppLoader.saga.test.js
  packages/containers/src/AppLoader/index.js
  packages/containers/src/index.js
  packages/datagrid/package.json
  version.js
  yarn.lock
Labels: need review

#1356 feat(Component/Breadcrumb): improve a11y
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/logging.eslint.txt
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/components/src/Breadcrumbs/Breadcrumbs.component.js
  packages/components/src/Breadcrumbs/Breadcrumbs.snapshot.test.js
  packages/components/src/Breadcrumbs/__snapshots__/Breadcrumbs.snapshot.test.js.snap
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/logging/package.json
  packages/sagas/package.json
  packages/theme/package.json
  yarn.lock
Labels: easy review, frontend, need review

#1358 feat(Component/CollapsiblePanel): improve a11y
  __mocks__/ally.js/style/_style.js
  output/datagrid.eslint.txt
  packages/components/package.json
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/ListView/Items/Item/Item.component.js
  packages/components/src/Status/Status.component.js
  packages/components/src/Status/Status.scss
  packages/components/src/Status/__snapshots__/Status.snapshot.test.js.snap
  packages/components/src/Status/index.js
  packages/components/src/polyfills/focus-within.js
  packages/containers/package.json
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  yarn.lock
Labels: easy review, frontend, need review

#1263 feat(Component/List): actions in a menu dropdown
  output/components.eslint.txt
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.snapshot.test.js
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.test.js.snap
  packages/components/src/Enumeration/Header/__snapshots__/header.snapshot.test.js.snap
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.test.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitle.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/index.js
  packages/components/src/VirtualizedList/ListTable/ListTable.scss
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
  packages/components/src/VirtualizedList/RowSelection/RowSelection.scss
  packages/components/stories/List.js
  packages/components/stories/VirtualizedList.js
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/theme/src/theme/_dropdowns.scss
Labels: frontend, need review

#1355 fix(Component): i18n on the cellDateTime component
  packages/components/src/DateFnsLocale/locale.js
  packages/components/src/DateFnsLocale/locale.test.js
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js
  packages/components/src/VirtualizedList/CellDatetime/__snapshots__/CellDatetime.test.js.snap
  packages/components/src/VirtualizedList/CellDatetime/index.js
  packages/components/src/translate.js
  packages/components/src/translate.test.js
  packages/components/stories/config/i18n.js
Labels: bug, need review

#1363 chore: several fixes on snapshot, lint, proptypes
  packages/cmf-cqrs/package.json
  packages/components/__mocks__/react-addons-css-transition-group.js
  packages/components/src/Layout/Layout.test.js
  packages/components/src/Layout/__snapshots__/Layout.test.js.snap
  packages/components/src/List/Toolbar/Pagination/Pagination.component.js
  packages/components/src/SubHeaderBar/SubHeaderBar.test.js
  packages/components/stories/List.js
  packages/containers/.storybook/webpack.config.js
  packages/containers/src/ActionDropdown/ActionDropdown.test.js
  packages/containers/src/ActionDropdown/__snapshots__/ActionDropdown.test.js.snap
  packages/forms/src/Form.js
Labels: easy review, frontend, need review

#1362 feat(Scripts): set source-map to map original files, not eval
  packages/scripts/preset/config/webpack.config.dev.js
Labels: easy review, frontend, need review

#1310 fix(component/FilterBar): pressing Enter causes an error
  packages/components/src/FilterBar/FilterBar.component.js
Labels: easy review, frontend, need review

#1364 feat(icons): logo Talend colored
  packages/components/src/IconsProvider/__snapshots__/IconsProvider.test.js.snap
  packages/icons/src/svg/logo-colored.svg
Labels: easy review, need review

#1372 fix(Form): Change uiSchema propType to avoid type conflicts
  packages/forms/src/Form.js
Labels: easy review, need review, proptypes warning

#1373 feat(Container): add CustomValidation props on Form container
  packages/containers/src/Form/Form.container.js
  packages/containers/src/Form/Form.test.js
  packages/containers/src/Form/__snapshots__/Form.test.js.snap
Labels: easy review, need review

#1374 fix(cmf/test): mock do a deepcopy
  packages/cmf/__tests__/action.test.js
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/src/mock/store.js
Labels: easy review, need review

#1369 doc(forms): remove bsDialogProps instance
  packages/components/stories/Dialog.js
  packages/forms/stories/index.js
Labels: easy review, need review

#1370 fix(List): already show the actions on the title when type is LARGE
  output/components.eslint.txt
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitle.test.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.test.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitle.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
  packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
  packages/components/src/VirtualizedList/utils/__snapshots__/gridrow.test.js.snap
  packages/components/src/VirtualizedList/utils/gridrow.js
  packages/components/src/VirtualizedList/utils/gridrow.test.js
Labels: bug, need review

#1367 feat(components/containers): allow to pass custom renderers to List
  output/containers.eslint.txt
  packages/components/src/List/List.md
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.test.js
  packages/components/stories/List.js
  packages/containers/examples/ExampleList.js
  packages/containers/src/List/List.container.js
Labels: need review

#1359 chore(cmf): simplify imports
  docs/_posts/2017-02-28-api-action.md
  output/cmf.eslint.txt
  output/containers.eslint.txt
  packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.container.js
  packages/cmf/__tests__/Dispatcher.test.js
  packages/cmf/__tests__/api.test.js
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/__tests__/component.test.js
  packages/cmf/__tests__/expression.test.js
  packages/cmf/docs.json
  packages/cmf/howto/best-practices.md
  packages/cmf/howto/how-to-add-a-new-page.md
  packages/cmf/src/Dispatcher.js
  packages/cmf/src/Inject.component.js
  packages/cmf/src/UIRouter.js
  packages/cmf/src/action.js
  packages/cmf/src/actionCreator.md
  packages/cmf/src/actions/saga.js
  packages/cmf/src/api.js
  packages/cmf/src/api.md
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/constant.js
  packages/cmf/src/expression.js
  packages/cmf/src/expressions/index.md
  packages/cmf/src/index.js
  packages/cmf/src/middlewares/http/index.md
  packages/cmf/src/route.js
  packages/cmf/src/sagas/index.md
  packages/cmf/src/sagas/putActionCreator.js
  packages/cmf/src/selectors/collections.md
  packages/cmf/src/selectors/index.md
  packages/cmf/src/selectors/toJS.js
  packages/cmf/src/selectors/toJS.md
  packages/cmf/src/settings.md
  packages/containers/src/Action/Action.connect.js
  packages/containers/src/ActionButton/ActionButton.connect.js
  packages/containers/src/ActionDropdown/ActionDropdown.connect.js
  packages/containers/src/ActionFile/ActionFile.connect.js
  packages/containers/src/ActionIconToggle/ActionIconToggle.connect.js
  packages/containers/src/ActionSplitDropdown/ActionSplitDropdown.connect.js
  packages/containers/src/AppLoader/AppLoader.saga.js
  packages/containers/src/AppLoader/AppLoader.saga.test.js
  packages/containers/src/ConfirmDialog/ConfirmDialog.connect.js
  packages/containers/src/DeleteResource/deleteResource.sagas.js
  packages/containers/src/SidePanel/SidePanel.connect.js
  packages/containers/src/actionAPI.js
  packages/containers/src/register.js
  packages/containers/src/register.test.js
  packages/containers/src/renderers.js
  packages/sagas/src/pending/pending.js
  packages/sagas/src/pending/pending.test.js
  scripts/cmf/README.md
  scripts/cmf/api_to_index.js
  scripts/cmf/componentState_to_cmfConnect.js
  scripts/cmf/package.json
Labels: need review

#1371 feat(cmf): add two state static accessors
  output/cmf.eslint.txt
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/cmfConnect.md
  packages/cmf/src/componentState.js
Labels: easy review, need review

#1377 fix(MultiSelectTag): show the component if no items.
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.js
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.test.js
  packages/forms/stories/json/multiSelectTag.json
Labels: bug, need review

#1323 chores(icons): update icon doc with svg filter
  packages/icons/scripts/docs.js
Labels: need review

#1381 fix(cmf/merge): destination is optional again
  packages/cmf/scripts/cmf-settings.merge.js
Labels: easy review, frontend, need review

#1365 chore: react-addons-css-transition-group to react-transition-group
  packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.container.js
  packages/components/__mocks__/react-addons-css-transition-group.js
  packages/components/package.json
  packages/components/src/Notification/Notification.component.js
  packages/components/src/Notification/Notification.scss
  packages/components/src/Notification/__snapshots__/Notification.snap.test.js.snap
  packages/components/stories/Notification.js
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  version.js
  yarn.lock
Labels: frontend, need review

#1382 fix(components): AppLoader - fix translation (defaultValue)
  packages/components/src/AppLoader/AppLoader.component.js
  packages/components/src/AppLoader/__snapshots__/AppLoader.test.js.snap
Labels: easy review, need review

#1383 fix(TabBar): propTypes.items is Tab.proptypes.item
  packages/components/src/TabBar/TabBar.component.js
Labels: easy review, need review, proptypes warning

#1351 fix(cmf): set default header on http saga
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
  packages/cmf/src/sagas/index.md
Labels: bug, need review

#1384 chore: revert babel-eslint version to fix it
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/logging.eslint.txt
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/logging/package.json
  packages/sagas/package.json
  version.js
  yarn.lock
Labels: frontend, need review

#1388 fix(UIForm): resetting form structure if it didn't change
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
Labels: need review

#1386 doc: fix storybook of containers and datagrid
  lerna.json
  package.json
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleList.js
  packages/containers/package.json
  packages/datagrid/package.json
  packages/datagrid/src/register.js
  packages/datagrid/src/register.test.js
  packages/datagrid/stories/datagrid.container.js
  packages/storybook-cmf/.babelrc
  packages/storybook-cmf/.gitignore
  packages/storybook-cmf/.npmignore
  packages/storybook-cmf/LICENSE
  packages/storybook-cmf/README.md
  packages/storybook-cmf/package.json
  packages/storybook-cmf/register.js
  packages/storybook-cmf/src/CMFDecorator.js
  packages/storybook-cmf/src/CMFStory/CMFStory.component.js
  packages/storybook-cmf/src/CMFStory/CMFStory.test.js
  packages/storybook-cmf/src/CMFStory/__snapshots__/CMFStory.test.js.snap
  packages/storybook-cmf/src/CMFStory/index.js
  packages/storybook-cmf/src/index.js
  packages/storybook-cmf/src/register.js
  yarn.lock
Labels: bug, need review

#1100 feat(containers/typeahead): new typeahead container
  packages/containers/examples/ExampleTypeahead.js
  packages/containers/examples/index.js
  packages/containers/src/Typeahead/Typeahead.connect.js
  packages/containers/src/Typeahead/Typeahead.container.js
  packages/containers/src/Typeahead/Typeahead.test.js
  packages/containers/src/Typeahead/__snapshots__/Typeahead.test.js.snap
  packages/containers/src/Typeahead/index.js
  packages/containers/src/index.js
Labels: enhancement, need review

#1402 fix(components) : improve translation in circularProgress
  packages/components/src/CircularProgress/CircularProgress.component.js
Labels: easy review, need review

#1405 fix(List): fix cellDictionary wrong proptype
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
Labels: easy review, need review

#1396 fix(components) : Drawer - don't keep all references in footerActions
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.test.js
Labels: easy review, need review

#1390 fix(cmf/router): add HOC WithProps for every components
  packages/cmf/__tests__/route.test.js
  packages/cmf/src/route.js
Labels: need review

#1404 chore(datagrid): optim on componentDidUpdate
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.test.js
Labels: need review

#761 chore(react): Updates to React 16
  .travis.yml
  lerna.json
  output/logging.eslint.txt
  package.json
  packages/cmf-cqrs/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/forms/src/fields/__snapshots__/CollapsibleFieldset.test.js.snap
  packages/forms/src/widgets/MultiSelectTagWidget/MultiSelectTagWidget.test.js
  packages/generator/generators/react-cmf/templates/package.json
  packages/generator/generators/react-cmf/templates/test-setup.js
  packages/icons/package.json
  packages/logging/package.json
  packages/logging/test-setup.js
  packages/sagas/package.json
  packages/scripts/package.json
  test-setup.js
  version.js
  yarn.lock
Labels: easy review, enhancement, frontend, need review

#1366 fix: forms datalist storybook
  packages/forms/stories/index.js
Labels: easy review, frontend, need review

#1406 feat(containers/AppLoader): add takeAction support
  packages/containers/src/AppLoader/AppLoader.md
  packages/containers/src/AppLoader/AppLoader.saga.js
  packages/containers/src/AppLoader/AppLoader.saga.test.js
Labels: need review
