Repository Talend/ui, pull requests merged in 2019-11, with the labels that each got.

#2514 fix(components/layout): skip links block default size
  packages/components/src/Layout/SkipLinks/SkipLinks.scss
Labels: easy review, enhancement, need review

#2516 feat(components/tooltiptrigger): expose css classes
  packages/components/src/TooltipTrigger/TooltipTrigger.component.js
Labels: easy review, enhancement, frontend, need review

#2515 fix(TCCUI-103): Cleared composed list
  npm-audit/html-webpack-plugin.json
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.test.js
  packages/components/stories/ListComposition/ListComposition.js
Labels: easy review, need review

#2520 fix(FacetedSearch): tql error on empty value array
  packages/faceted-search/src/queryClient/tql.js
  packages/faceted-search/src/queryClient/tql.test.js
Labels: need review

#2521 chore(FacetedSearch): add change log and update to 0.2.2
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
Labels: need review

#2523 fix(treeview&subheader): remove import ..
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
  packages/components/src/TreeView/TreeView.component.js
Labels: need review

#2531 fix(time picker): add maxLength of time input field
  npm-audit/audit.json
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap
  packages/components/src/DateTimePickers/Time/Input/Input.component.js
Labels: need review

#2532 feat(components/listcomposition): add boolean cell type
  packages/components/src/VirtualizedList/CellBoolean/BooleanColumn.component.js
  packages/components/src/VirtualizedList/CellBoolean/CellBoolean.component.js
  packages/components/src/VirtualizedList/CellBoolean/CellBoolean.scss
  packages/components/src/VirtualizedList/CellBoolean/CellBoolean.test.js
  packages/components/src/VirtualizedList/CellBoolean/__snapshots__/CellBoolean.test.js.snap
  packages/components/src/VirtualizedList/CellBoolean/index.js
  packages/components/src/VirtualizedList/index.js
  packages/components/stories/ListComposition/ListComposition.js
  packages/components/stories/ListComposition/collection.js
Labels: easy review, enhancement, frontend, need review

#2535 fix(faceted-search/BasicSearch): Fix onSubmit execution
  npm-audit/audit.json
  output/components.eslint.txt
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
  packages/faceted-search/src/CRUDBadges.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.test.js
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
  packages/faceted-search/src/components/facetedSearch.propTypes.js
  packages/faceted-search/yarn.lock
Labels: bug, frontend

#2530 feat(faceted-search/labels): Update tooltip labels
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.test.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
Labels: easy review, enhancement, frontend, need review

#2512 chore(forms/Toggle): calling onFinish on change event
  packages/forms/src/UIForm/fields/Toggle/Toggle.component.js
  packages/forms/src/UIForm/fields/Toggle/Toggle.component.test.js
  packages/forms/src/UIForm/fields/Toggle/__snapshots__/Toggle.component.test.js.snap
Labels: easy review, need review

#2474 fix(components/list): checkbox aligmnent issue
  packages/components/src/VirtualizedList/CellCheckbox/CellCheckbox.scss
  packages/components/src/VirtualizedList/HeaderCheckbox/HeaderCheckbox.scss
Labels: bug, easy review, frontend, need review

#2538 fix(faceted-search/BasicSearch): Do not contrain onSubmit trigger
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
Labels: bug, easy review, enhancement

#2544 fix(faceted-search/BadgeOverlay): Add Tooltip trigger for button icon
  npm-audit/audit.json
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.js
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
Labels: easy review, frontend, need review

#2529 feat(icons): abc.svg and cut.svg
  packages/icons/src/svg/core/abc.svg
  packages/icons/src/svg/core/cut.svg
Labels: easy review, need review

#2528 feat(icons):workday
  packages/icons/src/svg/brands/workday.svg
Labels: easy review, need review

#2519 feat(icons): flows
  packages/icons/src/svg/flows/flow-o.svg
  packages/icons/src/svg/flows/flow-source-o.svg
  packages/icons/src/svg/flows/flow-step-o.svg
  packages/icons/src/svg/flows/flow-target-o.svg
  packages/icons/src/svg/flows/flow-unfinished.svg
  packages/icons/src/svg/flows/flow.svg
Labels: easy review, need review

#2545 fix(faceted-search/tql): Full support of operator notEqual
  packages/faceted-search/src/dictionary/operator.dictionary.js
  packages/faceted-search/src/queryClient/tql.js
  packages/faceted-search/src/queryClient/tql.test.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: bug, easy review, frontend, need review

#2546 fix(theme): checkbox as switch
  npm-audit/audit.json
  packages/theme/src/theme/_forms.checkbox.scss
  packages/theme/src/theme/_forms.radio.scss
  packages/theme/src/theme/_forms.switch.scss
Labels: bug, easy review, need review

#2542 chore(List): add separator actions
  output/components.eslint.txt
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.test.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
  packages/components/stories/List.js
  packages/containers/examples/ExampleList.js
  packages/containers/src/List/List.container.js
Labels: easy review, need review

#2543 fix(i18n): missing key for deleteResource
  packages/containers/examples/config/i18n.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap
Labels: bug, easy review, need review

#2539 feat(range picker): Manager
  output/components.eslint.txt
  packages/components/src/DateTimePickers/DateRange/Inputs/Inputs.component.js
  packages/components/src/DateTimePickers/DateRange/Manager/Manager.component.js
  packages/components/src/DateTimePickers/DateRange/Manager/Manager.component.test.js
  packages/components/src/DateTimePickers/DateRange/Manager/__snapshots__/Manager.component.test.js.snap
  packages/components/src/DateTimePickers/DateRange/Manager/index.js
  packages/components/src/DateTimePickers/DateRange/Picker/Picker.component.js
  packages/components/src/DateTimePickers/DateRange/Picker/Picker.component.test.js
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js
  packages/components/src/DateTimePickers/shared/error-messages.js
Labels: need review

#1994 chore(CQRS): remove componentWillReceiveProps
  packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.connect.js
  packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.container.js
  packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.test.js
Labels: easy review, frontend, need review

#2444 fix(ComponentForm): initialState as an Immutable.Map
  npm-audit/audit.json
  output/components.eslint.txt
  packages/containers/src/ComponentForm/ComponentForm.component.js
Labels: need review

#2548 feat(faceted-search): Add number badge
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.test.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.scss
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumberForm.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumberForm.component.test.js
  packages/faceted-search/src/components/Badges/BadgeNumber/__snapshots__/BadgeNumber.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeNumber/__snapshots__/BadgeNumberForm.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeNumber/index.js
  packages/faceted-search/src/dictionary/badge.dictionary.js
  packages/faceted-search/src/dictionary/operator.dictionary.js
  packages/faceted-search/src/queryClient/tql.js
  packages/faceted-search/src/queryClient/tql.test.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: enhancement, frontend, need review

#2553 fix: remove dynamic import
  babel.config.js
  npm-audit/audit.json
  packages/components/package.json
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  yarn.lock
Labels: frontend, need review

#2557 fix(List): cell title actions makes the title unreadable
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
Labels: easy review, need review

#2552 chore(faceted-search): Release version 0.2.3 and update Changelog
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
Labels: easy review, enhancement, frontend, need review

#2562 chore: upgrade Storybook to 5.2.6
  npm-audit/audit.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  versions/dependencies.js
  yarn.lock
Labels: easy review, enhancement, need review
