Repository Talend/ui, pull requests merged in 2019-08, with the labels that each got.

#2060 fix(container): Drawer.Title behavior
  npm-audit/audit.json
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.test.js
Labels: need review

#2273 feat(cmf): mutating nested collections
  packages/cmf/__tests__/actions/collectionsActions.test.js
  packages/cmf/__tests__/reducers/collectionsReducers.test.js
  packages/cmf/src/actions/collectionsActions.js
  packages/cmf/src/reducers/collectionsReducers.js
Labels: need review

#2315 fix(package/components): no visual feedback when navigating with keyboard
  npm-audit/audit.json
  packages/components/src/Typeahead/Typeahead.scss
Labels: bug, easy review, frontend, need review

#2321 fix(forms): forms buttons ids generation
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
Labels: easy review, need review

#2320 feat(RichLayout): compound
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.scss
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/ColumnChooserBody.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserFooter/ColumnChooserFooter.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserFooter/__snapshots__/ColumnChooserFooter.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserHeader/ColumnChooserHeader.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserHeader/__snapshots__/ColumnChooserHeader.component.test.js.snap
  packages/components/src/RichTooltip/RichLayout/RichLayout.component.js
  packages/components/src/RichTooltip/RichLayout/__snapshots__/RichLayout.test.js.snap
  packages/components/src/Tooltip/Tooltip.component.js
  packages/components/src/Tooltip/Tooltip.scss
  packages/components/src/Tooltip/index.js
Labels: need review

#2323 chore(components): Add a snapshot serializer when using enzyme html
  npm-audit/audit.json
  packages/components/package.json
  packages/components/src/Badge/BadgeComposition/BadgeCategory/__snapshots__/BadgeCategory.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeDelete/__snapshots__/BadgeDelete.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeIcon/__snapshots__/BadgeIcon.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeLabel/__snapshots__/BadgeLabel.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeSeparator/__snapshots__/BadgeSeparator.component.test.js.snap
  packages/components/src/Badge/__snapshots__/Badge.component.test.js.snap
  packages/components/src/VirtualizedList/HeaderResizable/__snapshots__/HeaderResizable.component.test.js.snap
  yarn.lock
Labels: need review

#2326 fix(forms): display tooltips as block
  packages/components/src/TooltipTrigger/TooltipTrigger.component.js
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/Widget/Widget.component.scss
Labels: easy review, need review

#2327 feat(components/tooltiptrigger): z-index
  packages/components/src/TooltipTrigger/TooltipTrigger.scss
Labels: easy review, need review

#2329 feat(component/LazyLoadingList): Debounce support for callback
  packages/components/src/List/ListComposition/LazyLoadingList/LazyLoadingList.component.js
  packages/components/src/List/ListComposition/LazyLoadingList/__snapshots__/LazyLoadingList.component.test.js.snap
Labels: easy review, need review

#2332 fix(component): Datalist icon
  packages/components/src/Datalist/Datalist.component.js
Labels: easy review, need review

#2333 fix(List): list title cell not centered
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
Labels: need review

#2335 fix(TMC-18302): issue with drawer title
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.scss
Labels: need review

#2341 feat(icons): operators
  packages/icons/src/svg-deprecated/more-than-equal.svg
  packages/icons/src/svg-deprecated/more-than.svg
  packages/icons/src/svg/core/contains.svg
  packages/icons/src/svg/core/equal.svg
  packages/icons/src/svg/core/less-than-equal.svg
  packages/icons/src/svg/core/less-than.svg
  packages/icons/src/svg/core/not-equal.svg
  packages/icons/src/svg/operators/between.svg
  packages/icons/src/svg/operators/contains.svg
  packages/icons/src/svg/operators/ends-with.svg
  packages/icons/src/svg/operators/equal.svg
  packages/icons/src/svg/operators/greater-than-equal.svg
  packages/icons/src/svg/operators/greater-than.svg
  packages/icons/src/svg/operators/less-than-equal.svg
  packages/icons/src/svg/operators/less-than.svg
  packages/icons/src/svg/operators/not-contains.svg
  packages/icons/src/svg/operators/not-equal.svg
  packages/icons/src/svg/operators/regex.svg
  packages/icons/src/svg/operators/starts-with.svg
Labels: easy review, need review

#2167 feat(ColumnChooser): add column chooser
  output/components.sasslint.txt
  packages/components/src/List/List.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.scss
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/ColumnChooserBody.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/ColumnChooserBody.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/__snapshots__/ColumnChooserBody.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserFooter/ColumnChooserFooter.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserFooter/ColumnChooserFooter.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserFooter/__snapshots__/ColumnChooserFooter.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserFooter/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserHeader/ColumnChooserHeader.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserHeader/ColumnChooserHeader.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserHeader/__snapshots__/ColumnChooserHeader.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserHeader/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/ColumnChooserRow.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/ColumnChooserRow.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowCheckbox/RowCheckbox.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowCheckbox/RowCheckbox.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowCheckbox/__snapshots__/RowCheckbox.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowCheckbox/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowLabel/RowLabel.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowLabel/RowLabel.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowLabel/__snapshots__/RowLabel.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowLabel/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/__snapshots__/ColumnChooserRow.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserTable/ColumnChooserTable.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserTable/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/SelectAllColumnsCheckbox.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/SelectAllColumnsCheckbox.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/__snapshots__/SelectAllColumnsCheckbox.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/columnChooser.context.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooserButton.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooserButton.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/README.md
  packages/components/src/List/Toolbar/ColumnChooserButton/columnChooser.propTypes.js
  packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.js
  packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/hooks/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/service/columnChooser.utils.js
  packages/components/src/List/Toolbar/ColumnChooserButton/service/columnChooser.utils.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/service/index.js
  packages/components/src/List/Toolbar/Toolbar.component.js
  packages/components/src/List/Toolbar/Toolbar.scss
  packages/components/src/RichTooltip/RichLayout/RichLayout.component.js
  packages/components/src/RichTooltip/RichLayout/__snapshots__/RichLayout.test.js.snap
  packages/components/stories/ColumnChooser.js
  packages/components/stories/List.js
  packages/components/stories/index.js
  packages/eslint-config/.eslintrc.json
  packages/eslint-config/package.json
Labels: need review

#2343 fix(DatePicker): stop propagation of mouse down in the whole picker
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/stories/GridLayout.js
Labels: easy review, need review

#2344 fix(Table): e2e tests
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/TableTest.java
Labels: need review

#2348 fix(Notification): set Notification above the other
  packages/components/src/Notification/Notification.scss
  packages/theme/src/theme/_variables.scss
Labels: bug, easy review, need review

#2351 fix(Theme): follow guidelines on bold
  packages/theme/src/theme/_breadcrumbs.scss
  packages/theme/src/theme/_hyperlinks.scss
  packages/theme/src/theme/_labels.scss
  packages/theme/src/theme/_type.scss
  packages/theme/src/theme/_variables.scss
Labels: need review

#2346 feat(VirtualizedList): improve columns api
  packages/components/src/List/ListComposition/LazyLoadingList/__snapshots__/LazyLoadingList.component.test.js.snap
  packages/components/src/List/ListComposition/VList/VList.component.js
  packages/components/src/VirtualizedList/CellActions/ActionsColumn.component.js
  packages/components/src/VirtualizedList/CellActions/index.js
  packages/components/src/VirtualizedList/CellBadge/BadgeColumn.component.js
  packages/components/src/VirtualizedList/CellBadge/index.js
  packages/components/src/VirtualizedList/CellCheckbox/CheckboxColumn.component.js
  packages/components/src/VirtualizedList/CellCheckbox/index.js
  packages/components/src/VirtualizedList/CellDatetime/DatetimeColumn.component.js
  packages/components/src/VirtualizedList/CellDatetime/index.js
  packages/components/src/VirtualizedList/CellTextIcon/TextIconColumn.component.js
  packages/components/src/VirtualizedList/CellTextIcon/index.js
  packages/components/src/VirtualizedList/CellTitle/TitleColumn.component.js
  packages/components/src/VirtualizedList/CellTitle/index.js
  packages/components/src/VirtualizedList/Content.component.js
  packages/components/src/VirtualizedList/ListGrid/ListGrid.test.js
  packages/components/src/VirtualizedList/ListTable/ListTable.test.js
  packages/components/src/VirtualizedList/RendererSelector.test.js
  packages/components/src/VirtualizedList/RowLarge/RowLarge.test.js
  packages/components/src/VirtualizedList/VirtualizedList.component.js
  packages/components/src/VirtualizedList/index.js
  packages/components/src/VirtualizedList/utils/gridrow.test.js
  packages/components/src/VirtualizedList/utils/tablerow.test.js
  packages/components/stories/ListComposition/ListComposition.js
  packages/components/stories/VirtualizedList.js
Labels: need review

#2347 feat(List composition): expose sort hook
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/sort.hook.js
  packages/components/src/List/ListComposition/Manager/sort.hook.test.js
  packages/components/src/List/ListComposition/Manager/sort.js
  packages/components/src/List/ListComposition/Manager/sort.test.js
  packages/components/src/List/ListComposition/index.js
Labels: need review

#2357 feat(ListComposition): useLocalStorage
  npm-audit/audit.json
  packages/components/package.json
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.test.js
  packages/components/src/List/ListComposition/index.js
  yarn.lock
Labels: need review

#2354 feat(List composition): expose filter hook
  output/components.eslint.txt
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/filter.js
  packages/components/src/List/ListComposition/Manager/filter.test.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.test.js
  packages/components/src/List/ListComposition/TextFilter/TextFilter.component.js
Labels: need review

#2358 feat(ListComposition): collection selection hook
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.test.js
Labels: need review

#2355 fix(theme): do not apply styles for inverse
  packages/components/src/SidePanel/SidePanel.scss
  packages/components/stories/SidePanel.js
Labels: need review

#2345 chore(Badge): Add a props label to BadgeDelete
  packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.js
  packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.test.js
  packages/components/src/Badge/BadgeComposition/BadgeDelete/__snapshots__/BadgeDelete.component.test.js.snap
Labels: need review

#2361 feat(ListComposition): hook to insert actions into collection
  output/components.eslint.txt
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.test.js
  packages/components/src/List/ListComposition/index.js
Labels: easy review, need review

#2337 feat(TabBar): Tabs responsive layout
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/components/stories/TabBar.js
Labels: need review

#2366 feat(VirtualizedList): title cell accepts functions as column data
  output/components.eslint.txt
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitle.test.js
  packages/components/src/VirtualizedList/utils/tablerow.js
  packages/components/stories/ListComposition/ListComposition.js
Labels: frontend, need review

#2368 feat(VirtualizedList): custom actions by item in collection actions hook
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.test.js
Labels: frontend, need review

#2367 feat(components/SubHeaderBar): back button margin
  packages/components/src/ActionBar/ActionBar.scss
  packages/components/src/SubHeaderBar/SubHeaderBar.scss
Labels: easy review, need review

#2370 fix(VirtualizedList): cell title propTypes
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
Labels: easy review, need review

#2371 chore: remove travis e2e run
  .travis.yml
  .travis/after_success_e2e.sh
Labels: easy review, need review
