Repository Talend/ui, pull requests merged in 2019-10, with the labels that each got.

#2448 replace responsive tab bar with button dropdown
  npm-audit/audit.json
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/stories/TabBar.js
Labels: need review

#2450 chore(container): update sandbox
  packages/containers/sandbox/mockBackend/mock/kit/example.json
  packages/containers/sandbox/mockBackend/mock/kit/index.js
  packages/containers/sandbox/mockBackend/mock/kit/titleMap.json
  packages/containers/sandbox/src/app/ComponentFormSandbox.js
  packages/containers/sandbox/src/app/SandboxBody.js
  packages/containers/sandbox/src/app/example.scss
  packages/containers/sandbox/src/app/index.js
  packages/containers/sandbox/src/assets/settings.json
  packages/containers/sandbox/webpack.config.dev.js
  packages/containers/sandbox/webpack.config.js
  packages/containers/sandbox/yarn.lock
Labels: need review

#2451 feat(components/FilterBar): data-test
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/FilterBar/FilterBar.test.js
Labels: easy review, enhancement, need review

#2449 feat(components/CollapsiblePanel): add skeleton instead of status text
  output/components.sasslint.txt
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/src/Status/Status.component.js
  packages/components/src/Status/Status.scss
  packages/components/src/Status/Status.snapshot.test.js
  packages/components/src/Status/__snapshots__/Status.snapshot.test.js.snap
  packages/components/stories/CollapsiblePanel.js
Labels: need review

#2453 fix(datagrid): missing constant
  packages/datagrid/src/constants/avro-type.constant.js
Labels: easy review, need review

#2452 fix(TPSVC-11545): add missing icon for selected element
  packages/components/src/TabBar/TabBar.component.js
Labels: easy review, need review

#2456 chore(eslint-config) update eslint api config to remove globals for lodash and angular
  packages/eslint-config/api-app-angular.yaml
  packages/eslint-config/api-app.yaml
Labels: easy review, need review

#2458 fix(Forms/SimpleCheckbox): using value props for checked attribute
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.test.js
Labels: easy review, need review

#2455 fix(Drawer): close action is not aligned anymore
  packages/components/src/Drawer/Drawer.scss
Labels: bug, easy review, need review

#2454 fix(List): padding on display chooser in list composition
  packages/components/src/List/ListComposition/DisplayMode/DisplayModeToggle.scss
Labels: bug, need review

#2310 chore(FilterBar): guideline update
  output/components.sasslint.txt
  output/containers.eslint.txt
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/FilterBar/FilterBar.scss
  packages/components/src/FilterBar/FilterBar.snapshot.test.js
  packages/components/src/FilterBar/FilterBar.test.js
  packages/components/src/FilterBar/__snapshots__/FilterBar.snapshot.test.js.snap
  packages/components/src/List/ListComposition/TextFilter/TextFilter.component.js
  packages/components/src/List/ListComposition/TextFilter/TextFilter.component.test.js
  packages/components/stories/List.js
  packages/containers/src/FilterBar/FilterBar.container.js
  packages/containers/src/List/List.sagas.js
  packages/containers/src/List/List.sagas.test.js
Labels: need review

#2461 fix(components/ResourcePicker): display the button to remove the filter
  packages/components/src/ResourcePicker/Toolbar/NameFilter/NameFilter.scss
Labels: bug, easy review, need review

#2457 feat(components/list): allow single selection
  output/components.eslint.txt
  packages/components/src/List/ListComposition/LazyLoadingList/__snapshots__/LazyLoadingList.component.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/ResourcePicker/__snapshots__/ResourcePicker.snap.test.js.snap
  packages/components/src/VirtualizedList/CellCheckbox/CellCheckbox.component.js
  packages/components/src/VirtualizedList/CellCheckbox/CellCheckbox.test.js
  packages/components/src/VirtualizedList/CellCheckbox/__snapshots__/CellCheckbox.test.js.snap
  packages/components/src/VirtualizedList/PropTypes.js
  packages/components/src/VirtualizedList/VirtualizedList.component.js
  packages/components/src/VirtualizedList/utils/__snapshots__/tablerow.test.js.snap
  packages/components/src/VirtualizedList/utils/constants.js
  packages/components/src/VirtualizedList/utils/tablerow.js
  packages/components/stories/VirtualizedList.js
Labels: easy review, enhancement, frontend, need review

#2465 chore: upgrade Storybook to 5.2.3
  npm-audit/audit.json
  output/components.sasslint.txt
  output/containers.eslint.txt
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  yarn.lock
Labels: easy review, enhancement, need review

#2463 fix(EditableText): stop push content with elipsis
  packages/components/src/Drawer/Drawer.scss
  packages/components/src/EditableText/EditableText.component.js
  packages/components/src/EditableText/EditableText.scss
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/components/stories/Drawer.js
  packages/components/stories/EditableText.js
Labels: bug, need review

#2464 feat(forms/comparator): display icons
  packages/forms/src/UIForm/fields/Comparator/Comparator.component.js
  packages/forms/src/UIForm/fields/Comparator/Comparator.component.test.js
  packages/forms/src/UIForm/fields/Comparator/Comparator.scss
  packages/forms/src/UIForm/fields/Comparator/__snapshots__/Comparator.component.test.js.snap
  packages/forms/src/UIForm/fields/Comparator/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/Comparator/displayMode/__snapshots__/TextMode.test.js.snap
  packages/forms/stories-core/json/fields/core-comparator-input.json
Labels: enhancement, need review

#2466 feat(components/list): be able to disable rows
  output/components.eslint.txt
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/VirtualizedList/CellCheckbox/CellCheckbox.component.js
  packages/components/src/VirtualizedList/CellCheckbox/__snapshots__/CellCheckbox.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitle.test.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitle.test.js.snap
  packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js
  packages/components/src/VirtualizedList/ListTable/ListTable.component.js
  packages/components/src/VirtualizedList/PropTypes.js
  packages/components/src/VirtualizedList/RendererSelector.component.js
  packages/components/src/VirtualizedList/RowSelection/RowSelection.component.js
  packages/components/src/VirtualizedList/RowSelection/RowSelection.scss
  packages/components/src/VirtualizedList/VirtualizedList.component.js
  packages/components/src/VirtualizedList/utils/__snapshots__/tablerow.test.js.snap
  packages/components/src/VirtualizedList/utils/tablerow.js
  packages/components/stories/VirtualizedList.js
Labels: enhancement, frontend, need review

#2440 chore(faceted-search): init a new faceted search package
  packages/faceted-search/.editorconfig
  packages/faceted-search/.gitignore
  packages/faceted-search/.npmignore
  packages/faceted-search/.sass-lint.yml
  packages/faceted-search/.storybook/addons.js
  packages/faceted-search/.storybook/config.js
  packages/faceted-search/.storybook/preview-head.html
  packages/faceted-search/.storybook/webpack.config.js
  packages/faceted-search/LICENSE
  packages/faceted-search/README.md
  packages/faceted-search/__mocks__/uuid.js
  packages/faceted-search/babel.config.js
  packages/faceted-search/i18next-scanner.config.js
  packages/faceted-search/package.json
  packages/faceted-search/src/constants.js
  packages/faceted-search/test/styleMock.js
Labels: need review

#2476 chore(faceted-search): change import
  packages/faceted-search/package.json
  packages/faceted-search/src/components/AdvancedSearch/AdvancedSearch.component.js
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.js
Labels: easy review, need review

#2478 fix(CollapsiblePanel): Fix border with nested components
  output/components.sasslint.txt
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/stories/CollapsiblePanel.js
Labels: bug, easy review, frontend, need review

#2482 chore(container): cleanup import
  npm-audit/audit.json
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  packages/containers/src/AboutDialog/AboutDialog.container.js
  packages/containers/src/Action/Action.connect.js
  packages/containers/src/ActionBar/ActionBar.connect.js
  packages/containers/src/ActionButton/ActionButton.connect.js
  packages/containers/src/ActionButton/ActionButton.test.js
  packages/containers/src/ActionDropdown/ActionDropdown.connect.js
  packages/containers/src/ActionDropdown/ActionDropdown.test.js
  packages/containers/src/ActionFile/ActionFile.connect.js
  packages/containers/src/ActionFile/ActionFile.test.js
  packages/containers/src/ActionIconToggle/ActionIconToggle.connect.js
  packages/containers/src/ActionSplitDropdown/ActionSplitDropdown.connect.js
  packages/containers/src/Actions/Actions.connect.js
  packages/containers/src/AppLoader/AppLoader.connect.js
  packages/containers/src/AppLoader/AppLoader.connect.test.js
  packages/containers/src/Badge/Badge.component.js
  packages/containers/src/Badge/Badge.test.js
  packages/containers/src/Breadcrumbs/Breadcrumbs.connect.js
  packages/containers/src/ConfirmDialog/ConfirmDialog.container.js
  packages/containers/src/ConfirmDialog/ConfirmDialog.test.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/EditableText/EditableText.container.js
  packages/containers/src/FilterBar/FilterBar.container.js
  packages/containers/src/HeaderBar/HeaderBar.container.js
  packages/containers/src/HomeListView/HomeListView.component.js
  packages/containers/src/HomeListView/HomeListView.test.js
  packages/containers/src/List/List.container.js
  packages/containers/src/Notification/Notification.container.js
  packages/containers/src/Notification/Notification.test.js
  packages/containers/src/ObjectViewer/ObjectViewer.container.js
  packages/containers/src/ObjectViewer/ObjectViewer.test.js
  packages/containers/src/SelectObject/SelectObject.component.js
  packages/containers/src/SidePanel/SidePanel.container.js
  packages/containers/src/SubHeaderBar/SubHeaderBar.container.js
  packages/containers/src/TabBar/TabBar.connect.js
  packages/containers/src/TabBar/TabBar.selectors.js
  packages/containers/src/TabBar/TabBar.test.js
  packages/containers/src/TreeView/TreeView.container.js
  packages/containers/src/Typeahead/Typeahead.container.js
Labels: easy review, need review

#2483 fix(ActionIconToggle): transparent border on focus
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
Labels: bug, easy review, need review

#2419 feat(components/sidepanel): side panel updates
  npm-audit/audit.json
  packages/components/package.json
  packages/components/src/Layout/TwoColumns/TwoColumns.scss
  packages/components/src/SidePanel/SidePanel.component.js
  packages/components/src/SidePanel/SidePanel.scss
  packages/components/stories/SidePanel.js
  packages/containers/examples/ExampleHomeListView.js
  yarn.lock
Labels: easy review, enhancement, need review

#2486 Fix(date picker): fix focus issue of date picker
  packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.component.js
  packages/components/src/DateTimePickers/pickers/CalendarPicker/__snapshots__/CalendarPicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
  packages/components/src/DateTimePickers/pickers/YearPicker/__snapshots__/YearPicker.test.js.snap
Labels: need review

#2484 fix(forms/Select): Add missing descriptionId / errorId props
  packages/forms/src/UIForm/fields/Select/Select.component.js
  packages/forms/src/UIForm/fields/Select/__snapshots__/Select.component.test.js.snap
Labels: bug, easy review, frontend, need review

#2490 fix(components/CollapsiblePanel): Add missing key props
  npm-audit/audit.json
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
Labels: bug, easy review, frontend, need review

#2492 fix(components/FocusManager): support ref as object in PropTypes
  packages/components/src/FocusManager/FocusManager.component.js
Labels: bug, easy review, frontend, need review

#2494 fix(theme/forms): Align field error font-size to guideline
  npm-audit/audit.json
  output/theme.sasslint.txt
  packages/theme/src/theme/_forms.scss
Labels: bug, easy review, frontend, need review

#2497 fix(faceted-search): fix failing tu
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js
  packages/faceted-search/src/components/AddFacetPopover/__snapshots__/AddFacetPopver.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.test.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.test.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.test.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeTextArea.component.test.js
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeTextArea.component.test.js.snap
  packages/faceted-search/src/components/BadgesGenerator/BadgesGenerator.component.js
  packages/faceted-search/src/components/BadgesGenerator/BadgesGenerator.component.test.js
  packages/faceted-search/src/components/BadgesGenerator/__snapshots__/BadgesGenerator.component.test.js.snap
  packages/faceted-search/src/components/FacetedSearch/FacetedSearch.component.js
  packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.scss
  packages/faceted-search/src/components/facetedSearch.propTypes.js
  packages/faceted-search/test-setup.js
Labels: need review

#2499 fix(components/list): default value for collection using useCollectionActions hook
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionActions.hook.js
Labels: easy review, enhancement, need review

#2491 feat(date range): DatePicker with range
  packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.component.js
  packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.test.js
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.scss
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.test.js
  packages/components/src/DateTimePickers/views/DateView/DateView.component.js
  packages/components/stories/DatePicker.js
Labels: need review

#2485 fix(cmf/onError): remove uiState aka PII
  packages/cmf/__tests__/onError.test.js
  packages/cmf/src/bootstrap.md
  packages/cmf/src/onError.js
  packages/cmf/src/onError.md
  packages/cmf/website/README.md
  packages/containers/src/Notification/Notification.sagas.js
Labels: need review

#2487 feat(faceted-search): add connection type badge
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js
  packages/faceted-search/src/components/AddFacetPopover/__snapshots__/AddFacetPopver.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.test.js
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.scss
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.js
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.test.js
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/index.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.scss
  packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperator.scss
  packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperatorPopover.component.js
  packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperatorPopover.component.test.js
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.js
  packages/faceted-search/src/components/Badges/BadgeOverlay/__snapshots__/BadgeOverlay.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.test.js
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
  packages/faceted-search/src/components/BadgesGenerator/BadgesGenerator.component.js
  packages/faceted-search/src/components/BadgesGenerator/BadgesGenerator.component.test.js
  packages/faceted-search/src/components/BadgesGenerator/__snapshots__/BadgesGenerator.component.test.js.snap
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
  packages/faceted-search/src/components/FacetedSearchIcon/FacetedSearchIcon.component.test.js
  packages/faceted-search/src/dictionary/badge.dictionary.js
  packages/faceted-search/src/dictionary/operator.dictionary.js
  packages/faceted-search/src/queryClient/tql.js
  packages/faceted-search/src/queryClient/tql.test.js
  packages/faceted-search/src/translate.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: need review

#2501 fix(faceted-search): tql error on checkboxes badge
  npm-audit/scripts.json
  packages/faceted-search/package.json
  packages/faceted-search/src/queryClient/tql.js
  packages/faceted-search/src/queryClient/tql.test.js
Labels: need review

#2475 fix(Components): badge proptypes
  packages/components/src/Badge/Badge.component.js
  packages/components/src/Badge/Badge.component.test.js
Labels: need review

#2504 fix(containers/breadcrumbs): loading state
  npm-audit/scripts.json
  packages/containers/src/Breadcrumbs/Breadcrumbs.connect.js
Labels: easy review, need review

#2513 feat(webapp/SwitchFacetedMode): Invert action basic <> advanced
  npm-audit/audit.json
  packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
  packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.scss
Labels: easy review, enhancement, frontend

#2510 fix(faceted-search/BadgeTextArea): Disable resize on textarea
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.scss
Labels: bug, easy review, frontend

#2509 feat(faceted-search/AddFacetPopover): Filter badge by label, not attribute
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
Labels: easy review, enhancement, frontend

#2507 feat(cmf): add Sentry support
  npm-audit/audit.json
  packages/cmf/__tests__/bootstrap.test.js
  packages/cmf/__tests__/middlewares/cmf.test.js
  packages/cmf/__tests__/onError.test.js
  packages/cmf/package.json
  packages/cmf/src/bootstrap.js
  packages/cmf/src/components/ErrorPanel/ErrorPanel.component.js
  packages/cmf/src/components/ErrorPanel/__snapshots__/ErrorPanel.component.test.js.snap
  packages/cmf/src/middlewares/cmf/index.js
  packages/cmf/src/onError.js
  packages/cmf/src/onError.md
  yarn.lock
Labels: need review
