Repository Talend/ui, pull requests merged in 2019-09, with the labels that each got.

#2313 chore(Collapsible): updating style and using component in forms
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/CollapsiblePanel/index.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.scss
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap
Labels: need review

#2369 fix(form/TUI-343): Pass schema from items in array
  output/components.sasslint.txt
  output/forms.eslint.txt
  packages/forms/src/UIForm/utils/array.js
  packages/forms/src/UIForm/utils/array.test.js
Labels: bug, frontend, need review

#2382 fix(Dropdown): down to up is disabled when there is not enough space
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.test.js
Labels: easy review, need review

#2377 fix(List): layout integration
  npm-audit/audit.json
  packages/components/src/List/ListComposition/LazyLoadingList/__snapshots__/LazyLoadingList.component.test.js.snap
  packages/components/src/List/ListComposition/List.scss
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.component.js
  packages/components/src/List/ListComposition/VList/VList.component.js
  packages/components/stories/Layout.js
Labels: easy review, need review

#2372 chore(version.js): Upgrades only option + downgrades highlights
  versions/version.js
Labels: easy review, need review

#2384 fix(TMC-18455): data list positioning
  output/components.sasslint.txt
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.scss
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.scss
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Labels: need review

#2383 chore(forms/ResourcePicker): updating the way selection works and sel…
  packages/components/src/ResourcePicker/Resource/Resource.scss
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.test.js
Labels: easy review, need review

#2381 feat(ListToolbar): Enhance toolbar list compound css
  npm-audit/audit.json
  packages/components/src/List/ListComposition/DisplayMode/DisplayModeToggle.scss
  packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.js
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/components/src/List/ListComposition/README.md
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.component.js
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.component.test.js
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.scss
  packages/components/src/List/ListComposition/Toolbar/__snapshots__/ListToolbar.component.test.js.snap
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2389 chore(Component): Tweak the list display mode api
  packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.js
  packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.test.js
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/ListManager.component.test.js
Labels: need review

#2380 feat(SortBy): update sort by composition in large mode
  packages/components/src/List/ListComposition/SortBy/SortBy.component.js
  packages/components/src/List/ListComposition/SortBy/SortBy.component.test.js
  packages/components/src/List/ListComposition/SortBy/SortBy.scss
  packages/components/src/List/ListComposition/SortBy/__snapshots__/SortBy.component.test.js.snap
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2390 feat(Component): SortBy list composition improve api
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/SortBy/SortBy.component.js
  packages/components/src/List/ListComposition/SortBy/SortBy.component.test.js
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2391 fix(components): the list doesn't take the all available height
  packages/components/src/List/ListComposition/List.scss
Labels: bug, need review

#2386 chore(EditableText): managing blur and escape
  packages/components/src/EditableText/EditableText.test.js
  packages/components/src/EditableText/InlineForm.component.js
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
Labels: easy review, need review

#2393 fix(About): year in copyright
  packages/components/src/AboutDialog/AboutDialog.component.js
  packages/components/src/AboutDialog/AboutDialog.snapshot.test.js
Labels: easy review, need review

#2387 feat(components): make the ressource picker less specific
  packages/components/src/ResourcePicker/Resource/Resource.component.js
  packages/components/src/ResourcePicker/Resource/Resource.scss
  packages/components/src/ResourcePicker/Resource/Resource.snap.test.js
  packages/components/src/ResourcePicker/Resource/__snapshots__/Resource.snap.test.js.snap
  packages/components/src/ResourcePicker/ResourcePicker.component.js
  packages/components/src/ResourcePicker/Toolbar/NameFilter/NameFilter.component.js
  packages/components/src/ResourcePicker/Toolbar/NameFilter/NameFilter.scss
  packages/components/src/ResourcePicker/Toolbar/NameFilter/NameFilter.snap.test.js
  packages/components/src/ResourcePicker/Toolbar/NameFilter/__snapshots__/NameFilter.snap.test.js.snap
  packages/components/stories/ResourcePicker.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.test.js
Labels: enhancement, need review

#2392 fix(Component): Render child ListToolbar Right
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.component.js
Labels: need review

#2395 fix(UIForm/array): Add titleMap to schema if it exist
  packages/forms/src/UIForm/utils/array.js
  packages/forms/src/UIForm/utils/array.test.js
Labels: bug, frontend, need review

#2373 feat(theme): checkbox and radio
  output/theme.sasslint.txt
  packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/__snapshots__/ColumnChooserBody.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/__snapshots__/SelectAllColumnsCheckbox.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap
  packages/components/src/ListView/Items/Item/__snapshots__/item.snapshot.test.js.snap
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/Table/Filters/__snapshots__/FiltersBar.test.js.snap
  packages/components/src/Table/TitleBar/__snapshots__/TitleBar.test.js.snap
  packages/components/src/Toggle/Toggle.component.js
  packages/components/src/Toggle/Toggle.snapshot.test.js
  packages/components/src/Toggle/__snapshots__/Toggle.snapshot.test.js.snap
  packages/components/stories/Checkbox.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/__snapshots__/SimpleCheckBox.test.js.snap
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.scss
  packages/forms/src/UIForm/fields/Radios/Radios.component.js
  packages/forms/src/UIForm/fields/Radios/__snapshots__/Radios.component.test.js.snap
  packages/forms/src/UIForm/fields/Toggle/__snapshots__/Toggle.component.test.js.snap
  packages/forms/src/UIForm/fields/Toggle/displayMode/__snapshots__/TextMode.test.js.snap
  packages/theme/example/index.html
  packages/theme/src/theme/_forms.checkbox.scss
  packages/theme/src/theme/_forms.guideline.scss
  packages/theme/src/theme/_forms.radio.scss
  packages/theme/src/theme/_forms.scss
  packages/theme/src/theme/_forms.switch.scss
Labels: enhancement, need review

#2402 Revert "feat(TabBar): Tabs responsive layout"
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/components/stories/TabBar.js
Labels: bug, need review

#2401 feat(TabBar): Tabs responsive layout
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/components/stories/TabBar.js
Labels: need review

#2408 fix(theme): inline checkboxes style
  output/theme.sasslint.txt
  packages/theme/example/index.html
  packages/theme/src/theme/_forms.scss
Labels: easy review, need review

#1837 feat(CMF/TUI-64): add on error handling
  packages/cmf/__tests__/App.test.js
  packages/cmf/__tests__/bootstrap.test.js
  packages/cmf/__tests__/middlewares/cmf.test.js
  packages/cmf/__tests__/onError.test.js
  packages/cmf/__tests__/reducers/index.test.js
  packages/cmf/assets/diagram-onError-sequence.puml
  packages/cmf/assets/diagram-onError-sequence.svg
  packages/cmf/src/App.js
  packages/cmf/src/bootstrap.js
  packages/cmf/src/bootstrap.md
  packages/cmf/src/cmfModule.merge.js
  packages/cmf/src/components/ErrorBoundary/ErrorBoundary.component.js
  packages/cmf/src/components/ErrorBoundary/ErrorBoundary.component.test.js
  packages/cmf/src/components/ErrorFeedBack/ErrorFeedBack.component.js
  packages/cmf/src/components/ErrorFeedBack/ErrorFeedBack.component.test.js
  packages/cmf/src/components/ErrorFeedBack/index.js
  packages/cmf/src/components/ErrorPanel/ErrorPanel.component.js
  packages/cmf/src/components/ErrorPanel/ErrorPanel.component.test.js
  packages/cmf/src/components/ErrorPanel/__snapshots__/ErrorPanel.component.test.js.snap
  packages/cmf/src/components/ErrorPanel/index.js
  packages/cmf/src/constant.js
  packages/cmf/src/index.js
  packages/cmf/src/middlewares/cmf/index.js
  packages/cmf/src/onError.js
  packages/cmf/src/onError.md
  packages/cmf/src/reducers/index.js
  packages/cmf/src/store.js
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Notification/Notification.component.js
  packages/components/src/Notification/__snapshots__/Notification.snap.test.js.snap
  packages/components/src/Notification/__snapshots__/Notification.test.js.snap
  packages/containers/src/Notification/Notification.sagas.js
  packages/logging/src/api/errorTransformer.js
Labels: need review

#2412 feat(components/tabbar): be able to disable responsive behavior
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/components/stories/TabBar.js
Labels: easy review, need review

#2397 Jill(feat) use tertiary button for date and navigation button in date picker
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.scss
  packages/components/src/DateTimePickers/pickers/DatePicker/__snapshots__/DatePicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.scss
  packages/components/src/DateTimePickers/shared/styles/mixins.scss
  packages/components/src/DateTimePickers/views/DateTimeView/DateTimeView.component.js
  packages/components/src/DateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
  packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.component.js
  packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.scss
  packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.test.js
  packages/components/src/DateTimePickers/views/HeaderTitle/__snapshots__/HeaderTitle.test.js.snap
  packages/components/src/DateTimePickers/views/MonthYearView/MonthYearView.component.js
  packages/components/src/DateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
  packages/components/src/DateTimePickers/views/ViewLayout/ViewLayout.scss
Labels: need review

#2415 fix(Components): overflow in list composition
  packages/components/src/List/ListComposition/List.scss
Labels: need review

#2417 chore/enhance resize
  packages/components/src/VirtualizedList/HeaderResizable/HeaderResizable.component.js
  packages/components/src/VirtualizedList/HeaderResizable/HeaderResizable.component.test.js
  packages/components/src/VirtualizedList/HeaderResizable/__snapshots__/HeaderResizable.component.test.js.snap
  packages/components/src/VirtualizedList/VirtualizedList.component.js
Labels: need review

#2418 fix(cmf): trigger error on console when the value on the setting is null
  packages/cmf/__tests__/onError.test.js
  packages/cmf/src/onError.js
Labels: bug, easy review, need review

#2410 fix(UIForm/Array): For single select, set default value as first enum item
  packages/forms/src/UIForm/fieldsets/Array/Array.component.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js
Labels: bug, frontend, need review

#2421 fix(components/typeahead): fix popper usage
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
  npm-audit/router.json
  npm-audit/scripts.json
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/components/stories/Typeahead.js
Labels: easy review, enhancement, need review

#2423 chore(Component): renaming resizing variable in virtualized list
  packages/components/src/VirtualizedList/VirtualizedList.component.js
Labels: need review

#2424 fix(TSD-408): double scroll bar on deprecated multi tag select
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/MultiSelectTagWidget.scss
Labels: easy review, need review

#2426 fix(forms): step attribute for input with type number
  packages/forms/src/UIForm/fields/Comparator/README.md
  packages/forms/src/UIForm/fields/Text/Text.component.js
  packages/forms/src/UIForm/fields/Text/Text.component.test.js
  packages/forms/stories-core/json/fields/core-text.json
Labels: easy review, enhancement, need review

#2411 fix(components): fix errors on proptypes
  packages/components/src/ResourcePicker/Resource/Resource.component.js
  packages/components/src/ResourcePicker/ResourcePicker.component.js
  packages/components/src/ResourcePicker/Toolbar/SortOptions/OrderChooser/OrderChooser.component.js
  packages/components/src/ResourcePicker/Toolbar/Toolbar.component.js
  packages/components/src/RichTooltip/RichLayout/RichLayout.component.js
  packages/components/src/RichTooltip/RichLayout/RichLayout.test.js
  packages/components/src/RichTooltip/RichLayout/__snapshots__/RichLayout.test.js.snap
Labels: bug, easy review

#2429 fix(components/subheaderbar): icon not centered on ie
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
Labels: bug, easy review, frontend, need review

#2428 feat(components/slider): range
  packages/components/src/Slider/Slider.component.js
  packages/components/src/Slider/Slider.snap.test.js
  packages/components/src/Slider/__snapshots__/Slider.snap.test.js.snap
  packages/components/stories/Slider.js
Labels: easy review, enhancement, need review

#2430 fix(components/ListComposition): Expose useCollectionSelection hook
  packages/components/src/List/ListComposition/index.js
Labels: need review

#2406 feat(TCCUI65/calendar): show 6 weeks
  output/components.eslint.txt
  packages/components/__mocks__/day-calendar.js
  packages/components/__mocks__/month-calendar.js
  packages/components/src/DateTimePickers/generator.js
  packages/components/src/DateTimePickers/generator.test.js
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.component.js
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.scss
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.test.js
  packages/components/src/DateTimePickers/pickers/DatePicker/__snapshots__/DatePicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.component.js
  packages/components/src/DateTimePickers/pickers/MonthPicker/__snapshots__/MonthPicker.test.js.snap
  packages/components/src/Gesture/withCalendarGesture.js
  packages/components/src/Gesture/withCalendarGesture.test.js
Labels: need review

#2425 feat(TPSVC-11298): tabs update
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/components/stories/TabBar.js
  packages/forms/src/UIForm/fieldsets/Tabs/__snapshots__/Tabs.component.test.js.snap
  packages/theme/example/index.html
  packages/theme/src/theme/_navs.scss
Labels: easy review, enhancement, need review

#2340 fix(components/titlesubheader): fix warning when using non string subtitle
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
Labels: need review

#2432 chore: upgrade storybook to 5.2
  npm-audit/audit.json
  output/components.eslint.txt
  packages/components/package.json
  packages/components/src/GridLayout/Tile/Skeleton/SkeletonTile.component.js
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  yarn.lock
Labels: easy review, enhancement, need review

#2433 feat(TCCUI65 date picker)improve the padding for arrow
  packages/components/src/DateTimePickers/views/ViewLayout/ViewLayout.scss
Labels: easy review

#2434 feat(TCCUI-65/date picker): set min-height min-width
  packages/components/src/DateTimePickers/pickers/DateTimePicker/DateTimePicker.scss
  packages/components/stories/DatePicker.js
Labels: easy review, need review

#2435 feat(TCCUI-65/date picker): move black border for date button focus
  packages/components/src/DateTimePickers/pickers/DateTimePicker/DateTimePicker.scss
Labels: easy review, need review

#2439 fix: set back uppercase in tabs
  npm-audit/audit.json
  packages/theme/src/theme/_navs.scss
Labels: easy review, need review

#2431 feat(TCCUI65/Calendar) add underline in month picker
  npm-audit/audit.json
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.scss
  packages/components/src/DateTimePickers/pickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/pickers/DateTimePicker/DateTimePicker.scss
  packages/components/src/DateTimePickers/pickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/shared/styles/mixins.scss
  packages/components/src/DateTimePickers/views/ViewLayout/ViewLayout.scss
Labels: need review

#2353 fix(cmf): display loading screen during settings download
  packages/cmf/__tests__/App.test.js
  packages/cmf/__tests__/settings.test.js
  packages/cmf/src/App.js
  packages/cmf/src/bootstrap.js
  packages/cmf/src/settings.js
Labels: need review

#2446 fix(components/typeahead): autofocus
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
Labels: bug, easy review, need review
