Repository Talend/ui, pull requests merged in 2019-12, with the labels that each got.

#2554 fix(faceted-search/queryClient): Fix TQL creation function with numbers
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.test.js
  packages/components/stories/List.js
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/queryClient/tql.js
  packages/faceted-search/src/queryClient/tql.test.js
Labels: bug, easy review, frontend, need review

#2563 feat(forms/lang): Update some array messages to be more readable
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
  packages/forms/src/UIForm/lang.js
Labels: easy review, enhancement, frontend, need review

#2566 fix(components/sidepanel): remove border
  npm-audit/audit.json
  packages/components/src/SidePanel/SidePanel.scss
Labels: bug, easy review, frontend, need review

#2561 feat(components): richlayout with forwardref
  packages/components/src/RichTooltip/RichLayout/RichLayout.component.js
  packages/components/src/RichTooltip/RichLayout/__snapshots__/RichLayout.test.js.snap
  packages/components/stories/RichTooltip.js
Labels: bug, need review

#2564 fix(TMC-18418): simplebar-does-not-work-in-firefox
  packages/components/src/SidePanel/SidePanel.scss
Labels: easy review, need review

#2571 feat(List): expose visible rows range
  npm-audit/audit.json
  packages/components/src/List/ListComposition/LazyLoadingList/LazyLoadingList.component.js
  packages/components/src/VirtualizedList/RendererSelector.component.js
  packages/components/src/VirtualizedList/VirtualizedList.component.js
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2574 feat(cmf): allOf expression
  packages/cmf/__tests__/expressions/index.test.js
  packages/cmf/src/expressions/allOf.js
  packages/cmf/src/expressions/index.js
  packages/cmf/src/expressions/index.md
Labels: easy review, enhancement, need review

#2573 fix(List): fix loader position on large display mode
  npm-audit/audit.json
  packages/components/src/VirtualizedList/VirtualizedList.scss
Labels: easy review, need review

#2567 chore(Datalist): adding onBlur in props
  npm-audit/audit.json
  npm-audit/scripts.json
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
Labels: easy review, need review

#2578 fix(UIForm): pass array item key to resolve index in condition
  packages/forms/src/UIForm/utils/validation.js
Labels: easy review, need review

#2579 feat(containers/appLoader): add renderer props to allow customisation
  packages/components/src/AppLoader/AppLoader.md
  packages/containers/.storybook/webpack.config.js
  packages/containers/examples/ExampleAppLoader.js
  packages/containers/src/AppLoader/AppLoader.connect.js
Labels: enhancement, need review

#2577 feat(Components): Dynamic enumeration height
  packages/components/src/Enumeration/Enumeration.snapshot.test.js
  packages/components/src/Enumeration/Items/Items.component.js
  packages/components/src/Enumeration/Items/Items.scss
  packages/components/stories/Enumeration.js
  packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Labels: need review

#2580 chore(storybook) upgrade storybook deps
  npm-audit/audit.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  versions/dependencies.js
  yarn.lock
Labels: dependencies, easy review

#2565 feat(icons): conversion.svg mask.svg broom.svg maths.svg
  packages/icons/src/svg/core/broom.svg
  packages/icons/src/svg/core/conversion.svg
  packages/icons/src/svg/core/mask.svg
  packages/icons/src/svg/core/maths.svg
Labels: easy review, need review

#2584 fix(icons): svg close tag
  npm-audit/audit.json
  packages/icons/scripts/react.js
Labels: need review

#2587 feat(FacetedSearch): Add skeleton to faceted search icon
  npm-audit/audit.json
  packages/faceted-search/src/components/FacetedSearchIcon/FacetedSearchIcon.component.js
  packages/faceted-search/src/components/FacetedSearchIcon/FacetedSearchIcon.component.test.js
  packages/faceted-search/src/components/FacetedSearchIcon/__snapshots__/FacetedSearchIcon.component.test.js.snap
  packages/faceted-search/stories/facetedSearch.story.js
Labels: need review

#2588 chore(FacetedSearch): release 0.2.4
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
Labels: need review

#2570 fix(components/virtualizedlist): increase row height in large mode
  packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js
Labels: bug, easy review, frontend, need review

#2592 feat(TMC-15974): pass custom class name to field template
  npm-audit/audit.json
  packages/forms/src/UIForm/fields/CheckBox/CheckBox.component.js
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.js
Labels: easy review, need review
