Repository Talend/ui, pull requests merged in 2019-04, with the labels that each got.

#2109 poc(components): add css module util
  packages/components/src/PieChart/PieChartButton.component.js
  packages/components/src/PieChart/PieChartIcon.component.js
  packages/components/src/PieChart/__snapshots__/PieChartButton.test.js.snap
  packages/components/src/PieChart/__snapshots__/PieChartIcon.test.js.snap
  packages/components/src/Skeleton/Skeleton.component.js
  packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
  packages/components/src/theme.js
  packages/components/src/theme.test.js
Labels: enhancement, need review, question

#2122 fix(components/GuidedTour): style
  output/components.sasslint.txt
  packages/components/src/GuidedTour/GuidedTour.scss
Labels: easy review, enhancement, need review

#2089 fix(DatePicker): call onChange on Done button
  packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js
Labels: need review

#2123 chore: update react and enzyme
  npm-audit/audit.json
  npm-audit/package-lock.json
  npm-audit/package.json
  packages/cmf-cqrs/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/icons/package.json
  packages/router/package.json
  packages/sagas/package.json
  packages/scripts/package.json
  packages/storybook-cmf/package.json
  versions/dependencies.js
  versions/version.js
  yarn.lock
Labels: enhancement, need review

#2110 feat(cmf): allow bootstrap without settings
  packages/cmf/__tests__/bootstrap.test.js
  packages/cmf/src/bootstrap.js
Labels: breaking change, easy review, frontend, need review

#2112 Revert "Revert "fix(cmf): remove automatic event from onEvent [BC]"
  packages/cmf/src/onEvent.js
Labels: breaking change, easy review

#2127 fix(components/GuidedTour): valid jsx
  packages/components/src/GuidedTour/GuidedTour.component.js
Labels: easy review, enhancement, need review

#2040 feat(UIForm): trigger properties management from ComponentForm to UIForm
  npm-audit/audit.json
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
Labels: breaking change, frontend, need review

#2131 fix(forms): show scrollbar inside drawer form in IE11
  npm-audit/audit.json
  packages/forms/src/UIForm/UIForm.scss
Labels: need review

#2133 fix(Scripts): use path to build file path forw windows compat
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: easy review, need review

#2135 fix(UIForm): deep validation is now taken into account
  npm-audit/audit.json
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
Labels: frontend, need review

#2138 feat(scripts): support webpack config as function
  npm-audit/audit.json
  packages/scripts/webapp/config/webpack.config.js
Labels: easy review, need review

#2137 fix(components/GuidedTour): icons color and a11y
  output/components.sasslint.txt
  packages/components/package.json
  packages/components/src/GuidedTour/GuidedTour.scss
  yarn.lock
Labels: easy review, enhancement, need review

#2136 chore(component): Make vlist code more explicit
  packages/components/src/List/ListComposition/VList/VList.component.js
Labels: need review

#2141 fix(scripts): Update path for eslint in IDE
  packages/scripts/webapp/preset/README.md
Labels: easy review, need review

#2128 feat(scripts): accepts extension
  packages/scripts/webapp/preset/config/test/jest-preprocess.js
  packages/scripts/webapp/preset/preset-talend-babel.js
  packages/scripts/webapp/preset/preset-talend-eslint.js
  packages/scripts/webapp/preset/preset-talend-jest.js
  packages/scripts/webapp/preset/preset-talend-karma.js
  packages/scripts/webapp/scripts/build-lib.js
  packages/scripts/webapp/scripts/lint-es.js
  packages/scripts/webapp/scripts/test.js
  packages/scripts/webapp/utils/env.js
Labels: frontend, need review

#2129 feat(Scripts): extends preset configuration
  packages/scripts/index.js
  packages/scripts/package.json
  packages/scripts/webapp/doc/customisation.md
  packages/scripts/webapp/preset/config/jest.config.js
  packages/scripts/webapp/preset/config/test/jest-preprocess.js
  packages/scripts/webapp/scripts/extends.js
Labels: frontend, need review

#2139 fix(TUI-380): Tooltip not shown for actions with overlay
  packages/components/src/OverlayTrigger/OverlayTrigger.component.js
Labels: easy review, need review

#2142 chore(i18n): update talend-i18n project name
  talend-i18n.json
Labels: easy review, need review

#2124 fix(icon): remove icon border in enumeration
  npm-audit/audit.json
  packages/components/src/Enumeration/Enumeration.scss
  packages/components/src/Enumeration/Header/Header.scss
  packages/components/src/Enumeration/Items/Item/Item.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/stories/Enumeration.js
  packages/theme/src/theme/_buttons.scss
Labels: need review

#2144 fix(components): colors in pie chart button
  packages/components/src/PieChart/PieChartIcon.component.js
  packages/components/src/PieChart/__snapshots__/PieChartIcon.test.js.snap
Labels: bug, easy review, need review

#2148 fix(Icons): transform stop-color to stopColor for react
  packages/icons/scripts/react.js
Labels: easy review, frontend, need review

#2143 feat(Scripts): decorrelate dev server from dev mode
  packages/scripts/package.json
  packages/scripts/webapp/doc/getting-started.md
  packages/scripts/webapp/index.js
  packages/scripts/webapp/preset/config/webpack.config.dev.js
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: easy review, need review

#2150 fix(HeaderBar/icons): should be $larger width
  npm-audit/audit.json
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/theme/src/theme/_guidelines.scss
Labels: easy review, need review

#2153 chore(forms): playground
  package.json
  packages/forms/.storybook/addons.js
  packages/forms/package.json
  packages/forms/stories-core/index.js
  packages/forms/stories-core/playgroundStory.js
  yarn.lock
Labels: easy review, enhancement, need review

#2155 fix(tesb-25278): SidePanel visual update
  npm-audit/audit.json
  packages/components/src/SidePanel/SidePanel.scss
  screenshots/components-sidepanel.json
Labels: need review

#2156 feat(TPSVC-8903): add action btn to HeaderBar
  output/components.eslint.txt
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/stories/HeaderBar.js
Labels: need review

#2154 chore(ResourcePicker): making sort/filter customizable in form and hi…
  packages/components/src/ResourcePicker/Resource/Resource.component.js
  packages/components/src/ResourcePicker/Resource/Resource.snap.test.js
  packages/components/stories/ResourcePicker.js
  packages/forms/src/UIForm/fields/ResourcePicker/README.md
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.test.js
  packages/forms/src/UIForm/fields/ResourcePicker/__snapshots__/ResourcePicker.component.test.js.snap
  packages/forms/stories-core/json/fields/core-resource-picker.json
Labels: easy review, need review

#2161 fix(containers/HeaderBar): Broken saga on Edge
  packages/containers/src/HeaderBar/HeaderBar.sagas.js
  packages/containers/src/HeaderBar/HeaderBar.sagas.test.js
Labels: easy review, need review

#2163 chore: sass-lint dep vulnerability
  npm-audit/audit.json
  npm-audit/package-lock.json
  npm-audit/package.json
  output/components.sasslint.txt
  output/theme.sasslint.txt
  packages/components/package.json
  packages/forms/package.json
  packages/theme/package.json
  versions/dependencies.js
Labels: easy review, frontend, need review

#2159 feat(icons): rest
  packages/icons/src/svg/rest.svg
Labels: easy review, need review

#2147 chore: clean dependencies
  packages/cmf-cqrs/package.json
  packages/cmf/package.json
  packages/cmf/scripts/cmf-settings.utils.js
  packages/components/package.json
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleActionIconToggle.js
  packages/containers/package.json
  packages/containers/sandbox/package.json
  packages/containers/src/Notification/pushNotification.js
  packages/containers/src/SelectObject/SelectObject.component.js
  packages/containers/src/SidePanel/SidePanel.test.js
  packages/datagrid/.storybook/config.js
  packages/datagrid/package.json
  packages/forms/__mocks__/data.js
  packages/forms/package.json
  packages/html-webpack-plugin/package.json
  packages/router/package.json
  packages/sagas/package.json
  packages/scripts/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
  yarn.lock
Labels: frontend, need review

#2166 Revert "fix(forms): handle restricted option on the widget Datalist (#2029)
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/forms/stories-core/json/fields/core-datalist.json
Labels: easy review, frontend, need review

#2164 feat(cmf): separate cmf-settings extract and source configs
  packages/cmf/scripts/cmf-settings.i18n.js
Labels: easy review, frontend, need review

#2168 chore: talend/scripts dependency security issues
  npm-audit/audit.json
  packages/scripts/package.json
Labels: easy review, frontend, need review
