Repository Talend/ui, pull requests merged in 2019-07, with the labels that each got.

#2272 fix(components/Datalist): restricted mode
  npm-audit/scripts.json
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/stories/Datalist.js
  packages/forms/stories-core/json/fields/core-datalist.json
Labels: need review

#2274 feat(icons): history
  npm-audit/scripts.json
  packages/icons/src/svg/core/history.svg
Labels: easy review, need review

#2261 fix(component): add missing translation
  packages/components/src/ListView/ListView.component.js
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/VirtualizedList/NoRows/NoRows.component.js
Labels: easy review, need review

#2281 fix: stories with i18n, removing provider
  packages/components/stories/Enumeration.js
  packages/components/stories/GuidedTour.js
  packages/components/stories/HeaderBar.js
  packages/components/stories/List.js
  packages/components/stories/ListView.js
  packages/components/stories/SidePanel.js
  packages/components/stories/config/i18n.js
  packages/containers/examples/ExampleDeleteResource.js
  packages/containers/examples/ExampleList.js
  packages/containers/examples/config/i18n.js
  packages/datagrid/stories/config/i18n.js
  packages/datagrid/stories/datagrid.component.js
  packages/datagrid/stories/datagrid.container.js
  packages/forms/.storybook/config.js
  packages/forms/stories-core/index.js
Labels: frontend, need review

#2282 fix(i18n): update i18n
  I18n.md
  packages/components/.storybook/config.js
  packages/components/package.json
  packages/components/src/TranslateWrapper/TranslateWrapper.component.js
  packages/components/src/translate.js
  packages/components/src/translate.test.js
  packages/components/stories/Enumeration.js
  packages/containers/package.json
  packages/containers/sandbox/package.json
  packages/containers/src/GuidedTour/README.md
  packages/containers/src/Notification/README.md
  packages/containers/src/translate.js
  packages/datagrid/package.json
  packages/datagrid/src/translate.js
  packages/forms/package.json
  packages/forms/src/translate.js
  packages/forms/stories/config/i18n.js
  packages/generator/generators/react-cmf/templates/package.json
  versions/dependencies.js
  yarn.lock
Labels: enhancement, need review

#2275 feat(Components): Badge refactoring to composition
  output/components.eslint.txt
  packages/components/src/Badge/Badge.component.js
  packages/components/src/Badge/Badge.component.test.js
  packages/components/src/Badge/Badge.snap.test.js
  packages/components/src/Badge/BadgeComposition/BadgeCategory/BadgeCategory.component.js
  packages/components/src/Badge/BadgeComposition/BadgeCategory/BadgeCategory.component.test.js
  packages/components/src/Badge/BadgeComposition/BadgeCategory/__snapshots__/BadgeCategory.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeCategory/index.js
  packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.js
  packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.test.js
  packages/components/src/Badge/BadgeComposition/BadgeDelete/__snapshots__/BadgeDelete.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeDelete/index.js
  packages/components/src/Badge/BadgeComposition/BadgeIcon/BadgeIcon.component.js
  packages/components/src/Badge/BadgeComposition/BadgeIcon/BadgeIcon.component.test.js
  packages/components/src/Badge/BadgeComposition/BadgeIcon/__snapshots__/BadgeIcon.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeIcon/index.js
  packages/components/src/Badge/BadgeComposition/BadgeLabel/BadgeLabel.component.js
  packages/components/src/Badge/BadgeComposition/BadgeLabel/BadgeLabel.component.test.js
  packages/components/src/Badge/BadgeComposition/BadgeLabel/__snapshots__/BadgeLabel.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeLabel/index.js
  packages/components/src/Badge/BadgeComposition/BadgeSeparator/BadgeSeparator.component.js
  packages/components/src/Badge/BadgeComposition/BadgeSeparator/BadgeSeparator.component.test.js
  packages/components/src/Badge/BadgeComposition/BadgeSeparator/__snapshots__/BadgeSeparator.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeSeparator/index.js
  packages/components/src/Badge/BadgeComposition/index.js
  packages/components/src/Badge/__snapshots__/Badge.component.test.js.snap
  packages/components/src/Badge/__snapshots__/Badge.snap.test.js.snap
  packages/components/stories/Badge.js
Labels: need review

#2289 feat(forms/checkbox): data-feature
  packages/forms/src/UIForm/fields/CheckBox/README.md
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.test.js
  packages/forms/stories-core/json/fields/core-checkbox.json
Labels: easy review, need review

#2284 fix(drawer): do not override theme for cancel Action
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.test.js
  packages/components/stories/Drawer.js
Labels: need review

#2280 fix(forms): Add translations for tooltips in arrayitem/collapsiblefieldset
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/ArrayItem.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap
Labels: need review

#2291 fix(components): move translations from defaultProps
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
  npm-audit/router.json
  npm-audit/scripts.json
  packages/components/src/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.test.js
  packages/containers/src/Typeahead/__snapshots__/Typeahead.test.js.snap
  packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Labels: need review

#2287 fix(intercom): change default values on open/close
  packages/components/src/ActionIntercom/Intercom.component.js
  packages/components/src/ActionIntercom/Intercom.component.test.js
  packages/components/src/ActionIntercom/__snapshots__/Intercom.component.test.js.snap
Labels: easy review, need review

#2293 feat(components/datepicker): fixed position
  packages/components/package.json
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.scss
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap
  packages/components/stories/DatePicker.js
Labels: easy review, enhancement, need review

#2300 fix(components/Typeahead): import I18N_DOMAIN_COMPONENTS
  packages/components/src/Typeahead/Typeahead.component.js
Labels: need review

#2296 fix(ListComposition): Rename InfiniteScrollList to LazyLoadingList
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
  packages/components/src/List/ListComposition/InfiniteScrollList/index.js
  packages/components/src/List/ListComposition/LazyLoadingList/LazyLoadingList.component.js
  packages/components/src/List/ListComposition/LazyLoadingList/LazyLoadingList.component.test.js
  packages/components/src/List/ListComposition/LazyLoadingList/README.md
  packages/components/src/List/ListComposition/LazyLoadingList/__snapshots__/LazyLoadingList.component.test.js.snap
  packages/components/src/List/ListComposition/LazyLoadingList/index.js
  packages/components/src/List/ListComposition/index.js
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2304 chore: set key and default translation to singular
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
Labels: easy review, need review

#2230 fix(Resourcepicker): order chooser color
  packages/components/src/ResourcePicker/Toolbar/SortOptions/OrderChooser/OrderChooser.scss
Labels: easy review, need review

#2303 feat(components/tooltip): remove overlay usage
  packages/components/src/ActionIntercom/Intercom.component.test.js
  packages/components/src/ActionIntercom/__snapshots__/Intercom.component.test.js.snap
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeCategory/BadgeCategory.component.test.js
  packages/components/src/Badge/BadgeComposition/BadgeCategory/__snapshots__/BadgeCategory.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeDelete/__snapshots__/BadgeDelete.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeLabel/BadgeLabel.component.test.js
  packages/components/src/Badge/BadgeComposition/BadgeLabel/__snapshots__/BadgeLabel.component.test.js.snap
  packages/components/src/Badge/__snapshots__/Badge.component.test.js.snap
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
  packages/components/src/Enumeration/Items/Item/Item.test.js
  packages/components/src/HeaderBar/HeaderBar.test.js
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/components/src/List/ListComposition/TextFilter/__snapshots__/TextFilter.component.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/Header.snapshot.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/headerInput.snapshot.test.js.snap
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/Progress/__snapshots__/Progress.test.js.snap
  packages/components/src/Table/Filters/__snapshots__/FiltersBar.test.js.snap
  packages/components/src/Table/TitleBar/__snapshots__/TitleBar.test.js.snap
  packages/components/src/TooltipTrigger/TooltipTrigger.component.js
  packages/components/src/TooltipTrigger/TooltipTrigger.hook.js
  packages/components/src/TooltipTrigger/TooltipTrigger.scss
  packages/components/src/TooltipTrigger/TooltipTrigger.test.js
  packages/components/src/TooltipTrigger/__snapshots__/TooltipTrigger.test.js.snap
  packages/components/src/Typeahead/Typeahead.test.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/components/stories/TooltipTrigger.js
  packages/forms/src/UIForm/fields/ListView/__snapshots__/ListView.component.test.js.snap
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.test.js
  packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Labels: enhancement, need review

#2307 fix(components/datetimepicker): same z-index as dropdown by default
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
  npm-audit/router.json
  npm-audit/scripts.json
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.scss
Labels: easy review, need review

#2305 chore: set key and default translation to singular in dates
  packages/components/src/DateFnsLocale/locale.js
  packages/components/src/DateFnsLocale/locale.test.js
Labels: easy review, need review

#2285 fix(icons/operators): remove fill attribute
  packages/icons/src/svg/components/equal.svg
  packages/icons/src/svg/core/contains.svg
  packages/icons/src/svg/core/equal.svg
  packages/icons/src/svg/core/less-than-equal.svg
  packages/icons/src/svg/core/less-than.svg
  packages/icons/src/svg/core/more-than-equal.svg
  packages/icons/src/svg/core/more-than.svg
  packages/icons/src/svg/core/not-equal.svg
Labels: easy review, need review

#2309 fix(forms): onSubmitEnter should be passed all of the time
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
Labels: bug, easy review, enhancement, frontend, need review

#2299 fix(generator): cmf do not depends on dotfiles
  npm-audit/audit.json
  packages/generator/generators/react-cmf/index.js
Labels: easy review, need review
