Repository Talend/ui, pull requests merged in 2019-01, with the labels that each got.

#1938 fix(forms/Buttons): Not forwarded className
  npm-audit/audit.json
  packages/forms/src/UIForm/fields/Button/Buttons.component.js
  packages/forms/src/UIForm/fields/Button/Buttons.component.test.js
  packages/forms/src/UIForm/fields/Button/__snapshots__/Buttons.component.test.js.snap
Labels: easy review, need review

#1936 fix(UIFrom) : hidden error not clean
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
  packages/forms/src/UIForm/utils/validation.js
  packages/forms/src/UIForm/utils/validation.test.js
Labels: need review

#1937 fix(TPSVC-7304): add min and max attributes to text input
  packages/forms/src/UIForm/fields/Text/Text.component.js
  packages/forms/src/UIForm/fields/Text/Text.component.test.js
  packages/forms/src/UIForm/fields/Text/__snapshots__/Text.component.test.js.snap
  packages/forms/stories-core/json/fields/core-text.json
Labels: easy review, need review

#1940 fix(Typeahead): dropdown display
  output/components.sasslint.txt
  packages/components/src/Datalist/Datalist.scss
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.scss
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/forms/src/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Labels: easy review, frontend, need review

#1943 feat(Dialog): remove specific title style
  packages/components/src/Dialog/Dialog.scss
  packages/theme/src/theme/_modals.scss
Labels: easy review, frontend, need review

#1923 feat(scripts): i18n version
  packages/scripts/README.md
  packages/scripts/internationalization/README.md
  packages/scripts/internationalization/common/error.js
  packages/scripts/internationalization/common/log.js
  packages/scripts/internationalization/common/version.js
  packages/scripts/internationalization/common/xtm.js
  packages/scripts/internationalization/index.js
  packages/scripts/internationalization/scripts/download.js
  packages/scripts/internationalization/scripts/extract.js
  packages/scripts/internationalization/scripts/to-github.js
  packages/scripts/internationalization/scripts/upload.js
Labels: frontend, need review

#1946 feat(component): ResourcePicker
  output/components.eslint.txt
  packages/components/src/ResourcePicker/Resource/Resource.component.js
  packages/components/src/ResourcePicker/Resource/Resource.scss
  packages/components/src/ResourcePicker/Resource/Resource.snap.test.js
  packages/components/src/ResourcePicker/Resource/__snapshots__/Resource.snap.test.js.snap
  packages/components/src/ResourcePicker/Resource/index.js
  packages/components/src/ResourcePicker/ResourcePicker.component.js
  packages/components/src/ResourcePicker/ResourcePicker.snap.test.js
  packages/components/src/ResourcePicker/__snapshots__/ResourcePicker.snap.test.js.snap
  packages/components/src/ResourcePicker/index.js
  packages/components/src/index.js
  packages/components/stories/ResourcePicker.js
  packages/components/stories/index.js
Labels: easy review, frontend, need review

#1951 fix(containers/ComponentForm): security config from saga http
  packages/containers/src/ComponentForm/ComponentForm.md
  packages/containers/src/ComponentForm/kit/createTriggers.js
  packages/containers/src/ComponentForm/kit/createTriggers.test.js
Labels: easy review, need review

#1952 feat(component/resourcepicker) : add status flags
  packages/components/src/ResourcePicker/Resource/Resource.component.js
  packages/components/src/ResourcePicker/Resource/Resource.scss
  packages/components/src/ResourcePicker/Resource/Resource.snap.test.js
  packages/components/src/ResourcePicker/Resource/__snapshots__/Resource.snap.test.js.snap
  packages/components/stories/ResourcePicker.js
Labels: enhancement, frontend, need review

#1953 fix(frontend): TMC-15611 allow spaces (%20) on GIT url validation
  packages/forms/src/UIForm/customFormats.js
  packages/forms/src/UIForm/customFormats.test.js
Labels: easy review, need review

#1954 doc(cmf/bootstrap): add registry info
  packages/cmf/src/bootstrap.md
Labels: easy review, need review

#1944 feat(router): add support for registerFunctions
  packages/router/README.md
  packages/router/src/index.js
  packages/router/src/index.test.js
  packages/router/src/route.js
Labels: easy review, need review

#1942 chore(TUI-310): drop react-15
  .travis.yml
Labels: easy review, need review

#1948 fix(containers): SidePanel and router
  packages/containers/.storybook/config.js
  packages/containers/sandbox/package.json
  packages/containers/src/index.js
  packages/router/package.json
  packages/router/src/index.js
Labels: need review

#1956 doc(cmf/bootstrap): fix preReducers entry types
  packages/cmf/src/bootstrap.md
Labels: easy review, need review

#1955 fix: all target blank and window.open
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/containers/src/HeaderBar/HeaderBar.sagas.js
  packages/containers/src/HeaderBar/HeaderBar.sagas.test.js
Labels: easy review, need review

#1957 feat(router): support multiple config
  packages/cmf/src/cmfModule.merge.js
  packages/router/README.md
  packages/router/package.json
  packages/router/src/index.js
  packages/router/src/index.test.js
Labels: need review

#1962 chore(container): fix dependency
  packages/containers/package.json
  yarn.lock
Labels: need review

#1963 fix(containers): add withComponentRegistry to RichLayout
  packages/containers/src/index.js
Labels: need review

#1965 fix(containers): change context api on deleteResource
  packages/cmf/src/action.js
Labels: bug, easy review, need review

#1967 chore: i18next-scanner
  package.json
  packages/components/i18next-scanner.config.js
  packages/components/package.json
  packages/containers/i18next-scanner.config.js
  packages/containers/package.json
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/forms/i18next-scanner.config.js
  packages/forms/package.json
  talend-i18n.json
  yarn.lock
Labels: easy review, frontend, need review

#1950 feat(component/resourcepicker): add toolbar
  output/components.eslint.txt
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
  packages/components/src/Actions/ActionIconToggle/__snapshots__/ActionIconToggle.component.test.js.snap
  packages/components/src/ResourcePicker/Resource/Resource.component.js
  packages/components/src/ResourcePicker/Resource/Resource.scss
  packages/components/src/ResourcePicker/Resource/__snapshots__/Resource.snap.test.js.snap
  packages/components/src/ResourcePicker/ResourcePicker.component.js
  packages/components/src/ResourcePicker/ResourcePicker.scss
  packages/components/src/ResourcePicker/ResourcePicker.snap.test.js
  packages/components/src/ResourcePicker/Toolbar/NameFilter/NameFilter.component.js
  packages/components/src/ResourcePicker/Toolbar/NameFilter/NameFilter.scss
  packages/components/src/ResourcePicker/Toolbar/NameFilter/NameFilter.snap.test.js
  packages/components/src/ResourcePicker/Toolbar/NameFilter/NameFilter.test.js
  packages/components/src/ResourcePicker/Toolbar/NameFilter/__snapshots__/NameFilter.snap.test.js.snap
  packages/components/src/ResourcePicker/Toolbar/NameFilter/index.js
  packages/components/src/ResourcePicker/Toolbar/SortOptions/OrderChooser/OrderChooser.component.js
  packages/components/src/ResourcePicker/Toolbar/SortOptions/OrderChooser/OrderChooser.scss
  packages/components/src/ResourcePicker/Toolbar/SortOptions/OrderChooser/OrderChooser.snap.test.js
  packages/components/src/ResourcePicker/Toolbar/SortOptions/OrderChooser/OrderChooser.test.js
  packages/components/src/ResourcePicker/Toolbar/SortOptions/OrderChooser/__snapshots__/OrderChooser.snap.test.js.snap
  packages/components/src/ResourcePicker/Toolbar/SortOptions/OrderChooser/index.js
  packages/components/src/ResourcePicker/Toolbar/SortOptions/SortOptions.component.js
  packages/components/src/ResourcePicker/Toolbar/SortOptions/SortOptions.scss
  packages/components/src/ResourcePicker/Toolbar/SortOptions/SortOptions.snap.test.js
  packages/components/src/ResourcePicker/Toolbar/SortOptions/SortOptions.test.js
  packages/components/src/ResourcePicker/Toolbar/SortOptions/__snapshots__/SortOptions.snap.test.js.snap
  packages/components/src/ResourcePicker/Toolbar/SortOptions/index.js
  packages/components/src/ResourcePicker/Toolbar/StateFilter/StateFilter.component.js
  packages/components/src/ResourcePicker/Toolbar/StateFilter/StateFilter.scss
  packages/components/src/ResourcePicker/Toolbar/StateFilter/StateFilter.snap.test.js
  packages/components/src/ResourcePicker/Toolbar/StateFilter/StateFilter.test.js
  packages/components/src/ResourcePicker/Toolbar/StateFilter/__snapshots__/StateFilter.snap.test.js.snap
  packages/components/src/ResourcePicker/Toolbar/StateFilter/index.js
  packages/components/src/ResourcePicker/Toolbar/Toolbar.component.js
  packages/components/src/ResourcePicker/Toolbar/Toolbar.scss
  packages/components/src/ResourcePicker/Toolbar/Toolbar.snap.test.js
  packages/components/src/ResourcePicker/Toolbar/__snapshots__/Toolbar.snap.test.js.snap
  packages/components/src/ResourcePicker/Toolbar/index.js
  packages/components/src/ResourcePicker/__snapshots__/ResourcePicker.snap.test.js.snap
  packages/components/src/ResourcePicker/index.js
  packages/components/stories/ResourcePicker.js
Labels: enhancement, frontend, need review

#1969 fix(components/Drawer): close button color
  packages/components/src/Drawer/Drawer.scss
Labels: easy review, need review

#1949 chore(DatePicker): form mode
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.scss
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/README.md
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/components/stories/DatePicker.js
  packages/forms/src/UIForm/fields/Date/__snapshots__/Date.component.test.js.snap
Labels: need review

#1972 fix(components/Notifications): heading styles
  packages/components/src/Notification/Notification.scss
  packages/components/stories/Notification.js
Labels: easy review, need review

#1973 feat(scripts/i18n): accept token instead of password
  packages/scripts/internationalization/README.md
  packages/scripts/internationalization/common/xtm.js
  packages/scripts/internationalization/scripts/download.js
  packages/scripts/internationalization/scripts/upload.js
Labels: easy review, need review

#1974 chore(forms/NestedListView): Fix warnings
  packages/forms/src/UIForm/fields/NestedListView/NestedListView.component.js
  packages/forms/src/UIForm/fields/NestedListView/__snapshots__/NestedListView.test.js.snap
Labels: easy review, need review

#1935 fix(datagrid): header with type string
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/stories/sample.json
Labels: bug, need review

#1958 feat(forms): add resource picker form
  packages/components/src/ResourcePicker/Toolbar/StateFilter/StateFilter.component.js
  packages/components/src/ResourcePicker/Toolbar/StateFilter/StateFilter.scss
  packages/components/src/ResourcePicker/Toolbar/StateFilter/__snapshots__/StateFilter.snap.test.js.snap
  packages/forms/src/Form.test.js
  packages/forms/src/UIForm/fields/ResourcePicker/README.md
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.test.js
  packages/forms/src/UIForm/fields/ResourcePicker/__snapshots__/ResourcePicker.component.test.js.snap
  packages/forms/src/UIForm/fields/ResourcePicker/index.js
  packages/forms/src/UIForm/fields/ResourcePicker/screenshot.png
  packages/forms/src/UIForm/utils/widgets.js
  packages/forms/stories-core/json/fields/core-resource-picker.json
  packages/forms/stories-core/jsonStories.js
Labels: enhancement, frontend, need review

#1976 feat(icons): check-circle
  packages/icons/src/svg/check-circle.svg
Labels: easy review, need review

#1960 chore(component/ActionBar): Prepare component for Count extraction
  packages/components/src/ActionBar/ActionBar.component.js
  packages/components/src/ActionBar/ActionBar.snapshot.test.js
  packages/components/src/ActionBar/__snapshots__/ActionBar.snapshot.test.js.snap
  packages/components/src/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/Inject/Inject.component.js
  packages/components/src/Inject/Inject.test.js
  packages/components/src/List/Toolbar/Toolbar.component.js
  packages/components/src/List/Toolbar/Toolbar.snapshot.test.js
Labels: enhancement, frontend, need review

#1981 chore(i18n): talend-i18n scripts configuration
  .gitignore
  talend-i18n.json
Labels: easy review, need review

#1978 feat(icons): component
  packages/icons/src/svg/component-negative.svg
  packages/icons/src/svg/component-positive.svg
Labels: easy review, need review

#1979 feat(Containers): cmf form errors management
  packages/containers/src/Form/Form.container.js
  packages/containers/src/Form/Form.test.js
  packages/containers/src/Form/__snapshots__/Form.test.js.snap
Labels: need review

#1986 fix(icons) use baseSelector option to generate talend webicon css file properly
  packages/icons/src/talendicons.font.js
  packages/icons/src/talendicons.template.css
Labels: easy review, need review

#1980 chore: Remove i18n scripts
  packages/scripts/README.md
  packages/scripts/index.js
  packages/scripts/internationalization/README.md
  packages/scripts/internationalization/common/error.js
  packages/scripts/internationalization/common/files.js
  packages/scripts/internationalization/common/log.js
  packages/scripts/internationalization/common/version.js
  packages/scripts/internationalization/common/xtm.js
  packages/scripts/internationalization/generators/mvn/folder.manager.js
  packages/scripts/internationalization/generators/mvn/pom.generator.js
  packages/scripts/internationalization/generators/npm/folder.manager.js
  packages/scripts/internationalization/generators/npm/index.generator.js
  packages/scripts/internationalization/generators/npm/package.generator.js
  packages/scripts/internationalization/generators/npm/readme.generator.js
  packages/scripts/internationalization/index.js
  packages/scripts/internationalization/process.png
  packages/scripts/internationalization/scripts/deploy.js
  packages/scripts/internationalization/scripts/download.js
  packages/scripts/internationalization/scripts/extract.js
  packages/scripts/internationalization/scripts/upload.js
  packages/scripts/package.json
Labels: easy review, need review

#1982 feat(form): add multiselect widget with virtualized list
  output/components.eslint.txt
  packages/components/.storybook/config.js
  packages/components/package.json
  packages/components/src/MultiSelect/Dropdown.container.js
  packages/components/src/MultiSelect/Dropdown.scss
  packages/components/src/MultiSelect/ItemOption.component.js
  packages/components/src/MultiSelect/ItemOption.scss
  packages/components/src/MultiSelect/ItemView.component.js
  packages/components/src/MultiSelect/MultiSelect.container.js
  packages/components/src/MultiSelect/MultiSelect.container.test.js
  packages/components/src/MultiSelect/MultiSelect.scss
  packages/components/src/MultiSelect/README.md
  packages/components/src/MultiSelect/__snapshots__/MultiSelect.container.test.js.snap
  packages/components/src/MultiSelect/constants.js
  packages/components/src/MultiSelect/index.js
  packages/components/src/OverlayTrigger/OverlayTrigger.component.js
  packages/components/stories/MultiSelect.js
  packages/components/stories/index.js
  packages/containers/sandbox/mockBackend/kit.js
  packages/containers/sandbox/mockBackend/mock/kit/titleMap.json
  packages/containers/src/ComponentForm/__snapshots__/ComponentForm.test.js.snap
  packages/containers/src/ComponentForm/fields/MultiSelect/MultiSelect.component.js
  packages/containers/src/ComponentForm/fields/MultiSelect/README.md
  packages/containers/src/ComponentForm/fields/MultiSelect/displayMode/TextMode.component.js
  packages/containers/src/ComponentForm/fields/MultiSelect/index.js
  packages/containers/src/ComponentForm/fields/MultiSelect/screenshot.gif
  packages/containers/src/ComponentForm/fields/index.js
  packages/icons/src/svg/check-circle.svg
  packages/icons/src/svg/component-negative.svg
  packages/icons/src/svg/component-positive.svg
  packages/icons/src/svg/datastore.svg
  packages/icons/src/svg/union.svg
  yarn.lock
Labels: need review

#1988 fix(DeleteResource): use Trans component
  packages/containers/examples/config/i18n.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap
Labels: easy review, frontend, need review

#1993 chore(Typeahead): adding typeahead prop and track it on result click
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.snapshot.test.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/components/stories/Typeahead.js
Labels: easy review, need review

#1991 feat(component/resourcepicker): add loading mode
  packages/components/src/ResourcePicker/ResourcePicker.component.js
  packages/components/src/ResourcePicker/ResourcePicker.snap.test.js
  packages/components/src/ResourcePicker/__snapshots__/ResourcePicker.snap.test.js.snap
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.test.js
Labels: easy review, enhancement, frontend, need review

#1997 fix(Dialog): Title cut off
  packages/components/src/Dialog/Dialog.scss
Labels: easy review, need review

#1992 feat(forms/resourcepicker): a11y props
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
  packages/forms/src/UIForm/fields/ResourcePicker/__snapshots__/ResourcePicker.component.test.js.snap
  packages/forms/stories-core/jsonStories.js
Labels: easy review, enhancement, frontend, need review

#1999 feat(theme): forms input ellipsis
  output/theme.sasslint.txt
  packages/theme/src/theme/_forms.scss
Labels: easy review, frontend, need review

#1998 fix(icons) generate webfont with [fontname].[ext] format
  packages/icons/src/talendicons.font.js
Labels: easy review, need review

#2001 feat(form/resourcepicker): manage single selection
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.test.js
  packages/forms/stories-core/json/fields/core-resource-picker.json
  packages/forms/stories-core/jsonStories.js
Labels: bug, easy review, frontend, need review

#1984 fix(components/AppLoader): reset style
  packages/components/src/AppLoader/AppLoader.md
  packages/components/src/AppLoader/constant.js
Labels: enhancement, need review
