Repository Talend/ui, pull requests merged in 2019-05, with the labels that each got.

#2169 chore(scripts): update karma dependency
  npm-audit/audit.json
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/karma/karma.conf.js
Labels: need review

#2151 feat(icons): dropper
  packages/icons/src/svg/dropper.svg
Labels: easy review, need review

#2152 feat(icons): couchbase
  packages/icons/src/svg/couchbase.svg
Labels: easy review, need review

#2172 chore(DatePicker): adding id to input
  npm-audit/audit.json
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap
Labels: easy review, need review

#2158 fix(packages/forms): fix uiform tester
  packages/forms/stories-core/playgroundStory.js
Labels: bug, easy review, need review

#2179 feat(icons): azure and azure-blob
  packages/icons/src/svg/azure-blob.svg
  packages/icons/src/svg/azure.svg
Labels: easy review, need review

#2170 fix(UIForm): props.data update in componentWillReceiveProps
  packages/containers/src/Form/Form.container.js
  packages/containers/src/Form/Form.test.js
Labels: need review

#2162 feat(List Toolbar): Merge 2 toolbars into one line
  output/components.sasslint.txt
  packages/components/src/List/List.component.js
  packages/components/src/List/List.md
  packages/components/src/List/Toolbar/DisplayModeToggle/DisplayModeToggle.component.js
  packages/components/src/List/Toolbar/DisplayModeToggle/DisplayModeToggle.scss
  packages/components/src/List/Toolbar/DisplayModeToggle/DisplayModeToggle.test.js
  packages/components/src/List/Toolbar/DisplayModeToggle/__snapshots__/DisplayModeToggle.test.js.snap
  packages/components/src/List/Toolbar/DisplayModeToggle/index.js
  packages/components/src/List/Toolbar/Pagination/Pagination.component.js
  packages/components/src/List/Toolbar/SelectAll/SelectAll.scss
  packages/components/src/List/Toolbar/SelectDisplayMode/SelectDisplayMode.component.js
  packages/components/src/List/Toolbar/SelectDisplayMode/SelectDisplayMode.scss
  packages/components/src/List/Toolbar/SelectDisplayMode/SelectDisplayMode.test.js
  packages/components/src/List/Toolbar/SelectDisplayMode/__snapshots__/SelectDisplayMode.test.js.snap
  packages/components/src/List/Toolbar/SelectDisplayMode/index.js
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.test.js
  packages/components/src/List/Toolbar/SelectSortBy/__snapshots__/SelectSortBy.test.js.snap
  packages/components/src/List/Toolbar/Toolbar.component.js
  packages/components/src/List/Toolbar/Toolbar.scss
  packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/stories/List.js
Labels: need review

#2181 fix(TPSVC-9400): remove separator for empty elements
  packages/containers/src/HeaderBar/HeaderBar.connect.js
Labels: easy review, need review

#2093 feat(Notification): Give directly access to simple actions
  output/containers.eslint.txt
  packages/containers/src/Notification/Notification.actions.js
  packages/containers/src/Notification/Notification.connect.js
  packages/containers/src/Notification/Notification.constants.js
  packages/containers/src/Notification/Notification.sagas.js
  packages/containers/src/Notification/Notification.sagas.test.js
  packages/containers/src/Notification/README.md
  packages/containers/src/Notification/index.js
Labels: easy review, enhancement, frontend, need review

#2173 chore: remove dotfile generator
  packages/generator/README.md
  packages/generator/generators/app/index.js
  packages/generator/generators/dotfiles/index.js
  packages/generator/package.json
  packages/generator/test/app.js
  packages/generator/test/dotfiles.js
  yarn.lock
Labels: need review

#2175 chore(TUI-250): remove storyshots
  packages/components/package.json
  packages/components/src/ActionList/ActionList.snapshot.test.js
  packages/components/src/ActionList/__snapshots__/ActionList.snapshot.test.js.snap
  packages/components/src/ActionList/__snapshots__/config.js
  packages/components/src/HeaderBar/HeaderBar.snapshot.test.js
  packages/components/src/HeaderBar/HeaderBar.test.js
  packages/components/src/HeaderBar/__snapshots__/HeaderBar.snapshot.test.js.snap
  packages/components/src/HeaderBar/__snapshots__/config.js
  packages/components/src/SidePanel/SidePanel.snapshot.test.js
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/src/SidePanel/__snapshots__/config.js
  packages/components/src/Skeleton/Skeleton.test.js
  packages/components/src/Skeleton/__snapshots__/Skeleton.test.js.snap
  packages/components/src/Skeleton/__snapshots__/config.js
  yarn.lock
Labels: need review

#2184 fix(TMC-17222,TMC-17310): error in form when some widgets are empty
  packages/forms/src/UIForm/UIForm.component.js
Labels: easy review, need review

#2165 feat(cmf): add http interceptors
  packages/cmf/__tests__/httpInterceptors.tests.js
  packages/cmf/__tests__/middlewares/http.test.js
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/bootstrap.js
  packages/cmf/src/bootstrap.md
  packages/cmf/src/cmfModule.merge.js
  packages/cmf/src/httpInterceptors.js
  packages/cmf/src/httpInterceptors.md
  packages/cmf/src/middlewares/http/middleware.js
  packages/cmf/src/sagas/http.js
Labels: need review

#2176 feat(containers):change dirty state component form
  packages/containers/sandbox/src/app/SandboxBody.js
  packages/containers/sandbox/src/app/index.js
  packages/containers/sandbox/src/assets/settings.json
  packages/containers/src/ComponentForm/ComponentForm.actions.js
  packages/containers/src/ComponentForm/ComponentForm.actions.test.js
  packages/containers/src/ComponentForm/ComponentForm.md
  packages/containers/src/ComponentForm/ComponentForm.saga.test.js
  packages/containers/src/ComponentForm/ComponentForm.sagas.js
  packages/containers/src/ComponentForm/ComponentForm.selectors.js
  packages/containers/src/ComponentForm/ComponentForm.selectors.test.js
Labels: need review

#2191 Fix(scripts): testRegex in jest.config.js for Windows users
  packages/scripts/webapp/preset/config/jest.config.js
Labels: easy review, need review

#2193 chore(Forms): fixing validation when using array type with checkboxes
  packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.component.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.test.js
  packages/forms/src/UIForm/fields/CheckBox/__snapshots__/CheckBoxes.test.js.snap
Labels: easy review, need review

#2190 fix(TMC-17307): remove static height for sidepanel list item
  output/components.sasslint.txt
  packages/components/src/SidePanel/SidePanel.scss
  packages/components/src/VirtualizedList/RowCollapsiblePanel/RowCollapsiblePanel.scss
Labels: easy review, need review

#2188 feat(components/ListComposition): Text filter feature
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/ListManager.component.test.js
  packages/components/src/List/ListComposition/Manager/filter.js
  packages/components/src/List/ListComposition/Manager/filter.test.js
  packages/components/src/List/ListComposition/TextFilter/TextFilter.component.js
  packages/components/src/List/ListComposition/TextFilter/TextFilter.component.md
  packages/components/src/List/ListComposition/TextFilter/TextFilter.component.test.js
  packages/components/src/List/ListComposition/TextFilter/__snapshots__/TextFilter.component.test.js.snap
  packages/components/src/List/ListComposition/TextFilter/index.js
  packages/components/src/List/ListComposition/index.js
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2186 feat(components/ListComposition): Sort feature
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/ListManager.component.test.js
  packages/components/src/List/ListComposition/Manager/sort.js
  packages/components/src/List/ListComposition/Manager/sort.test.js
  packages/components/src/List/ListComposition/SortBy/SortBy.component.js
  packages/components/src/List/ListComposition/SortBy/SortBy.component.test.js
  packages/components/src/List/ListComposition/SortBy/SortBy.md
  packages/components/src/List/ListComposition/SortBy/__snapshots__/SortBy.component.test.js.snap
  packages/components/src/List/ListComposition/SortBy/index.js
  packages/components/src/List/ListComposition/index.js
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2189 feat(TMC-15753/containers/List): add persistentItemsActions support
  packages/containers/examples/ExampleList.js
  packages/containers/src/List/List.container.js
  packages/containers/src/List/__snapshots__/List.test.js.snap
Labels: need review

#2059 chore(Scripts): upgrade eslint
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/.eslintrc
Labels: frontend, need review

#2192 feat: intercom integration
  output/components.eslint.txt
  packages/components/src/ActionIntercom/Intercom.component.js
  packages/components/src/ActionIntercom/Intercom.component.test.js
  packages/components/src/ActionIntercom/Intercom.scss
  packages/components/src/ActionIntercom/Intercom.service.js
  packages/components/src/ActionIntercom/Intercom.service.test.js
  packages/components/src/ActionIntercom/__snapshots__/Intercom.component.test.js.snap
  packages/components/src/ActionIntercom/index.js
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/HeaderBar/HeaderBar.test.js
  packages/components/stories/ActionIntercom.js
  packages/components/stories/HeaderBar.js
  packages/components/stories/index.js
Labels: frontend, need review

#2195 fix(cmf/httpInterceptors): merge wait for intercentors
  packages/cmf/__tests__/cmfModule.merge.test.js
  packages/cmf/src/cmfModule.merge.js
Labels: need review

#2196 fix(containers/Notification): add missing saga
  output/containers.eslint.txt
  packages/containers/src/Notification/Notification.sagas.js
  packages/containers/src/Notification/index.js
Labels: need review

#2180 feat(forms): add tooltip to widgets
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/Widget/Widget.component.test.js
  packages/forms/stories-core/json/fields/core-buttons.json
Labels: easy review, enhancement, frontend, need review

#2130 feat(forms): comparator field
  packages/forms/src/UIForm/fields/Comparator/Comparator.component.js
  packages/forms/src/UIForm/fields/Comparator/Comparator.component.test.js
  packages/forms/src/UIForm/fields/Comparator/Comparator.scss
  packages/forms/src/UIForm/fields/Comparator/README.md
  packages/forms/src/UIForm/fields/Comparator/__snapshots__/Comparator.component.test.js.snap
  packages/forms/src/UIForm/fields/Comparator/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/Comparator/displayMode/TextMode.test.js
  packages/forms/src/UIForm/fields/Comparator/displayMode/__snapshots__/TextMode.test.js.snap
  packages/forms/src/UIForm/fields/Comparator/index.js
  packages/forms/src/UIForm/utils/widgets.js
  packages/forms/stories-core/json/fields/core-comparator-input.json
  packages/theme/src/theme/_forms.guideline.scss
  packages/theme/src/theme/_forms.scss
Labels: enhancement, frontend, need review

#2197 feat(components/actionbutton): manage hover
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/ActionButton.test.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/components/stories/Action.js
Labels: easy review, enhancement, frontend, need review

#2202 feat(forms): add hover handlers for the submit button
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
  packages/forms/stories-core/customHoverSubmitStory.js
  packages/forms/stories-core/index.js
Labels: easy review, enhancement, frontend, need review

#2201 feat(icons): line-charts
  packages/icons/src/svg/line-charts.svg
Labels: easy review, need review

#2205 fix(forms): call onSubmit with mergedSchema
  packages/forms/src/UIForm/UIForm.component.js
Labels: bug, easy review, enhancement, frontend, need review

#2210 fix(form): call onSubmit with mergedSchema
  packages/forms/src/UIForm/UIForm.container.js
Labels: bug, easy review, enhancement, frontend, need review

#2212 feat(ListComposition/DisplayMode): update design
  packages/components/src/List/ListComposition/DisplayMode/DisplayModeToggle.scss
  packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.js
  packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.test.js
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.scss
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2213 fix(File): update text input when the file input value is changed
  packages/forms/src/UIForm/fields/File/File.component.js
  packages/forms/src/UIForm/fields/File/File.component.test.js
Labels: need review

#2215 fix(Form/Array): Disable add/delete button when Array is disabled
  packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
Labels: easy review, need review

#2207 fix(DatePicker): picker doesn't close + can't open picker when focused
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap
Labels: need review

#2217 fix(toolbar): update composition list toolbar size
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.scss
Labels: easy review, need review

#2219 fix(components/List/SortBy): change "sort by" label color to $dove-gray
  packages/components/src/List/Toolbar/Toolbar.scss
Labels: easy review, need review

#2013 fix: remove warn from console
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
  packages/components/src/Actions/ActionIconToggle/__snapshots__/ActionIconToggle.component.test.js.snap
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/forms/src/FormSkeleton.js
  packages/forms/src/FormSkeleton.scss
Labels: need review

#2218 fix(forms): avoid Text component crash
  packages/forms/src/UIForm/fields/Text/Text.component.js
Labels: need review

#2146 feat(components): Add pendo placeholders
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
  packages/components/src/SubHeaderBar/SubHeaderBar.component.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
Labels: easy review, need review
