Repository Talend/ui, pull requests merged in 2019-03, with the labels that each got.

#2031 fix(frontend): translate date picker error messages
  packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.test.js
  packages/components/src/DateTimePickers/DateTime/Validation/Error.component.js
  packages/components/src/DateTimePickers/DateTime/Validation/Error.component.test.js
  packages/components/src/DateTimePickers/DateTime/Validation/__snapshots__/Error.component.test.js.snap
  packages/components/src/DateTimePickers/DateTime/date-extraction.js
  packages/components/src/DateTimePickers/DateTime/date-extraction.test.js
  packages/components/src/DateTimePickers/DateTime/error-messages.js
  packages/components/src/DateTimePickers/DateTime/error-messages.test.js
Labels: need review

#2072 fix(datagrid): miss ellipsis on the large header
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.scss
  packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/DefaultHeaderRenderer.test.js.snap
Labels: bug, need review

#2074 fix(List): toolbar menu text capitalisation
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss
  packages/components/src/List/Toolbar/Toolbar.scss
Labels: easy review, frontend, need review

#2073 fix(datagrid): js error when onFocusColumns is not defined
  output/components.sasslint.txt
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
Labels: bug, easy review, need review

#2077 feat(Scripts): support angularJS apps
  packages/scripts/index.js
  packages/scripts/package.json
  packages/scripts/webapp/README.md
  packages/scripts/webapp/doc/presets.md
  packages/scripts/webapp/preset/README.md
  packages/scripts/webapp/preset/config/.eslintrc
  packages/scripts/webapp/preset/config/karma/karma.conf.js
  packages/scripts/webapp/preset/config/karma/webpack.config.js
  packages/scripts/webapp/preset/config/test/test-setup.js
  packages/scripts/webapp/preset/config/webpack.config.dev.js
  packages/scripts/webapp/preset/config/webpack.config.js
  packages/scripts/webapp/preset/config/webpack.config.prod.js
  packages/scripts/webapp/preset/details.md
  packages/scripts/webapp/preset/preset-talend-karma.js
  packages/scripts/webapp/preset/preset-talend.js
  packages/scripts/webapp/scripts/start.js
  packages/scripts/webapp/scripts/test-ng.js
Labels: frontend, need review

#2078 fix(Scripts): remove window location mock
  npm-audit/audit.json
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/.eslintrc
  packages/scripts/webapp/preset/config/test/test-setup.js
Labels: need review

#2079 fix(Scripts): eslint remove List and Map from mandatory new
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/.eslintrc
Labels: easy review, need review

#1910 feat(scripts): add splitChunks in webpack default config
  packages/containers/sandbox/.gitignore
  packages/containers/sandbox/README.md
  packages/containers/sandbox/package.json
  packages/containers/sandbox/serve-dist.js
  packages/containers/sandbox/src/app/index.js
  packages/scripts/webapp/preset/config/webpack.config.js
  packages/scripts/webapp/preset/preset-talend-babel.js
Labels: need review

#2083 fix(TUI-362/ComponentForm): use error.description if present
  npm-audit/audit.json
  packages/containers/src/ComponentForm/kit/createTriggers.test.js
  packages/containers/src/ComponentForm/kit/defaultRegistry.js
  packages/containers/src/ComponentForm/kit/defaultRegistry.test.js
Labels: easy review, need review

#2084 feat(Scripts): eslint react hooks
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/.eslintrc
Labels: easy review, frontend, need review

#2069 fix(components/Datalist): select suggestion value from typed title
  npm-audit/audit.json
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
Labels: bug, easy review, need review

#2090 fix(UiForm): remove value from state if empty
  npm-audit/audit.json
  packages/forms/src/UIForm/utils/properties.js
  packages/forms/src/UIForm/utils/properties.test.js
Labels: need review

#2092 chore(i18n): extract datagrid i18n file
  package.json
  packages/datagrid/i18next-scanner.config.js
Labels: easy review, frontend, need review

#2094 chore(TUI-370/Scripts): remove unused karma-coverage - security issue
  packages/scripts/package.json
  yarn.lock
Labels: easy review, frontend, need review

#2098 feat(TUI-371/Surge): upgrade surge to remove a vulnerability
  npm-audit/audit.json
  package.json
  yarn.lock
Labels: easy review, frontend, need review

#2006 feat(icons): shield, shield-full, shield-full-check
  packages/icons/src/svg/shield-full-check.svg
  packages/icons/src/svg/shield-full.svg
  packages/icons/src/svg/shield.svg
Labels: easy review, need review

#2097 chore(components/Typeahead): Add ref container to items container renderer
  packages/components/src/Typeahead/Typeahead.component.renderers.js
Labels: need review

#2095 chore: remove unused jest-environment-jsdom dependency
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/forms/src/UIForm/fields/ResourcePicker/__snapshots__/ResourcePicker.component.test.js.snap
  packages/forms/src/widgets/DatalistWidget/__snapshots__/DatalistWidget.test.js.snap
  packages/forms/src/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/router/package.json
  yarn.lock
Labels: easy review, frontend, need review

#2101 fix(components/treeview): aligment issue with ie11
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.scss
Labels: bug, easy review, need review

#2099 fix(forms/MultiSelectTag): TUI-373 - Scrollbar can't be used with click
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.scss
  packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap
Labels: need review

#2088 fix(Scripts): avoid relative path in jest config
  packages/scripts/webapp/preset/config/jest.config.js
  packages/scripts/webapp/utils/preset.js
Labels: frontend, need review

#2081 fix(cmf): remove automatic event from onEvent [BC]
  npm-audit/audit.json
  packages/cmf/src/onEvent.js
Labels: breaking change

#2100 feat(List): composition - display mode
  packages/components/.storybook/preview-head.html
  packages/components/src/List/ListComposition/DisplayMode/DisplayMode.component.js
  packages/components/src/List/ListComposition/DisplayMode/DisplayMode.component.test.js
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/DisplayMode.component.test.js.snap
  packages/components/src/List/ListComposition/DisplayMode/index.js
  packages/components/src/List/ListComposition/Manager/Manager.component.js
  packages/components/src/List/ListComposition/Manager/Manager.component.test.js
  packages/components/src/List/ListComposition/Manager/__snapshots__/Manager.component.test.js.snap
  packages/components/src/List/ListComposition/Manager/index.js
  packages/components/src/List/ListComposition/README.md
  packages/components/src/List/ListComposition/Toolbar/Toolbar.component.js
  packages/components/src/List/ListComposition/Toolbar/Toolbar.component.test.js
  packages/components/src/List/ListComposition/Toolbar/Toolbar.scss
  packages/components/src/List/ListComposition/Toolbar/__snapshots__/Toolbar.component.test.js.snap
  packages/components/src/List/ListComposition/Toolbar/index.js
  packages/components/src/List/ListComposition/VList/VList.component.js
  packages/components/src/List/ListComposition/VList/VList.component.test.js
  packages/components/src/List/ListComposition/VList/index.js
  packages/components/src/List/ListComposition/context.js
  packages/components/src/List/ListComposition/context.test.js
  packages/components/src/List/ListComposition/index.js
  packages/components/src/OverlayTrigger/index.js
  packages/components/stories/List.js
  packages/components/stories/List/MyCustomRow.component.js
  packages/components/stories/ListComposition/ListComposition.js
  packages/components/stories/ListComposition/collection.js
  packages/components/stories/VirtualizedList.js
  packages/components/stories/index.js
Labels: frontend, need review

#2106 chore(ListComposition): rename list composition elements
  packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.js
  packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.test.js
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/components/src/List/ListComposition/DisplayMode/index.js
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/ListManager.component.test.js
  packages/components/src/List/ListComposition/Manager/__snapshots__/ListManager.component.test.js.snap
  packages/components/src/List/ListComposition/Manager/index.js
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.component.js
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.component.test.js
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.scss
  packages/components/src/List/ListComposition/Toolbar/__snapshots__/ListToolbar.component.test.js.snap
  packages/components/src/List/ListComposition/Toolbar/index.js
  packages/components/src/List/ListComposition/VList/VList.component.js
Labels: easy review, frontend, need review

#2107 feat(Scripts): add dynamic import support
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/.babelrc.json
Labels: easy review, frontend, need review

#2104 fix(forms/TDC-1885): focus the first error after submit
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
Labels: bug, need review

#2108 fix(Scripts): custom .babelrc file load
  packages/scripts/webapp/preset/config/babel-resolver.js
Labels: easy review, frontend, need review

#2085 feat(components): Guided tour
  npm-audit/audit.json
  packages/components/package.json
  packages/components/src/GuidedTour/GuidedTour.component.js
  packages/components/src/GuidedTour/GuidedTour.scss
  packages/components/src/GuidedTour/GuidedTour.test.js
  packages/components/src/GuidedTour/README.md
  packages/components/src/GuidedTour/index.js
  packages/components/src/SidePanel/__snapshots__/SidePanel.snapshot.test.js.snap
  packages/components/src/index.js
  packages/components/stories/GuidedTour.js
  packages/components/stories/SidePanel.js
  packages/components/stories/config/i18n.js
  packages/components/stories/index.js
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleGuidedTour.js
  packages/containers/examples/index.js
  packages/containers/src/GuidedTour/GuidedTour.connect.js
  packages/containers/src/GuidedTour/GuidedTour.constants.js
  packages/containers/src/GuidedTour/GuidedTour.container.js
  packages/containers/src/GuidedTour/GuidedTour.sagas.js
  packages/containers/src/GuidedTour/GuidedTour.sagas.test.js
  packages/containers/src/GuidedTour/GuidedTour.test.js
  packages/containers/src/GuidedTour/README.md
  packages/containers/src/GuidedTour/__snapshots__/GuidedTour.test.js.snap
  packages/containers/src/GuidedTour/index.js
  packages/containers/src/containers.js
  yarn.lock
Labels: enhancement, need review

#2113 fix(Scripts): allow start in non git repo
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: easy review, frontend, need review

#2117 fix(UIForms): conditional rendering demo
  npm-audit/audit.json
  packages/forms/stories-core/json/concepts/core-conditional-render.json
Labels: easy review, frontend, need review

#2115 fix(generator): react-cmf app
  packages/generator/generators/react-cmf/index.js
  packages/generator/generators/react-cmf/templates/.eslintrc
  packages/generator/generators/react-cmf/templates/cmf.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/generator/generators/react-cmf/templates/src/app/index.js
  packages/generator/generators/react-cmf/templates/src/settings/router.json
  packages/generator/generators/react-cmf/templates/talend-scripts.json
  packages/generator/generators/react-cmf/templates/test-setup.js
Labels: frontend, need review

#2118 feat(icons): Mongo DB
  packages/icons/src/svg/mongodb.svg
Labels: easy review, need review

#2120 feat(icons): Azure Event Hubs
  packages/icons/src/svg/azure-event-hubs.svg
Labels: easy review, need review

#2114 feat(forms): Move delete button from arrayItem to closeable widgets
  output/forms.eslint.txt
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.test.js
  packages/components/src/Actions/ActionIconToggle/__snapshots__/ActionIconToggle.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/Array.component.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.scss
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/ArrayItem.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.scss
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap
  packages/icons/src/svg/azure-event-hubs.svg
  packages/icons/src/svg/mongodb.svg
  packages/icons/src/svg/shield-full-check.svg
  packages/icons/src/svg/shield-full.svg
  packages/icons/src/svg/shield.svg
Labels: need review

#2121 fix(datagrid/TDC-1534): handle bytes value
  packages/datagrid/src/components/DefaultCellRenderer/DefaultRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultValueRenderer.test.js.snap
  packages/datagrid/stories/sample.json
Labels: bug, need review
