Repository Talend/ui, pull requests merged in 2019-02, with the labels that each got.

#2007 fix(datagrid): enable text selection in the grid
  packages/datagrid/src/components/DataGrid/DataGrid.scss
Labels: bug, need review

#2000 feat(icons): calendar-move
  packages/icons/src/svg/calendar-move.svg
Labels: easy review, need review

#2010 fix(i18n): small i18n adjustment
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/forms/src/widgets/EnumerationWidget/EnumerationWidget.js
Labels: easy review

#1975 chore(DatePicker): managing multi error
  packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/DateTimePicker/DateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/DateTimeValidation.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/DateTimeValidation.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.scss
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePickerContext.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/DateTimeValidation.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/constants.js
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.js
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.test.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.scss
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.test.js
  packages/components/src/DateTimePickers/pickers/TimePicker/__snapshots__/TimePicker.test.js.snap
  packages/components/stories/DatePicker.js
  packages/components/stories/index.js
Labels: need review

#2005 fix(list): icon tooltip in CellTitle
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitle.test.js.snap
Labels: easy review, need review

#2012 fix(List): Apply Title case to sort by in the list
  packages/components/src/List/Toolbar/Toolbar.scss
  packages/components/stories/List.js
Labels: easy review, need review

#2004 fix(TUI-332): make ComponentForm support error onTrigger
  packages/containers/sandbox/mockBackend/kit.js
  packages/containers/sandbox/mockBackend/mock/kit/titleMap.json
  packages/containers/sandbox/src/app/index.html
  packages/containers/sandbox/src/assets/settings.json
  packages/containers/src/ComponentForm/kit/createTriggers.js
  packages/containers/src/ComponentForm/kit/createTriggers.test.js
  packages/containers/src/ComponentForm/kit/defaultRegistry.js
  packages/forms/src/UIForm/fields/Button/SingleButton.component.js
Labels: need review

#1990 feat(TMC-15843): disabled item in datalist
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.scss
  packages/components/stories/Datalist.js
Labels: need review

#2015 fix(Notification): animation
  packages/components/src/Notification/Notification.scss
Labels: easy review, frontend, need review

#2018 fix(frontend): missing ID in UIForm default array template Action
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/DefaultArrayTemplate.component.test.js.snap
Labels: easy review

#2003 chore: update jest 24
  npm-audit/audit.json
  npm-audit/package-lock.json
  npm-audit/package.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/app/templates/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/html-webpack-plugin/package.json
  packages/router/package.json
  packages/router/src/route.test.js
  packages/router/test-setup.js
  packages/sagas/package.json
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/jest.config.js
  packages/storybook-cmf/package.json
  packages/storybook-cmf/src/CMFStory/__snapshots__/CMFStory.test.js.snap
  packages/theme/package.json
  versions/dependencies.js
  yarn.lock
Labels: need review

#2017 chore(DatePicker): call on change when empty values and fixing case w…
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/README.md
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.js
  packages/components/src/DateTimePickers/InputDateTimePicker/date-extraction.test.js
  packages/components/stories/DatePicker.js
  packages/forms/src/UIForm/fields/Date/__snapshots__/Date.component.test.js.snap
Labels: easy review, need review

#2025 chore: upgrade React to 16.8.0
  npm-audit/package-lock.json
  npm-audit/package.json
  packages/cmf-cqrs/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/icons/package.json
  packages/router/package.json
  packages/sagas/package.json
  packages/scripts/package.json
  packages/storybook-cmf/package.json
  versions/dependencies.js
  yarn.lock
Labels: easy review, frontend, need review

#2024 feat(forms): be able to fill fields from the outside
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
  packages/forms/src/UIForm/fields/ResourcePicker/README.md
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.test.js
  packages/forms/src/UIForm/fields/ResourcePicker/__snapshots__/ResourcePicker.component.test.js.snap
  packages/forms/src/UIForm/fields/ResourcePicker/constants.js
  packages/forms/stories-core/json/fields/core-resource-picker.json
  packages/forms/stories-core/jsonStories.js
Labels: enhancement, frontend, need review

#2022 feat(datagrid): option to hide the subtile on the header
  packages/datagrid/README.md
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.test.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.scss
  packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/DefaultHeaderRenderer.test.js.snap
  packages/datagrid/stories/datagrid.component.js
Labels: enhancement, need review

#2008 feat(forms): add toggle widget in text mode
  packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap
  packages/components/src/Table/Filters/__snapshots__/FiltersBar.test.js.snap
  packages/components/src/Table/TitleBar/__snapshots__/TitleBar.test.js.snap
  packages/components/src/Toggle/Toggle.component.js
  packages/components/src/Toggle/Toggle.scss
  packages/components/src/Toggle/__snapshots__/Toggle.snapshot.test.js.snap
  packages/forms/src/UIForm/fields/Toggle/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/Toggle/displayMode/TextMode.test.js
  packages/forms/src/UIForm/fields/Toggle/displayMode/__snapshots__/TextMode.test.js.snap
  packages/forms/src/UIForm/fields/Toggle/index.js
  packages/forms/src/UIForm/utils/widgets.js
Labels: need review

#2030 fix(DatePicker): scooter when hovering month year button
  packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.scss
Labels: easy review, need review

#2029 fix(forms): handle restricted option on the widget Datalist
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/forms/stories-core/json/fields/core-datalist.json
Labels: bug, easy review, need review

#2032 feat(icons): sort, sort-az, sort-za, sort-asc, sort-desc, sort-19, sort-91
  npm-audit/audit.json
  packages/icons/src/svg/sort-19.svg
  packages/icons/src/svg/sort-91.svg
  packages/icons/src/svg/sort-asc.svg
  packages/icons/src/svg/sort-az.svg
  packages/icons/src/svg/sort-desc.svg
  packages/icons/src/svg/sort-za.svg
  packages/icons/src/svg/sort.svg
Labels: easy review, need review

#2016 fix(TUI-335/Tabs): hide tab panes legends
  npm-audit/audit.json
  packages/forms/src/UIForm/fieldsets/Fieldset/Fieldset.component.js
  packages/forms/src/UIForm/fieldsets/Fieldset/Fieldset.component.test.js
  packages/forms/src/UIForm/fieldsets/Fieldset/__snapshots__/Fieldset.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Tabs/Tabs.component.js
  packages/forms/src/UIForm/fieldsets/Tabs/__snapshots__/Tabs.component.test.js.snap
Labels: easy review, frontend, need review

#2036 fix(components/Headerbar): dropdowns with drawer
  output/components.sasslint.txt
  packages/components/src/Drawer/Drawer.scss
  packages/components/src/Layout/Layout.scss
  packages/theme/src/theme/_guidelines.scss
Labels: bug, easy review, need review

#2035 feat(cmf): provide more precise options about saga onHttpError
  npm-audit/audit.json
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
  packages/cmf/src/sagas/index.md
Labels: need review

#2021 feat(forms/TUI-336): add updating feedback
  babel.config.js
  packages/containers/sandbox/mockBackend/kit.js
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.md
  packages/forms/__mocks__/data.js
  packages/forms/src/UIForm/README.md
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/Widget/Widget.component.test.js
  packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap
  packages/forms/src/UIForm/fields/Button/SingleButton.component.js
  packages/forms/src/UIForm/fields/Button/SingleButton.component.test.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.component.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/__snapshots__/CheckBox.test.js.snap
  packages/forms/src/UIForm/fields/CheckBox/__snapshots__/CheckBoxes.test.js.snap
  packages/forms/src/UIForm/fields/CheckBox/__snapshots__/SimpleCheckBox.test.js.snap
  packages/forms/src/UIForm/fields/Code/Code.component.js
  packages/forms/src/UIForm/fields/Code/Code.component.test.js
  packages/forms/src/UIForm/fields/Code/__snapshots__/Code.component.test.js.snap
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/forms/src/UIForm/fields/Date/Date.component.js
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.js
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.test.js
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.scss
  packages/forms/src/UIForm/fields/FieldTemplate/__snapshots__/FieldTemplate.component.test.js.snap
  packages/forms/src/UIForm/fields/File/File.component.js
  packages/forms/src/UIForm/fields/File/__snapshots__/File.component.test.js.snap
  packages/forms/src/UIForm/fields/KeyValue/KeyValue.component.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/NestedListView/NestedListView.component.js
  packages/forms/src/UIForm/fields/Radios/Radios.component.js
  packages/forms/src/UIForm/fields/Radios/__snapshots__/Radios.component.test.js.snap
  packages/forms/src/UIForm/fields/Select/Select.component.js
  packages/forms/src/UIForm/fields/Select/__snapshots__/Select.component.test.js.snap
  packages/forms/src/UIForm/fields/Text/Text.component.js
  packages/forms/src/UIForm/fields/Text/__snapshots__/Text.component.test.js.snap
  packages/forms/src/UIForm/fields/TextArea/TextArea.component.js
  packages/forms/src/UIForm/fields/TextArea/__snapshots__/TextArea.component.test.js.snap
  packages/forms/src/UIForm/fields/Toggle/Toggle.component.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/stories-core/customUpdating.js
  packages/forms/stories-core/index.js
  packages/forms/stories-core/json/concepts/aaa.json
  packages/theme/src/theme/_forms.scss
Labels: need review

#2028 chore(DatePicker): refactor to make its layout flexible
  packages/components/src/DateTimePickers/DateTime/Context.js
  packages/components/src/DateTimePickers/DateTime/Input/Input.component.js
  packages/components/src/DateTimePickers/DateTime/Input/Input.component.test.js
  packages/components/src/DateTimePickers/DateTime/Input/__snapshots__/Input.component.test.js.snap
  packages/components/src/DateTimePickers/DateTime/Input/index.js
  packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js
  packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.test.js
  packages/components/src/DateTimePickers/DateTime/Manager/__snapshots__/Manager.component.test.js.snap
  packages/components/src/DateTimePickers/DateTime/Manager/index.js
  packages/components/src/DateTimePickers/DateTime/Picker/Picker.component.js
  packages/components/src/DateTimePickers/DateTime/Picker/Picker.component.test.js
  packages/components/src/DateTimePickers/DateTime/Picker/index.js
  packages/components/src/DateTimePickers/DateTime/Validation/Error.component.js
  packages/components/src/DateTimePickers/DateTime/Validation/Error.component.test.js
  packages/components/src/DateTimePickers/DateTime/Validation/Validation.component.js
  packages/components/src/DateTimePickers/DateTime/Validation/Validation.component.test.js
  packages/components/src/DateTimePickers/DateTime/Validation/Validation.scss
  packages/components/src/DateTimePickers/DateTime/Validation/__snapshots__/Error.component.test.js.snap
  packages/components/src/DateTimePickers/DateTime/Validation/__snapshots__/Validation.component.test.js.snap
  packages/components/src/DateTimePickers/DateTime/Validation/index.js
  packages/components/src/DateTimePickers/DateTime/constants.js
  packages/components/src/DateTimePickers/DateTime/date-extraction.js
  packages/components/src/DateTimePickers/DateTime/date-extraction.test.js
  packages/components/src/DateTimePickers/DateTime/index.js
  packages/components/src/DateTimePickers/InputDateTimePicker/DateTimeValidation.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/DateTimeValidation.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.scss
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.snapshot.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/DateTimeValidation.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/index.js
  packages/components/src/DateTimePickers/pickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/pickers/DateTimePicker/DateTimePicker.scss
  packages/components/src/DateTimePickers/pickers/DateTimePicker/DateTimePicker.test.js
  packages/components/src/DateTimePickers/pickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/DateTimePicker/index.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.test.js
  packages/components/src/FocusManager/FocusManager.component.js
  packages/components/src/FocusManager/FocusManager.test.js
  packages/components/stories/DatePicker.js
Labels: frontend, need review

#2037 fix(cmf): http saga options documentation
  packages/cmf/src/sagas/index.md
Labels: easy review, need review

#2027 doc: UIForm
  packages/forms/src/UIForm/README.md
  packages/forms/src/UIForm/doc/conditional-rendering.md
  packages/forms/src/UIForm/doc/display-mode.md
  packages/forms/src/UIForm/doc/how-to-use.md
  packages/forms/src/UIForm/doc/principles.md
  packages/forms/src/UIForm/doc/triggers.md
  packages/forms/src/UIForm/doc/validation.md
  packages/forms/src/UIForm/doc/widgets.md
Labels: easy review, frontend, need review

#2034 feat(components/subheader): subtitle in loading mode
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js
  packages/components/src/SubHeaderBar/TitleSubHeader/__snapshots__/TitleSubHeader.test.js.snap
  packages/components/stories/SubHeaderBar.js
Labels: easy review, enhancement, frontend, need review

#2039 fix(container/uiform): onTrigger update properties only if function
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
Labels: need review

#2043 feat(Scripts): add build timestamp
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: easy review, frontend, need review

#2042 feat(Scripts): add images and svg loaders
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: easy review, frontend, need review

#2047 fix(CMFWebpackPlugin): cmfConfig set properly (typo cmfconfig)
  packages/cmf-webpack-plugin/src/index.js
Labels: easy review, frontend, need review

#2045 feat(Scripts): remove eslint from webpack build
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/webpack.config.dev.js
Labels: easy review, frontend, need review

#2041 fix(UIForm): trigger properties modifier calls onChange with proper info
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
Labels: easy review, frontend, need review

#2046 feat(Scripts): option to disable css modules
  packages/scripts/webapp/preset/README.md
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: easy review, frontend, need review

#2048 feat(Scripts): disable cmf webpack plugin by default
  packages/scripts/package.json
  packages/scripts/webapp/preset/README.md
  packages/scripts/webapp/preset/config/webpack.config.dev.js
  packages/scripts/webapp/preset/config/webpack.config.prod.js
Labels: easy review, frontend, need review

#2049 feat(Scripts): analyze option and spread user cli options
  npm-audit/audit.json
  packages/scripts/package.json
  packages/scripts/webapp/README.md
  packages/scripts/webapp/config/webpack.analyzer.js
  packages/scripts/webapp/config/webpack.config.js
  packages/scripts/webapp/scripts/build.js
  packages/scripts/webapp/scripts/start.js
Labels: frontend, need review

#2050 feat(Scripts): css load priority
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: easy review, frontend, need review

#2051 feat(Scripts): use clean-webpack-plugin to remove dist/
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/webpack.config.js
  packages/scripts/webapp/scripts/build.js
Labels: easy review, frontend, need review

#2053 feat(Scripts): complete jest config in talend preset
  packages/scripts/index.js
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/jest.config.js
  packages/scripts/webapp/preset/config/test/file-mock.js
  packages/scripts/webapp/preset/config/test/test-setup.js
Labels: frontend, need review

#2054 doc: talend scripts
  npm-audit/audit.json
  packages/scripts/webapp/README.md
  packages/scripts/webapp/doc/customisation.md
  packages/scripts/webapp/doc/getting-started.md
  packages/scripts/webapp/doc/presets.md
  packages/scripts/webapp/preset/README.md
  packages/scripts/webapp/preset/details.md
Labels: easy review, frontend, need review

#2057 fix(TUI-355/forms): improve displayMode=text
  packages/forms/src/UIForm/fields/Select/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/Select/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/Select/displayMode/__snapshots__/TextMode.component.test.js.snap
  packages/forms/src/UIForm/fields/Select/index.js
  packages/forms/src/UIForm/utils/widgets.js
  packages/forms/stories-core/customDisplayMode.js
  packages/forms/stories-core/index.js
Labels: easy review, need review

#2062 feat(Scripts): remove devServer proxy definition
  packages/scripts/webapp/preset/README.md
  packages/scripts/webapp/preset/config/webpack.config.dev.js
Labels: easy review, frontend, need review

#2058 fix(TUI-358): moderate CVE on bootstrap sass
  npm-audit/package-lock.json
  npm-audit/package.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/router/package.json
  packages/sagas/package.json
  packages/scripts/package.json
  packages/theme/package.json
  versions/dependencies.js
  versions/version.js
  yarn.lock
Labels: need review

#2044 docs: add error core concepts
  packages/forms/stories-core/customErrors.js
  packages/forms/stories-core/index.js
Labels: easy review, need review

#2064 fix(containers/Dialog): use getComponent
  npm-audit/package-lock.json
  packages/containers/src/index.js
Labels: easy review

#2066 fix(Scripts): output public path
  packages/scripts/package.json
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: easy review, frontend, need review

#2061 feat(Scripts): get versions and sha info, et as global var
  npm-audit/audit.json
  packages/scripts/webapp/preset/README.md
  packages/scripts/webapp/preset/config/webpack.config.js
Labels: frontend, need review

#2063 fix(TPSVC-7920/CollapsiblePanel): use onEntered/onExited
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/VirtualizedList/RowCollapsiblePanel/PureCollapsiblePanel.js
  packages/components/src/VirtualizedList/RowCollapsiblePanel/RowCollapsiblePanel.component.js
  packages/components/src/VirtualizedList/RowCollapsiblePanel/__snapshots__/RowCollapsiblePanel.test.js.snap
  packages/components/stories/VirtualizedList.js
Labels: need review

#2067 feat: scripts build lib
  packages/scripts/index.js
  packages/scripts/package.json
  packages/scripts/webapp/doc/presets.md
  packages/scripts/webapp/preset/config/babel.config.js
  packages/scripts/webapp/preset/config/webpack.config.js
  packages/scripts/webapp/preset/preset-talend-babel.js
  packages/scripts/webapp/preset/preset-talend.js
  packages/scripts/webapp/scripts/build-lib.js
  packages/scripts/webapp/scripts/test.js
Labels: frontend, need review

#2070 feat(CMF/TUI-337 and TUI-346): add saga devtool
  npm-audit/audit.json
  packages/cmf/src/bootstrap.js
  packages/cmf/src/store.js
Labels: easy review, need review

#2071 fix(theme): optimize dist size
  packages/theme/webpack.config.js
Labels: easy review, need review

#2068 fix(enum): icon tooltip in Item
  packages/components/src/Enumeration/Items/Item/Item.component.js
  packages/components/src/Enumeration/Items/Item/Item.scss
  packages/icons/src/svg/calendar-move.svg
  packages/icons/src/svg/sort-19.svg
  packages/icons/src/svg/sort-91.svg
  packages/icons/src/svg/sort-asc.svg
  packages/icons/src/svg/sort-az.svg
  packages/icons/src/svg/sort-desc.svg
  packages/icons/src/svg/sort-za.svg
  packages/icons/src/svg/sort.svg
Labels: need review
