Repository Talend/ui, pull requests merged in 2019-06, with the labels that each got.

#2221 feat(icons): re-cluster
  packages/icons/src/svg/re-cluster.svg
Labels: easy review, need review

#2220 fix(components/comparator): be able to pass a symbol
  packages/forms/src/UIForm/fields/Comparator/Comparator.component.js
  packages/forms/src/UIForm/fields/Comparator/Comparator.component.test.js
  packages/forms/src/UIForm/fields/Comparator/__snapshots__/Comparator.component.test.js.snap
  packages/forms/stories-core/json/fields/core-comparator-input.json
Labels: bug, easy review, enhancement, frontend, need review

#2140 fix(Typeahead): pendo gets no click event when the tag is placed on the <li> element
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
Labels: easy review, need review

#2216 chore(theme): aligning labels to guidelines
  output/theme.sasslint.txt
  packages/theme/src/theme/_labels.scss
  packages/theme/src/theme/_variables.scss
  packages/theme/src/theme/theme.scss
Labels: need review

#2160 feat(gridlayout) : adding grid layout and tile implementation
  output/components.eslint.txt
  output/theme.sasslint.txt
  packages/components/package.json
  packages/components/src/GridLayout/Grid.component.js
  packages/components/src/GridLayout/Grid.component.test.js
  packages/components/src/GridLayout/Grid.scss
  packages/components/src/GridLayout/Tile/Body/TileBody.component.js
  packages/components/src/GridLayout/Tile/Body/TileBody.component.test.js
  packages/components/src/GridLayout/Tile/Body/__snapshots__/TileBody.component.test.js.snap
  packages/components/src/GridLayout/Tile/Header/TileHeader.component.js
  packages/components/src/GridLayout/Tile/Header/TileHeader.component.test.js
  packages/components/src/GridLayout/Tile/Header/TileHeader.scss
  packages/components/src/GridLayout/Tile/Header/__snapshots__/TileHeader.component.test.js.snap
  packages/components/src/GridLayout/Tile/Skeleton/SkeletonTile.component.js
  packages/components/src/GridLayout/Tile/Skeleton/SkeletonTile.component.test.js
  packages/components/src/GridLayout/Tile/Skeleton/__snapshots__/SkeletonTile.component.test.js.snap
  packages/components/src/GridLayout/Tile/Tile.component.js
  packages/components/src/GridLayout/Tile/Tile.component.test.js
  packages/components/src/GridLayout/Tile/Tile.scss
  packages/components/src/GridLayout/Tile/__snapshots__/Tile.component.test.js.snap
  packages/components/src/GridLayout/Tile/context.js
  packages/components/src/GridLayout/Tile/index.js
  packages/components/src/GridLayout/index.js
  packages/components/src/index.js
  packages/components/stories/GridLayout.js
  packages/components/stories/index.js
  yarn.lock
Labels: need review

#2224 feat(components/VirtualizedList): Loading state for collapsible panel
  packages/components/src/VirtualizedList/RowCollapsiblePanel/RowCollapsiblePanel.component.js
  packages/components/src/VirtualizedList/RowCollapsiblePanel/RowCollapsiblePanel.scss
  packages/components/src/VirtualizedList/RowCollapsiblePanel/RowCollapsiblePanel.test.js
  packages/components/src/VirtualizedList/RowCollapsiblePanel/__snapshots__/RowCollapsiblePanel.test.js.snap
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2223 feat(components/VirtualizedList): RowLarge supporting unloaded data
  packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
  packages/components/src/VirtualizedList/RowLarge/RowLarge.test.js
  packages/components/stories/ListComposition/ListComposition.js
Labels: need review

#2231 fix(components): make email a required prop
  packages/components/src/ActionIntercom/Intercom.component.js
Labels: easy review, frontend, need review

#2233 fix(GridLayout): issue with shrink when content is bigger than tile and changing compact type
  output/components.eslint.txt
  packages/components/src/GridLayout/Grid.component.js
  packages/components/src/GridLayout/Tile/Tile.scss
Labels: easy review, need review

#2232 fix(TCCUI-35/datalist): prevent long value to overlap caret
  output/components.sasslint.txt
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.scss
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/icons/src/svg/azure-blob.svg
  packages/icons/src/svg/azure.svg
  packages/icons/src/svg/couchbase.svg
  packages/icons/src/svg/dropper.svg
  packages/icons/src/svg/line-charts.svg
  packages/icons/src/svg/re-cluster.svg
  packages/icons/src/svg/rest.svg
Labels: bug, need review

#2235 fix(theme): revert brand-info/warning color and set label-info/warning
  packages/theme/src/theme/_variables.scss
Labels: easy review, need review

#2226 feat(icons): azure-datalake
  packages/icons/src/svg/azure-datalake.svg
Labels: easy review, need review

#2238 fix(forms/TUI-382): support optional object
  packages/forms/src/UIForm/utils/validation.js
  packages/forms/src/UIForm/utils/validation.test.js
Labels: need review

#2240 fix(forms/Date): issue when emptying picker in other case than string
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
  npm-audit/router.json
  npm-audit/scripts.json
  output/components.eslint.txt
  packages/components/src/DateTimePickers/DateTime/error-messages.js
  packages/forms/src/UIForm/fields/Date/Date.component.js
  packages/forms/src/UIForm/fields/Date/Date.component.test.js
Labels: easy review, need review

#2239 fix(GridLayout): compactType as props and vertical for default value
  npm-audit/html-webpack-plugin.json
  npm-audit/router.json
  output/components.eslint.txt
  packages/components/src/GridLayout/Grid.component.js
Labels: easy review, need review

#2237 fix(TCCUI-34/datalist) remove caret on disabled and readonly mode
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/stories/Datalist.js
Labels: bug, easy review, need review

#2245 chore(ci): use openJDK8 instead of oracleJDK8
  .travis.yml
Labels: work in progress

#2244 feat(components/notification): pause/resume when mouse is entering/leaving
  packages/components/src/Notification/Notification.component.js
  packages/components/src/Notification/Notification.scss
  packages/components/src/Notification/Notification.test.js
Labels: easy review, enhancement, need review

#2243 fix(Components): Badge visual update 2
  packages/components/src/Badge/Badge.component.js
  packages/components/src/Badge/Badge.scss
  packages/components/stories/Badge.js
Labels: need review

#2246 fix(icons): bubbles
  packages/icons/src/svg/bubbles.svg
Labels: easy review, need review

#2241 feat(TPSVC-9500): add placeholder, custom error message and required props to EditableText component
  packages/components/src/EditableText/EditableText.test.js
  packages/components/src/EditableText/InlineForm.component.js
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/components/stories/EditableText.js
Labels: easy review, need review

#2250 fix(components/subheaderbar): title edition does not work
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
Labels: bug, easy review, frontend, need review

#2251 fix(icons): bubble fill
  packages/icons/src/svg/azure-datalake.svg
  packages/icons/src/svg/bubbles.svg
Labels: easy review, frontend, need review

#2252 fix(icons): empty-calendar fill
  packages/icons/src/svg/empty-calendar.svg
Labels: easy review, need review

#2236 feat(containers/Redirect): use AppLoader while redirect
  packages/containers/src/Redirect/Redirect.container.js
  packages/containers/src/Redirect/Redirect.test.js
  packages/containers/src/Redirect/__snapshots__/Redirect.test.js.snap
Labels: easy review, need review

#2256 fix(Intercom): remove cross from button to avoid double cross
  packages/components/src/ActionIntercom/Intercom.component.js
  packages/components/src/ActionIntercom/Intercom.component.test.js
Labels: easy review, need review

#2087 chore: storybook 5
  .storybook/webpack.config.js
  .travis.yml
  npm-audit/audit.json
  npm-audit/package.json
  package.json
  packages/components/.storybook/config.js
  packages/components/.storybook/webpack.config.js
  packages/components/e2e/component-objects/src/test/java/org/talend/component/StorybookTest.java
  packages/components/package.json
  packages/components/src/Slider/Slider.component.js
  packages/components/stories/Action.js
  packages/containers/.storybook/config.js
  packages/containers/.storybook/webpack.config.js
  packages/containers/package.json
  packages/datagrid/.storybook/config.js
  packages/datagrid/.storybook/webpack.config.js
  packages/datagrid/package.json
  packages/forms/.storybook/config.js
  packages/forms/package.json
  packages/storybook-cmf/package.json
  versions/dependencies.js
  yarn.lock
Labels: frontend, need review

#2260 chore: revert unwanted commit, removing the demo deployment
  .travis.yml
Labels: easy review, need review

#2259 feat(forms/TDC-876): pass formData in the result action
  packages/containers/src/ComponentForm/ComponentForm.actions.js
  packages/containers/src/ComponentForm/ComponentForm.saga.test.js
  packages/containers/src/ComponentForm/ComponentForm.sagas.js
Labels: easy review, enhancement, need review

#2262 fix(components): Prevent intercom from rerendering with same props
  packages/components/src/HeaderBar/HeaderBar.component.js
Labels: easy review, need review

#2258 feat(Containers/DeleteResource): pass action property to sucessful action
  output/containers.eslint.txt
  packages/containers/src/DeleteResource/sagas.js
  packages/containers/src/DeleteResource/sagas.test.js
Labels: bug, easy review

#2263 fix(component/MultiSelect): clear searchTerm on dropdown close
  packages/components/src/MultiSelect/MultiSelect.container.js
Labels: need review

#2242 fix(forms/TUI-393): array support readonly
  .travis.yml
  output/forms.eslint.txt
  packages/forms/src/UIForm/fieldsets/Array/Array.component.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.test.js
  packages/forms/src/UIForm/utils/array.js
  packages/forms/src/UIForm/utils/array.test.js
  packages/forms/stories-core/json/fieldsets/core-arrays.json
Labels: need review

#2265 fix(components/list): iconactiontoggle misaligned on ie
  packages/components/src/List/Toolbar/DisplayModeToggle/DisplayModeToggle.scss
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss
Labels: bug, easy review, frontend, need review

#2249 feat(TDP-6894): datalist selected item indicator
  output/components.sasslint.txt
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.scss
Labels: easy review, enhancement, frontend, work in progress

#2253 fix(components/ListView): Automatic rows sizing
  packages/components/src/ListView/Items/Item/Item.component.js
  packages/components/src/ListView/Items/Item/Item.scss
  packages/components/src/ListView/Items/Item/Item.test.js
  packages/components/src/ListView/Items/Item/__snapshots__/item.snapshot.test.js.snap
  packages/components/src/ListView/Items/Items.component.js
  packages/components/src/ListView/Items/Items.scss
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/stories/ListView.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.test.js
  packages/forms/src/UIForm/fields/NestedListView/NestedListView.component.js
  packages/forms/src/widgets/ListViewWidget/ListViewWidget.test.js
  packages/forms/stories-core/json/fields/core-nestedListView.json
Labels: need review

#2269 feat(icons): flag
  packages/icons/src/svg/core/flag.svg
Labels: easy review, need review

#2271 fix(component/ListView): Hidden focus outline
  npm-audit/scripts.json
  packages/components/src/ListView/Items/Items.scss
Labels: easy review, need review

#2270 fix(components/SubHeaderBar): subheader edit icon should only be visible when hover on title
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
Labels: bug, easy review, frontend

#2266 feat(datagrid): update ag-grid
  npm-audit/audit.json
  output/datagrid.eslint.txt
  packages/datagrid/README.md
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js
  packages/datagrid/src/components/DataGrid/DataGrid.scss
  packages/datagrid/src/components/DataGrid/DataGrid.test.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.test.js
  packages/datagrid/stories/DynamicDataGrid.component.js
  packages/datagrid/stories/FasterDatagrid.component.js
  packages/datagrid/stories/ImmutableDatagrid.component.js
  packages/datagrid/stories/datagrid.component.js
  yarn.lock
Labels: need review
