Repository Talend/ui, pull requests merged in 2020-07, with the labels that each got.

#2876 fix(component): Remove wrong ways to discover schema
  packages/components/src/DataViewer/RecordsViewer/RecordsViewer.parser.js
  packages/components/src/DataViewer/RecordsViewer/RecordsViewer.parser.test.js
Labels: bug, easy review, need review

#2879 fix(icons): close path of shield-full-check.svg
  packages/icons/src/svg/core/shield-full-check.svg
Labels: easy review, need review

#2880 fix(icons): close path on shield-full.svg
  packages/icons/src/svg/core/shield-full.svg
Labels: easy review, need review

#2881 fix(BasicSearch): set overflow prop from "auto" to "visible" to hide scrollbar for IE and Edge.
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/BasicSearch/BasicSearch.scss
Labels: need review

#2884 fix(ListComposition): selection with lazy loaded list (2)
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.test.js
Labels: need review

#2853 feat: http package
  packages/http/README.md
  packages/http/babel.config.js
  packages/http/package.json
  packages/http/src/async.js
  packages/http/src/config.js
  packages/http/src/config.test.js
  packages/http/src/csrfHandling.js
  packages/http/src/generators.js
  packages/http/src/http.common.js
  packages/http/src/http.common.test.js
  packages/http/src/http.constants.js
  packages/http/src/index.js
  packages/http/yarn.lock
Labels: need review

#2886 fix(TCCUI-178) - show suggestions when clicking on the datalist
  output/components.eslint.txt
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/src/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/components/src/Typeahead/Typeahead.component.js
Labels: need review

#2885 chore: gh actions publish
  .github/workflows/release-variables.sh
  .github/workflows/release.yml
  package.json
Labels: need review

#2887 fix(forms/datalist): merge async titlemaps in schema
  output/forms.eslint.txt
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js
Labels: easy review, need review

#2889 chore: release v5.12.0
  lerna.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
Labels: Release

#2890 chore: set back the build-demo npm script
  package.json
Labels: easy review, need review

#2892 feat(AppGuidedTour): Make demo content optional
  packages/components/src/AppGuidedTour/AppGuidedTour.component.js
  packages/components/src/AppGuidedTour/AppGuidedTour.stories.js
  packages/components/src/AppGuidedTour/AppGuidedTour.test.js
Labels: easy review, enhancement, need review

#2899 fix(components): ActionIconToggle now handle the ref to the button
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
Labels: easy review, need review

#2902 feat(icons): adaptative pie-charts
  packages/icons/src/svg/core/pie-charts.svg
Labels: easy review, need review

#2901 chore: install dependencies before trying to build demo in gh release action
  .github/workflows/release.yml
Labels: easy review, need review

#2903 feat(icon): ThoughtSpot.svg
  packages/icons/src/svg/brands/thoughtspot.svg
Labels: easy review, need review

#2904 feat(icon): spark.svg
  packages/icons/src/svg/brands/spark.svg
Labels: easy review, need review

#2909 chore(faceted): add storybook
  .surge/index.html
  .travis/after_success_demo.sh
  .travis/after_success_static.sh
  package.json
  yarn.lock
Labels: easy review, enhancement, need review

#2911 feat(components/slider): improve slider api
  output/components.eslint.txt
  packages/components/src/Slider/Slider.component.js
  packages/components/src/Slider/index.js
  packages/containers/src/Slider/__snapshots__/Slider.test.js.snap
Labels: easy review, enhancement, need review

#2912 feat(icon): rules.svg
  packages/icons/src/svg/core/rules.svg
Labels: easy review, need review

#2914 feat(icon): rabbitmq.svg
  packages/icons/src/svg/brands/rabbitmq.svg
Labels: easy review, need review

#2897 feat(faceted): add slider facet
  packages/faceted-search/package.json
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.component.js
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.component.test.js
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.scss
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.test.js
  packages/faceted-search/src/components/Badges/BadgeSlider/__snapshots__/BadgeSlider.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeSlider/__snapshots__/BadgeSliderForm.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeSlider/index.js
  packages/faceted-search/src/components/Badges/index.js
  packages/faceted-search/src/dictionary/badge.dictionary.js
  packages/faceted-search/stories/badgesDefinitions.story.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: enhancement, need review

#2913 feat(icon): neo4j.svg
  packages/icons/src/svg/brands/neo4j.svg
Labels: easy review, need review

#2915 chore(faceted-search): remove it from yarn workspace
  package.json
  packages/faceted-search/yarn.lock
  yarn.lock
Labels: need review

#2916 feat(faceted): embed error messages in slider facet
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.test.js
  packages/faceted-search/stories/badgesDefinitions.story.js
Labels: bug, easy review, enhancement, need review

#2919 fix(faceted): fallback to default for slider facet
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.component.js
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js
Labels: need review

#2920 fix(datagrid): Fix height calculation in Safari
  packages/datagrid/src/components/DataGrid/DataGrid.scss
Labels: bug, easy review
