Repository Talend/ui, pull requests merged in 2020-12, with the labels that each got.

#3103 fix(forms): remove ie11 support to be umd compliant
  output/components.eslint.txt
  packages/forms/src/rhf/fields/Input/Input.stories.js
  packages/forms/src/rhf/fields/Input/Input.test.js
  packages/forms/src/rhf/fields/Input/RHFInput.component.js
Labels: breaking change, need review

#3099 fix(theme): remove line-height on nav items
  packages/theme/src/theme/_navs.scss
Labels: easy review, need review

#3098 fix(tabbar): make tabs take full space
  packages/components/src/TabBar/TabBar.scss
Labels: need review

#3106 fix(drawer): spread props to Transition
  output/components.eslint.txt
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.stories.js
  packages/components/src/WithDrawer/WithDrawer.component.js
Labels: need review

#3108 fix(icons): remove z at the end of polyline
  packages/icons/src/svg/brands/dynamodb.svg
Labels: need review

#3110 fix(ComponentForm): export name resolver
  packages/containers/src/ComponentForm/index.js
Labels: need review

#3096 chore(Collapsible): status style
  output/components.eslint.txt
  output/components.sasslint.txt
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/src/CollapsiblePanel/CollapsiblePanel.stories.js
Labels: need review

#3115 fix(components/enumeration): Fix checkbox position
  packages/components/src/Enumeration/Items/Item/Item.scss
Labels: easy review, need review

#3104 feat(icons): collapse.svg
  packages/icons/src/svg/core/collapse.svg
Labels: easy review, need review

#3116 fix(components/list composition): wrong position for the order icon with resizable column
  packages/components/src/VirtualizedList/HeaderResizable/HeaderResizable.scss
Labels: easy review, need review

#3117 chore(theme): flexible icon peer dep
  packages/theme/package.json
Labels: easy review, need review

#3112 chore: remove addon-info from storybook cmf
  packages/storybook-cmf/package.json
Labels: need review

#3114 feat(components/typeahead): align to guidelines
  packages/components/src/Datalist/Datalist.scss
  packages/components/src/Emphasis/Emphasis.scss
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.scss
  packages/components/src/Typeahead/Typeahead.stories.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Labels: enhancement, need review

#3118 feat(forms): Add Select widget in React Hook Form
  packages/forms/src/rhf/fields/Select/RHFSelect.component.js
  packages/forms/src/rhf/fields/Select/Select.stories.js
  packages/forms/src/rhf/fields/Select/Select.test.js
  packages/forms/src/rhf/fields/Select/index.js
  packages/forms/src/rhf/index.js
  packages/forms/src/widgets/fields/Select/Select.component.js
  packages/forms/src/widgets/fields/Select/Select.test.js
  packages/forms/src/widgets/fields/Select/index.js
  packages/forms/src/widgets/fields/index.js
Labels: enhancement, need review

#3119 fix(container/notification): fix strange error with delete
  packages/containers/src/Notification/Notification.connect.js
  packages/containers/src/Notification/Notification.test.js
Labels: bug, easy review, need review

#3125 fix(Drawer): add transitioned props for BCompat
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/WithDrawer/WithDrawer.component.js
Labels: need review

#3126 fix(components): ListComposition/DefaultSort - simplify body of defaultSort function
  output/components.eslint.txt
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.test.js
Labels: easy review, need review

#3131 chore: trigger webhook to update cdn content after a release
  .github/workflows/dataviz-autopublish.yml
  .github/workflows/release.yml
Labels: easy review, enhancement, need review

#3129 feat(TDC-3961): Text mode for file input fields
  packages/forms/src/UIForm/fields/File/File.component.js
  packages/forms/src/UIForm/fields/File/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/File/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/File/displayMode/__snapshots__/TextMode.component.test.js.snap
  packages/forms/src/UIForm/fields/File/index.js
  packages/forms/src/UIForm/utils/widgets.js
Labels: need review

#3137 chore: trigger webhook to update cdn content after a release
  .github/workflows/validation-autopublish.yml
Labels: easy review, enhancement, need review

#3134 feat(icon): tableau.svg
  packages/icons/src/svg/brands/tableau.svg
Labels: easy review, need review

#3130 chore(components): use d3 instead of d3-shape
  packages/components/package.json
  packages/components/src/PieChart/PieChartIcon.component.js
  versions/dependencies.json
  yarn.lock
Labels: need review

#3136 feat(component/ratiobar): optionally hide label
  packages/components/src/RatioBar/RatioBar.component.js
  packages/components/src/RatioBar/RatioBar.component.test.js
  packages/components/src/RatioBar/RatioBar.stories.js
Labels: easy review, enhancement, need review

#3144 feat(TPSVC-15539): add data attributes to the forms
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/stories-core/json/fields/core-datalist.json
Labels: need review

#3148 chore: prepare release 6.6.0
  lerna.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
Labels: need review
