Repository Talend/ui, pull requests merged in 2020-10, with the labels that each got.

#2978 chore: expose getTheme in index
  packages/components/src/index.js
  packages/icons/6.0 - breaking changes.md
Labels: easy review, need review

#2968 feat(icons): import.svg , export.svg
  packages/icons/src/svg/core/export.svg
  packages/icons/src/svg/core/import.svg
Labels: easy review, need review

#2966 feat(icon): error.svg
  packages/icons/src/svg/core/error.svg
Labels: easy review, need review

#2985 chore: refactor to use ag-grid umd compliant
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  yarn.lock
Labels: easy review, need review

#2987 chore(containers): reorganize exports to prepare 6.0
  packages/containers/6.0 - breaking changes.md
  packages/containers/src/AboutDialog/index.js
  packages/containers/src/Action/Action.connect.js
  packages/containers/src/ActionButton/ActionButton.connect.js
  packages/containers/src/ActionButton/ActionButton.test.js
  packages/containers/src/ActionDropdown/ActionDropdown.connect.js
  packages/containers/src/ActionDropdown/ActionDropdown.test.js
  packages/containers/src/ActionFile/ActionFile.connect.js
  packages/containers/src/ActionIconToggle/ActionIconToggle.connect.js
  packages/containers/src/ActionSplitDropdown/ActionSplitDropdown.connect.js
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/index.js
  packages/containers/src/EditableText/index.js
  packages/containers/src/FilterBar/index.js
  packages/containers/src/GuidedTour/index.js
  packages/containers/src/HeaderBar/index.js
  packages/containers/src/List/index.js
  packages/containers/src/SubHeaderBar/index.js
  packages/containers/src/TabBar/index.js
  packages/containers/src/cmfModule.js
  packages/containers/src/index.js
  packages/containers/src/register.js
  yarn.lock
Labels: need review

#2990 fix(containers/notification): attach actions to Notification
  packages/containers/src/Notification/index.js
Labels: need review

#2986 feat(components/RadarChart): Interactive RadarChart axis dots
  output/components.eslint.txt
  packages/components/src/RadarChart/RadarChart.component.js
  packages/components/src/RadarChart/RadarChart.stories.js
  packages/components/src/RadarChart/RadarChart.test.js
Labels: enhancement, need review

#2991 feat(drawer): allow to add actions in title
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.stories.js
  packages/components/src/Drawer/Drawer.test.js
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
Labels: need review

#2983 feat(icons): routes.svg
  packages/icons/src/svg/core/routes.svg
Labels: easy review, need review

#2981 feat(icon): semantic-filter.svg
  packages/icons/src/svg/processors/semantic-filter.svg
Labels: easy review, need review

#2984 feat(icon): data-services.svg
  packages/icons/src/svg/core/data-services.svg
Labels: easy review, need review

#2988 chore(forms): upgrading react hook form to v6
  packages/forms/package.json
  packages/forms/src/rhf/fields/Input/Input.stories.js
  packages/forms/src/rhf/fields/Input/Input.test.js
  packages/forms/src/rhf/fields/Input/RHFInput.component.js
  versions/dependencies.json
  yarn.lock
Labels: breaking change

#2969 feat(icons): download.svg, upload.svg
  output/components.eslint.txt
  output/containers.eslint.txt
  output/forms.eslint.txt
  packages/icons/package.json
  packages/icons/src/svg/core/download.svg
  packages/icons/src/svg/core/upload.svg
  yarn.lock
Labels: easy review, need review

#2996 chore: change deep imports to non deep to prepare cdn
  output/containers.eslint.txt
  output/forms.eslint.txt
  packages/containers/src/ActionFile/ActionFile.test.js
  packages/containers/src/ComponentForm/fields/MultiSelect/MultiSelect.component.js
  packages/containers/src/ComponentForm/fields/MultiSelect/displayMode/TextMode.component.js
  packages/containers/src/ComponentForm/fields/NameResolver/NameResolver.component.js
  packages/containers/src/ComponentForm/fields/index.js
  packages/containers/src/ComponentForm/kit/defaultRegistry.js
  packages/forms/src/UIForm/Message/index.js
  packages/forms/src/UIForm/fields/Button/SingleButton.component.js
  packages/forms/src/UIForm/fields/Comparator/Comparator.component.js
  packages/forms/src/UIForm/fields/FieldTemplate/index.js
  packages/forms/src/UIForm/index.js
Labels: need review

#2999 chore: change imports to not being too deep
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/AdvancedSearch/AdvancedSearch.component.js
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumberForm.component.js
  packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperatorPopover.component.js
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js
  packages/faceted-search/src/components/Badges/BadgeTags/BadgeTagsForm.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeTextForm.component.js
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/FacetedSearchIcon/FacetedSearchIcon.component.js
  packages/forms/src/deprecated/Form.js
  packages/stepper/src/index.js
  packages/stepper/src/service/Stepper.selectors.js
Labels: need review

#3001 feat(components/radarchart): pass index to the dotwithclick onclick callback
  packages/components/src/RadarChart/RadarChart.component.js
  packages/components/src/RadarChart/RadarChart.test.js
Labels: easy review, enhancement

#3003 fix:(faceted-search): upgrade tui deps and fix imports
  packages/faceted-search/package.json
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumberForm.component.js
  packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperatorPopover.component.js
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.scss
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeTextForm.component.js
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeTextForm.component.test.js.snap
  packages/faceted-search/yarn.lock
Labels: need review

#2994 chore(faceted-search): read only support
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js
  packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperatorOverlay.component.js
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.js
  packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: easy review, need review

#3004 fix(TDC-4797/components/radarchart): Increase chart axis label spacing
  packages/components/src/RadarChart/RadarChart.component.js
  packages/components/src/RadarChart/RadarChart.scss
  packages/components/src/RadarChart/__snapshots__/RadarChart.test.js.snap
Labels: easy review, need review

#2939 fix(cmf): Avoid infinite rerender on error page
  packages/cmf/src/components/ErrorPanel/ErrorPanel.component.js
Labels: bug, easy review, need review

#3007 fix: datagrid keyboard regression and VirtualizedList story
  packages/components/src/VirtualizedList/VirtualizedList.stories.js
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
Labels: easy review, need review

#3006 feat(icons): group.svg; ungroup.svg
  packages/icons/src/svg/core/group.svg
  packages/icons/src/svg/core/ungroup.svg
Labels: easy review, need review

#3010 fix: datagrid keyboard navigation
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
Labels: easy review, need review

#3000 feat(faceted-search): Add pattern operators
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/dictionary/operator.dictionary.js
  packages/faceted-search/src/queryClient/tql.js
  packages/faceted-search/src/queryClient/tql.test.js
Labels: easy review, need review

#3011 feat(components): ratio and quality bar
  packages/components/src/QualityBar/QualityBar.component.js
  packages/components/src/QualityBar/QualityBar.component.test.js
  packages/components/src/QualityBar/QualityBar.stories.js
  packages/components/src/QualityBar/QualityRatioBar.component.js
  packages/components/src/QualityBar/QualityRatioBar.scss
  packages/components/src/QualityBar/index.js
  packages/components/src/RatioBar/RatioBar.component.js
  packages/components/src/RatioBar/RatioBar.component.test.js
  packages/components/src/RatioBar/RatioBar.scss
  packages/components/src/RatioBar/RatioBar.stories.js
  packages/components/src/RatioBar/RatioBarComposition.component.js
  packages/components/src/RatioBar/RatioBarLines.component.js
  packages/components/src/RatioBar/index.js
  packages/components/src/index.js
Labels: need review

#3013 feat(faceted-search): Add colored badge support
  output/components.eslint.txt
  output/components.sasslint.txt
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js
  packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperator.scss
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.component.js
  packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js
  packages/faceted-search/src/dictionary/badge.dictionary.js
  packages/faceted-search/src/hooks/facetedBadges.hook.js
  packages/faceted-search/stories/facetedSearch.story.js
  packages/faceted-search/yarn.lock
Labels: easy review, need review

#3020 chore: change RatioBar composition pattern
  packages/components/src/QualityBar/QualityBar.component.js
  packages/components/src/QualityBar/QualityRatioBar.component.js
  packages/components/src/RatioBar/index.js
  packages/components/src/index.js
Labels: easy review, need review

#3019 chore: update eslint libraries
  packages/eslint-config/package.json
Labels: need review

#3018 chore: release umd bundles of talend UI
  .storybook/webpack.config.js
  package.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/__tests__/bootstrap.test.js
  packages/cmf/package.json
  packages/components/package.json
  packages/components/src/polyfills/focus-within.js
  packages/containers/package.json
  packages/containers/src/PieChartButton/PieChartButton.connect.js
  packages/datagrid/package.json
  packages/forms/package.json
  packages/forms/src/UIForm/fields/Datalist/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/FieldTemplate/__snapshots__/FieldTemplate.component.test.js.snap
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js
  packages/generator/package.json
  packages/html-webpack-plugin/package.json
  packages/http/package.json
  packages/icons/.babelrc.json
  packages/icons/index.js
  packages/icons/package.json
  packages/icons/scripts/react.js
  packages/icons/src/umd.js
  packages/icons/umd.dependencies.json
  packages/icons/umd.min.dependencies.json
  packages/icons/webpack.umd.js
  packages/jsfc/webpack.config.js
  packages/router/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
  packages/theme/webpack.config.js
  yarn.lock
Labels: need review

#2998 chore(DatePicker): add minWidth for inputs
  output/components.eslint.txt
  packages/components/src/DateTimePickers/Date/Input/Input.component.js
  packages/components/src/DateTimePickers/DateRange/Input/Input.component.js
  packages/components/src/DateTimePickers/InputDatePicker/DatePicker.stories.js
  packages/components/src/DateTimePickers/InputDateRangePicker/DateRangePicker.stories.js
  packages/components/src/DateTimePickers/shared/InputSizer/InputSizer.component.js
Labels: easy review

#3017 feat(components/list): enrich cellicontext api
  packages/components/src/List/ListComposition.stories.js
  packages/components/src/List/ListComposition/collection.js
  packages/components/src/VirtualizedList/CellIconText/CellIconText.component.js
  packages/components/src/VirtualizedList/CellIconText/CellIconText.test.js
  packages/components/src/VirtualizedList/CellIconText/__snapshots__/CellIconText.test.js.snap
Labels: easy review, enhancement, need review

#3022 chore: expose missing elements in index
  output/containers.eslint.txt
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/package.json
  packages/cmf/src/index.js
  packages/components/package.json
  packages/components/src/IconsProvider/IconsProvider.component.js
  packages/containers/6.0 - breaking changes.md
  packages/containers/package.json
  packages/containers/src/ComponentForm/ComponentForm.actions.js
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/index.js
  packages/containers/src/Form/Form.container.js
  packages/containers/src/containers.js
  packages/containers/src/register.test.js
  packages/datagrid/6.0 - breaking changes.md
  packages/datagrid/package.json
  packages/datagrid/src/index.js
  packages/forms/package.json
  packages/html-webpack-plugin/package.json
  packages/http/package.json
  packages/icons/index.js
  packages/router/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/stepper/src/index.js
  packages/storybook-cmf/package.json
  packages/theme/webpack.config.js
  yarn.lock
Labels: easy review, need review

#3024 feat(router): option for path getter to include hash
  packages/router/package.json
  packages/router/src/selectors.js
  packages/router/src/selectors.test.js
Labels: easy review, need review

#3026 chore: remove double build and fix some lints
  output/components.eslint.txt
  packages/cmf-cqrs/package.json
  packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.test.js
  packages/cmf/README.md
  packages/cmf/package.json
  packages/cmf/src/cmfConnect.md
  packages/components/package.json
  packages/components/src/List/ListComposition.stories.js
  packages/components/src/VirtualizedList/CellIconText/CellIconText.component.js
  packages/containers/.storybook/config.js
  packages/containers/src/Action/Action.test.js
  packages/containers/src/ActionBar/ActionBar.test.js
  packages/containers/src/ActionButton/ActionButton.test.js
  packages/containers/src/ActionDropdown/ActionDropdown.test.js
  packages/containers/src/ActionFile/ActionFile.test.js
  packages/containers/src/ActionIconToggle/ActionIconToggle.test.js
  packages/containers/src/ActionSplitDropdown/ActionSplitDropdown.test.js
  packages/containers/src/Actions/Actions.test.js
  packages/containers/src/ConfirmDialog/ConfirmDialog.test.js
  packages/containers/src/DeleteResource/DeleteResource.test.js
  packages/containers/src/List/selector.test.js
  packages/containers/src/Notification/Notification.test.js
  packages/containers/src/SelectObject/SelectObject.test.js
  packages/containers/src/ShortcutManager/ShortcutManager.test.js
  packages/containers/src/SidePanel/SidePanel.test.js
  packages/containers/src/TreeView/TreeView.test.js
  packages/containers/src/actionAPI.test.js
  packages/datagrid/package.json
  packages/datagrid/src/containers/DataGrid/DataGrid.connect.test.js
  packages/datagrid/src/containers/datagrid.container.stories.js
  packages/forms/package.json
  packages/generator/generators/react-cmf/templates/src/app/components/App/App.container.test.js
  packages/http/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/src/CMFStory/CMFStory.component.js
Labels: easy review, need review

#3028 fix(IconsProvider): function name
  packages/components/src/IconsProvider/IconsProvider.component.js
Labels: easy review, need review

#3032 chore(router): upgrade cmf dep
  packages/containers/package.json
  packages/router/package.json
  packages/router/yarn.lock
  yarn.lock
Labels: easy review, need review
