Repository Talend/ui, pull requests merged in 2020-11, with the labels that each got.

#3030 feat(ARCH-203): add Icon support for remote svg
  .storybook/webpack.config.js
  packages/components/src/Icon/Icon.component.js
  packages/components/src/Icon/Icon.stories.js
  packages/components/src/Icon/Icon.test.js
  packages/components/src/Icon/__snapshots__/Icon.test.js.snap
Labels: need review

#3029 feat(components/guidedtour): add data-feature to the let me try button
  output/components.eslint.txt
  packages/components/src/AppGuidedTour/AppGuidedTour.stories.js
  packages/components/src/GuidedTour/GuidedTour.component.js
  packages/components/src/GuidedTour/GuidedTour.stories.js
Labels: easy review, enhancement, need review

#3033 chore(RHFInput): use required props to display required star
  packages/forms/src/widgets/fields/Input/Input.component.js
  packages/forms/src/widgets/templates/FieldTemplate/FieldTemplate.component.js
  packages/forms/src/widgets/templates/FieldTemplate/FieldTemplate.scss
Labels: easy review

#3038 chore(Stepper): export constants
  packages/stepper/src/index.js
Labels: easy review, need review

#3041 fix(components/AboutModal): add optional version
  packages/components/src/AboutDialog/AboutDialog.component.js
  packages/components/src/AboutDialog/AboutModal.stories.js
Labels: need review

#3042 fix(ListComposition): filter without accents or diacritics
  output/components.eslint.txt
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.test.js
  packages/components/src/List/ListComposition/collection.js
Labels: easy review, enhancement, need review

#3043 feat(ListComposition): filter on limited column list
  packages/components/src/List/ListComposition.stories.js
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/ListManager.component.test.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionFilter.hook.test.js
  packages/components/src/List/ListComposition/TextFilter/TextFilter.component.js
  packages/components/src/List/ListComposition/TextFilter/TextFilter.component.test.js
Labels: enhancement, need review

#3045 fix(containers): import in storybook initialisation
  packages/containers/.storybook/config.js
Labels: easy review, need review

#3046 feat(icons): dataprep.svg
  packages/icons/src/svg/products/dataprep.svg
Labels: easy review, need review

#3035 chore(forms/MultiSelectTag): adding onBlur callback
  output/forms.eslint.txt
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js
  packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap
Labels: easy review, need review

#3047 feat(components/ListComposition): ColumnChooser
  packages/components/src/List/ListComposition.stories.js
  packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.js
  packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.test.js
  packages/components/src/List/ListComposition/ColumnChooser/index.js
  packages/components/src/List/ListComposition/LazyLoadingList/LazyLoadingList.component.test.js
  packages/components/src/List/ListComposition/Manager/ListManager.component.js
  packages/components/src/List/ListComposition/Manager/ListManager.component.test.js
  packages/components/src/List/ListComposition/VList/VList.component.js
  packages/components/src/List/ListComposition/VList/VList.component.test.js
  packages/components/src/List/ListComposition/index.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserTable/ColumnChooserTable.component.js
Labels: easy review, enhancement, need review

#3021 chore(TabBar): adding component on menu's right
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/src/TabBar/TabBar.test.js
  packages/components/src/TabBar/Tabs.stories.js
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
Labels: easy review, need review

#3037 feat(cmf): combine reducers in modules
  packages/cmf/__tests__/cmfModule.merge.test.js
  packages/cmf/package.json
  packages/cmf/src/cmfModule.merge.js
  packages/cmf/src/store.js
  yarn.lock
Labels: need review

#3048 fix: expose missing exports
  packages/components/src/Gesture/index.js
  packages/components/src/List/List.component.js
  packages/components/src/List/Toolbar/index.js
  packages/components/src/VirtualizedList/HeaderResizable/index.js
  packages/components/src/VirtualizedList/index.js
  packages/components/src/index.js
  packages/containers/src/containers.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.component.js
  packages/forms/src/UIForm/fields/CheckBox/index.js
  packages/forms/src/UIForm/index.js
  packages/forms/src/UIForm/utils/index.js
  packages/router/src/index.js
Labels: need review

#3050 chore: expose List constants and SelectAll
  output/forms.eslint.txt
  packages/components/src/List/ListComposition/index.js
Labels: easy review, need review

#3051 feat(icons): studio logos
  packages/icons/src/svg/products/studio-colored.svg
  packages/icons/src/svg/products/studio-negative.svg
  packages/icons/src/svg/products/studio-postive.svg
Labels: easy review, need review

#3053 feat(components/ColumnChooser): call props.onSubmit if exist
  packages/components/src/List/ListComposition.stories.js
  packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.js
  packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.test.js
Labels: easy review, need review

#3059 fix(datagrid): add missing exports needed for integration
  output/datagrid.eslint.txt
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultValueRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/FormatValue.component.js
  packages/datagrid/src/components/DefaultCellRenderer/QualityIndicator.component.js
  packages/datagrid/src/components/DefaultCellRenderer/index.js
  packages/datagrid/src/components/index.js
  packages/datagrid/src/index.js
Labels: need review

#3060 fix(containers): use same Forms import
  packages/containers/src/Form/Form.container.js
Labels: easy review, enhancement

#3039 chore: add intermediare deps used accross our project
  versions/dependencies.json
Labels: need review

#3062 fix(components/DateTimePicker): add missing exports
  packages/components/src/DateTimePickers/index.js
  packages/components/src/index.js
Labels: need review

#3058 feat(icons): rebrand product logos
  packages/components/src/AppLoader/AppLoader.stories.js
  packages/components/src/Layout/AppLayout.stories.js
  packages/components/src/Layout/Layout.component.js
  packages/components/src/SidePanel/SidePanel.stories.js
  packages/components/stories/config/themes.scss
  packages/containers/examples/config/themes.scss
  packages/icons/src/svg/products/api-designer-colored.svg
  packages/icons/src/svg/products/api-designer-negative.svg
  packages/icons/src/svg/products/api-designer-positive.svg
  packages/icons/src/svg/products/api-tester-colored.svg
  packages/icons/src/svg/products/api-tester-negative.svg
  packages/icons/src/svg/products/api-tester-positive.svg
  packages/icons/src/svg/products/component-kit-colored.svg
  packages/icons/src/svg/products/component-kit-negative.svg
  packages/icons/src/svg/products/component-kit-positive.svg
  packages/icons/src/svg/products/data-fabric-colored.svg
  packages/icons/src/svg/products/data-fabric-negative.svg
  packages/icons/src/svg/products/data-fabric-positive.svg
  packages/icons/src/svg/products/datacatalog-colored.svg
  packages/icons/src/svg/products/datacatalog-negative.svg
  packages/icons/src/svg/products/datacatalog-positive.svg
  packages/icons/src/svg/products/datastreams-colored.svg
  packages/icons/src/svg/products/datastreams-negative.svg
  packages/icons/src/svg/products/datastreams-positive.svg
  packages/icons/src/svg/products/mdm-colored.svg
  packages/icons/src/svg/products/mdm-negative.svg
  packages/icons/src/svg/products/mdm-positive.svg
  packages/icons/src/svg/products/studio-colored.svg
  packages/icons/src/svg/products/studio-negative.svg
  packages/icons/src/svg/products/studio-postive.svg
  packages/icons/src/svg/products/tdc-colored.svg
  packages/icons/src/svg/products/tdc-negative.svg
  packages/icons/src/svg/products/tdc-positive.svg
  packages/icons/src/svg/products/tdp-colored.svg
  packages/icons/src/svg/products/tdp-negative.svg
  packages/icons/src/svg/products/tdp-positive.svg
  packages/icons/src/svg/products/tds-colored.svg
  packages/icons/src/svg/products/tds-negative.svg
  packages/icons/src/svg/products/tds-positive.svg
  packages/icons/src/svg/products/tmc-colored.svg
  packages/icons/src/svg/products/tmc-negative.svg
  packages/icons/src/svg/products/tmc-positive.svg
  packages/theme/package.json
  packages/theme/src/theme/_visual-helpers.scss
  packages/theme/src/theme/variations/_mdm.scss
  packages/theme/src/theme/variations/_tdc.scss
  packages/theme/src/theme/variations/_tdp.scss
  packages/theme/src/theme/variations/_tds.scss
  packages/theme/src/theme/variations/_tfd.scss
  packages/theme/src/theme/variations/_tmc.scss
  yarn.lock
Labels: need review

#3069 fix(TMC-23400/CollapsiblePanel): warning colors update
  output/forms.eslint.txt
  packages/theme/src/theme/_variables.scss
Labels: need review

#3071 fix(IconsProvider): make it work without context
  packages/components/6.0 - breaking changes.md
  packages/components/src/Icon/Icon.component.js
  packages/components/src/Icon/Icon.stories.js
  packages/components/src/IconsProvider/IconsProvider.component.js
  packages/components/src/IconsProvider/README.md
Labels: need review

#3066 fix(security): upgrade json-logic 2.0
  output/components.eslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  packages/cmf-cqrs/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/generators/app/templates/package.json
  packages/generator/generators/react-cmf/templates/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/stepper/package.json
  versions/dependencies.json
  yarn.lock
Labels: need review

#3075 fix(HeaderBar): logo color
  packages/components/src/HeaderBar/HeaderBar.scss
Labels: need review

#3077 fix: remove key props
  packages/components/src/DataViewer/Virtualized/TreeCellMeasurer/TreeCellMeasurer.component.js
Labels: need review

#3078 fix(forms): expose arrayitem
  packages/components/src/Badge/Badge.component.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
Labels: need review

#3079 fix(forms/storybook): unwrap IconsProvider
  packages/forms/.storybook/config.js
Labels: need review

#3080 fix: add missing export
  packages/components/src/VirtualizedList/CellDatetime/DatetimeColumn.component.js
Labels: need review

#3082 fix(icons): rename studio icon
  packages/icons/src/svg/products/studio-positive.svg
Labels: easy review, need review

#3084 chore(forms): break circular dependencies
  output/forms.eslint.txt
  packages/forms/src/UIForm/Message/Message.component.test.js
  packages/forms/src/UIForm/Message/__snapshots__/Message.component.test.js.snap
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/Widget/Widget.component.test.js
  packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
  packages/forms/src/UIForm/context.js
  packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.test.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/Radios/Radios.component.js
  packages/forms/src/UIForm/fields/Text/Text.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/displayMode/TextModeArrayTemplate.component.js
Labels: need review

#3088 chore(forms): break circular dependencies (#3084)
  output/forms.eslint.txt
  packages/forms/src/UIForm/Message/Message.component.test.js
  packages/forms/src/UIForm/Message/__snapshots__/Message.component.test.js.snap
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/Widget/Widget.component.test.js
  packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
  packages/forms/src/UIForm/context.js
  packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.test.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/Radios/Radios.component.js
  packages/forms/src/UIForm/fields/Text/Text.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/displayMode/TextModeArrayTemplate.component.js
Labels: need review

#3092 fix(List/ColumnChooser): let's defined its own columns
  packages/components/src/List/ListComposition/ColumnChooser/ColumnChooser.component.js
Labels: bug, easy review, need review

#3081 chore(DateTime/Time): adding minWidth support for datetime range and time
  output/components.eslint.txt
  packages/components/src/DateTimePickers/Date/Input/Input.component.js
  packages/components/src/DateTimePickers/DateRange/Input/Input.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/DateTimeRangePicker.stories.js
  packages/components/src/DateTimePickers/InputTimePicker/TimePicker.stories.js
  packages/components/src/DateTimePickers/Time/Input/Input.component.js
Labels: easy review, need review

#2958 chore(components/Drawer): use react-transition-group
  output/components.eslint.txt
  packages/components/package.json
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.stories.js
  packages/components/src/WithDrawer/WithDrawer.component.js
  yarn.lock
Labels: need review

#3094 fix(TDC-3764/File): Support base64 encoded file names with multi-byte characters
  packages/forms/src/UIForm/fields/File/File.component.js
  packages/forms/src/UIForm/fields/File/File.component.test.js
  packages/forms/stories-core/jsonStories.js
Labels: easy review, enhancement, need review, question

#3093 fix(TimePicker): default width should be slightly bigger
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.scss
Labels: easy review, need review
