Repository Talend/ui, pull requests merged in 2020-05, with the labels that each got.

#2797 feat(forms): parameterize id concatenation separator
  packages/forms/__mocks__/data.js
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
  packages/forms/src/UIForm/Widget/Widget.component.js
Labels: need review

#2805 feat(components): Handle long values in RecordsViewer
  packages/components/src/DataViewer/Core/Tree/Tree.scss
  packages/components/src/DataViewer/Icons/TreeBranchIcon/TreeBranchIcon.scss
  packages/components/src/DataViewer/ModelViewer/Branch/__snapshots__/ModelViewerBranch.test.js.snap
  packages/components/src/DataViewer/ModelViewer/Leaf/__snapshots__/ModelViewerLeaf.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/Branch/RecordsViewerBranch.component.js
  packages/components/src/DataViewer/RecordsViewer/Branch/__snapshots__/RecordsViewerBranch.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/Leaf/RecordsViewerLeaf.component.js
  packages/components/src/DataViewer/RecordsViewer/Leaf/__snapshots__/RecordsViewerLeaf.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/RecordsViewer.scss
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/DefaultValueRenderer.component.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/DefaultValueRenderer.scss
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/DefaultValueRenderer.test.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.scss
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/DefaultValueRenderer.test.js.snap
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/SimpleTextKeyValue.test.js.snap
Labels: need review

#2808 chore(components): some refacto for forms snapshots
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Badge/Badge.component.js
  packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/ListView/ListView.component.js
Labels: need review

#2807 fix(forms): tests
  packages/cmf/jest.config.js
  packages/datagrid/jest.config.js
  packages/forms/__mocks__/styleMock.js
  packages/forms/src/UIForm/UIForm.component.test.js
  packages/forms/src/UIForm/fields/Code/Code.component.test.js
  packages/forms/src/UIForm/fields/Comparator/__snapshots__/Comparator.component.test.js.snap
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js
  packages/forms/src/UIForm/fields/Datalist/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/Enumeration/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/src/UIForm/fields/File/File.component.test.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.test.js
  packages/forms/src/UIForm/fields/ListView/__snapshots__/ListView.component.test.js.snap
  packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap
  packages/forms/src/UIForm/fields/NestedListView/__snapshots__/NestedListView.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Tabs/Tabs.component.js
  packages/forms/src/UIForm/fieldsets/Tabs/Tabs.component.test.js
  packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/src/deprecated/widgets/ListViewWidget/ListViewWidget.test.js
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
  test-setup.js
Labels: need review

#2813 chore(forms): eslint --fix
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/Widget/Widget.component.test.js
  packages/forms/src/UIForm/fields/Button/Button.component.test.js
  packages/forms/src/UIForm/fields/Button/Buttons.component.test.js
  packages/forms/src/UIForm/fields/Button/SingleButton.component.test.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBox.test.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.test.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.test.js
  packages/forms/src/UIForm/fields/CheckBox/displayMode/TextMode.test.js
  packages/forms/src/UIForm/fields/Code/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/Comparator/Comparator.component.js
  packages/forms/src/UIForm/fields/Comparator/displayMode/TextMode.test.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js
  packages/forms/src/UIForm/fields/Datalist/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/Date/Date.component.test.js
  packages/forms/src/UIForm/fields/Date/DateTime.component.test.js
  packages/forms/src/UIForm/fields/Date/Time.component.test.js
  packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.component.test.js
  packages/forms/src/UIForm/fields/FieldTemplate/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/RadioOrSelect/RadioOrSelect.component.test.js
  packages/forms/src/UIForm/fields/Radios/Radios.component.js
  packages/forms/src/UIForm/fields/Radios/Radios.component.test.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.test.js
  packages/forms/src/UIForm/fields/Select/Select.component.test.js
  packages/forms/src/UIForm/fields/Select/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/Text/Text.component.test.js
  packages/forms/src/UIForm/fields/Text/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/TextArea/TextArea.component.test.js
  packages/forms/src/UIForm/fields/TextArea/displayMode/TextMode.component.test.js
  packages/forms/src/UIForm/fields/Toggle/Toggle.component.test.js
  packages/forms/src/UIForm/fields/Toggle/displayMode/TextMode.test.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.component.test.js
  packages/forms/src/UIForm/fieldsets/Array/displayMode/TextModeArrayTemplate.component.test.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
  packages/forms/src/deprecated/fields/BooleanField.js
  packages/forms/src/deprecated/templates/FieldTemplate.js
  packages/forms/src/deprecated/widgets/CodeWidget/CodeWidget.component.js
  packages/forms/src/deprecated/widgets/ColumnsWidget/ColumnsWidget.js
  packages/forms/src/deprecated/widgets/DatalistWidget/DatalistWidget.js
  packages/forms/src/deprecated/widgets/TabsWidget.js
Labels: easy review, need review

#2814 feat(faceted-search): i18n configuration
  output/components.eslint.txt
  packages/faceted-search/.gitignore
  packages/faceted-search/i18next-scanner.config.js
  packages/faceted-search/package.json
  packages/faceted-search/talend-i18n.json
  packages/faceted-search/yarn.lock
Labels: need review

#2816 chore(forms): fix lint errors using @talend/scripts
  packages/forms/.eslintrc
  packages/forms/package.json
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/Widget/Widget.component.js
  packages/forms/src/UIForm/fields/Button/SingleButton.component.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.component.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
  packages/forms/src/UIForm/fields/Code/Code.component.js
  packages/forms/src/UIForm/fields/Comparator/Comparator.component.js
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.js
  packages/forms/src/UIForm/fields/Datalist/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fields/Date/Date.component.js
  packages/forms/src/UIForm/fields/Date/DateTime.component.js
  packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
  packages/forms/src/UIForm/fields/Enumeration/utils/utils.test.js
  packages/forms/src/UIForm/fields/File/File.component.js
  packages/forms/src/UIForm/fields/KeyValue/KeyValue.component.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.test.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/RadioOrSelect/RadioOrSelect.component.js
  packages/forms/src/UIForm/fields/Radios/Radios.component.js
  packages/forms/src/UIForm/fields/ResourcePicker/ResourcePicker.component.js
  packages/forms/src/UIForm/fields/Select/Select.component.js
  packages/forms/src/UIForm/fields/Text/Text.component.js
  packages/forms/src/UIForm/fields/TextArea/TextArea.component.js
  packages/forms/src/UIForm/fields/Toggle/Toggle.component.js
  packages/forms/src/UIForm/fields/Toggle/displayMode/TextMode.component.js
  packages/forms/src/UIForm/fieldsets/Array/Array.component.js
  packages/forms/src/UIForm/fieldsets/Array/ArrayItem.component.js
  packages/forms/src/UIForm/fieldsets/Array/__snapshots__/Array.component.test.js.snap
  packages/forms/src/UIForm/fieldsets/Array/displayMode/TextModeArrayTemplate.component.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
  packages/forms/src/UIForm/fieldsets/Columns/Columns.component.js
  packages/forms/src/UIForm/fieldsets/Fieldset/Fieldset.component.js
  packages/forms/src/UIForm/utils/condition.js
  packages/forms/src/UIForm/utils/validation.js
Labels: easy review, need review

#2799 feat(icons): logo-colored.svg; logo-square.svg
  packages/icons/src/svg/products/logo-colored.svg
  packages/icons/src/svg/products/logo-square.svg
Labels: easy review, need review

#2818 fix(BadgeOperator/TMDM-14276) IE11 : Center icons faceted
  packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperator.scss
Labels: need review

#2821 fix(theme): Fix box-shadow on Safari
  packages/theme/src/theme/_visual-helpers.scss
Labels: bug, easy review, need review

#2819 feat(CollapsibleFieldset/TMDM-14604): display description
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/README.md
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap
  packages/forms/stories-core/json/fieldsets/core-collapsibleFieldset.json
Labels: need review

#2822 feat(component/actionicontoggle): add tick
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/Actions/ActionIconToggle/IconToggle.stories.js
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/components/src/List/Toolbar/DisplayModeToggle/__snapshots__/DisplayModeToggle.test.js.snap
  packages/components/src/ResourceList/Toolbar/StateFilter/__snapshots__/StateFilter.snap.test.js.snap
  packages/containers/src/ActionIconToggle/__snapshots__/ActionIconToggle.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
  packages/faceted-search/src/components/FacetedSearchIcon/FacetedSearchIcon.component.js
Labels: easy review, enhancement, need review

#2802 feat(icons): shield-full-check.svg; shield-full.svg; shield.svg
  packages/icons/src/svg/core/shield-full-check.svg
  packages/icons/src/svg/core/shield-full.svg
  packages/icons/src/svg/core/shield.svg
Labels: easy review, need review

#2824 feat(component): Allow to customize RecordsViewer types render
  packages/components/src/DataViewer/DataViewer.stories.js
  packages/components/src/DataViewer/ModelViewer/Branch/__snapshots__/ModelViewerBranch.test.js.snap
  packages/components/src/DataViewer/ModelViewer/Leaf/__snapshots__/ModelViewerLeaf.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/Leaf/RecordsViewerLeaf.component.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.test.js
Labels: easy review, need review

#2823 feat(DataViewer): Dataset should leverage the new name in avro format
  packages/components/src/DataViewer/ModelViewer/ModelViewer.container.js
  packages/components/src/DataViewer/ModelViewer/ModelViewer.parser.test.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.test.js
Labels: need review

#2829 feat(icons): file-connect-o.svg
  packages/icons/src/svg/files/file-connect-o.svg
Labels: easy review, need review

#2830 fix(component): Fix TabBar with Dropdown
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
Labels: bug, easy review, need review

#2831 fix(Components): talend scripts components tests
  packages/components/src/Actions/ActionFile/__snapshots__/ActionFile.test.js.snap
  packages/components/src/Badge/Badge.component.test.js
  packages/components/src/Badge/__snapshots__/Badge.component.test.js.snap
  packages/components/src/Breadcrumbs/__snapshots__/Breadcrumbs.snapshot.test.js.snap
  packages/components/src/CircularProgress/CircularProgress.component.js
  packages/components/src/DataViewer/ModelViewer/Branch/__snapshots__/ModelViewerBranch.test.js.snap
  packages/components/src/DataViewer/ModelViewer/Leaf/__snapshots__/ModelViewerLeaf.test.js.snap
  packages/components/src/DataViewer/ModelViewer/__snapshots__/ModelViewer.component.test.js.snap
  packages/components/src/DataViewer/ModelViewer/__snapshots__/ModelViewer.container.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/Branch/__snapshots__/RecordsViewerBranch.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/Leaf/__snapshots__/RecordsViewerLeaf.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/__snapshots__/RecordsViewer.component.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/__snapshots__/RecordsViewer.container.test.js.snap
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/DefaultValueRenderer.test.js.snap
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Validation/__snapshots__/Validation.component.test.js.snap
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/__snapshots__/HeaderTitle.test.js.snap
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
  packages/components/src/DateTimePickers/views/DateView/__snapshots__/DateView.test.js.snap
  packages/components/src/DateTimePickers/views/HeaderTitle/__snapshots__/HeaderTitle.test.js.snap
  packages/components/src/DateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap
  packages/components/src/GridLayout/Tile/Skeleton/__snapshots__/SkeletonTile.component.test.js.snap
  packages/components/src/Layout/__snapshots__/Layout.test.js.snap
  packages/components/src/List/ListComposition/Manager/__snapshots__/ListManager.component.test.js.snap
  packages/components/src/List/ListComposition/TextFilter/__snapshots__/TextFilter.component.test.js.snap
Labels: need review

#2832 fix(Components): adapt tests for @talend/scripts
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/Notification/__snapshots__/Notification.test.js.snap
  packages/components/src/ObjectViewer/JSONLike/__snapshots__/JSONLike.test.js.snap
  packages/components/src/PieChart/__snapshots__/PieChart.test.js.snap
  packages/components/src/PieChart/__snapshots__/PieChartButton.test.js.snap
  packages/components/src/PieChart/__snapshots__/PieChartIcon.test.js.snap
  packages/components/src/ResourceList/Toolbar/__snapshots__/Toolbar.snap.test.js.snap
  packages/components/src/Stepper/__snapshots__/Stepper.component.test.js.snap
  packages/components/src/SubHeaderBar/TitleSubHeader/__snapshots__/TitleSubHeader.test.js.snap
  packages/components/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap
  packages/components/src/TreeView/TreeViewItem/__snapshots__/TreeViewItem.test.js.snap
  packages/components/src/VirtualizedList/CellBadge/CellBadge.test.js
  packages/components/src/VirtualizedList/CellBadge/__snapshots__/CellBadge.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitle.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
  packages/components/src/VirtualizedList/NoRows/__snapshots__/NoRows.test.js.snap
  packages/components/src/VirtualizedList/RowCollapsiblePanel/__snapshots__/RowCollapsiblePanel.test.js.snap
  packages/components/src/VirtualizedList/RowLarge/__snapshots__/RowLarge.test.js.snap
Labels: need review

#2834 fix(Components): snapshot tests with @talend/scripts
  packages/components/src/Actions/ActionDropdown/ActionDropdown.snapshot.test.js
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
  packages/components/src/MultiSelect/MultiSelect.container.test.js
  packages/components/src/MultiSelect/__snapshots__/MultiSelect.container.test.js.snap
  packages/components/src/VirtualizedList/CellBoolean/CellBoolean.component.js
  packages/components/src/VirtualizedList/CellBoolean/CellBoolean.test.js
  packages/components/src/VirtualizedList/CellBoolean/__snapshots__/CellBoolean.test.js.snap
Labels: need review

#2835 fix(Components): tests with @talend/scripts
  packages/components/src/AboutDialog/AboutDialog.snapshot.test.js
  packages/components/src/ActionBar/ActionBar.snapshot.test.js
  packages/components/src/ActionBar/__snapshots__/ActionBar.snapshot.test.js.snap
  packages/components/src/ActionIntercom/Intercom.component.test.js
  packages/components/src/ActionIntercom/__snapshots__/Intercom.component.test.js.snap
  packages/components/src/Actions/ActionButton/ActionButton.test.js
  packages/components/src/Actions/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/components/src/DateTimePickers/Date/Picker/Picker.component.test.js
  packages/components/src/DateTimePickers/DateRange/Picker/Picker.component.test.js
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.test.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/InputDateTimePicker.component.test.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/DateTimePicker/DateTimePicker.test.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/DateTimePicker/__snapshots__/DateTimePicker.test.js.snap
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/YearPicker/YearPicker.test.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/DateTimeView/__snapshots__/DateTimeView.test.js.snap
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/HeaderTitle.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/index.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
  packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.test.js
  packages/components/src/DateTimePickers/pickers/CalendarPicker/__snapshots__/CalendarPicker.test.js.snap
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.test.js
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.test.js
  packages/components/src/DateTimePickers/views/DateView/__snapshots__/DateView.test.js.snap
  packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.component.js
  packages/components/src/DateTimePickers/views/HeaderTitle/index.js
  packages/components/src/DateTimePickers/views/MonthYearView/__snapshots__/MonthYearView.test.js.snap
  packages/router/package.json
  test-setup.js
Labels: need review

#2839 fix(TCCUI-167): change link margin size
  packages/components/src/InlineMessage/InlineMessage.scss
Labels: easy review, need review
