Repository Talend/ui, pull requests merged in 2020-03, with the labels that each got.

#2675 feat(faceted-search): Empty string for filter badges with no result
  npm-audit/router.json
  npm-audit/scripts.json
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.scss
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js
Labels: easy review, need review

#2678 feat(components/FilterBar): Add a prop disabled to pass into filter input
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/FilterBar/FilterBar.test.js
  packages/components/src/FilterBar/__snapshots__/FilterBar.snapshot.test.js.snap
  packages/components/src/List/ListComposition/TextFilter/__snapshots__/TextFilter.component.test.js.snap
  packages/components/stories/FilterBar.js
Labels: easy review, enhancement, need review

#2679 feat(cmf): add root option to target render element
  packages/cmf/__tests__/bootstrap.test.js
  packages/cmf/src/bootstrap.js
  packages/cmf/src/bootstrap.md
  packages/cmf/src/cmfModule.merge.js
Labels: need review

#2681 chore(components/ResourceList): tree shaking
  npm-audit/audit.json
  packages/components/package.json
  packages/components/src/ResourceList/Toolbar/NameFilter/NameFilter.component.js
  yarn.lock
Labels: easy review, need review

#2682 feat: remove letter-spacing from buttons
  npm-audit/audit.json
  output/components.sasslint.txt
  output/theme.sasslint.txt
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/src/Enumeration/Items/Item/Item.scss
  packages/components/src/HttpError/HttpError.scss
  packages/components/src/List/ListComposition/SortBy/SortBy.scss
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss
  packages/components/src/ObjectViewer/Table/Table.scss
  packages/components/src/Typeahead/Typeahead.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.scss
  packages/theme/src/theme/_breadcrumbs.scss
  packages/theme/src/theme/_buttons.scss
  packages/theme/src/theme/_navbar.scss
Labels: easy review, enhancement, need review

#2673 feat(faceted-search): Handle category in badge definitions
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.scss
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js
  packages/faceted-search/src/components/AddFacetPopover/__snapshots__/AddFacetPopver.component.test.js.snap
  packages/faceted-search/stories/badgesDefinitions.story.js
  packages/faceted-search/stories/facetedSearch.story.js
  packages/faceted-search/yarn.lock
Labels: enhancement, frontend, need review

#2684 chore: remove unused log package
  .travis/after_success_coverage.sh
  .travis/after_success_lint.sh
  .travis/after_success_static.sh
  README.md
  package.json
  packages/logging/.babelrc
  packages/logging/.editorconfig
  packages/logging/.gitignore
  packages/logging/.npmignore
  packages/logging/README.md
  packages/logging/package.json
  packages/logging/src/angular/README.md
  packages/logging/src/angular/angular-logger.js
  packages/logging/src/angular/angular-logger.test.js
  packages/logging/src/angular/index.js
  packages/logging/src/api/errorTransformer.js
  packages/logging/src/api/errorTransformer.test.js
  packages/logging/src/api/payloadMiddleware.js
  packages/logging/src/api/transport.js
  packages/logging/src/react/README.md
  packages/logging/src/react/index.js
  packages/logging/src/react/react-logger.js
  packages/logging/src/react/react-logger.test.js
  packages/logging/src/redux/README.md
  packages/logging/src/redux/index.js
  packages/logging/src/redux/redux-logger.js
  packages/logging/src/redux/redux-logger.test.js
  packages/logging/test-setup.js
  packages/logging/yarn.lock
Labels: easy review, need review

#2685 fix(components/listcomposition): rigth toolbar vertical alignment
  npm-audit/html-webpack-plugin.json
  npm-audit/router.json
  npm-audit/scripts.json
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.scss
Labels: bug, easy review, need review

#2688 chore(faceted-search): release 0.4.0
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
  packages/faceted-search/yarn.lock
Labels: easy review, enhancement, need review

#2690 fix: i18n extract ignore stories
  package.json
Labels: easy review, need review

#2693 fix(components/sidepanel): sidepanel docked initial width
  npm-audit/html-webpack-plugin.json
  npm-audit/router.json
  npm-audit/scripts.json
  packages/components/src/SidePanel/SidePanel.component.js
Labels: easy review, need review

#2692 feat(faceted-search): Handle badgePerFacet metadata
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
Labels: enhancement, need review

#2696 fix(faceted-search): Do not display empty label badge
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
  npm-audit/router.json
  npm-audit/scripts.json
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js
  packages/faceted-search/stories/badgesDefinitions.story.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: bug, easy review, frontend, need review

#2697 fix: eslint issue
  .eslintignore
  .eslintrc
  output/cmf-webpack-plugin.eslint.txt
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.eslint.txt
  output/router.eslint.txt
  output/sagas.eslint.txt
  output/stepper.eslint.txt
  packages/components/package.json
  packages/datagrid/package.json
Labels: need review

#2694 feat(icons): ftp.svg
  packages/icons/src/svg/processors/ftp.svg
Labels: easy review, need review

#2703 fix(components/list): title actions overflow
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
Labels: bug, easy review, need review

#2700 feat(theme): enable font-smoothing
  output/theme.sasslint.txt
  packages/theme/src/theme/_fonts.scss
Labels: easy review, need review

#2704 fix(components): update font-size in sidepanel
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
  packages/components/src/SidePanel/SidePanel.scss
Labels: easy review, need review

#2702 fix(components): application icon size in header
  packages/components/src/HeaderBar/HeaderBar.scss
Labels: easy review, need review

#2706 feat(cmf): handle blob type
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
Labels: easy review, enhancement, need review

#2708 feat(components/slider): accept getTooltipContainer props
  packages/components/src/Slider/Slider.component.js
  packages/components/src/Slider/Slider.stories.js
Labels: easy review, enhancement

#2698 feat(icons):pause.svg
  npm-audit/audit.json
  packages/icons/src/svg/core/pause.svg
Labels: easy review, need review

#2707 feat(icons):marketo.svg
  npm-audit/scripts.json
  output/theme.sasslint.txt
  packages/icons/src/svg/brands/marketo.svg
Labels: easy review, need review

#2709 fix(faceted-search): Set initialOperatorOpened to false on hiding the value overlay
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
Labels: bug, easy review, need review

#2714 fix(ci): use latest 1.X version of Prettier
  .travis.yml
  npm-audit/audit.json
  npm-audit/html-webpack-plugin.json
Labels: easy review, need review

#2713 chore(components): buttons in list update
  output/components.eslint.txt
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
Labels: easy review, enhancement, need review

#2715 feat(components/resourcelist): be able to pass options to items
  packages/components/src/ResourceList/Resource/Resource.component.js
  packages/components/src/ResourceList/ResourceList.component.js
  packages/components/src/ResourceList/ResourceList.propTypes.js
  packages/components/src/ResourceList/ResourceList.stories.js
  packages/components/src/VirtualizedList/RowSelection/RowSelection.component.js
Labels: enhancement, frontend, need review
