Repository Talend/ui, pull requests merged in 2020-09, with the labels that each got.

#2935 feat(TPSVC-15467): show list items number
  packages/components/src/ActionBar/ActionBar.component.js
  packages/components/src/ActionBar/ActionBar.test.js
  packages/components/src/List/List.stories.js
  packages/components/src/List/ListComposition/ItemsNumber/ItemsNumber.component.js
  packages/components/src/List/ListComposition/ItemsNumber/ItemsNumber.component.test.js
  packages/components/src/List/ListComposition/ItemsNumber/README.md
  packages/components/src/List/ListComposition/ItemsNumber/index.js
  packages/components/src/List/ListComposition/ListComposition.stories.js
  packages/components/src/List/ListComposition/index.js
  packages/components/src/List/Toolbar/ItemsNumber/ItemsNumber.component.js
  packages/components/src/List/Toolbar/ItemsNumber/ItemsNumber.component.test.js
  packages/components/src/List/Toolbar/ItemsNumber/index.js
  packages/components/src/List/Toolbar/Toolbar.component.js
Labels: need review

#2943 feat(theme): brand-primary is not customizable anymore
  packages/theme/src/theme/_variables.scss
Labels: easy review, enhancement, need review

#2936 feat(Badge): Add color support
  packages/components/src/Badge/Badge.component.js
  packages/components/src/Badge/Badge.scss
  packages/components/src/Badge/Badge.stories.js
Labels: need review

#2948 feat(icons): plus-circle.svg; minus-circle.svg
  packages/icons/src/svg/core/minus-circle.svg
  packages/icons/src/svg/core/plus-circle.svg
Labels: easy review, need review

#2933 feat(component/guidedtour): allow to disable welcome step
  packages/components/src/AppGuidedTour/AppGuidedTour.component.js
Labels: easy review, enhancement, need review

#2941 feat(TDC-4605): Add radar chart component for trust score display
  packages/components/package.json
  packages/components/src/RadarChart/RadarChart.component.js
  packages/components/src/RadarChart/RadarChart.scss
  packages/components/src/RadarChart/RadarChart.stories.js
  packages/components/src/RadarChart/RadarChart.test.js
  packages/components/src/RadarChart/__snapshots__/RadarChart.test.js.snap
  packages/components/src/RadarChart/index.js
  yarn.lock
Labels: need review

#2949 feat(icon): snowflake.svg
  packages/icons/src/svg/brands/snowflake.svg
Labels: easy review, need review

#2950 feat(icon): pulsar.svg
  output/components.eslint.txt
  packages/icons/src/svg/brands/pulsar.svg
Labels: easy review, need review

#2953 chore: fix high security issue in cmf website deps
  packages/cmf/website/package.json
  packages/cmf/website/yarn.lock
Labels: easy review, need review

#2959 feat(TPSVC-15539): add data attributes to the forms
  output/forms.eslint.txt
  packages/forms/src/UIForm/fields/CheckBox/CheckBoxes.component.js
  packages/forms/src/UIForm/fields/CheckBox/SimpleCheckBox.component.js
  packages/forms/src/UIForm/fields/CheckBox/__snapshots__/CheckBoxes.test.js.snap
  packages/forms/src/UIForm/fields/Date/Date.component.js
  packages/forms/src/UIForm/fields/File/File.component.js
  packages/forms/src/UIForm/fields/Radios/Radios.component.js
  packages/forms/src/UIForm/fields/Select/Select.component.js
  packages/forms/src/UIForm/fields/Text/Text.component.js
  packages/forms/src/UIForm/fields/Toggle/Toggle.component.js
  packages/forms/src/UIForm/utils/properties.js
  packages/forms/stories-core/json/fields/core-checkbox.json
  packages/forms/stories-core/json/fields/core-date.json
  packages/forms/stories-core/json/fields/core-file.json
  packages/forms/stories-core/json/fields/core-radios-or-select.json
  packages/forms/stories-core/json/fields/core-radios.json
  packages/forms/stories-core/json/fields/core-select.json
  packages/forms/stories-core/json/fields/core-text.json
  packages/forms/stories-core/json/fields/core-toggle.json
Labels: need review

#2942 feat(TMC-22423/TabBar): tab bar with labels
  output/components.eslint.txt
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.scss
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/src/TabBar/TabBar.test.js
  packages/components/src/TabBar/Tabs.stories.js
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/components/src/utils/getTabBarBadgeLabel.js
  packages/components/src/utils/getTabBarBadgeLabel.test.js
Labels: need review

#2960 chore(components): align dependencies
  packages/components/package.json
  versions/dependencies.json
  yarn.lock
Labels: easy review, need review

#2961 feat(icon): dynamodb.svg
  packages/icons/src/svg/brands/dynamodb.svg
Labels: easy review, need review

#2964 feat(forms): export from index
  packages/forms/6.0-BreakingChanges.md
  packages/forms/src/UIForm/Message/index.js
  packages/forms/src/UIForm/fields/index.js
  packages/forms/src/UIForm/fieldsets/index.js
  packages/forms/src/UIForm/index.js
  packages/forms/src/UIForm/utils/index.js
  packages/forms/src/deprecated/fields/index.js
  packages/forms/src/deprecated/index.js
  packages/forms/src/deprecated/templates/index.js
  packages/forms/src/deprecated/widgets/EnumerationWidget/index.js
  packages/forms/src/deprecated/widgets/ListViewWidget/index.js
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/index.js
  packages/forms/src/deprecated/widgets/index.js
  packages/forms/src/index.js
  packages/forms/src/rhf/index.js
  packages/forms/src/widgets/fields/index.js
  packages/forms/src/widgets/index.js
  packages/forms/src/widgets/templates/index.js
Labels: easy review, enhancement, need review

#2965 chore: remove dist from npm ignore
  packages/components/.npmignore
  packages/html-webpack-plugin/.npmignore
  packages/local-libs-webpack-plugin/.npmignore
  packages/sagas/.npmignore
Labels: easy review, need review

#2932 feat(facetedsearch/sliderfacet): pointer cursor on the slider facet value
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSlider.scss
  packages/faceted-search/src/components/Badges/BadgeSlider/BadgeSliderForm.component.js
Labels: easy review, enhancement, need review

#2967 feat(icon): update play.svg
  packages/icons/src/svg/core/play.svg
Labels: easy review, need review

#2970 feat(components/RadarChart): Event tracking support
  packages/components/src/RadarChart/RadarChart.component.js
Labels: easy review

#2962 feat(cmf): prepare export for umd compat
  packages/cmf/6.0-BreakingChanges.md
  packages/cmf/src/cmfModule.js
  packages/cmf/src/cmfModule.merge.js
  packages/cmf/src/index.js
  packages/cmf/src/middlewares/error/index.js
  packages/cmf/src/middlewares/http/index.js
  packages/cmf/src/middlewares/index.js
  packages/cmf/src/settings.md
  packages/containers/src/ComponentForm/kit/createTriggers.js
  packages/containers/src/Notification/Notification.sagas.js
  packages/router/src/index.js
  packages/router/src/selectors.js
Labels: need review

#2972 fix(faceted-search): don't reopen the value tooltip for badges with default operator
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
Labels: bug, easy review, need review

#2976 fix(theme): body fonts should be black
  packages/theme/src/theme/_variables.scss
Labels: bug, easy review, need review

#2975 fix(TPSVC-15962/AppSwitcher): connect it with component registry
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/containers/src/index.js
Labels: easy review, need review

#2977 fix(forms): rhf from peer to dependencies
  packages/forms/package.json
  versions/dependencies.json
Labels: need review
