Repository Talend/ui, pull requests merged in 2020-06, with the labels that each got.

#2838 fix(components/ColumnChooser): add key in columns config
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.js
  packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.test.js
Labels: need review

#2828 feat(TDC-3908): Add badge tags in faceted-search
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.component.js
  packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.scss
  packages/faceted-search/src/components/Badges/BadgeTags/BadgeTagsForm.component.js
  packages/faceted-search/src/components/Badges/BadgeTags/index.js
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
  packages/faceted-search/src/components/BadgesGenerator/BadgesGenerator.component.js
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
  packages/faceted-search/src/components/facetedSearch.propTypes.js
  packages/faceted-search/src/dictionary/badge.dictionary.js
  packages/faceted-search/stories/badgesDefinitions.story.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: enhancement, need review

#2840 fix(Layout): Drawer with layout 1 column
  packages/components/src/Drawer/Drawer.stories.js
  packages/components/src/Layout/OneColumn/OneColumn.scss
Labels: easy review, need review

#2842 fix(faceted-search): Avoid error when there is no callbacks props
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeTags/BadgeTags.component.js
Labels: bug, easy review, need review

#2815 fix(faceted-search): update some labels
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.test.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
Labels: need review

#2844 fix(Components): tests with @talend/scripts
  packages/components/src/ActionBar/ActionBar.component.js
  packages/components/src/ActionBar/__snapshots__/ActionBar.snapshot.test.js.snap
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/HeaderTitle.test.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/__snapshots__/HeaderTitle.test.js.snap
  packages/components/src/Drawer/Drawer.test.js
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/FilterBar/FilterBar.test.js
  packages/components/src/Gesture/withCalendarGesture.test.js
  packages/components/src/Gesture/withDynamicListGesture.test.js
  packages/components/src/Gesture/withListGesture.test.js
  packages/components/src/Gesture/withTreeGesture.test.js
  packages/components/src/HeaderBar/HeaderBar.test.js
  packages/components/src/Layout/SkipLinks/SkipLinks.test.js
  packages/components/src/Layout/SkipLinks/__snapshots__/SkipLinks.test.js.snap
  packages/components/src/ResourceList/Resource/Resource.snap.test.js
  packages/components/src/ResourceList/Toolbar/StateFilter/StateFilter.snap.test.js
  packages/components/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap
Labels: need review

#2847 fix(faceted-search): check badge existence before trying to set it
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/CRUDBadges.js
Labels: need review

#2849 chore: remove deprecated package @talend/scripts
  packages/scripts/README.md
  packages/scripts/common/log.js
  packages/scripts/index.js
  packages/scripts/package.json
  packages/scripts/webapp/README.md
  packages/scripts/webapp/config/webpack.analyzer.js
  packages/scripts/webapp/config/webpack.config.js
  packages/scripts/webapp/doc/customisation.md
  packages/scripts/webapp/doc/getting-started.md
  packages/scripts/webapp/doc/presets.md
  packages/scripts/webapp/index.js
  packages/scripts/webapp/preset/README.md
  packages/scripts/webapp/preset/config/.babelrc.json
  packages/scripts/webapp/preset/config/.eslintrc
  packages/scripts/webapp/preset/config/babel-resolver.js
  packages/scripts/webapp/preset/config/jest.config.js
  packages/scripts/webapp/preset/config/karma/karma.conf.js
  packages/scripts/webapp/preset/config/karma/webpack.config.js
  packages/scripts/webapp/preset/config/licence.js
  packages/scripts/webapp/preset/config/test/file-mock.js
  packages/scripts/webapp/preset/config/test/jest-preprocess.js
  packages/scripts/webapp/preset/config/test/style-mock.js
  packages/scripts/webapp/preset/config/test/test-setup.js
  packages/scripts/webapp/preset/config/webpack.config.dev.js
  packages/scripts/webapp/preset/config/webpack.config.js
  packages/scripts/webapp/preset/config/webpack.config.prod.js
  packages/scripts/webapp/preset/details.md
  packages/scripts/webapp/preset/preset-talend-babel.js
  packages/scripts/webapp/preset/preset-talend-eslint.js
  packages/scripts/webapp/preset/preset-talend-jest.js
  packages/scripts/webapp/preset/preset-talend-karma.js
  packages/scripts/webapp/preset/preset-talend-webpack.js
  packages/scripts/webapp/preset/preset-talend.js
  packages/scripts/webapp/scripts/build-lib.js
  packages/scripts/webapp/scripts/build.js
  packages/scripts/webapp/scripts/extends.js
  packages/scripts/webapp/scripts/lint-es.js
  packages/scripts/webapp/scripts/start.js
  packages/scripts/webapp/scripts/test-ng.js
  packages/scripts/webapp/scripts/test.js
  packages/scripts/webapp/utils/env.js
  packages/scripts/webapp/utils/path-resolver.js
  packages/scripts/webapp/utils/preset.js
  packages/scripts/yarn.lock
Labels: easy review, need review

#2848 fix(Components): tests with @talend/scripts
  packages/components/src/List/ListComposition/TextFilter/TextFilter.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/ColumnChooserBody.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserFooter/ColumnChooserFooter.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserHeader/ColumnChooserHeader.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowCheckbox/RowCheckbox.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowLabel/RowLabel.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/SelectAllColumnsCheckbox.component.test.js
  packages/components/src/ResourceList/Toolbar/SortOptions/SortOptions.snap.test.js
  packages/components/src/Skeleton/Skeleton.test.js
  packages/components/src/translate.test.js
Labels: need review

#2850 fix(Components): linter errors with @talend/scripts
  packages/components/.eslintrc
  packages/components/package.json
  packages/components/src/AboutDialog/AboutDialog.component.js
  packages/components/src/ActionBar/ActionBar.component.js
  packages/components/src/Actions/Action/Action.component.js
  packages/components/src/Actions/Action/Action.test.js
  packages/components/src/Actions/Action/index.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.snapshot.test.js
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.component.js
  packages/components/src/Actions/wrapOnClick.js
  packages/components/src/Actions/wrapOnClick.test.js
  packages/components/src/ResourceList/ResourceList.component.js
  packages/components/src/VirtualizedList/ListGrid/ListGrid.component.js
  packages/components/src/VirtualizedList/RowLarge/RowLarge.component.js
  packages/components/src/VirtualizedList/VirtualizedList.stories.js
  packages/forms/package.json
  yarn.lock
Labels: need review

#2854 fix(containers/SidePanel): improve management of metakey and ctrlkey
  packages/containers/src/SidePanel/SidePanel.connect.js
Labels: need review

#2851 feat(components): create AppSwitcher component
  output/components.eslint.txt
  packages/components/src/AppSwitcher/AppSwitcher.component.js
  packages/components/src/AppSwitcher/AppSwitcher.component.test.js
  packages/components/src/AppSwitcher/AppSwitcher.scss
  packages/components/src/AppSwitcher/__snapshots__/AppSwitcher.component.test.js.snap
  packages/components/src/AppSwitcher/index.js
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.stories.js
  packages/components/src/HeaderBar/HeaderBar.test.js
Labels: enhancement, need review

#2857 fix(Components): linter errors with @talend/scripts
  packages/components/src/Actions/Actions.component.js
  packages/components/src/AppGuidedTour/AppGuidedTour.component.js
  packages/components/src/AppLoader/AppLoader.component.js
  packages/components/src/Badge/Badge.component.test.js
  packages/components/src/ConfirmDialog/ConfirmDialog.component.js
  packages/components/src/ConfirmDialog/ConfirmDialog.stories.js
  packages/components/src/DataViewer/Core/Tree/Tree.test.js
  packages/components/src/DataViewer/Core/Tree/__snapshots__/Tree.test.js.snap
  packages/components/src/DataViewer/DataViewer.stories.js
  packages/components/src/DataViewer/Managers/TreeManager/TreeManager.container.js
  packages/components/src/DataViewer/ModelViewer/Leaf/ModelViewerLeaf.component.js
  packages/components/src/DataViewer/ModelViewer/ModelViewer.container.js
  packages/components/src/DataViewer/RecordsViewer/RecordsViewer.component.js
  packages/components/src/DataViewer/RecordsViewer/RecordsViewer.container.js
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/DateTimePickers/Date/Manager/Manager.component.js
  packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js
  packages/components/src/DateTimePickers/DateTimeRange/Manager/Manager.component.js
  packages/components/src/DateTimePickers/InputDateRangePicker/InputDateRangePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Manager/Manager.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Validation/Validation.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/YearPicker/YearPicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/DateTimeView/DateTimeView.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/HeaderTitle.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/MonthYearView/MonthYearView.component.js
  packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.component.js
  packages/components/src/VirtualizedList/CellActions/__snapshots__/CellActions.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
Labels: need review

#2860 fix(form/Time): can't input `:` into time field
  packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js
  packages/components/src/DateTimePickers/DateTime/datetime-extraction.js
  packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.component.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/__snapshots__/InputDateTimeRangePicker.component.test.js.snap
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js
  packages/components/src/DateTimePickers/Time/Input/Input.component.js
  packages/components/src/DateTimePickers/Time/Manager/Manager.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/DateTimePickers/pickers/TimePicker/TimePicker.component.test.js
  packages/forms/src/UIForm/fields/Date/Time.component.js
Labels: need review

#2861 fix(Components): linter errors with @talend/scripts
  packages/components/.eslintrc
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Validation/__snapshots__/Validation.component.test.js.snap
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/GridLayout/Dashboard.stories.js
  packages/components/src/GuidedTour/GuidedTour.stories.js
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.stories.js
  packages/components/src/IconsProvider/IconsProvider.component.js
  packages/components/src/InlineMessage/InlineMessage.component.js
  packages/components/src/InlineMessage/InlineMessage.stories.js
  packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.component.js
  packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.test.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSelection.hook.js
  packages/components/src/List/ListComposition/SortBy/SortBy.component.js
  packages/components/src/List/ListComposition/collection.js
  packages/components/src/List/ListToVirtualizedList/ListToVirtualizedList.component.js
  packages/components/src/List/Toolbar/ColumnChooserButton/hooks/columnChooserManager.hook.test.js
  packages/components/src/List/Toolbar/DisplayModeToggle/DisplayModeToggle.component.js
  packages/components/src/List/Toolbar/Pagination/Pagination.component.js
  packages/components/src/List/Toolbar/SelectAll/SelectAll.component.js
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js
  packages/components/src/ListView/Items/Items.component.js
  packages/components/src/ListView/ListView.component.js
Labels: need review

#2862 fix(faceted): hide delete icon if no filters
  output/components.eslint.txt
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
Labels: bug, easy review, need review

#2863 chore(container): use @talend/scripts for tests
  packages/containers/src/ActionButton/ActionButton.connect.js
  packages/containers/src/ActionButton/ActionButton.test.js
  packages/containers/src/ActionButton/__snapshots__/ActionButton.test.js.snap
  packages/containers/src/ActionDropdown/__snapshots__/ActionDropdown.test.js.snap
  packages/containers/src/Badge/Badge.test.js
  packages/containers/src/EditableText/__snapshots__/EditableText.test.js.snap
  packages/containers/src/FilterBar/__snapshots__/FilterBar.test.js.snap
  packages/containers/src/HeaderBar/HeaderBar.sagas.test.js
  packages/containers/src/HeaderBar/__snapshots__/HeaderBar.test.js.snap
  packages/containers/src/HomeListView/__snapshots__/HomeListView.test.js.snap
  packages/containers/src/Redirect/__snapshots__/Redirect.test.js.snap
  packages/containers/src/SidePanel/__snapshots__/SidePanel.test.js.snap
  packages/containers/src/SubHeaderBar/SubHeaderBar.container.js
  packages/containers/src/SubHeaderBar/SubHeaderBar.test.js
  packages/containers/src/SubHeaderBar/__snapshots__/SubHeaderBar.test.js.snap
Labels: need review

#2864 fix(Containers): linter errors
  packages/containers/src/AboutDialog/AboutDialog.container.js
  packages/containers/src/Action/Action.connect.js
  packages/containers/src/ActionBar/ActionBar.connect.js
  packages/containers/src/ActionDropdown/ActionDropdown.connect.js
  packages/containers/src/ActionFile/ActionFile.connect.js
  packages/containers/src/ActionIconToggle/ActionIconToggle.connect.js
  packages/containers/src/ActionIconToggle/ActionIconToggle.test.js
  packages/containers/src/ActionSplitDropdown/ActionSplitDropdown.connect.js
  packages/containers/src/Actions/Actions.connect.js
  packages/containers/src/ComponentForm/fields/MultiSelect/MultiSelect.component.js
  packages/containers/src/ConfirmDialog/ConfirmDialog.container.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/EditableText/EditableText.container.js
  packages/containers/src/FilterBar/FilterBar.container.js
  packages/containers/src/Form/Form.container.js
  packages/containers/src/HeaderBar/HeaderBar.connect.js
  packages/containers/src/HeaderBar/HeaderBar.container.js
  packages/containers/src/List/List.connect.js
  packages/containers/src/List/List.container.js
  packages/containers/src/Notification/Notification.connect.js
  packages/containers/src/Notification/clearNotifications.js
  packages/containers/src/Notification/pushNotification.js
  packages/containers/src/ObjectViewer/ObjectViewer.container.js
  packages/containers/src/SelectObject/SelectObject.connect.js
  packages/containers/src/SelectObject/SelectObject.container.js
  packages/containers/src/ShortcutManager/ShortcutManager.container.js
  packages/containers/src/SidePanel/SidePanel.connect.js
  packages/containers/src/SidePanel/SidePanel.container.js
  packages/containers/src/Slider/Slider.container.js
  packages/containers/src/TreeView/TreeView.container.js
  packages/containers/src/Typeahead/Typeahead.container.js
  packages/containers/src/actionAPI.js
  packages/containers/src/actionOnClick.js
  packages/containers/src/renderers.js
Labels: need review

#2865 fix(Containers): linter errors
  packages/containers/.eslintrc
  packages/containers/package.json
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
  packages/containers/src/ComponentForm/fields/MultiSelect/MultiSelect.component.js
  packages/containers/src/ConfirmDialog/ConfirmDialog.container.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/EditableText/EditableText.test.js
  packages/containers/src/Form/Form.container.js
  packages/containers/src/HomeListView/HomeListView.test.js
  packages/containers/src/List/selector.js
  packages/containers/src/TreeView/TreeView.container.js
  packages/containers/src/Typeahead/Typeahead.test.js
Labels: need review

#2855 feat(icons): delete-field.svg
  packages/icons/src/svg/processors/delete-field.svg
Labels: easy review, need review

#2856 feat(icons): concatenate.svg
  packages/icons/src/svg/processors/concatenate.svg
Labels: easy review, need review

#2866 fix(router): linter ci loops
  .travis/after_success_lint.sh
Labels: need review

#2867 chore: make eslint and demo works
  .gitignore
  .travis.yml
  .travis/after_success_lint.sh
  package.json
  packages/containers/package.json
  packages/forms/package.json
  packages/icons/package.json
  packages/icons/webpack.config.js
  packages/theme/babel.config.js
  packages/theme/package.json
  yarn.lock
Labels: need review

#2869 chore(faceted-search): use @talend/scripts
  packages/faceted-search/babel.config.js
  packages/faceted-search/package.json
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.test.js
  packages/faceted-search/src/components/BadgesGenerator/BadgesGenerator.component.test.js
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
  packages/faceted-search/talend-scripts.json
  packages/faceted-search/yarn.lock
Labels: need review

#2871 fix(components): Add support to some Avro data structure
  packages/components/src/DataViewer/RecordsViewer/Leaf/RecordsViewerLeaf.component.js
  packages/components/src/DataViewer/RecordsViewer/RecordsViewer.parser.js
  packages/components/src/DataViewer/RecordsViewer/RecordsViewer.parser.test.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
Labels: bug, easy review, need review

#2873 chore: clean remaining babel config
  babel.config.js
  packages/cmf-cqrs/babel.config.js
  packages/components/babel.config.js
  packages/containers/babel.config.js
  test-setup.js
Labels: easy review, need review
