Repository Talend/ui, pull requests merged in 2020-08, with the labels that each got.

#2923 feat(components/Enumeration): Support custom actions for Enumeration item
  output/components.eslint.txt
  packages/components/src/Enumeration/Enumeration.component.js
  packages/components/src/Enumeration/Enumeration.stories.js
  packages/components/src/Enumeration/Items/Items.component.js
Labels: need review

#2926 feat(components/list): use natural sort order
  output/components.eslint.txt
  packages/components/src/List/ListComposition/Manager/hooks/__snapshots__/useCollectionSort.hook.test.js.snap
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.js
  packages/components/src/List/ListComposition/Manager/hooks/useCollectionSort.hook.test.js
Labels: easy review, enhancement, need review

#2893 fix(forms/datalist): improve datalist async tests
  output/forms.eslint.txt
  packages/forms/src/UIForm/fields/Datalist/Datalist.component.test.js
Labels: easy review, enhancement, need review

#2928 feat(DeleteResource): pass a resource to the component
  packages/containers/src/DeleteResource/DeleteResource.connect.js
  packages/containers/src/DeleteResource/DeleteResource.container.js
  packages/containers/src/DeleteResource/DeleteResource.test.js
  packages/containers/src/DeleteResource/__snapshots__/DeleteResource.test.js.snap
  packages/containers/src/DeleteResource/sagas.js
Labels: enhancement, need review

#2931 fix(icons): remove sym links
  packages/icons/src/svg/core/local-storage.svg
  packages/icons/src/svg/files/file-connect-o.svg
Labels: bug, need review

#2922 fix(http): Fix import generator documentation
  packages/http/README.md
Labels: easy review, need review

#2934 feat(components/HeaderBar): Accept custom Intercom component
  output/components.eslint.txt
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.stories.js
  packages/components/src/HeaderBar/HeaderBar.test.js
Labels: need review
