Repository Talend/ui, pull requests merged in 2020-01, with the labels that each got.

#2598 fix(TFD-8758): Edit icon disappears when the artifact title is too long
  packages/components/src/EditableText/EditableText.scss
Labels: easy review, frontend, need review

#2600 chore(FacetedSearch): change some field, snake case to camel case
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.test.js
  packages/faceted-search/src/components/facetedSearch.propTypes.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: need review

#2599 fix(FacetedSearch): Change equal key operator to equals
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/dictionary/operator.dictionary.js
  packages/faceted-search/src/queryClient/tql.js
  packages/faceted-search/src/queryClient/tql.test.js
Labels: need review

#2583 feat(components/drawer): style
  npm-audit/audit.json
  output/components.sasslint.txt
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.scss
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/stories/Drawer.js
  packages/forms/src/FormSkeleton.js
  packages/forms/src/FormSkeleton.scss
  packages/forms/src/UIForm/UIForm.scss
  packages/forms/src/UIForm/fields/Button/Buttons.scss
  packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/stories-core/layouts.js
Labels: enhancement, need review

#2590 feat(FacetedSearch): Add label in add facet button
  npm-audit/audit.json
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeOperator/BadgeOperatorOverlay.component.js
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.js
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.test.js
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.scss
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
Labels: enhancement, frontend, need review

#2591 feat(FacetedSearch): Remove Header in AddFacetPopover
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/AddFacetPopover/__snapshots__/AddFacetPopver.component.test.js.snap
Labels: easy review, enhancement, frontend, need review

#2604 fix(faceted-search): Fix missing operators name changes
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js
  packages/faceted-search/src/dictionary/operator.dictionary.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: bug, frontend, need review

#2602 chore(FacetedSearch): release 0.2.5
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
Labels: need review

#2601 fix(components): align timezone-support version
  packages/components/package.json
  versions/dependencies.js
  yarn.lock
Labels: need review

#2606 feat(theme): avoid using css-modules
  packages/theme/src/theme/_visual-helpers.scss
Labels: easy review, need review

#2589 feat(icons):azure-dynamics
  packages/icons/src/svg/brands/azure-dynamics.svg
Labels: easy review, need review

#2610 fix(component): imports
  output/components.eslint.txt
  packages/components/src/AboutDialog/AboutDialog.component.js
  packages/components/src/ResourcePicker/ResourcePicker.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js
  packages/components/src/Table/Header/TableSortHeader.js
  packages/components/src/Toggle/Checkbox.js
  packages/components/src/Toggle/index.js
  packages/components/src/TreeView/TreeView.component.js
Labels: need review

#2613 feat(component/grid): allow to disable drag n drop
  packages/components/src/GridLayout/Grid.component.js
  packages/components/src/GridLayout/Grid.scss
  packages/components/stories/GridLayout.js
Labels: easy review, enhancement, need review

#2615 fix(components/grid): lint error
  output/components.eslint.txt
  packages/components/src/GridLayout/Grid.component.js
Labels: bug, easy review, frontend, need review

#2526 chore(FacetedSearch): Add documentation
  packages/faceted-search/README.md
  packages/faceted-search/src/components/AdvancedSearch/AdvancedSearch.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js
  packages/faceted-search/src/components/Badges/BadgeOverlay/BadgeOverlay.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js
  packages/faceted-search/src/components/README.md
  packages/faceted-search/src/hooks/README.md
Labels: need review

#2609 feat(icons): marketo.svg
  packages/icons/src/svg/brands/marketo.svg
Labels: easy review, need review

#2608 feat(icons): dataprep.svg
  packages/icons/src/svg/products/dataprep.svg
Labels: easy review, need review

#2616 chore: bump Storybook to 5.3.1
  npm-audit/audit.json
  npm-audit/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/faceted-search/package.json
  packages/forms/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  versions/dependencies.js
  yarn.lock
Labels: easy review, enhancement, need review

#2586 feat(components): review about modal style
  packages/components/src/AboutDialog/AboutDialog.component.js
  packages/components/src/AboutDialog/AboutDialog.scss
  packages/components/src/AboutDialog/AboutDialogTable.component.js
  packages/components/src/AboutDialog/__snapshots__/AboutDialog.snapshot.test.js.snap
  packages/components/src/translate.js
  packages/components/stories/AboutDialog.js
  packages/components/stories/config/i18n.js
Labels: need review

#2617 fix(FacetedSearch): overflow x and y, add facet popover
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.scss
  packages/faceted-search/src/components/AddFacetPopover/__snapshots__/AddFacetPopver.component.test.js.snap
  packages/faceted-search/src/components/FacetedSearch/FacetedSearch.component.js
  packages/faceted-search/stories/badgesDefinitions.story.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: need review

#2585 chore(i18n): TMC-19729 remove text transformations
  packages/components/src/ActionList/ActionList.scss
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/TimePicker/TimePicker.scss
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/HeaderTitle.scss
  packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.scss
  packages/components/src/Drawer/Drawer.scss
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/JSONSchemaRenderer/JSONSchemaRenderer.scss
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss
  packages/components/src/Notification/Notification.scss
  packages/components/src/Status/Status.scss
  packages/components/src/TreeView/TreeView.scss
  packages/components/src/Typeahead/Typeahead.scss
Labels: easy review, need review

#2576 fix(TCCUI-112): removing empty options when there's no placeholder
  packages/forms/src/UIForm/fields/Select/Select.component.js
  packages/forms/src/UIForm/fields/Select/__snapshots__/Select.component.test.js.snap
Labels: easy review, need review

#2582 feat(icons): classify, wrench, grouping, merge
  packages/icons/src/svg/core/classify.svg
  packages/icons/src/svg/core/grouping.svg
  packages/icons/src/svg/core/merge.svg
  packages/icons/src/svg/core/wrench.svg
Labels: easy review, need review

#2336 chore: correct link
  packages/cmf/src/cmfConnect.md
Labels: easy review

#2618 chore(FacetedSearch): release 0.2.6
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
Labels: need review

#2105 doc(ListComposition): developer guide
  packages/components/src/List/ListComposition/README.md
  packages/components/src/List/ListComposition/doc/developer-guide.md
  packages/components/src/List/ListComposition/doc/img/compound-set.gif
  packages/components/src/List/ListComposition/doc/img/controlled-set.gif
  packages/components/src/List/ListComposition/doc/img/jsx-to-schema.gif
  packages/components/src/List/ListComposition/doc/principle.md
Labels: frontend, need review

#2612 feat(components/Drawers): style
  output/components.sasslint.txt
  packages/components/.storybook/preview-head.html
  packages/components/src/ActionBar/ActionBar.scss
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/ActionButton.scss
  packages/components/src/Drawer/Drawer.component.js
  packages/components/src/Drawer/Drawer.scss
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.scss
  packages/components/src/List/Toolbar/SelectAll/SelectAll.scss
  packages/components/stories/Drawer.js
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/forms/src/FormSkeleton.js
  packages/forms/src/FormSkeleton.scss
  packages/forms/src/FormSkeleton.test.js
  packages/forms/src/FormSwitcher.js
  packages/forms/src/UIForm/UIForm.scss
  packages/forms/src/UIForm/fields/Button/Buttons.scss
  packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/stories-core/layouts.js
Labels: easy review, enhancement, need review

#2624 fix(components/virtualizedlist): horizontal scrollbar
  packages/components/src/VirtualizedList/RowLarge/RowLarge.scss
Labels: easy review, enhancement, need review

#2621 feat(cmf): customize sentry initialization
  packages/cmf/__tests__/onError.test.js
  packages/cmf/package.json
  packages/cmf/src/onError.js
  packages/cmf/src/onError.md
  versions/dependencies.js
  yarn.lock
Labels: enhancement, need review

#2627 fix: remove sidepanel uppercase
  packages/components/src/ActionList/ActionList.scss
Labels: easy review, need review

#2628 chore: upgrade babel
  npm-audit/package.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/faceted-search/package.json
  packages/forms/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/router/package.json
  packages/sagas/package.json
  packages/scripts/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
  versions/dependencies.js
  yarn.lock
Labels: easy review, need review

#2629 Revert "fix: remove sidepanel uppercase (#2627)"
  packages/components/src/ActionList/ActionList.scss
Labels: need review

#2630 fix(components/action): tooltip when action is disabled
  npm-audit/html-webpack-plugin.json
  packages/components/src/Actions/ActionButton/ActionButton.scss
  packages/components/stories/Action.js
Labels: bug, easy review, need review

#2633 feat(components): add label toggle component
  npm-audit/html-webpack-plugin.json
  packages/components/src/Toggle/LabelToggle/LabelToggle.component.js
  packages/components/src/Toggle/LabelToggle/LabelToggle.scss
  packages/components/src/Toggle/LabelToggle/LabelToggleComponent.test.js
  packages/components/src/Toggle/LabelToggle/index.js
  packages/components/src/Toggle/index.js
  packages/components/stories/Toggle.js
Labels: need review
