Repository Talend/ui, pull requests merged in 2020-02, with the labels that each got.

#2626 fix(components/objectviewer): long line break issue on safari/IE
  npm-audit/audit.json
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.scss
  packages/components/stories/ObjectViewer.js
Labels: frontend, need review

#2638 feat(faceted): use toggle for basic/advance button
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
  packages/faceted-search/src/components/AdvancedSearch/AdvancedSearch.scss
  packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
  packages/faceted-search/yarn.lock
Labels: need review

#2631 fix(faceted): remove selected values only
  npm-audit/audit.json
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.scss
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.js
  packages/faceted-search/yarn.lock
Labels: need review

#2636 TMDM-14362: Faceted Search - use input text for Badge text
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeTextForm.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeTextForm.component.test.js
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeTextForm.component.test.js.snap
Labels: easy review, enhancement, frontend, need review

#2639 TMDM-14355: Faceted-search - Update operators labels
  npm-audit/router.json
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/dictionary/operator.dictionary.js
Labels: easy review, enhancement, frontend, need review

#2640 feat(faceted): select operator if only one
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.test.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
Labels: need review

#2641 fix(faceted) : unknown operators should not throw
  npm-audit/router.json
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/dictionary/operator.dictionary.js
  packages/faceted-search/stories/badgesDefinitions.story.js
Labels: need review

#2642 chore(faceted): release 0.3.0
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.test.js
Labels: need review

#2643 feat(component/gridlayout): add footer
  packages/components/src/GridLayout/Tile/Footer/TileFooter.component.js
  packages/components/src/GridLayout/Tile/Footer/TileFooter.component.test.js
  packages/components/src/GridLayout/Tile/Footer/TileFooter.scss
  packages/components/src/GridLayout/Tile/Footer/__snapshots__/TileFooter.component.test.js.snap
  packages/components/src/GridLayout/Tile/Header/TileHeader.scss
  packages/components/src/GridLayout/Tile/Tile.component.js
  packages/components/src/GridLayout/Tile/index.js
  packages/components/stories/GridLayout.js
Labels: easy review, enhancement, frontend, need review

#2644 fix(TFD-9265/Components): converting timestamp to isoDate
  packages/cmf/src/sagas/index.md
  packages/components/src/ObjectViewer/JSONLike/JSONLike.component.js
  packages/components/src/ObjectViewer/JSONLike/JSONLike.test.js
  packages/components/src/ObjectViewer/ObjectViewer.component.js
  packages/components/src/ObjectViewer/ObjectViewer.test.js
Labels: frontend, need review

#2646 feat(DateTimeRangePicker): ability to set default time value
  output/components.eslint.txt
  packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.js
  packages/components/src/DateTimePickers/DateTime/Manager/Manager.component.test.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.component.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.component.test.js
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/__snapshots__/InputDateTimeRangePicker.component.test.js.snap
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js
  packages/components/stories/DatePicker.js
Labels: need review

#2648 feat(icons): cloudstorage
  packages/icons/src/svg/brands/cloudstorage.svg
Labels: easy review, need review

#2650 fix(tdc-3286): forms array validation
  packages/containers/sandbox/mockBackend/kit.js
  packages/containers/sandbox/mockBackend/mock/kit/example.json
  packages/containers/sandbox/src/app/ComponentFormSandbox.js
  packages/containers/sandbox/src/app/index.js
  packages/containers/sandbox/yarn.lock
  packages/forms/src/UIForm/utils/array.js
  packages/forms/src/UIForm/utils/validation.js
  packages/forms/src/UIForm/utils/validation.test.js
  packages/forms/stories-core/json/fieldsets/core-arrays.json
Labels: need review

#2651 feat(components/piechart): new sizes
  packages/components/src/PieChart/PieChartButton.test.js
  packages/components/src/PieChart/PieChartIcon.component.js
  packages/components/src/PieChart/PieChartIcon.test.js
  packages/components/src/PieChart/index.js
  packages/components/stories/PieChart.js
Labels: easy review, enhancement, frontend, need review

#2656 feat(containers/headerbar): don't open Apps in new browser tab
  packages/containers/src/HeaderBar/HeaderBar.sagas.js
  packages/containers/src/HeaderBar/HeaderBar.sagas.test.js
Labels: easy review, enhancement, need review

#2655 fix(ActionButton): Remove styles and span
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/ActionButton.scss
  packages/components/src/EditableText/EditableText.scss
  packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Labels: need review

#2657 fix(TFD-9265): convert date in sample view
  packages/components/src/ObjectViewer/ObjectViewer.component.js
  packages/components/src/ObjectViewer/ObjectViewer.test.js
  packages/components/src/ObjectViewer/convertDate.js
Labels: frontend, need review

#2652 feat(VirtualizedList): add CellLabel type
  packages/components/src/VirtualizedList/CellLabel/CellLabel.component.js
  packages/components/src/VirtualizedList/CellLabel/CellLabel.test.js
  packages/components/src/VirtualizedList/CellLabel/LabelColumn.component.js
  packages/components/src/VirtualizedList/CellLabel/__snapshots__/CellLabel.test.js.snap
  packages/components/src/VirtualizedList/CellLabel/index.js
  packages/components/src/VirtualizedList/index.js
  packages/components/src/VirtualizedList/utils/dictionary.js
  packages/components/stories/VirtualizedList.js
Labels: need review

#2649 feat(SubHeaderBar): add label display
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js
  packages/components/src/SubHeaderBar/TitleSubHeader/__snapshots__/TitleSubHeader.test.js.snap
  packages/components/stories/SubHeaderBar.js
Labels: need review

#2654 feat(TMC-20092): provide possibility to start router after specified action
  packages/router/src/index.js
Labels: need review

#2660 fix(ResourceList): i18n extraction
  npm-audit/audit.json
  packages/components/src/ResourceList/ResourceList.component.js
Labels: easy review, need review

#2661 feat: remove uppercase for fixed labels (#2627)
  output/components.sasslint.txt
  output/theme.sasslint.txt
  packages/components/src/ActionBar/ActionBar.scss
  packages/components/src/ActionList/ActionList.scss
  packages/components/src/CollapsiblePanel/CollapsiblePanel.scss
  packages/components/src/HttpError/HttpError.scss
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.scss
  packages/components/src/Table/TitleBar/TitleBar.scss
  packages/components/stories/GuidedTour.js
  packages/forms/src/UIForm/UIForm.scss
  packages/forms/src/UIForm/fieldsets/Array/DefaultArrayTemplate.scss
  packages/forms/src/deprecated/templates/ArrayFieldTemplate.scss
  packages/forms/stories-core/customDisplayMode.js
  packages/forms/stories-core/customErrors.js
  packages/forms/stories-core/customUpdating.js
  packages/forms/stories-core/json/fields/core-keyValue.json
  packages/forms/stories-core/json/fieldsets/core-arrays-complex.json
  packages/forms/stories-core/json/fieldsets/core-arrays-with-custom-options.json
  packages/forms/stories-core/json/fieldsets/core-arrays.json
  packages/theme/src/theme/_forms.scss
  packages/theme/src/theme/_navbar.dropdown.scss
  packages/theme/src/theme/_navbar.scss
  packages/theme/src/theme/_navs.scss
Labels: easy review, need review

#2653 feat(forms): add default title to collapsible
  output/forms.eslint.txt
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap
Labels: need review

#2662 fix(faceted-search): values open up at start
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: need review

#2671 fix(RichTooltip): the resourceList should take all the width
  packages/components/src/RichTooltip/RichLayout/RichLayout.scss
  packages/components/stories/RichTooltip.js
Labels: bug, easy review, need review

#2670 fix(SidePanel): fit content width
  output/components.eslint.txt
  packages/components/src/ActionList/ActionList.scss
  packages/components/src/Layout/TwoColumns/TwoColumns.scss
  packages/components/src/SidePanel/SidePanel.component.js
  packages/components/src/SidePanel/SidePanel.scss
  packages/components/src/SidePanel/SidePanel.test.js
  packages/components/stories/Layout.js
  packages/components/stories/SidePanel.js
Labels: frontend, need review

#2668 chore(i18n): language switcher and @talend locales for Storybook
  .storybook/i18n.js
  npm-audit/audit.json
  output/components.eslint.txt
  packages/components/.storybook/addons.js
  packages/components/.storybook/config.js
  packages/components/package.json
  packages/components/src/FilterBar/FilterBar.component.js
  packages/components/src/FilterBar/__snapshots__/FilterBar.snapshot.test.js.snap
  packages/components/src/List/ListComposition/TextFilter/__snapshots__/TextFilter.component.test.js.snap
  packages/components/stories/AboutDialog.js
  packages/components/stories/Enumeration.js
  packages/components/stories/GuidedTour.js
  packages/components/stories/HeaderBar.js
  packages/components/stories/List.js
  packages/components/stories/ListView.js
  packages/components/stories/SidePanel.js
  packages/components/stories/config/i18n.js
  packages/containers/.storybook/addons.js
  packages/containers/.storybook/config.js
  packages/containers/examples/ExampleDeleteResource.js
  packages/containers/examples/ExampleList.js
  packages/containers/examples/config/i18n.js
  packages/containers/package.json
  packages/datagrid/.storybook/addons.js
  packages/datagrid/.storybook/config.js
  packages/datagrid/package.json
  packages/datagrid/stories/config/i18n.js
  packages/datagrid/stories/datagrid.component.js
  packages/datagrid/stories/datagrid.container.js
  packages/faceted-search/yarn.lock
  packages/forms/.storybook/addons.js
  packages/forms/.storybook/config.js
  packages/forms/package.json
  packages/forms/stories/config/i18n.js
  yarn.lock
Labels: breaking change, easy review, enhancement, need review
