Repository Talend/ui, pull requests merged in 2020-04, with the labels that each got.

#2717 feat(GuidedTour): send event when the guided tour is closed
  packages/containers/src/GuidedTour/GuidedTour.container.js
Labels: bug, need review

#2716 fix(components): scrollbar in sidepanel
  packages/components/src/SidePanel/SidePanel.scss
Labels: easy review, need review

#2725 fix(faceted): ignore unknown badges types
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/dictionary/badge.dictionary.js
  packages/faceted-search/src/dictionary/badge.dictionary.test.js
  packages/faceted-search/stories/badgesDefinitions.story.js
  packages/faceted-search/stories/facetedSearch.story.js
Labels: need review

#2727 feat(icons):datasets.svg
  packages/icons/src/svg/core/datasets.svg
Labels: easy review, need review

#2726 feat(icons):semantic.svg
  packages/icons/src/svg/core/semantic.svg
Labels: easy review, need review

#2728 fix(sidepanel): incorrect docked width
  packages/components/src/SidePanel/SidePanel.scss
Labels: easy review, need review

#2729 feat(components/stepper): allow empty children
  npm-audit/audit.json
  packages/components/src/Stepper/Stepper.component.js
  packages/components/src/Stepper/Stepper.component.test.js
  packages/components/src/Stepper/Stepper.stories.js
  packages/components/src/Stepper/__snapshots__/Stepper.component.test.js.snap
Labels: easy review, enhancement, need review

#2722 chore(prettier): update to prettier 2
  .prettierrc
  .travis.yml
  npm-audit/package.json
  versions/dependencies.js
Labels: need review

#2732 feat(TDC-3798): Implement containsIgnoreCase operator
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/dictionary/operator.dictionary.js
  packages/faceted-search/src/queryClient/tql.js
  packages/faceted-search/src/queryClient/tql.test.js
  packages/faceted-search/stories/badgesDefinitions.story.js
Labels: easy review, enhancement, need review

#2735 fix: proptypes issues
  npm-audit/audit.json
  packages/components/src/GuidedTour/GuidedTour.component.js
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.component.js
  packages/components/src/PieChart/PieChart.component.js
  packages/components/src/PieChart/PieChartIcon.component.js
  packages/components/src/PieChart/__snapshots__/PieChart.test.js.snap
  packages/components/src/Slider/Slider.component.js
  packages/containers/src/GuidedTour/GuidedTour.container.js
Labels: need review

#2743 fix(cmf): rollback some exports for router
  npm-audit/audit.json
  packages/cmf/src/cmfModule.merge.js
Labels: bug, need review

#2745 chore(audit): temporary disable the CI job
  .travis.yml
  .travis/after_success_git.sh
Labels: help wanted, need review

#2741 fix(datalist): dropdown click and item data-feature
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/Typeahead.test.js
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Labels: need review

#2734 feat(TDC-3798): Expose helpers to filter badgeDefinitions operator
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/dictionary/helpers.dictionary.js
  packages/faceted-search/src/dictionary/helpers.dictionary.test.js
  packages/faceted-search/src/dictionary/operator.dictionary.js
  packages/faceted-search/src/index.js
Labels: enhancement, frontend, need review

#2746 feat: rebranding
  output/cmf.eslint.txt
  output/components.eslint.txt
  packages/components/src/AppLoader/AppLoader.stories.js
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/HeaderBar/HeaderBar.stories.js
  packages/components/src/HeaderBar/HeaderBar.test.js
  packages/icons/src/svg/products/logo-colored.svg
  packages/icons/src/svg/products/logo-square.svg
  packages/icons/src/svg/products/logo.svg
  packages/theme/src/theme/_navbar.scss
Labels: easy review, enhancement, need review

#2750 fix: Storybook on IE11
  .storybook/i18n.js
  .storybook/sortStories.js
Labels: easy review, enhancement, need review

#2749 fix(components/headerbar): style
  output/components.eslint.txt
  packages/components/src/HeaderBar/HeaderBar.component.js
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/components/src/HeaderBar/HeaderBar.stories.js
  packages/components/src/HeaderBar/HeaderBar.test.js
Labels: need review

#2753 fix(components/datalist): onBlur is called before onClick
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Labels: easy review, enhancement, need review

#2751 fix: root libs security
  .travis/after_success_screenshots.sh
  package.json
  packages/components/package.json
  packages/theme/package.json
  packages/theme/test/screenshots.phantomcss.js
  packages/theme/test/screenshots.slimerjs.js
  screenshots.js
  screenshots.md
  screenshots/components-aboutdialog.json
  screenshots/components-actionlist.json
  screenshots/components-actions.json
  screenshots/components-badge.json
  screenshots/components-breadcrumbs.json
  screenshots/components-checkbox.json
  screenshots/components-collapsiblepanel.json
  screenshots/components-confirmdialog.json
  screenshots/components-drawer.json
  screenshots/components-editabletext.json
  screenshots/components-listview.json
  screenshots/components-richtooltip.json
  screenshots/components-sidepanel.json
  screenshots/components-subheader.json
  screenshots/components-tabbar.json
  screenshots/components-virtualized-list.json
  screenshots/forms-core-concepts.json
  screenshots/forms-core-fields.json
  screenshots/forms-core-fieldsets.json
  screenshots/theme.json
  versions/dependencies.js
  yarn.lock
Labels: frontend, need review

#2756 fix(cmf): dependencies vulnerabilities
  package.json
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/package.json
  packages/cmf/scripts/cmf-settings.i18n.js
  packages/cmf/src/cmfConnect.js
  packages/cmf/website/pages/en/index.js
  packages/cmf/website/yarn.lock
  yarn.lock
Labels: need review

#2757 fix: dependencies vulnerabilities
  package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/faceted-search/package.json
  packages/forms/package.json
  packages/scripts/package.json
  packages/stepper/package.json
  packages/theme/package.json
  yarn.lock
Labels: need review

#2760 TDC-3820: Pass props data-feature in BadgeDelete
  packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.js
  packages/components/src/Badge/BadgeComposition/BadgeDelete/BadgeDelete.component.test.js
Labels: easy review, enhancement, need review

#2762 feat(theme): update regal-blue value
  packages/theme/src/theme/_colors.scss
Labels: easy review, need review

#2763 fix(tests): jsdom - acorn vulnerability
  output/components.eslint.txt
  packages/components/package.json
  packages/components/src/Drawer/Drawer.component.js
  packages/datagrid/package.json
  packages/faceted-search/package.json
  packages/stepper/package.json
  yarn.lock
Labels: easy review, need review

#2765 fix(icons): dependencies vulnerabilities
  packages/icons/package.json
  packages/theme/package.json
  yarn.lock
Labels: need review

#2761 feat(components/gridlayout): authorize to override columns and breakpoints props
  output/components.eslint.txt
  packages/components/src/GridLayout/Grid.component.js
Labels: easy review, enhancement, need review

#2769 chore: build clean dist folder and ignore tests/stories
  package.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/faceted-search/package.json
  packages/faceted-search/yarn.lock
  packages/forms/package.json
  packages/icons/package.json
  packages/router/package.json
  packages/router/yarn.lock
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
  yarn.lock
Labels: need review

#2768 fix: replace cpx by cpx2 to fix vulnerability
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/faceted-search/package.json
  packages/forms/package.json
  packages/scripts/package.json
  packages/stepper/package.json
  yarn.lock
Labels: easy review, need review

#2771 fix: sass-loader transitive vulnerability
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/faceted-search/package.json
  packages/forms/package.json
  packages/scripts/package.json
  packages/stepper/package.json
  packages/theme/package.json
  yarn.lock
Labels: easy review, need review

#2773 fix(router): dependencies vulnerabilities
  packages/router/package.json
  packages/router/yarn.lock
Labels: need review

#2775 chore(html-webpack-plugin): use @talend/scripts
  packages/html-webpack-plugin/.eslintrc
  packages/html-webpack-plugin/index.test.js
  packages/html-webpack-plugin/jest.config.js
  packages/html-webpack-plugin/package.json
  packages/html-webpack-plugin/talend-scripts.json
  packages/html-webpack-plugin/yarn.lock
Labels: easy review, need review

#2772 fix(Stepper): link to common yarn.lock
  packages/stepper/yarn.lock
Labels: easy review, need review

#2776 feat(theme): rebranding colors
  packages/theme/src/theme/_colors.scss
Labels: easy review, need review

#2777 chore(router): use @talend/scripts
  .eslintrc
  packages/html-webpack-plugin/package.json
  packages/html-webpack-plugin/yarn.lock
  packages/router/.eslintrc
  packages/router/babel.config.js
  packages/router/package.json
  packages/router/src/route.js
  packages/router/src/sagas/documentTitle.test.js
  packages/router/talend-scripts.json
  packages/router/test-setup.js
  packages/router/yarn.lock
Labels: need review

#2767 feat(icons): warning.svg; check-circle.svg; info-circle.svg
  packages/icons/src/svg/core/check-circle.svg
  packages/icons/src/svg/core/info-circle.svg
  packages/icons/src/svg/core/warning.svg
Labels: easy review, need review

#2766 feat(icons): cross-circle.svg
  packages/icons/src/svg/core/cross-circle.svg
Labels: easy review, need review

#2754 feat(icons):variable.svg
  packages/icons/src/svg/core/variable.svg
Labels: easy review, need review

#2752 feat(icons): comment.svg
  packages/icons/src/svg/core/comment.svg
Labels: easy review, need review

#2779 chore(cmf): use @talend/scripts
  packages/cmf-cqrs/package.json
  packages/cmf/babel.config.js
  packages/cmf/jest.config.js
  packages/cmf/package.json
  packages/cmf/talend-scripts.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/faceted-search/package.json
  packages/forms/package.json
  packages/local-libs-webpack-plugin/package.json
  packages/sagas/package.json
  packages/scripts/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  test-setup.js
  yarn.lock
Labels: need review

#2759 feat(faceted-search): Add some data-feature for Pendo / e2e tests
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/AdvancedSearch/AdvancedSearch.component.js
  packages/faceted-search/src/components/AdvancedSearch/__snapshots__/AdvancedSearch.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.js
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.test.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumberForm.component.js
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumberForm.component.test.js
  packages/faceted-search/src/components/Badges/BadgeNumber/__snapshots__/BadgeNumberForm.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeTextForm.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeTextForm.component.test.js
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeTextForm.component.test.js.snap
  packages/faceted-search/src/components/FacetedSearchIcon/FacetedSearchIcon.component.js
  packages/faceted-search/src/components/FacetedSearchIcon/__snapshots__/FacetedSearchIcon.component.test.js.snap
  packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
  packages/faceted-search/src/constants.js
  packages/faceted-search/src/helpers/usage.helpers.js
  packages/faceted-search/src/helpers/usage.helpers.test.js
Labels: enhancement, frontend, need review

#2780 chore(cmf-cqrs): use @talend/scripts
  .eslintrc
  packages/cmf-cqrs/package.json
  packages/cmf-cqrs/src/components/ACKDispatcher/ACKDispatcher.container.js
  packages/cmf-cqrs/src/index.test.js
  packages/cmf-cqrs/src/middleware/__snapshots__/socketMiddleware.test.js.snap
  packages/cmf-cqrs/src/middleware/socketMiddleware.test.js
  packages/cmf-cqrs/src/reducers/ack.js
  packages/cmf-cqrs/talend-scripts.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/src/Dispatcher.js
  packages/cmf/src/Inject.component.js
  packages/cmf/src/RegistryProvider.js
  packages/cmf/src/action.js
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/cmfModule.js
  packages/cmf/src/cmfModule.merge.js
  packages/cmf/src/componentState.js
  packages/cmf/src/components/ErrorPanel/ErrorPanel.component.js
  packages/cmf/src/components/ErrorPanel/index.js
  packages/cmf/src/deprecated.js
  packages/cmf/src/expression.js
  packages/cmf/src/index.js
  packages/cmf/src/middlewares/http/middleware.js
  packages/cmf/src/mock/provider.js
  packages/cmf/src/onEvent.js
  packages/cmf/src/reducers/settingsReducers.js
  packages/cmf/src/registry.js
  packages/cmf/src/store.js
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/faceted-search/package.json
  packages/forms/package.json
  packages/icons/package.json
  packages/local-libs-webpack-plugin/package.json
  packages/sagas/package.json
  packages/scripts/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  yarn.lock
Labels: need review

#2781 feat(icons): eye.svg
  packages/icons/src/svg/core/eye.svg
Labels: easy review, need review

#2783 chore(components): use @talend/scripts for build
  packages/components/.eslintrc
  packages/components/package.json
  packages/components/talend-scripts.json
Labels: need review

#2785 fix(guided-tour): no opacity on background
  packages/components/src/GuidedTour/GuidedTour.component.js
Labels: bug, easy review, need review

#2786 fix(sidepanel): double tooltip
  packages/components/src/ActionList/ActionList.component.js
Labels: bug, easy review, need review

#2784 chore(containers): use @talend/scripts for build
  packages/components/package.json
  packages/components/test/styleMock.js
  packages/containers/package.json
  packages/containers/talend-scripts.json
  packages/containers/test/styleMock.js
  packages/datagrid/package.json
  packages/forms/package.json
  test-setup.js
  yarn.lock
Labels: need review

#2787 chore(datagrid): use @talend/scripts for build
  packages/datagrid/.eslintrc
  packages/datagrid/babel.config.js
  packages/datagrid/package.json
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/src/components/datagrid.component.stories.js
  packages/datagrid/src/containers/DataGrid/DataGrid.container.js
  packages/datagrid/src/containers/datagrid.container.stories.js
  packages/datagrid/talend-scripts.json
  packages/datagrid/test/styleMock.js
Labels: need review

#2764 fix(GuidedTour): add loading message
  packages/components/src/AppGuidedTour/AppGuidedTour.component.js
  packages/components/src/AppGuidedTour/AppGuidedTour.test.js
  packages/components/src/AppGuidedTour/DemoContentStep.component.js
  packages/components/src/AppGuidedTour/DemoContentStep.component.test.js
  packages/components/src/AppGuidedTour/DemoContentStep.scss
  packages/components/src/AppGuidedTour/__snapshots__/DemoContentStep.component.test.js.snap
Labels: bug, need review

#2788 feat(forms): use @talend/scripts for build
  packages/forms/babel.config.js
  packages/forms/package.json
  packages/forms/talend-scripts.json
  yarn.lock
Labels: need review

#2789 feat(icons): use @talend/scripts
  packages/icons/package.json
  packages/icons/scripts/react.js
  yarn.lock
Labels: need review

#2790 feat(sagas): use @talend/scripts
  packages/sagas/.eslintrc
  packages/sagas/babel.config.js
  packages/sagas/package.json
  packages/sagas/talend-scripts.json
Labels: need review

#2774 feat(TFD-10234): Add optionnal display of types
  packages/components/src/DataViewer/ModelViewer/Branch/__snapshots__/ModelViewerBranch.test.js.snap
  packages/components/src/DataViewer/ModelViewer/Leaf/__snapshots__/ModelViewerLeaf.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/Leaf/RecordsViewerLeaf.component.js
  packages/components/src/DataViewer/RecordsViewer/Leaf/__snapshots__/RecordsViewerLeaf.test.js.snap
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.scss
Labels: easy review, need review

#2605 feat: update ag-grid to 22.1
  npm-audit/audit.json
  output/datagrid.eslint.txt
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.js
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.test.js
  packages/datagrid/stories/DynamicDataGrid.component.js
  packages/datagrid/stories/sample3.json
  yarn.lock
Labels: enhancement, need review

#2791 chore(stepper): use @talend/scripts
  packages/stepper/babel.config.js
  packages/stepper/package.json
  packages/stepper/talend-scripts.json
  packages/stepper/test/styleMock.js
  yarn.lock
Labels: need review

#2792 chore(storybook-cmf): use @talend/scripts
  packages/storybook-cmf/babel.config.js
  packages/storybook-cmf/package.json
  packages/storybook-cmf/talend-scripts.json
Labels: need review

#2798 chore(datagrid): lint errors
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DefaultCellRenderer/FormatValue.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
  packages/datagrid/src/components/datagrid.component.stories.js
  packages/datagrid/src/containers/datagrid.container.stories.js
  yarn.lock
Labels: need review

#2793 TDC-2949: Add a clear button to remove all badges in faceted-search
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.test.js
  packages/faceted-search/src/components/BasicSearch/BasicSearch.scss
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
  packages/faceted-search/src/constants.js
  packages/faceted-search/src/hooks/facetedBadges.hook.js
Labels: enhancement, need review

#2801 fix(TDC-3820): Fix somes user tracking in faceted-search
  packages/faceted-search/CHANGELOG.md
  packages/faceted-search/package.json
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxes.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/BadgeFaceted.component.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeNumber/BadgeNumber.component.js
  packages/faceted-search/src/components/Badges/BadgeText/BadgeText.component.js
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
  packages/faceted-search/stories/badgesDefinitions.story.js
  packages/faceted-search/stories/facetedSearch.story.js
  packages/faceted-search/yarn.lock
Labels: bug, need review

#2803 feat(List): Boolean Cell with Icon
  output/components.eslint.txt
  packages/components/src/List/ListComposition/ListComposition.stories.js
  packages/components/src/VirtualizedList/CellBoolean/BooleanColumn.component.js
  packages/components/src/VirtualizedList/CellBoolean/CellBoolean.component.js
  packages/components/src/VirtualizedList/CellBoolean/CellBoolean.scss
  packages/components/src/VirtualizedList/CellBoolean/CellBoolean.test.js
  packages/components/src/VirtualizedList/CellBoolean/__snapshots__/CellBoolean.test.js.snap
Labels: easy review, need review

#2806 feat(List): add IconTextCell column
  packages/components/src/List/ListComposition/ListComposition.stories.js
  packages/components/src/List/ListComposition/collection.js
  packages/components/src/VirtualizedList/CellIconText/CellIconText.component.js
  packages/components/src/VirtualizedList/CellIconText/CellIconText.scss
  packages/components/src/VirtualizedList/CellIconText/CellIconText.test.js
  packages/components/src/VirtualizedList/CellIconText/IconTextColumn.component.js
  packages/components/src/VirtualizedList/CellIconText/__snapshots__/CellIconText.test.js.snap
  packages/components/src/VirtualizedList/CellIconText/index.js
  packages/components/src/VirtualizedList/index.js
Labels: need review
