Repository Talend/ui, pull requests merged in 2021-03, with the labels that each got.

#3239 chore(Storybook): use latest icons
  packages/components/.storybook/config.js
  packages/containers/.storybook/config.js
  packages/forms/.storybook/config.js
  packages/stepper/.storybook/config.js
Labels: easy review, enhancement, need review

#3241 chore(Surge): remove faceted search links
  .surge/index.html
Labels: easy review, enhancement, need review

#3242 fix(components/SubHeaderBar): icon style ponderation
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
Labels: bug, easy review, need review

#3246 fix(icons): grayscale filter
  packages/components/src/VirtualizedList/CellTitle/CellTitle.scss
  packages/icons/scripts/docs.js
  packages/icons/src/filters/grayscale.svg
Labels: bug, need review

#3249 chore: upgrade deps
  output/components.eslint.txt
  yarn.lock
Labels: need review

#3251 chore(theme): Webpack 5
  .travis/after_success_demo.sh
  packages/theme/.npmignore
  packages/theme/example/index.html
  packages/theme/package.json
  packages/theme/webpack.config.js
  yarn.lock
Labels: easy review, enhancement, need review

#3254 chore(theme): theme folder output for demo
  .travis/after_success_demo.sh
Labels: easy review, need review

#3259 fix(dataviz): deps manifest
  packages/dataviz/CHANGELOG.md
  packages/dataviz/package.json
  packages/dataviz/yarn.lock
Labels: need review
