Repository Talend/ui, pull requests merged in 2021-12, with the labels that each got.

#3526 fix(GeoChart): remove the use of ?? which break karma
  .changeset/hot-terms-buy.md
  packages/dataviz/src/components/GeoChart/GeoChart.component.tsx
Labels: bug, need review, easy review

#3470 chore(dataviz&components): major upgrade recharts 2
  .changeset/little-carpets-stare.md
  .github/workflows/before-surge.sh
  .github/workflows/lerna-ci.yml
  packages/components/package.json
  packages/components/src/RadarChart/__snapshots__/RadarChart.test.js.snap
  packages/dataviz/.eslintrc
  packages/dataviz/package.json
  packages/dataviz/src/components/BarChart/ColoredBar/ColoredBar.component.tsx
  packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.scss
  packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.test.tsx
  packages/dataviz/src/components/BarChart/HorizontalBarChart/HorizontalBarChart.component.tsx
  packages/dataviz/src/components/BarChart/TooltipCursor/TooltipCursor.component.tsx
  packages/dataviz/src/components/BarChart/VerticalBarChart/VerticalBarChart.component.scss
  packages/dataviz/src/components/BarChart/VerticalBarChart/VerticalBarChart.component.tsx
  packages/dataviz/src/components/BarChart/_bar-chart.scss
  packages/dataviz/src/components/BarChart/useBarChart.hook.tsx
  packages/dataviz/src/components/GeoChart/GeoChart.scss
  versions/dependencies.json
  yarn.lock
Labels: need review

#3533 fix(InlineEditing): enter key should not submit in multiline mode
  .changeset/early-cooks-collect.md
  packages/design-system/src/components/InlineEditing/InlineEditing.spec.tsx
  packages/design-system/src/components/InlineEditing/InlineEditing.tsx
Labels: bug, need review, easy review

#3540 fix(TDOPS-1376/components/dataviz): recharts path in dependencies.json
  .changeset/healthy-carrots-stare.md
  yarn.lock
Labels: need review

#3529 chore(design-system/ADR): CSS modules
  packages/design-system/adr/css-modules.md
Labels: architecture decision record

#3535 chore(design-system): components testing gh action
  .github/workflows/components-testing.yml
Labels: enhancement, easy review

#3541 feat(InlineEditing): add placeholder support
  .changeset/thirty-roses-cheer.md
  packages/design-system/src/components/InlineEditing/InlineEditing.stories.mdx
  packages/design-system/src/components/InlineEditing/InlineEditing.stories.tsx
  packages/design-system/src/components/InlineEditing/InlineEditing.style.ts
  packages/design-system/src/components/InlineEditing/InlineEditing.tsx
Labels: enhancement, need review, easy review

#3546 chore(design-system): deploy gh action
  .github/workflows/design-system-deploy.yml
  packages/design-system/README.md
Labels: enhancement, need review, easy review

#3545 chore(design-system): Contribution guidelines
  packages/design-system/CONTRIBUTING.md
  packages/design-system/DOCTEMPLATE.md
  packages/design-system/README.md
Labels: need review, easy review

#3536 feat(design-tokens): dedicated package
  .changeset/empty-taxis-beam.md
  .github/workflows/before-surge.sh
  .github/workflows/design-tokens.yml
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/design-system/package.json
  packages/design-tokens/.npmignore
  packages/design-tokens/.storybook/main.js
  packages/design-tokens/.storybook/preview.js
  packages/design-tokens/README.md
  packages/design-tokens/dependencies.json
  packages/design-tokens/package.json
  packages/design-tokens/scripts/compare.js
  packages/design-tokens/src/Welcome.stories.mdx
  packages/design-tokens/src/_tokens.scss
  packages/design-tokens/src/dark/_index.scss
  packages/design-tokens/src/dark/dictionary.ts
  packages/design-tokens/src/dark/index.ts
  packages/design-tokens/src/index.scss
  packages/design-tokens/src/index.ts
  packages/design-tokens/src/light/_index.scss
  packages/design-tokens/src/light/dictionary.ts
  packages/design-tokens/src/light/index.ts
  packages/design-tokens/talend-scripts.json
  packages/design-tokens/tsconfig.json
  packages/design-tokens/webpack.config.js
  packages/design-tokens/yarn.lock
  packages/faceted-search/package.json
  packages/forms/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  yarn.lock
Labels: enhancement, easy review

#3560 chore(design-tokens): exclude Storybook stuff from NPM package
  .changeset/short-cheetahs-drive.md
  packages/design-tokens/.npmignore
Labels: enhancement, need review, easy review

#3556 fix(ARCH-395/containers/Redirect): dispatch in effect
  .changeset/fluffy-kangaroos-study.md
  packages/containers/src/Redirect/Redirect.container.js
  packages/containers/src/Redirect/Redirect.test.js
  packages/containers/src/Redirect/__snapshots__/Redirect.test.js.snap
Labels: need review

#3573 chore(ADR): Added ADR on using closed component APIs or composition
  packages/design-system/adr/composition-vs-api.md
Labels: easy review, architecture decision record

#3583 fix(design-system/buttons): default cursor for busy buttons
  .changeset/green-swans-lick.md
  packages/design-system/src/components/Button/variations/Button.base.tsx
Labels: bug, enhancement, need review, easy review

#3582 feat(utils/date): format date in specified locale
  .changeset/mighty-colts-clap.md
  packages/utils/src/date/date.test.ts
  packages/utils/src/date/index.ts
Labels: enhancement, need review, easy review

#3554 feat(TDP-10570): Increaser Layout header z-index
  packages/components/src/Layout/Layout.scss
Labels: need review

#3587 fix(design-system): i18n
  .changeset/grumpy-ears-wonder.md
  packages/design-system/src/components/Form/Field/Input/Input.Copy.tsx
  packages/design-system/src/components/Form/Field/Input/Input.File.tsx
  packages/design-system/src/components/HeaderBar/HeaderBar.tsx
  packages/design-system/src/components/Layout/Footer.tsx
  packages/design-system/src/components/Layout/SkipLinks/SkipLinks.tsx
  packages/design-system/src/components/Menu/Menu.tsx
  packages/design-system/src/components/Modal/Modal.tsx
  packages/design-system/src/components/ThemeProvider/ThemeSwitcher/ThemeSwitcher.tsx
Labels: enhancement, need review, easy review

#3512 chore(http): requests status
  .changeset/cool-items-boil.md
  packages/http/src/async.js
  packages/http/src/http.constants.js
  size.json
Labels: need review
