Repository Talend/ui, pull requests merged in 2021-07, with the labels that each got.

#3361 chore(List/CellLabel): specify bstyle for cellLabel
  packages/components/src/List/ListComposition.stories.js
  packages/components/src/List/ListComposition/collection.js
  packages/components/src/VirtualizedList/CellLabel/CellLabel.component.js
  packages/components/src/VirtualizedList/CellLabel/CellLabel.test.js
  packages/components/src/VirtualizedList/CellLabel/__snapshots__/CellLabel.test.js.snap
  packages/components/src/VirtualizedList/VirtualizedList.stories.js
Labels: easy review, need review

#3365 fix(theme): hover disabled buttons
  packages/components/src/Actions/ActionButton/Button.stories.js
  packages/theme/src/theme/_buttons.scss
  packages/theme/src/theme/_visual-helpers.scss
Labels: bug, easy review, need review

#3356 chore(CI): fix eslint and stylelint, add github annotation
  .github/workflows/dataviz-ci.yml
  .github/workflows/lerna-ci.yml
  .github/workflows/lerna-lint.yml
  .gitignore
  babel.config.js
  merge-report.js
  output/cmf.eslint.txt
  output/components.eslint.txt
  output/components.sasslint.txt
  output/containers.eslint.txt
  output/datagrid.eslint.txt
  output/forms.sasslint.txt
  output/theme.sasslint.txt
  package.json
  packages/cmf-cqrs/.babelrc.json
  packages/cmf-cqrs/package.json
  packages/cmf-router/.babelrc.json
  packages/cmf-router/package.json
  packages/cmf-webpack-plugin/.babelrc.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/.babelrc.json
  packages/cmf/package.json
  packages/components/.babelrc.json
  packages/components/package.json
  packages/containers/.babelrc.json
  packages/containers/package.json
  packages/datagrid/.babelrc.json
  packages/datagrid/package.json
  packages/dataviz/.babelrc.json
  packages/dataviz/package.json
  packages/dataviz/src/components/TooltipContent/__snapshots__/TooltipContent.component.test.tsx.snap
  packages/dataviz/tsconfig.json
  packages/dataviz/yarn.lock
  packages/forms/.babelrc.json
  packages/forms/.eslintrc
  packages/forms/package.json
  packages/generator/generators/app/index.js
  packages/generator/generators/create-cell/index.js
  packages/generator/generators/react-cmf/index.js
  packages/generator/package.json
  packages/http/package.json
  packages/icons/package.json
  packages/sagas/.babelrc.json
  packages/sagas/package.json
  packages/stepper/.babelrc.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
  packages/utils/package.json
  yarn.lock
Labels: need review

#3367 feat(TCCUI-213/List): add custom tooltips to Virtualized list cells
  packages/components/src/List/ListComposition.stories.js
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js
  packages/components/src/VirtualizedList/CellDatetime/__snapshots__/CellDatetime.test.js.snap
  packages/components/src/VirtualizedList/CellIconText/CellIconText.component.js
  packages/components/src/VirtualizedList/CellIconText/CellIconText.test.js
  packages/components/src/VirtualizedList/CellIconText/__snapshots__/CellIconText.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleSelector.test.js.snap
  packages/components/src/VirtualizedList/Content.component.js
Labels: need review

#3369 chore: release 6.33.0
  lerna.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
Labels: need review

#3366 feat(TDOPS-14/TreeView): added ability to pass className for a TreeViewItem
  packages/components/src/TreeView/FolderTreeView.stories.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.component.js
  packages/components/src/TreeView/TreeViewItem/TreeViewItem.test.js
Labels: easy review, enhancement, need review
