Repository Talend/ui, pull requests merged in 2021-08, with the labels that each got.

#3373 chore(deps): bump @talend deps
  yarn.lock
Labels: dependencies, need review

#3376 feat(theme): add $pale-cyan and its shades
  packages/theme/src/theme/_colors.scss
Labels: easy review, need review

#3388 chore(actions): enable manual security scan
  .github/workflows/security-scan.yml
Labels: need review

#3394 chore: set security scan prod mode
  .github/workflows/security-scan.yml
Labels: need review

#3397 chore(theme): add yarn.lock for secu scan
  packages/theme/yarn.lock
Labels: need review

#3401 chore: init changelog using changeset
  .changeset/blue-rings-fetch.md
  .changeset/fair-dodos-remain.md
  .changeset/flat-planes-help.md
  .changeset/new-mangos-smell.md
  .changeset/real-mayflies-fetch.md
Labels: need review

#3317 feat(ARCH-343/CMF): remove sentry dependency
  .changeset/soft-waves-occur.md
  packages/cmf/__tests__/onError.test.js
  packages/cmf/package.json
  packages/cmf/src/onError.js
  packages/cmf/src/onError.md
  yarn.lock
Labels: need review

#3402 chore: restore security scan cron
  .github/workflows/security-scan.yml
Labels: need review

#3406 chore: fix test:demo script
  .github/workflows/pr-demo.yml
  workspace-run.js
Labels: need review

#3404 fix(theme): update to remove deprecation warning
  .changeset/polite-lizards-film.md
  packages/theme/package.json
  packages/theme/src/theme/_dropdowns.scss
  packages/theme/src/theme/_guidelines.scss
  packages/theme/src/theme/_navs.scss
  packages/theme/src/theme/_variables.scss
  packages/theme/src/theme/theme.scss
  packages/theme/webpack.config.js
  yarn.lock
Labels: need review

#3409 chore: remove prepublishOnly script
  .github/workflows/changeset.yml
  .github/workflows/lerna-ci.yml
  .github/workflows/pr-demo.yml
  package.json
  packages/cmf-cqrs/package.json
  packages/cmf-router/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/eslint-config/package.json
  packages/forms/package.json
  packages/http/package.json
  packages/icons/package.json
  packages/jsfc/package.json
  packages/local-libs-webpack-plugin/package.json
  packages/router-bridge/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
  packages/utils/package.json
  workspace-run.js
Labels: need review
