Repository Talend/ui, pull requests merged in 2021-01, with the labels that each got.

#3150 fix(EnumerationWidget): focus input on validate add when not connected
  packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
Labels: easy review, need review

#3128 feat(cmf): add http error attributes from RFC 7807
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
Labels: need review

#3151 chore: release 6.7.0
  lerna.json
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/forms/package.json
  packages/generator/package.json
  packages/icons/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
Labels: need review

#3153 fix(TDS-5773/Enumeration): msgs placement and behavior
  packages/components/src/Enumeration/Enumeration.scss
  packages/components/src/Enumeration/Items/Item/Item.scss
  packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
Labels: need review

#3154 fix(Collapsible): tooltip only when label is there for element
  output/components.eslint.txt
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.stories.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.test.js
Labels: easy review, need review

#3140 feat(TDP-9660) : Add menu dropdown on quality bar component
  output/components.eslint.txt
  packages/components/src/QualityBar/QualityBar.component.js
  packages/components/src/QualityBar/QualityBar.component.test.js
  packages/components/src/QualityBar/QualityBar.stories.js
  packages/components/src/QualityBar/QualityRatioBar.component.js
  packages/components/src/QualityBar/index.js
  packages/components/src/RatioBar/RatioBarComposition.component.js
Labels: need review

#3155 feat(components/headercheckbox): add intermediate state
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/VirtualizedList/HeaderCheckbox/HeaderCheckbox.component.js
  packages/components/src/VirtualizedList/HeaderCheckbox/HeaderCheckbox.scss
  packages/components/src/VirtualizedList/HeaderCheckbox/HeaderCheckbox.test.js
  packages/components/src/VirtualizedList/HeaderCheckbox/__snapshots__/HeaderCheckbox.test.js.snap
Labels: easy review, enhancement

#3158 fix(components/TDP-9660): lint errors RatioBar/QualityBar
  output/components.eslint.txt
  packages/components/src/QualityBar/QualityBar.component.js
  packages/components/src/QualityBar/QualityBar.component.test.js
  packages/components/src/QualityBar/QualityBar.stories.js
  packages/components/src/QualityBar/QualityRatioBar.component.js
  packages/components/src/QualityBar/index.js
  packages/components/src/RatioBar/RatioBarComposition.component.js
Labels: need review

#3162 feat(icons): TS definition
  packages/icons/package.json
  packages/icons/scripts/typescript.js
Labels: easy review, need review

#3163 feat(Dataviz): Date & Time ranges
  packages/dataviz/CHANGELOG.md
  packages/dataviz/README.md
  packages/dataviz/package.json
  packages/dataviz/src/components/BarChart/VerticalBarChart/VerticalBarChart.component.test.tsx
  packages/dataviz/src/components/BarChart/VerticalBarChart/VerticalBarChart.component.tsx
  packages/dataviz/src/components/BarChart/VerticalBarChart/VerticalBarChart.stories.tsx
  packages/dataviz/src/components/BarChart/barChart.tooltip.test.ts
  packages/dataviz/src/components/BarChart/barChart.types.ts
  packages/dataviz/src/components/BoxPlot/BoxPlot.component.test.tsx
  packages/dataviz/src/components/BoxPlot/BoxPlot.component.tsx
  packages/dataviz/src/components/ChartPanel/VerticalChartFilter/VerticalChartFilter.component.test.tsx
  packages/dataviz/src/components/ChartPanel/VerticalChartFilter/VerticalChartFilter.component.tsx
  packages/dataviz/src/components/ChartPanel/VerticalChartFilter/VerticalChartFilter.stories.tsx
  packages/dataviz/src/components/RangeFilter/RangeFilter.component.scss
  packages/dataviz/src/components/RangeFilter/RangeFilter.component.stories.tsx
  packages/dataviz/src/components/RangeFilter/RangeFilter.component.test.tsx
  packages/dataviz/src/components/RangeFilter/RangeFilter.component.tsx
  packages/dataviz/src/components/RangeFilter/handlers/DateRangeHandler/DateRangeHandler.test.tsx
  packages/dataviz/src/components/RangeFilter/handlers/DateRangeHandler/DateRangeHandler.tsx
  packages/dataviz/src/components/RangeFilter/handlers/DateTimeRangeHandler/DateTimeInputField.component.scss
  packages/dataviz/src/components/RangeFilter/handlers/DateTimeRangeHandler/DateTimeRangeHandler.test.tsx
  packages/dataviz/src/components/RangeFilter/handlers/DateTimeRangeHandler/DateTimeRangeHandler.tsx
  packages/dataviz/src/components/RangeFilter/handlers/NumberRangeHandler/NumberInputField.component.scss
  packages/dataviz/src/components/RangeFilter/handlers/NumberRangeHandler/NumberRangeHandler.test.tsx
  packages/dataviz/src/components/RangeFilter/handlers/NumberRangeHandler/NumberRangeHandler.tsx
  packages/dataviz/src/components/RangeFilter/handlers/TimeRangeHandler/TimeRangeHandler.test.tsx
  packages/dataviz/src/components/RangeFilter/handlers/TimeRangeHandler/TimeRangeHandler.tsx
  packages/dataviz/src/components/RangeFilter/handlers/index.ts
  packages/dataviz/src/components/RangeFilter/handlers/range-handler.types.ts
  packages/dataviz/src/components/RangeFilter/handlers/useRangeInputField.hook.ts
  packages/dataviz/src/components/RangeFilter/index.ts
  packages/dataviz/src/components/RangeFilter/input-fields/DateInputField.component.test.tsx
  packages/dataviz/src/components/RangeFilter/input-fields/DateInputField.component.tsx
  packages/dataviz/src/components/RangeFilter/input-fields/NumberInputField.component.test.tsx
  packages/dataviz/src/components/RangeFilter/input-fields/NumberInputField.component.tsx
  packages/dataviz/src/formatters/formatters.ts
  packages/dataviz/src/index.ts
  packages/dataviz/src/types/index.ts
  packages/dataviz/src/types/types.d.ts
Labels: PoC do not merge

#3168 fix(components/typeahead): remove double border at the top of the items container
  output/components.sasslint.txt
  packages/components/src/Typeahead/Typeahead.scss
Labels: bug, easy review, need review

#3170 fix(theme): chesnut-rose is the new black
  packages/components/src/QualityBar/QualityRatioBar.scss
  packages/theme/src/theme/_datagrid.scss
Labels: easy review, enhancement, need review

#3174 chore(surge): landing page style
  .surge/index.html
Labels: easy review, enhancement, need review

#3177 chore: copy bootsrap theme on surge
  .travis/after_success_umd.sh
Labels: need review

#3171 chore(components): fix small typo in InlineMessage component css
  packages/components/src/InlineMessage/InlineMessage.scss
Labels: easy review, need review

#3181 chore: upgrade to ui-scripts 7.5
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/dataviz/yarn.lock
  packages/forms/package.json
  packages/html-webpack-plugin/package.json
  packages/http/package.json
  packages/router/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/validation/package.json
  packages/validation/yarn.lock
  yarn.lock
Labels: need review

#3184 fix(TPSVC-16945): fix label in CollapsiblePanel
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
Labels: need review

#3190 chore(components): IconsProvider wait for all bundles
  packages/components/src/IconsProvider/IconsProvider.component.js
Labels: easy review, enhancement, javascript, need review

#3191 feat(icon): open-window.svg
  packages/icons/src/svg/core/open-window.svg
Labels: easy review, need review

#3192 fix: eslint empty report is not updated
  .travis/after_success_lint.sh
  output/forms.eslint.txt
  output/router.eslint.txt
Labels: need review

#3185 feat(forms/CollapsibleFieldSet): allow definition of fallback title
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
Labels: need review

#3193 feat(icons): parser.svg, generator.svg
  packages/icons/src/svg/processors/generator.svg
  packages/icons/src/svg/processors/parser.svg
Labels: easy review, need review

#3195 chore: gh action release note content
  .github/workflows/release-variables.sh
Labels: easy review, need review

#3196 fix(CellDatetime): fix displaying if there is no date or it is invalid
  packages/components/src/List/List.stories.js
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js
Labels: need review
