Repository Talend/ui, pull requests merged in 2021-06, with the labels that each got.

#3300 chore: surge with umd in a folder with PR number
  .travis/after_success_umd.sh
Labels: need review

#3310 fix(components): Remove dep cycle in DataViewer
  output/components.eslint.txt
  packages/components/src/DataViewer/Core/Tree/Tree.component.js
  packages/components/src/DataViewer/Core/Tree/__snapshots__/Tree.test.js.snap
  packages/components/src/DataViewer/Core/TreeNode/TreeNode.component.js
Labels: need review

#3322 chore: add react-router-dom in dependencies.json
  versions/dependencies.json
Labels: need review

#3327 fix(Dataviz): Show special chars in tooltip
  packages/dataviz/.storybook/preview.js
  packages/dataviz/CHANGELOG.md
  packages/dataviz/package.json
  packages/dataviz/src/components/TooltipContent/TooltipContent.component.tsx
  packages/dataviz/src/components/TooltipContent/TooltipContent.stories.tsx
  packages/dataviz/src/components/TooltipContent/__snapshots__/TooltipContent.component.test.tsx.snap
Labels: easy review, need review

#3318 fix(arch-343/cmf-router): upgrade dependencies.json
  packages/cmf-router/CHANGELOG.md
  packages/cmf-router/package.json
  packages/cmf-router/yarn.lock
Labels: need review

#3313 feat(forms/TimezoneList): TimezoneList form field
  packages/forms/package.json
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
  packages/forms/src/UIForm/fields/TimezoneList/README.md
  packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.component.js
  packages/forms/src/UIForm/fields/TimezoneList/TimezoneList.utils.js
  packages/forms/src/UIForm/fields/TimezoneList/index.js
  packages/forms/src/UIForm/fields/TimezoneList/screenshot.gif
  packages/forms/src/UIForm/fields/index.js
  packages/forms/src/UIForm/utils/widgets.js
  packages/forms/stories-core/json/fields/core-timezoneList.json
  yarn.lock
Labels: need review

#3332 feat(containers): Support async multisection datalist
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/ComponentForm/ComponentForm.test.js
Labels: need review

#3339 chore(arch-364): add surge demo
  .github/workflows/lerna-ci.yml
  .github/workflows/pr-demo.yml
  .travis/after_success_coverage.sh
  .travis/after_success_demo.sh
  .travis/after_success_deploy.sh
  .travis/after_success_git.sh
  .travis/after_success_prettier.sh
  .travis/after_success_static.sh
  .travis/after_success_umd.sh
  .travis/before_install.sh
  .travis/before_script_icons.sh
  prettier.sh
Labels: need review

#3342 feat(components/ratiobar): add errors count
  packages/components/src/RatioBar/RatioBar.component.js
  packages/components/src/RatioBar/RatioBar.component.test.js
  packages/components/src/RatioBar/RatioBar.scss
  packages/components/src/RatioBar/RatioBar.stories.js
  packages/components/src/RatioBar/RatioBarLines.component.js
Labels: easy review, enhancement, need review

#3314 chore(components): Coral InlineMessage
  packages/components/package.json
  packages/components/src/InlineMessage/InlineMessage.component.js
  packages/components/src/InlineMessage/InlineMessage.scss
  packages/components/src/InlineMessage/__snapshots__/InlineMessage.snapshot.test.js.snap
  packages/components/src/Link/index.js
  packages/components/src/index.js
  yarn.lock
Labels: easy review, need review

#3349 fix(ActionButton): update forms snapshot
  packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Labels: bug, need review

#3351 feat(VirtualizedList): add CellQualityBar renderer
  packages/components/src/FilterBar/FilterBar.test.js
  packages/components/src/List/ListComposition.stories.js
  packages/components/src/List/ListComposition/collection.js
  packages/components/src/VirtualizedList/CellQualityBar/CellQualityBar.component.js
  packages/components/src/VirtualizedList/CellQualityBar/CellQualityBar.test.js
  packages/components/src/VirtualizedList/CellQualityBar/QualityBarColumn.component.js
  packages/components/src/VirtualizedList/CellQualityBar/__snapshots__/CellQualityBar.test.js.snap
  packages/components/src/VirtualizedList/CellQualityBar/index.js
  packages/components/src/VirtualizedList/VirtualizedList.stories.js
  packages/components/src/VirtualizedList/index.js
Labels: enhancement, need review

#3348 chore(forms): Coral InlineMessage
  packages/forms/.storybook/config.js
  packages/forms/package.json
  packages/forms/src/UIForm/Message/Message.component.js
  packages/forms/src/UIForm/Message/__snapshots__/Message.component.test.js.snap
  packages/forms/src/UIForm/Widget/Widget.component.test.js
  packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap
  packages/forms/src/UIForm/fields/Enumeration/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/CollapsibleFieldset.component.test.js
  packages/forms/src/UIForm/fieldsets/CollapsibleFieldset/__snapshots__/CollapsibleFieldset.component.test.js.snap
  packages/forms/src/rhf/fields/Input/Input.test.js
  packages/forms/src/rhf/fields/Select/Select.test.js
  packages/forms/src/rhf/fields/TextArea/RHFTextArea.test.js
  packages/forms/src/widgets/templates/FieldTemplate/FieldTemplate.component.js
  packages/forms/src/widgets/templates/FieldTemplate/FieldTemplate.test.js
  packages/forms/src/widgets/templates/FieldTemplate/__snapshots__/FieldTemplate.test.js.snap
  yarn.lock
Labels: easy review, enhancement, need review

#3354 chore(CI): add dedupe and upgrade GH actions
  .github/workflows/dependencies.yml
  .github/workflows/lerna-ci.yml
  .github/workflows/yarn-deduplicate.yml
  packages/cmf/package.json
  yarn.lock
Labels: need review

#3359 chore: fix release job
  .github/workflows/before-surge.sh
  .github/workflows/pr-demo.yml
  .github/workflows/release.yml
  package.json
Labels: need review
