Repository Talend/ui, pull requests merged in 2021-04, with the labels that each got.

#3260 chore: remove unused polyfills
  packages/cmf-cqrs/package.json
  packages/generator/package.json
  yarn.lock
Labels: need review

#3261 fix(dataviz): add dev umd
  packages/dataviz/CHANGELOG.md
  packages/dataviz/package.json
Labels: need review

#3257 fix(Emphasis/TMC-24631): error in datalist when value is not a string
  packages/components/src/Emphasis/Emphasis.component.js
  packages/components/src/Emphasis/Emphasis.test.js
Labels: need review

#3267 feat(components/QualityBar): not applicable
  output/components.sasslint.txt
  packages/components/src/QualityBar/QualityBar.component.js
  packages/components/src/QualityBar/QualityBar.component.test.js
  packages/components/src/QualityBar/QualityBar.stories.js
  packages/components/src/QualityBar/QualityRatioBar.component.js
  packages/components/src/QualityBar/QualityRatioBar.scss
Labels: easy review, need review

#3271 fix(container): context.store.dispatch not a function
  packages/containers/src/actionAPI.js
Labels: need review

#3273 feat(components/stepper): export coral form stepper
  output/components.eslint.txt
  packages/components/package.json
  packages/components/src/Stepper/Stepper.component.js
  packages/components/src/Stepper/Stepper.stories.js
  yarn.lock
Labels: easy review, enhancement, need review

#3276 chore: remove demo when PR is closed
  .github/workflows/surge-cleanup.yml
Labels: easy review, need review

#3275 chore(security): upgrades
  packages/cmf/package.json
  packages/cmf/website/package.json
  packages/cmf/website/yarn.lock
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/dataviz/yarn.lock
  packages/forms/package.json
  packages/stepper/package.json
  packages/theme/package.json
  yarn.lock
Labels: need review

#3277 chore(TDC-5473/datagrid): update ag-grid deps
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  yarn.lock
Labels: dependencies, need review

#3224 chore(containers): remove cmf-router from dependencies
  packages/containers/package.json
  packages/containers/src/DeleteResource/actions.js
  packages/containers/src/DeleteResource/actions.test.js
  packages/containers/src/HomeListView/__snapshots__/HomeListView.test.js.snap
  packages/containers/src/ShortcutManager/ShortcutManager.connect.js
  packages/containers/src/SidePanel/SidePanel.connect.js
  packages/containers/src/SidePanel/SidePanel.test.js
  packages/containers/src/actionAPI.test.js
  packages/containers/src/register.test.js
  yarn.lock
Labels: breaking change, need review

#3280 fix(Typeahead): update position when items list changes
  output/components.eslint.txt
  packages/components/src/Typeahead/Typeahead.component.js
Labels: easy review, need review

#3270 feat(TRR-287/components/LegacyDateTime): Add date/time support
  output/components.eslint.txt
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Manager/Manager.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/date-extraction.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/date-extraction.test.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap
  packages/components/src/DateTimePickers/LegacyDateTimePickers/LegacyDateTimePicker.stories.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/README.md
Labels: need review
