Repository Talend/ui, pull requests merged in 2021-05, with the labels that each got.

#3282 chore(deps): upgrade Design System
  yarn.lock
Labels: dependencies, need review

#3285 fix(components/resourceslist): i18n domain is not provided
  output/components.eslint.txt
  packages/components/src/ResourceList/ResourceList.component.js
Labels: bug, easy review, need review

#3288 feat(component/actiondropdown): add ellipsis mode
  output/components.eslint.txt
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.scss
  packages/components/src/Actions/ActionDropdown/ActionDropdown.snapshot.test.js
  packages/components/src/Actions/ActionDropdown/Dropdown.stories.js
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.scss
  packages/components/src/VirtualizedList/CellTitle/__snapshots__/CellTitleActions.test.js.snap
Labels: easy review, enhancement, need review

#3290 fix(i18n): Fix createInstance import
  packages/components/src/translate.js
  packages/containers/src/translate.js
  packages/datagrid/src/translate.js
  packages/forms/src/translate.js
  packages/stepper/src/translate.js
Labels: bug, need review

#3292 feat(icons): flash.svg
  packages/icons/src/svg/core/flash.svg
Labels: easy review, need review

#3298 feat(icon): api.svg
  packages/icons/src/svg/core/api.svg
Labels: easy review, need review

#3299 feat(icons): shape-tools.svg
  packages/icons/src/svg/processors/shape-tools.svg
Labels: easy review, need review

#3302 feat(http): add head method
  packages/cmf/__tests__/sagas/http.test.js
  packages/cmf/src/sagas/http.js
  packages/http/src/async.js
Labels: easy review, enhancement, need review

#3306 fix(icons): build prod mode
  packages/icons/webpack.umd.js
Labels: need review

#3307 fix(theme): add manifest for CDN build
  packages/theme/dependencies.json
  packages/theme/webpack.config.js
Labels: need review

#3294 chore(components): rewrite List stories using new CSF
  output/components.eslint.txt
  packages/components/package.json
  packages/components/src/List/List.stories.js
Labels: need review

#3309 chore(Date): remove cycle deps
  output/components.eslint.txt
  packages/components/src/DateTimePickers/Date/date-extraction.js
  packages/components/src/DateTimePickers/DateTime/datetime-extraction.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/date-extraction.js
  packages/components/src/utils/date.js
  packages/components/src/utils/date.test.js
Labels: need review

#3252 feat(theme): buttons
  output/theme.sasslint.txt
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/HeaderBar/HeaderBar.scss
  packages/forms/src/UIForm/fields/Button/SingleButton.component.js
  packages/theme/example/index.html
  packages/theme/package.json
  packages/theme/src/theme/_button-groups.scss
  packages/theme/src/theme/_buttons.scss
  packages/theme/src/theme/_colors.scss
  packages/theme/src/theme/_hyperlinks.scss
  packages/theme/src/theme/_navbar.scss
  packages/theme/src/theme/_navs.scss
  packages/theme/src/theme/_variables.scss
  packages/theme/src/theme/theme.scss
  packages/theme/webpack.config.js
  yarn.lock
Labels: enhancement, need review

#3305 feat(components/HeaderBar): Accept custom AppNotification component
  packages/components/src/HeaderBar/HeaderBar.component.js
Labels: easy review, enhancement, need review
