Repository Talend/ui, pull requests merged in 2021-09, with the labels that each got.

#3415 feat(components): update semantic awareness display
  .changeset/healthy-cats-cover.md
  packages/components/src/DataViewer/DataViewer.stories.js
  packages/components/src/DataViewer/ModelViewer/Leaf/ModelViewerLeaf.component.js
  packages/components/src/DataViewer/ModelViewer/Leaf/__snapshots__/ModelViewerLeaf.test.js.snap
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.component.js
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/SimpleTextKeyValue.scss
  packages/components/src/DataViewer/Text/SimpleTextKeyValue/__snapshots__/SimpleTextKeyValue.test.js.snap
Labels: need review

#3418 fix(forms/NestedListView): Component should now detect props change
  .changeset/quick-colts-join.md
  packages/forms/src/UIForm/fields/NestedListView/NestedListView.component.js
  packages/forms/src/UIForm/fields/NestedListView/NestedListView.test.js
Labels: need review

#3421 fix(theme): Fix chevron rotation on firefox
  .changeset/great-panthers-wink.md
  packages/theme/src/theme/_forms.switch-nested.scss
Labels: need review

#3422 chore: add some entries in npmignore
  packages/cmf-cqrs/.npmignore
  packages/cmf-router/.npmignore
  packages/cmf-webpack-plugin/.npmignore
  packages/cmf/.npmignore
  packages/components/.npmignore
  packages/containers/.npmignore
  packages/datagrid/.npmignore
  packages/dataviz/.npmignore
  packages/forms/.npmignore
  packages/router-bridge/.npmignore
  packages/sagas/.npmignore
  packages/stepper/.npmignore
  packages/storybook-cmf/.npmignore
  packages/theme/.npmignore
Labels: need review

#3090 feat(cmf): add bootstrap option to not render the app
  .changeset/selfish-kangaroos-change.md
  packages/cmf/__tests__/cmfModule.merge.test.js
  packages/cmf/src/bootstrap.js
  packages/cmf/src/bootstrap.md
  packages/cmf/src/cmfModule.merge.js
Labels: need review

#3430 fix(theme): resolve font url
  .changeset/khaki-pets-know.md
  packages/theme/webpack.config.js
Labels: need review

#3429 chore(security): upgrade @talend packages
  fork/bootstrap-sass/package.json
  package.json
  packages/cmf-cqrs/package.json
  packages/cmf-router/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/eslint-config/package.json
  packages/forms/package.json
  packages/http/package.json
  packages/icons/package.json
  packages/jsfc/package.json
  packages/local-libs-webpack-plugin/package.json
  packages/router-bridge/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
  packages/utils/package.json
  yarn.lock
Labels: need review

#3268 feat(theme): forms
  packages/components/src/DateTimePickers/Date/Input/__snapshots__/Input.component.test.js.snap
  packages/components/src/DateTimePickers/DateRange/Input/__snapshots__/Input.component.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.component.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/__snapshots__/InputDateTimeRangePicker.component.test.js.snap
  packages/components/src/DateTimePickers/TimeZone/TimeZone.scss
  packages/components/src/DateTimePickers/shared/InputSizer/InputSizer.component.js
  packages/components/src/DateTimePickers/shared/InputSizer/InputSizer.component.test.js
  packages/components/src/DateTimePickers/shared/styles/mixins.scss
  packages/components/src/EditableText/EditableText.scss
  packages/components/src/Enumeration/Items/Item/Item.scss
  packages/components/src/FilterBar/FilterBar.scss
  packages/components/src/ListView/Items/Items.scss
  packages/components/src/MultiSelect/MultiSelect.scss
  packages/components/src/MultiSelect/MultiSelect.stories.js
  packages/components/src/Typeahead/Typeahead.scss
  packages/components/src/VirtualizedList/CellCheckbox/CellCheckbox.scss
  packages/forms/src/UIForm/UIForm.scss
  packages/forms/src/UIForm/Widget/Widget.component.scss
  packages/forms/src/UIForm/fields/Comparator/Comparator.scss
  packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.scss
  packages/forms/src/UIForm/fields/File/File.scss
  packages/forms/src/UIForm/fields/KeyValue/KeyValue.scss
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.scss
  packages/forms/src/UIForm/fields/Select/Select.component.js
  packages/forms/src/UIForm/fields/Select/__snapshots__/Select.component.test.js.snap
  packages/forms/src/UIForm/fields/Text/Text.component.js
  packages/forms/src/UIForm/fields/Text/__snapshots__/Text.component.test.js.snap
  packages/forms/src/UIForm/fields/TextArea/TextArea.component.js
  packages/forms/src/UIForm/fields/TextArea/__snapshots__/TextArea.component.test.js.snap
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/MultiSelectTagWidget.scss
  packages/forms/stories-core/json/fields/core-checkbox.json
  packages/forms/stories-core/json/fields/core-radios.json
  packages/forms/stories-core/json/fields/core-select.json
  packages/forms/stories-core/json/fields/core-toggle.json
  packages/theme/src/theme/_colors.scss
  packages/theme/src/theme/_forms.checkbox.scss
  packages/theme/src/theme/_forms.guideline.scss
  packages/theme/src/theme/_forms.input.scss
  packages/theme/src/theme/_forms.label.scss
  packages/theme/src/theme/_forms.legend.scss
  packages/theme/src/theme/_forms.radio.scss
  packages/theme/src/theme/_forms.scss
  packages/theme/src/theme/_forms.select.scss
  packages/theme/src/theme/_forms.switch-nested.scss
  packages/theme/src/theme/_forms.switch.scss
  packages/theme/src/theme/_forms.textarea.scss
  packages/theme/src/theme/_guidelines.scss
  packages/theme/src/theme/_navbar.search.scss
  packages/theme/src/theme/_variables.scss
Labels: enhancement, need review

#3438 chore(Components): remove DraggableComponent
  .changeset/shiny-cooks-camp.md
  packages/components/package.json
  packages/components/src/Draggable/DraggableComponent.js
  packages/components/src/Draggable/DraggableComponent.test.js
  packages/components/src/Draggable/__snapshots__/DraggableComponent.test.js.snap
  packages/components/src/Draggable/index.js
  packages/components/src/index.js
  yarn.lock
Labels: need review

#3435 fix(components): use sass math.div
  .changeset/sweet-peas-worry.md
  .storybook/config.js
  .storybook/webpack.config.js
  packages/cmf-webpack-plugin/package.json
  packages/cmf/docs/getting-started.md
  packages/components/.storybook/config.js
  packages/components/package.json
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/Badge/Badge.scss
  packages/components/src/Drawer/Drawer.scss
  packages/components/src/GuidedTour/GuidedTour.scss
  packages/components/src/ObjectViewer/JSONLike/JSONLike.scss
  packages/components/src/Progress/Progress.scss
  packages/components/src/Slider/Slider.scss
  packages/containers/.storybook/config.js
  packages/containers/README.md
  packages/datagrid/.storybook/config.js
  packages/dataviz/.storybook/main.js
  packages/dataviz/package.json
  packages/forms/.storybook/config.js
  packages/forms/package.json
  packages/stepper/.storybook/config.js
  packages/storybook-cmf/package.json
  packages/theme/README.md
  packages/theme/src/theme/_dropdowns.scss
  packages/theme/src/theme/_navs.scss
  yarn.lock
Labels: need review

#3440 chore(build): order packages on pre-release hook
  .changeset/quiet-crews-sit.md
  workspace-run.js
Labels: need review

#3443 fix(workspace-run): package run order
  .changeset/clever-poems-tan.md
  workspace-run.js
Labels: need review

#3446 fix(form/router-bridge): declare peer deps meta for optional deps
  packages/forms/package.json
  packages/router-bridge/package.json
Labels: need review

#3447 fix(theme): revert sass:math.div
  .changeset/shaggy-peaches-cough.md
  fork/bootstrap-sass/assets/stylesheets/bootstrap/_carousel.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/_code.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/_forms.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/_jumbotron.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/_navbar.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/_type.scss
  package.json
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/Badge/Badge.scss
  packages/components/src/Drawer/Drawer.scss
  packages/components/src/GuidedTour/GuidedTour.scss
  packages/components/src/ObjectViewer/JSONLike/JSONLike.scss
  packages/components/src/Progress/Progress.scss
  packages/components/src/Slider/Slider.scss
  packages/theme/src/theme/_dropdowns.scss
  packages/theme/src/theme/_navs.scss
  packages/theme/src/theme/_variables.scss
  packages/theme/webpack.config.js
  workspace-run.js
Labels: need review

#3450 chore: remove build warning
  yarn.lock
Labels: need review

#3449 fix(boostrap-sass): use calc instead of math.div
  .changeset/rich-cows-jog.md
  fork/bootstrap-sass/assets/stylesheets/bootstrap/_navbar.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_grid-framework.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_grid.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_nav-divider.scss
  fork/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_nav-vertical-align.scss
  packages/theme/src/theme/_variables.scss
Labels: need review

#3460 fix(IconToggle/Drawer/Slider/ObjectViewer): calc with sass vars
  .changeset/gold-ghosts-laugh.md
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.scss
  packages/components/src/Drawer/Drawer.scss
  packages/components/src/ObjectViewer/JSONLike/JSONLike.scss
  packages/components/src/Slider/Slider.scss
Labels: need review, easy review
