Repository Talend/ui, pull requests merged in 2021-02, with the labels that each got.

#3197 chore: upgrade @talend/scripts to v8.0.0
  mocks/dateMock.js
  packages/cmf-cqrs/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/dataviz/yarn.lock
  packages/forms/package.json
  packages/html-webpack-plugin/package.json
  packages/html-webpack-plugin/yarn.lock
  packages/http/package.json
  packages/http/yarn.lock
  packages/router/package.json
  packages/router/yarn.lock
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/validation/package.json
  packages/validation/yarn.lock
  yarn.lock
Labels: easy review, need review

#3198 chore: remove custom html-webpack-plugin
  .github/actions/sourceclear/entrypoint.sh
  .travis.yml
  package.json
  packages/html-webpack-plugin/.editorconfig
  packages/html-webpack-plugin/.gitignore
  packages/html-webpack-plugin/.npmignore
  packages/html-webpack-plugin/LICENSE
  packages/html-webpack-plugin/README.md
  packages/html-webpack-plugin/index.js
  packages/html-webpack-plugin/index.test.js
  packages/html-webpack-plugin/jest.config.js
  packages/html-webpack-plugin/package.json
  packages/html-webpack-plugin/talend-scripts.json
  packages/html-webpack-plugin/yarn.lock
Labels: easy review, need review

#3182 feat(forms): add textarea RHF component
  output/theme.sasslint.txt
  packages/forms/src/rhf/fields/TextArea/RHFTextArea.component.js
  packages/forms/src/rhf/fields/TextArea/RHFTextArea.test.js
  packages/forms/src/rhf/fields/TextArea/TextArea.stories.js
  packages/forms/src/rhf/fields/TextArea/index.js
  packages/forms/src/widgets/fields/TextArea/TextArea.component.js
  packages/forms/src/widgets/fields/TextArea/TextArea.test.js
  packages/forms/src/widgets/fields/TextArea/index.js
  packages/theme/src/theme/_forms.scss
Labels: easy review, need review

#3203 feat(components/List): performance
  packages/components/src/List/ListComposition/VList/VList.component.js
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js
  packages/components/src/VirtualizedList/CellTitle/CellTitle.component.js
Labels: bug, enhancement, need review

#3208 chore(i18n): change from edit to rename in EditableText
  packages/components/src/EditableText/EditableText.component.js
  packages/components/src/EditableText/__snapshots__/EditableText.test.js.snap
Labels: easy review, need review

#3152 fix(RangePicker): make the global div fit the content
  packages/components/src/DateTimePickers/shared/styles/mixins.scss
Labels: easy review, need review

#3209 feat(dataviz): add geo chart component
  packages/dataviz/CHANGELOG.md
  packages/dataviz/package.json
  packages/dataviz/src/components/BoxPlot/BoxPlot.component.tsx
  packages/dataviz/src/components/GeoChart/GeoChart.component.tsx
  packages/dataviz/src/components/GeoChart/GeoChart.scss
  packages/dataviz/src/components/GeoChart/GeoChart.stories.tsx
  packages/dataviz/src/components/GeoChart/GeoChart.test.js
  packages/dataviz/src/components/GeoChart/GeoChart.utils.ts
  packages/dataviz/src/components/GeoChart/README.md
  packages/dataviz/src/components/GeoChart/index.ts
  packages/dataviz/src/components/GeoChart/maps/CA.topo.json
  packages/dataviz/src/components/GeoChart/maps/FR.topo.json
  packages/dataviz/src/components/GeoChart/maps/MX.topo.json
  packages/dataviz/src/components/GeoChart/maps/US.topo.json
  packages/dataviz/src/components/GeoChart/maps/US_CA.topo.json
  packages/dataviz/src/components/GeoChart/maps/continents.topo.json
  packages/dataviz/src/components/GeoChart/maps/world.topo.json
  packages/dataviz/src/components/TooltipContent/TooltipContent.component.scss
  packages/dataviz/src/index.ts
  packages/dataviz/yarn.lock
Labels: dependencies, enhancement, need review

#3211 chore(DatePickers): disabled mode
  output/components.eslint.txt
  packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js
  packages/components/src/DateTimePickers/InputDateRangePicker/DateRangePicker.stories.js
  packages/components/src/DateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/DateTimeRangePicker.stories.js
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.test.js
  packages/components/src/DateTimePickers/InputTimePicker/TimePicker.stories.js
  packages/components/src/DateTimePickers/hooks/useInputPickerHandlers.js
Labels: easy review, need review

#3213 chore: UMD size checker
  .github/workflows/umd-size-checker.yml
  .travis/after_success_umd.sh
Labels: easy review, need review

#3214 fix(icons): generated font
  packages/icons/scripts/docs.js
  packages/icons/src/svg/core/group-circle.svg
  packages/icons/src/svg/core/launch.svg
  packages/icons/src/svg/core/minus-circle.svg
  packages/icons/src/svg/core/pause.svg
  packages/icons/src/svg/core/plus-circle.svg
  packages/icons/src/svg/core/question-circle.svg
  packages/icons/src/svg/core/user-circle.svg
  packages/icons/src/svg/products/api-designer-colored.svg
  packages/icons/src/talendicons.font.js
Labels: easy review, need review

#3176 chore(components): migrate react-popper to v2
  output/components.eslint.txt
  packages/components/package.json
  packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js
  packages/components/src/DateTimePickers/InputDateRangePicker/InputDateRangePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.component.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/__snapshots__/InputDateTimeRangePicker.component.test.js.snap
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.test.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/InputDateTimePicker.component.test.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.snapshot.test.js.snap
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
  yarn.lock
Labels: need review

#3219 feat(ActionDropdown): applying transformation on icon
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.test.js
Labels: need review

#3222 feat(components/CellDatetime): handling timezone
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.component.js
  packages/components/src/VirtualizedList/CellDatetime/CellDatetime.test.js
  packages/components/src/VirtualizedList/CellDatetime/__snapshots__/CellDatetime.test.js.snap
Labels: need review

#3220 fix(dataviz): remove locale as peer dep
  packages/dataviz/CHANGELOG.md
  packages/dataviz/package.json
Labels: need review

#3164 feat(components): tags
  output/components.eslint.txt
  packages/components/.storybook/config.js
  packages/components/__mocks__/@talend/design-system.js
  packages/components/package.json
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.snapshot.test.js
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/Drawer/__snapshots__/Drawer.test.js.snap
  packages/components/src/Layout/Layout.component.js
  packages/components/src/Layout/__snapshots__/Layout.test.js.snap
  packages/components/src/SubHeaderBar/SubHeader.stories.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js
  packages/components/src/TabBar/TabBar.component.js
  packages/components/src/TabBar/TabBar.scss
  packages/components/src/TabBar/__snapshots__/TabBar.test.js.snap
  packages/components/src/Tag/Tag.component.js
  packages/components/src/Tag/Tag.test.js
  packages/components/src/Tag/__snapshots__/Tag.test.js.snap
  packages/components/src/Tag/index.js
  packages/components/src/VirtualizedList/CellLabel/CellLabel.component.js
  packages/components/src/VirtualizedList/CellLabel/CellLabel.test.js
  packages/components/src/VirtualizedList/CellLabel/__snapshots__/CellLabel.test.js.snap
  packages/components/src/index.js
  yarn.lock
Labels: enhancement, need review

#3225 chore(router): rename folder to cmf-router
  .github/actions/sourceclear/entrypoint.sh
  .travis.yml
  .travis/after_success_lint.sh
  .travis/after_success_umd.sh
  package.json
  packages/cmf-router/.gitignore
  packages/cmf-router/.npmignore
  packages/cmf-router/README.md
  packages/cmf-router/package.json
  packages/cmf-router/src/UIRouter.js
  packages/cmf-router/src/constant.js
  packages/cmf-router/src/expressions.js
  packages/cmf-router/src/expressions.md
  packages/cmf-router/src/expressions.test.js
  packages/cmf-router/src/index.js
  packages/cmf-router/src/index.test.js
  packages/cmf-router/src/middleware.js
  packages/cmf-router/src/middleware.md
  packages/cmf-router/src/middleware.test.js
  packages/cmf-router/src/route.js
  packages/cmf-router/src/route.md
  packages/cmf-router/src/route.test.js
  packages/cmf-router/src/sagaRouter.js
  packages/cmf-router/src/sagaRouter.md
  packages/cmf-router/src/sagaRouter.test.js
  packages/cmf-router/src/sagas/documentTitle.js
  packages/cmf-router/src/sagas/documentTitle.test.js
  packages/cmf-router/src/selectors.js
  packages/cmf-router/src/selectors.test.js
  packages/cmf-router/talend-scripts.json
  packages/cmf-router/yarn.lock
Labels: need review

#3227 fix(components/Typeahead): fit in viewport
  packages/components/src/Typeahead/Typeahead.component.js
Labels: bug, easy review, need review

#3226 feat: router bridge package
  packages/router-bridge/.gitignore
  packages/router-bridge/.npmignore
  packages/router-bridge/README.md
  packages/router-bridge/img/action-creator.png
  packages/router-bridge/img/route-mapping-cmf.png
  packages/router-bridge/img/route-mapping-rrv5.png
  packages/router-bridge/jest.config.js
  packages/router-bridge/package.json
  packages/router-bridge/src/index.js
  packages/router-bridge/src/redux/index.js
  packages/router-bridge/src/redux/redux-legacy-mode.test.js
  packages/router-bridge/src/redux/redux-rr5-mode.test.js
  packages/router-bridge/src/router/index.js
  packages/router-bridge/src/router/router-legacy-mode.test.js
  packages/router-bridge/src/router/router-rr5-mode.test.js
  packages/router-bridge/talend-scripts.json
  packages/router-bridge/yarn.lock
Labels: need review

#3229 chore(release): trigger GitHub Action after release
  .github/workflows/dataviz-autopublish.yml
  .github/workflows/release.yml
Labels: easy review, enhancement, need review

#3230 fix(DatePicker): ref error
  packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js
  packages/components/src/DateTimePickers/InputDateTimePicker/__snapshots__/InputDateTimePicker.component.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/__snapshots__/InputDateTimeRangePicker.component.test.js.snap
Labels: need review

#3231 chore: remove scss ie11 fix
  packages/components/src/VirtualizedList/VirtualizedList.scss
Labels: need review

#3232 chore(deps): bump ui scripts version
  packages/cmf-cqrs/package.json
  packages/cmf-router/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/__mocks__/@talend/design-system.js
  packages/components/package.json
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/VirtualizedList/CellLabel/__snapshots__/CellLabel.test.js.snap
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/dataviz/yarn.lock
  packages/forms/package.json
  packages/http/package.json
  packages/router-bridge/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/validation/package.json
  packages/validation/yarn.lock
  yarn.lock
Labels: easy review, enhancement, need review

#3175 chore(component): use Icon & Provider from design-system
  packages/components/src/ActionIntercom/__snapshots__/Intercom.component.test.js.snap
  packages/components/src/Actions/ActionDropdown/ActionDropdown.test.js
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
  packages/components/src/AppSwitcher/__snapshots__/AppSwitcher.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeDelete/__snapshots__/BadgeDelete.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeDropdown/__snapshots__/BadgeDropdown.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeIcon/__snapshots__/BadgeIcon.component.test.js.snap
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/__snapshots__/InputDateTimeRangePicker.component.test.js.snap
  packages/components/src/Enumeration/Items/Item/Item.test.js
  packages/components/src/HttpError/__snapshots__/HttpError.snapshot.test.js.snap
  packages/components/src/Icon/Icon.component.js
  packages/components/src/Icon/Icon.scss
  packages/components/src/Icon/Icon.stories.js
  packages/components/src/Icon/Icon.test.js
  packages/components/src/Icon/__snapshots__/Icon.test.js.snap
  packages/components/src/Icon/index.js
  packages/components/src/IconsProvider/IconsProvider.component.js
  packages/components/src/IconsProvider/IconsProvider.test.js
  packages/components/src/IconsProvider/index.js
  packages/components/src/InlineMessage/InlineMessage.component.js
  packages/components/src/InlineMessage/__snapshots__/InlineMessage.snapshot.test.js.snap
  packages/components/src/Layout/SkipLinks/__snapshots__/SkipLinks.test.js.snap
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/components/src/List/ListComposition/TextFilter/__snapshots__/TextFilter.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooser.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/__snapshots__/ColumnChooserBody.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowCheckbox/RowCheckbox.component.test.js
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooserButton.component.test.js
  packages/components/src/List/Toolbar/Pagination/__snapshots__/Pagination.snapshot.test.js.snap
  packages/components/src/List/Toolbar/SelectSortBy/__snapshots__/SelectSortBy.test.js.snap
  packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/Header.snapshot.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/headerInput.snapshot.test.js.snap
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/Notification/__snapshots__/Notification.snap.test.js.snap
  packages/components/src/Status/Status.component.js
  packages/components/src/Status/__snapshots__/Status.snapshot.test.js.snap
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/components/src/VirtualizedList/CellBoolean/__snapshots__/CellBoolean.test.js.snap
  packages/components/src/index.js
  packages/forms/src/UIForm/fields/Enumeration/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/src/UIForm/fields/ListView/__snapshots__/ListView.component.test.js.snap
  packages/forms/src/deprecated/fields/__snapshots__/CollapsibleFieldset.test.js.snap
  packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Labels: need review
