Repository Talend/ui, pull requests merged in 2022-06, with the labels that each got.

#4068 chore(icons): Add changeset when importing from figma
  .github/workflows/icons.yml
Labels: enhancement, need review, easy review

#4070 feat(icons): search on desc
  packages/icons/.storybook/preview-head.html
  packages/icons/stories/DeprecatedIcons.stories.mdx
  packages/icons/stories/Icon.stories.mdx
  packages/icons/stories/Icon.stories.tsx
  packages/icons/stories/Icon.tsx
  packages/icons/stories/IconsByName.stories.mdx
  packages/icons/stories/IconsBySize.stories.mdx
Labels: enhancement, need review

#4073 fix(assets-api/ARCH-537): use correct meta attribute
  .changeset/odd-falcons-yawn.md
  packages/assets-api/src/index.test.ts
  packages/assets-api/src/index.ts
Labels: need review

#4056 feat(design-system): Add data-feature to Modal
  packages/design-system/src/components/Button/Primitive/ButtonPrimitive.tsx
  packages/design-system/src/components/Modal/Modal.stories.tsx
  packages/design-system/src/components/Modal/Modal.tsx
  packages/design-system/src/types/index.ts
Labels: need review, easy review

#4030 fix(ARCH-515/datagrid): use assets-api to get aggrid
  .changeset/good-mirrors-stare.md
  .changeset/tall-eagles-mix.md
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  tools/scripts-config-ng-webpack/config/webpack.config.js
  tools/scripts-config-ng-webpack/package.json
  tools/scripts-config-react-webpack/config/webpack.config.js
  tools/scripts-config-react-webpack/config/webpack.config.prod.js
  tools/scripts-config-react-webpack/config/webpack.config.umd.js
  tools/scripts-config-react-webpack/package.json
  tools/scripts-utils/README.md
  tools/scripts-utils/babel.js
  tools/scripts-utils/fs.js
  tools/scripts-utils/index.js
  tools/scripts-utils/package.json
Labels: need review

#4083 fix(Containers): add react-dom as peer dep
  .changeset/fast-ducks-stare.md
  packages/containers/package.json
Labels: need review, easy review

#4061 feat(design-system): new icon set for status
  .changeset/silver-pandas-rescue.md
  .github/workflows/visual-testing.yml
  packages/design-system/.storybook/preview.js
  packages/design-system/custom.d.ts
  packages/design-system/package.json
  packages/design-system/src/components/Icon/SizedIcon.tsx
  packages/design-system/src/components/Icon/index.ts
  packages/design-system/src/components/IconsProvider/IconsProvider.tsx
  packages/design-system/src/components/Status/Primitive/StatusPrimitive.tsx
  packages/design-system/src/components/Status/variations/StatusCanceled.tsx
  packages/design-system/src/components/Status/variations/StatusFailed.tsx
  packages/design-system/src/components/Status/variations/StatusSuccessful.tsx
  packages/design-system/src/components/Status/variations/StatusWarning.tsx
  packages/design-system/src/index.ts
Labels: enhancement, need review, easy review, need visual approval

#4090 chore(ci): Enable chromatic on react-forms
  .github/workflows/visual-testing.yml
  packages/forms/package.json
Labels: need visual approval

#4091 fix(router-bridge): Router props not passed
  .changeset/odd-suns-check.md
  packages/router-bridge/src/redux/index.js
  packages/router-bridge/src/router/index.js
  packages/router-bridge/src/router/router-legacy-mode.test.js
  packages/router-bridge/src/router/router-rr5-mode.test.js
Labels: need review

#4064 feat(forms): Use design-system skeleton in FormSkeleton
  packages/forms/src/FormSkeleton.js
  packages/forms/src/FormSkeleton.scss
  packages/forms/src/FormSkeleton.test.js
Labels: need visual approval

#4087 fix(ARCH-537): add peerDependency in manifest
  .changeset/bright-kangaroos-invite.md
  .changeset/orange-moose-kick.md
  fork/dynamic-cdn-webpack-plugin/src/find.js
  fork/dynamic-cdn-webpack-plugin/src/find.test.js
  fork/dynamic-cdn-webpack-plugin/src/index.js
  fork/dynamic-cdn-webpack-plugin/src/resolve-pkg.js
  fork/dynamic-cdn-webpack-plugin/test/core.test.js
  fork/dynamic-cdn-webpack-plugin/test/fixtures/app/package.json
Labels: need review

#4100 fix(TDC-6341): RatioBarLine should use Tooltip from DS
  .changeset/cool-apples-joke.md
  packages/components/src/RatioBar/RatioBarComposition.component.js
  packages/components/src/VirtualizedList/CellQualityBar/__snapshots__/CellQualityBar.test.js.snap
Labels: bug, enhancement, need review, easy review

#4102 fix(TDC-6341): improve RatioBarComposition accessibility
  .changeset/violet-cherries-repeat.md
  packages/components/src/RatioBar/RatioBarComposition.component.js
  packages/components/src/VirtualizedList/CellQualityBar/__snapshots__/CellQualityBar.test.js.snap
Labels: enhancement, need review, easy review

#4101 fix(ARCH-537/fork/bootstrap): add publish access config
  .changeset/two-tables-eat.md
  fork/react-bootstrap/package.json
Labels: need review

#4107 fix(ARCH-537/Forms): build and configure modes
  .changeset/slimy-swans-scream.md
  packages/forms/README.md
  packages/forms/build-utils.js
  packages/forms/package.json
  packages/forms/webpack.ace.config.js
  packages/playground/webpack.config.dev.js
Labels: need review

#4116 fix(design-system): Popover transparent background
  .changeset/curvy-games-suffer.md
  packages/design-system/src/components/Popover/Popover.module.scss
Labels: need review

#4046 feat(design-system/TUX-1081): private Field component
  packages/design-system/src/components/Form/Primitives/Checkbox/Checkbox.tsx
  packages/design-system/src/components/Form/Primitives/Field/Field.tsx
  packages/design-system/src/components/Form/Primitives/Input/Input.tsx
  packages/design-system/src/components/Form/Primitives/InputWrapper/InputWrapper.tsx
  packages/design-system/src/components/Form/Primitives/Label/Label.tsx
  packages/design-system/src/components/Form/Primitives/Primitives.stories.mdx
  packages/design-system/src/components/Form/Primitives/Primitives.stories.tsx
  packages/design-system/src/components/Form/Primitives/Radio/Radio.tsx
  packages/design-system/src/components/Form/Primitives/Textarea/Textarea.tsx
  packages/design-system/src/components/Form/Primitives/_mixins.scss
Labels: need review, easy review

#4121 feat(design-system): allow to control popover
  .changeset/silver-wolves-serve.md
  .changeset/weak-beers-worry.md
  packages/design-system/src/components/Popover/Popover.stories.mdx
  packages/design-system/src/components/Popover/Popover.stories.tsx
  packages/design-system/src/components/Popover/Popover.tsx
Labels: need review

#4126 feat(design-system): FloatingDrawer component
  .changeset/swift-fans-obey.md
  packages/design-system/src/components/Drawer/Drawer.component.tsx
  packages/design-system/src/components/Drawer/Drawer.stories.tsx
  packages/design-system/src/components/Drawer/Drawer.style.ts
  packages/design-system/src/components/Drawer/Primitive/PrimitiveDrawer.scss
  packages/design-system/src/components/Drawer/Primitive/PrimitiveDrawer.tsx
  packages/design-system/src/components/Drawer/docs/Drawer.stories.mdx
  packages/design-system/src/components/Drawer/index.ts
  packages/design-system/src/components/Drawer/variants/FloatingDrawer/FloatingDrawer.scss
  packages/design-system/src/components/Drawer/variants/FloatingDrawer/FloatingDrawer.stories.tsx
  packages/design-system/src/components/Drawer/variants/FloatingDrawer/FloatingDrawer.tsx
  packages/design-system/src/index.ts
  packages/design-system/src/pages/ docs/Pages.stories.tsx
Labels: need review, need visual approval

#4128 fix(ARCH-537): dynamic-cdn use find instead of require.resolve
  .changeset/flat-rivers-wait.md
  fork/dynamic-cdn-webpack-plugin/src/index.js
  fork/dynamic-cdn-webpack-plugin/src/resolve-pkg.js
Labels: need review

#4133 feat(design-system): add BetaTag
  .changeset/fluffy-glasses-accept.md
  packages/design-system/src/components/Tag/Tag.stories.mdx
  packages/design-system/src/components/Tag/Tag.stories.tsx
  packages/design-system/src/components/Tag/Tag.tsx
  packages/design-system/src/components/Tag/index.ts
  packages/design-system/src/components/Tag/variations/TagBeta.module.scss
  packages/design-system/src/components/Tag/variations/TagBeta.tsx
  packages/design-system/src/components/Tag/variations/index.ts
  packages/design-system/src/index.ts
Labels: need review

#4136 feat(compoments): add beta tag for sidepanel
  .changeset/nasty-chairs-push.md
  packages/components/src/ActionList/ActionList.component.js
  packages/components/src/ActionList/ActionList.stories.js
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/SidePanel/SidePanel.stories.js
Labels: need review

#4142 fix(scripts-cmf): path to bin
  .changeset/forty-tools-rest.md
  tools/scripts-cmf/package.json
Labels: need review

#4144 chore(security/react-bootstrap): remove colors from dev deps
  fork/react-bootstrap/package.json
  yarn.lock
Labels: need review

#4137 fix(ARCH-537): add language attribute to i18next mock
  .changeset/wild-owls-warn.md
  tools/scripts-config-jest/test-setup.js
Labels: need review

#4141 feat(components): new icons in old buttons
  .changeset/old-socks-obey.md
  packages/components/src/ActionList/ActionList.scss
  packages/components/src/ActionList/ActionList.stories.js
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionButton/Button.stories.js
  packages/components/src/SidePanel/SidePanel.scss
Labels: need review

#4150 fix(components): align icons in sidepanel
  .changeset/wise-lizards-sell.md
  packages/components/src/SidePanel/SidePanel.scss
  packages/components/src/SidePanel/SidePanel.stories.js
Labels: need review

#4147 feat(design-system/TUX-1191/SizedIcon): Document SizedIcon component in DS
  packages/design-system/.storybook/docs/Icons.tsx
  packages/design-system/.storybook/preview.js
  packages/design-system/src/components/Icon/Icon.stories.mdx
  packages/design-system/src/components/Icon/Icon.tsx
  packages/design-system/src/components/Icon/Icons.stories.mdx
  packages/design-system/src/components/Icon/SizedIcon.stories.mdx
  packages/design-system/src/components/Icon/SizedIcon.stories.tsx
  packages/design-system/src/components/Icon/SizedIcon.tsx
  packages/design-system/src/components/IconsProvider/IconsProvider.tsx
Labels: need review, easy review

#4158 fix(design-system/Dropdown): Default styles should be in CSS module
  .changeset/fluffy-items-applaud.md
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/Primitive/DropdownShell.module.scss
Labels: need review, easy review

#4145 chore(ARCH-537): udpate github url in package.json
  .changeset/silent-cheetahs-count.md
  fork/module-to-cdn/package.json
  tools/babel-plugin-import-d3/package.json
  tools/babel-plugin-import-from-index/package.json
  tools/cypress-api-mock-plugin/package.json
  tools/scripts-build-cdn/package.json
  tools/scripts-config-babel/package.json
  tools/scripts-config-eslint/package.json
  tools/scripts-config-jest/package.json
  tools/scripts-config-ng-webpack/package.json
  tools/scripts-config-prettier/package.json
  tools/scripts-config-react-webpack/package.json
  tools/scripts-config-storybook-lib/package.json
  tools/scripts-config-stylelint/package.json
  tools/scripts-config-typescript/package.json
  tools/scripts-core/package.json
  tools/scripts-preset-react-lib/package.json
  tools/scripts-preset-react/package.json
  tools/upgrade-deps/package.json
Labels: need review

#4166 feat(cmf-router): allow children with composition
  .changeset/real-walls-relax.md
  packages/cmf-router/src/UIRouter.js
  packages/cmf-router/src/index.js
Labels: need review

#4164 fix(TDC-6368): no ellipsis on long subheaderbar titles
  .changeset/serious-bulldogs-hug.md
  packages/components/src/SubHeaderBar/SubHeader.stories.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.scss
Labels: bug, need review, easy review

#4171 fix(design-system/buttonIcon): SVG in ButtonIcon does not register click anymore
  .changeset/odd-bobcats-jump.md
  packages/design-system/src/components/ButtonIcon/Primitive/ButtonIcon.module.scss
Labels: need review, easy review

#4005 chore: upgrade webpack 5
  .changeset/thick-coins-mix.md
  fork/dynamic-cdn-webpack-plugin/.editorconfig
  fork/dynamic-cdn-webpack-plugin/.travis.yml
  fork/dynamic-cdn-webpack-plugin/package.json
  fork/dynamic-cdn-webpack-plugin/readme.md
  fork/dynamic-cdn-webpack-plugin/src/index.js
  fork/dynamic-cdn-webpack-plugin/test/core.test.js
  fork/dynamic-cdn-webpack-plugin/test/helpers/clean-dir.js
  fork/dynamic-cdn-webpack-plugin/test/helpers/run-webpack.js
  fork/dynamic-cdn-webpack-plugin/test/optional-peer-dep.test.js
  fork/dynamic-cdn-webpack-plugin/test/webpack-manifest-plugin.test.js
  package.json
  packages/cmf/__tests__/reducers/componentsReducers.test.js
  packages/cmf/src/bootstrap.js
  packages/design-system/.storybook/main.js
  packages/design-system/cypress/plugins/index.js
  packages/design-system/package.json
  packages/design-tokens/.storybook/main.js
  packages/design-tokens/.storybook/preview-head.html
  packages/icons/.storybook/main.js
  packages/icons/package.json
  packages/icons/webpack.config.js
  packages/icons/webpack.umd.js
  packages/playground/src/app/index.js
  packages/playground/src/assets/inject.js
  packages/playground/src/assets/settings.json
  packages/playground/webpack.config.dev.js
  packages/theme/package.json
  packages/theme/webpack.config.js
  tools/scripts-build-cdn/package.json
  tools/scripts-config-ng-webpack/package.json
  tools/scripts-config-react-webpack/config/webpack.config.common.js
  tools/scripts-config-react-webpack/config/webpack.config.js
  tools/scripts-config-react-webpack/config/webpack.config.prod.js
  tools/scripts-config-react-webpack/config/webpack.config.umd.js
  tools/scripts-config-react-webpack/package.json
  tools/scripts-config-storybook-lib/.storybook-templates/main.js
  tools/scripts-config-storybook-lib/.storybook-templates/preview.js
  tools/scripts-config-storybook-lib/package.json
  tools/scripts-core/config/webpack.config.js
  tools/scripts-core/index.test.js
  tools/scripts-core/package.json
  yarn.lock
Labels: need review

#4176 fix(ARCH-537/storybook): add ThemeProvider import
  .changeset/honest-houses-wave.md
  tools/scripts-config-storybook-lib/.storybook-templates/preview.js
Labels: need review

#4178 fix(component): don't pass rowdata to cell title
  .changeset/pink-gorillas-hug.md
  packages/components/src/VirtualizedList/CellTitle/CellTitleSelector.component.js
Labels: need review
