Repository Talend/ui, pull requests merged in 2022-10, with the labels that each got.

#4374 feat(design-system): add isFullWidth to StackH
  .changeset/cool-socks-repeat.md
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.module.scss
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.tsx
  packages/design-system/src/components/Stack/StackHorizontal.stories.tsx
  packages/design-system/src/components/Stack/StackVertical.tsx
Labels: need review

#4379 fix(TFD-14627): jest config
  .changeset/twenty-horses-brush.md
  tools/scripts-config-jest/jest.config.js
Labels: need review, easy review

#4385 fix(components): quality bar in split mode
  .changeset/cold-toys-tickle.md
  packages/components/src/QualityBar/QualityBar.component.js
  packages/components/src/QualityBar/QualityBar.stories.js
Labels: need review

#4389 feat(TDC-6507): Datagrid header cell dqRule icon
  .changeset/spotty-cats-mix.md
  packages/datagrid/src/components/HeaderCellRenderer/HeaderCellRenderer.component.stories.tsx
  packages/datagrid/src/components/HeaderCellRenderer/HeaderCellRenderer.component.tsx
  packages/datagrid/src/components/HeaderCellRenderer/HeaderCellRenderer.module.scss
  packages/datagrid/src/types/index.ts
Labels: need review, need visual approval

#4395 feat(Combobox): Remove styled components
  .changeset/ten-dryers-accept.md
  packages/design-system/src/components/WIP/Combobox/Combobox.module.scss
  packages/design-system/src/components/WIP/Combobox/Combobox.style.ts
  packages/design-system/src/components/WIP/Combobox/Combobox.tsx
Labels: need review, easy review

#4397 chore: Rewrite welcome page without styled components
  packages/design-system/src/Welcome.module.scss
  packages/design-system/src/Welcome.tsx
Labels: need review, easy review

#4387 feat(design-system/TUX-1212): Stepper component without StyledComponents
  .changeset/slimy-dolphins-relax.md
  packages/components/src/Stepper/Stepper.stories.js
  packages/design-system/src/components/Stepper/Progress/Primitive/Progress.module.scss
  packages/design-system/src/components/Stepper/Progress/Primitive/Progress.tsx
  packages/design-system/src/components/Stepper/Progress/Progress.style.ts
  packages/design-system/src/components/Stepper/Progress/Progress.tsx
  packages/design-system/src/components/Stepper/Progress/index.ts
  packages/design-system/src/components/Stepper/Progress/variations/Progress.horizontal.module.scss
  packages/design-system/src/components/Stepper/Progress/variations/Progress.horizontal.tsx
  packages/design-system/src/components/Stepper/Progress/variations/Progress.vertical.module.scss
  packages/design-system/src/components/Stepper/Progress/variations/Progress.vertical.ts
  packages/design-system/src/components/Stepper/Progress/variations/Progress.vertical.tsx
  packages/design-system/src/components/Stepper/Step/Primitive/Step.module.scss
  packages/design-system/src/components/Stepper/Step/Primitive/Step.tsx
  packages/design-system/src/components/Stepper/Step/Step.style.ts
  packages/design-system/src/components/Stepper/Step/Step.tsx
  packages/design-system/src/components/Stepper/Step/Stepper.Step.stories.mdx
  packages/design-system/src/components/Stepper/Step/Stepper.Step.stories.tsx
  packages/design-system/src/components/Stepper/Step/index.ts
  packages/design-system/src/components/Stepper/Step/variations/Step.Skeleton.module.scss
  packages/design-system/src/components/Stepper/Step/variations/Step.disabled.tsx
  packages/design-system/src/components/Stepper/Step/variations/Step.enabled.tsx
  packages/design-system/src/components/Stepper/Step/variations/Step.error.tsx
  packages/design-system/src/components/Stepper/Step/variations/Step.progress.tsx
  packages/design-system/src/components/Stepper/Step/variations/Step.skeleton.tsx
  packages/design-system/src/components/Stepper/Step/variations/Step.validated.tsx
  packages/design-system/src/components/Stepper/Stepper.module.scss
  packages/design-system/src/components/Stepper/Stepper.stories.mdx
  packages/design-system/src/components/Stepper/Stepper.stories.tsx
  packages/design-system/src/components/Stepper/Stepper.style.ts
  packages/design-system/src/components/Stepper/Stepper.tsx
  packages/design-system/src/components/Stepper/docs/Stepper.step.stories.mdx
  packages/design-system/src/components/Stepper/variations/Stepper.horizontal.ts
  packages/design-system/src/components/Stepper/variations/Stepper.horizontal.tsx
  packages/design-system/src/components/Stepper/variations/Stepper.vertical.ts
  packages/design-system/src/components/Stepper/variations/Stepper.vertical.tsx
Labels: need review, easy review, need visual approval

#4400 feat(design-system/TUX-1212): Removing StyledComponent from doc components
  packages/design-system/.storybook/docs/Area.module.scss
  packages/design-system/.storybook/docs/Area.tsx
  packages/design-system/.storybook/docs/Card.module.scss
  packages/design-system/.storybook/docs/Card.tsx
  packages/design-system/.storybook/docs/FigmaIframe.module.scss
  packages/design-system/.storybook/docs/FigmaIframe.tsx
  packages/design-system/.storybook/docs/FigmaImage.module.scss
  packages/design-system/.storybook/docs/FigmaImage.tsx
  packages/design-system/.storybook/docs/Grid.module.scss
  packages/design-system/.storybook/docs/Grid.tsx
  packages/design-system/.storybook/docs/Themes.tsx
  packages/design-system/.storybook/docs/Use.module.scss
  packages/design-system/.storybook/docs/Use.tsx
  packages/design-system/.storybook/docs/index.ts
  packages/design-system/.storybook/main.js
  packages/design-system/src/deprecatedTokens/docs/Tokens.stories.mdx
  packages/design-system/src/themes/docs/Themes.stories.mdx
Labels: need review, easy review

#4406 chore(ARCH-658): pin react router
  .changeset/empty-maps-swim.md
  packages/cmf-router/package.json
  packages/design-system/package.json
  packages/router-bridge/package.json
  yarn.lock
Labels: need review
