Repository Talend/ui, pull requests merged in 2022-01, with the labels that each got.

#3595 fix(component): typehead icon is not aligned
  .changeset/blue-phones-hide.md
  packages/components/src/Typeahead/Typeahead.scss
  size.json
Labels: need review

#3558 feat(Design-System/Stack): Creating layout component Stack
  .changeset/lazy-roses-rule.md
  packages/design-system/.eslintrc
  packages/design-system/custom.d.ts
  packages/design-system/package.json
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.module.scss
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.tsx
  packages/design-system/src/components/Stack/Stack.stories.mdx
  packages/design-system/src/components/Stack/StackHorizontal.stories.tsx
  packages/design-system/src/components/Stack/StackHorizontal.tsx
  packages/design-system/src/components/Stack/StackItem.module.scss
  packages/design-system/src/components/Stack/StackItem.tsx
  packages/design-system/src/components/Stack/StackVertical.stories.tsx
  packages/design-system/src/components/Stack/StackVertical.tsx
  packages/design-system/src/components/Stack/index.ts
  packages/design-system/tsconfig.json
  packages/design-system/yarn.lock
Labels: enhancement, need review

#3592 feat(cmf): Saga Component
  .changeset/lazy-poets-crash.md
  packages/cmf/src/bootstrap.js
  packages/cmf/src/components/Saga/CmfRegisteredSaga.component.js
  packages/cmf/src/components/Saga/CmfRegisteredSaga.component.test.js
  packages/cmf/src/components/Saga/Saga.component.js
  packages/cmf/src/components/Saga/Saga.component.md
  packages/cmf/src/components/Saga/Saga.component.test.js
  packages/cmf/src/components/Saga/Saga.saga.js
  packages/cmf/src/components/Saga/Saga.saga.test.js
  packages/cmf/src/components/Saga/index.js
  packages/cmf/src/index.js
  size.json
Labels: need review

#3602 fix(design-system): ts errors
  .changeset/funny-poems-joke.md
  packages/design-system/cypress/support/index.d.ts
  packages/design-system/cypress/tsconfig.json
  packages/design-system/jest.config.js
  packages/design-system/package.json
  packages/design-system/src/components/Button/Button.spec.tsx
  packages/design-system/src/components/Button/Button.stories.tsx
  packages/design-system/src/components/Button/variations/Button.icon.tsx
  packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
  packages/design-system/src/components/Form/Field/Field.stories.tsx
  packages/design-system/src/components/Form/Field/Field.tsx
  packages/design-system/src/components/Form/Field/Input/Input.Checkbox.tsx
  packages/design-system/src/components/Form/Field/Input/Input.Copy.tsx
  packages/design-system/src/components/Form/Field/Input/Password/Password.stories.tsx
  packages/design-system/src/components/Form/FieldGroup/FieldGroup.tsx
  packages/design-system/src/components/HeaderBar/HeaderBar.style.ts
  packages/design-system/src/components/InlineEditing/InlineEditing.stories.tsx
  packages/design-system/src/components/InlineMessage/InlineMessage.stories.tsx
  packages/design-system/src/components/Layout/Footer.tsx
  packages/design-system/src/components/Layout/Nav.tsx
  packages/design-system/src/components/Menu/Menu.tsx
  packages/design-system/src/components/Menu/MenuItem.tsx
  packages/design-system/src/components/Status/index.ts
  packages/design-system/src/components/Tag/Tag.stories.tsx
  packages/design-system/src/components/Toggle/Toggle.spec.tsx
  packages/design-system/src/components/Tooltip/Tooltip.stories.tsx
  packages/design-system/src/pages/ docs/Pages.stories.js
  packages/design-system/src/pages/Home.tsx
  packages/design-system/src/pages/Login.tsx
  packages/design-system/src/pages/blocks/Footer.js
  packages/design-system/src/pages/blocks/HeaderBar.js
  packages/design-system/src/pages/blocks/Menu.js
  packages/design-system/src/pages/blocks/SignupCTA.js
  packages/design-system/src/pages/index.ts
  packages/design-system/src/templates/Step.tsx
  packages/design-system/tsconfig.json
  size.json
  yarn.lock
Labels: need review, easy review, need visual approval

#3607 fix(design-system): build with design tokens
  .changeset/light-insects-boil.md
  packages/design-system/package.json
  packages/design-system/src/components/Stack/StackHorizontal.stories.tsx
  packages/design-system/src/components/Stack/StackVertical.stories.tsx
Labels: need review, easy review

#3586 chore(Design-System/Status): Updated using tokens and CSS modules
  packages/design-system/.storybook/preview.js
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.module.scss
  packages/design-system/src/components/Status/Primitive/Status.module.scss
  packages/design-system/src/components/Status/Primitive/StatusPrimitive.tsx
  packages/design-system/src/components/Status/Status.stories.mdx
  packages/design-system/src/components/Status/Status.stories.tsx
  packages/design-system/src/components/Status/Status.style.ts
  packages/design-system/src/components/Status/Status.tsx
  packages/design-system/src/components/Status/index.ts
  packages/design-system/src/components/Status/variations/Status.canceled.ts
  packages/design-system/src/components/Status/variations/Status.failed.ts
  packages/design-system/src/components/Status/variations/Status.inprogress.ts
  packages/design-system/src/components/Status/variations/Status.successful.ts
  packages/design-system/src/components/Status/variations/Status.warning.ts
  packages/design-system/src/components/Status/variations/StatusCanceled.tsx
  packages/design-system/src/components/Status/variations/StatusFailed.tsx
  packages/design-system/src/components/Status/variations/StatusInProgress.tsx
  packages/design-system/src/components/Status/variations/StatusSuccessful.tsx
  packages/design-system/src/components/Status/variations/StatusWarning.tsx
  packages/design-system/src/components/ThemeProvider/ThemeProvider.tsx
  packages/design-system/src/index.js
  size.json
Labels: need review

#3608 fix(components): Toggle should reuse Checkbox
  .changeset/angry-windows-pretend.md
  packages/components/src/Checkbox/Checkbox.js
  packages/components/src/Enumeration/__snapshots__/Enumeration.snapshot.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/__snapshots__/ColumnChooserBody.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserRow/RowCheckbox/__snapshots__/RowCheckbox.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/SelectAllColumnsCheckbox/__snapshots__/SelectAllColumnsCheckbox.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/ListView/Items/Item/__snapshots__/item.snapshot.test.js.snap
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/Toggle/Toggle.component.js
  packages/components/src/Toggle/Toggle.scss
  packages/components/src/Toggle/__snapshots__/Toggle.snapshot.test.js.snap
  packages/components/src/VirtualizedList/HeaderCheckbox/__snapshots__/HeaderCheckbox.test.js.snap
  size.json
Labels: need review, easy review

#3614 chore(CI): UMD size check
  .github/workflows/pr-playground.yml
  package.json
  size.js
  size.json
Labels: need review, easy review

#3615 chore(components): remove E2E helpers
  .gitignore
  packages/components/.npmignore
  packages/components/e2e/component-objects/README.md
  packages/components/e2e/component-objects/pom.xml
  packages/components/e2e/component-objects/src/main/java/org/talend/component/ActionList.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/AppHeaderBar.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/Application.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/Component.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/ConfirmDialog.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/Drawer.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/List.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/Notification.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/SidePanel.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/TabBar.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/Cell.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/Display.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/Item.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/ListDisplay.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/display/Large.java
  packages/components/e2e/component-objects/src/main/java/org/talend/component/list/display/Table.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/ActionListTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/AppHeaderBarTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/ListTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/NotificationTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/SidePanelTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/StorybookTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/TabBarTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/LargeTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/component/display/TableTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/BrowserStackWebDriverTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/LocalWebDriverTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/WebDriverTest.java
  packages/components/e2e/component-objects/src/test/java/org/talend/config/WebDriverTestFactory.java
  packages/components/e2e/component-objects/src/test/resources/log4j2.xml
Labels: need review, easy review

#3627 chore(Surge): DS build
  .github/workflows/design-system-deploy.yml
  .github/workflows/pr-demo.yml
Labels: enhancement, need review, easy review

#3634 fix(design-system): remove hardcoded string in the input file component
  .changeset/brown-impalas-attack.md
  packages/design-system/src/components/Form/Field/Input/Input.File.tsx
Labels: enhancement, need review, easy review

#3636 chore(design-system): Chromatic GH Action
  .github/workflows/design-system-visual-testing.yml
Labels: need review, easy review

#3637 fix(ARCH-421/OverlayTrigger): use portal
  .changeset/stupid-bears-flow.md
  packages/components/src/Actions/ActionButton/ActionButton.component.js
  packages/components/src/Actions/ActionDropdown/ActionDropdown.component.js
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/Actions/ActionIconToggle/ActionIconToggle.component.js
  packages/components/src/Actions/Actions.component.js
  packages/components/src/CollapsiblePanel/CollapsiblePanel.component.js
  packages/components/src/OverlayTrigger/OverlayTrigger.component.js
  packages/components/src/OverlayTrigger/OverlayTrigger.forked.js
  packages/components/src/OverlayTrigger/OverlayTrigger.test.js
  packages/components/src/OverlayTrigger/__snapshots__/OverlayTrigger.test.js.snap
  packages/components/src/PieChart/PieChart.component.js
  packages/components/src/PieChart/PieChartButton.component.js
  packages/components/src/PieChart/__snapshots__/PieChartButton.test.js.snap
  packages/components/src/TabBar/TabBar.component.js
  packages/containers/.storybook/ComponentOverlay.js
  yarn.lock
Labels: need review

#3628 test(ARCH-421/cmf): migrate to testing library
  .changeset/pretty-cycles-exercise.md
  package.json
  packages/cmf-cqrs/package.json
  packages/cmf-router/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/README.md
  packages/cmf/__tests__/App.test.js
  packages/cmf/__tests__/Dispatcher.test.js
  packages/cmf/__tests__/Inject.test.js
  packages/cmf/__tests__/__snapshots__/cmfConnect.test.js.snap
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/__tests__/cmfModule.merge.test.js
  packages/cmf/__tests__/expression.test.js
  packages/cmf/__tests__/middlewares/http.test.js
  packages/cmf/__tests__/settings.test.js
  packages/cmf/package.json
  packages/cmf/src/Inject.component.js
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/cmfConnect.md
  packages/cmf/src/cmfModule.js
  packages/cmf/src/components/ErrorBoundary/ErrorBoundary.component.test.js
  packages/cmf/src/components/ErrorFeedBack/ErrorFeedBack.component.test.js
  packages/cmf/src/components/ErrorPanel/ErrorPanel.component.test.js
  packages/cmf/src/components/ErrorPanel/__snapshots__/ErrorPanel.component.test.js.snap
  packages/cmf/src/components/Saga/CmfRegisteredSaga.component.test.js
  packages/cmf/src/components/Saga/Saga.component.test.js
  packages/cmf/src/expression.js
  packages/cmf/src/mock/provider.js
  packages/cmf/src/settings.js
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/design-system/.eslintrc
  packages/design-system/.eslintrc.js
  packages/design-system/package.json
  packages/design-system/src/components/Icon/__snapshots__/Icon.test.js.snap
  packages/design-tokens/package.json
  packages/faceted-search/.eslintrc
  packages/faceted-search/package.json
  packages/flow-designer/package.json
  packages/forms/package.json
  packages/jsfc/package.json
  packages/playground/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
  packages/utils/package.json
  yarn.lock
Labels: enhancement, need review, dependencies

#3645 fix(flow-designer): handle some component position
  .changeset/tender-stingrays-wink.md
  packages/flow-designer/src/reducers/flow.reducer.ts
Labels: need review

#3646 fix(design-system): add tsconfig rootDir
  .changeset/violet-icons-rule.md
  packages/design-system/tsconfig.json
Labels: need review

#3655 chore(design-system): Usage story was not rendering
  packages/design-system/src/components/InlineMessage/InlineMessage.stories.tsx
  packages/design-system/src/components/InlineMessage/docs/InlineMessage.stories.mdx
Labels: need review, easy review, need visual approval

#3660 fix(design-system): tooltip with css modules
  .changeset/nine-pigs-speak.md
  packages/design-system/src/components/Tooltip/Tooltip.module.scss
  packages/design-system/src/components/Tooltip/Tooltip.stories.mdx
  packages/design-system/src/components/Tooltip/Tooltip.stories.tsx
  packages/design-system/src/components/Tooltip/Tooltip.style.ts
  packages/design-system/src/components/Tooltip/Tooltip.tsx
Labels: need review, easy review

#3661 fix: update withDrawer z-index
  .changeset/kind-pigs-brush.md
  packages/components/src/WithDrawer/withDrawer.scss
Labels: need review
