Repository Talend/ui, pull requests merged in 2022-03, with the labels that each got.

#3743 chore(changeset): set proper PAT to create changeset PR
  .github/workflows/changeset.yml
Labels: need review

#3747 chore(ARCH-466/Dataviz): storybook via ui-scripts
  packages/dataviz/.storybook/main.js
  packages/dataviz/.storybook/preview-head.html
  packages/dataviz/.storybook/preview.js
  packages/dataviz/.storybook/webpack.config.js
  packages/dataviz/package.json
Labels: need review

#3745 chore(ARCH-466/Datagrid): storybook via ui-scripts
  packages/datagrid/.storybook/cmfModule/actionCreators.js
  packages/datagrid/.storybook/cmfModule/components.js
  packages/datagrid/.storybook/cmfModule/index.js
  packages/datagrid/.storybook/cmfModule/middlewares.js
  packages/datagrid/.storybook/cmfModule/preloadedState.js
  packages/datagrid/.storybook/cmfModule/settings.js
  packages/datagrid/.storybook/main.js
  packages/datagrid/.storybook/preview-head.html
  packages/datagrid/.storybook/preview.js
  packages/datagrid/.storybook/webpack.config.js
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/datagrid.component.stories.js
  packages/datagrid/src/containers/datagrid.container.stories.js
Labels: need review

#3750 chore(ARCH-466/Faceted-Search): storybook via ui-scripts
  packages/faceted-search/.storybook/i18n.js
  packages/faceted-search/.storybook/main.js
  packages/faceted-search/.storybook/preview-head.html
  packages/faceted-search/.storybook/preview.js
  packages/faceted-search/.storybook/webpack.config.js
  packages/faceted-search/package.json
  packages/faceted-search/stories/facetedSearch.stories.js
Labels: need review

#3758 chore(ARCH-466/Stepper): remove storybook
  .github/workflows/before-surge.sh
  .surge/index.html
  packages/stepper/.storybook/addons.js
  packages/stepper/.storybook/config.js
  packages/stepper/.storybook/preview-head.html
  packages/stepper/.storybook/webpack.config.js
  packages/stepper/package.json
  packages/stepper/stories/index.js
  packages/stepper/stories/stepper.component.js
  packages/stepper/stories/style.scss
Labels: need review

#3763 doc(design-system): remove remark plugin
  packages/design-system/.storybook/main.js
Labels: enhancement, need review, easy review

#3765 feat(icons): field-remover.svg
  .changeset/spicy-camels-judge.md
  packages/icons/src/svg/processors/field-remover.svg
Labels: need review, easy review

#3764 fix(ARCH-465/design-tokens): umd are not well defined
  .changeset/sixty-mirrors-chew.md
  packages/design-tokens/package.json
  packages/design-tokens/scripts/umd.test.js
  packages/design-tokens/src/index.umd.ts
  packages/design-tokens/webpack.config.js
Labels: need review

#3766 fix(design-system): export AffixButton
  .changeset/sixty-yaks-jam.md
  packages/design-system/src/components/Form/Field/Input/Input.Copy.tsx
  packages/design-system/src/components/Form/FieldGroup/Affix/AffixStyles.module.scss
  packages/design-system/src/components/Form/FieldGroup/Affix/index.ts
  packages/design-system/src/components/Form/FieldGroup/Affix/variations/AffixButton.tsx
  packages/design-system/src/components/Form/FieldGroup/Affix/variations/AffixReadOnly.tsx
  packages/design-system/src/components/Form/FieldGroup/FieldGroup.tsx
  packages/design-system/src/components/Form/docs/Input.group.stories.mdx
  packages/design-system/src/index.ts
Labels: need review, easy review

#3730 doc: add ADR for dependencies in package.json
  docs/adr-dependencies.md
Labels: need review

#3776 test(components): avoid tests over timezone with DST
  packages/components/src/DateTimePickers/DateTime/datetime-extraction.test.js
Labels: need review, easy review

#3761 feat(Design-System): TUX-1145 - Breadcrumbs
  packages/design-system/.storybook/preview.js
  packages/design-system/DOCTEMPLATE.md
  packages/design-system/MIGRATING.md
  packages/design-system/src/Catalog.stories.mdx
  packages/design-system/src/components/Breadcrumbs/Breadcrumbs.module.scss
  packages/design-system/src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  packages/design-system/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  packages/design-system/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/design-system/src/components/Button/Primitive/ButtonStyles.module.scss
  packages/design-system/src/components/Button/variations/ButtonSecondary.module.scss
  packages/design-system/src/components/Button/variations/ButtonTertiary.module.scss
  packages/design-system/src/components/Clickable/Clickable.tsx
  packages/design-system/src/components/Divider/Divider.module.scss
  packages/design-system/src/components/Dropdown/Dropdown.spec.tsx
  packages/design-system/src/components/Dropdown/Dropdown.stories.mdx
  packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
  packages/design-system/src/components/Dropdown/Dropdown.style.ts
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/Primitive/DropdownButton.tsx
  packages/design-system/src/components/Dropdown/Primitive/DropdownDivider.module.scss
  packages/design-system/src/components/Dropdown/Primitive/DropdownDivider.tsx
  packages/design-system/src/components/Dropdown/Primitive/DropdownEntry.module.scss
  packages/design-system/src/components/Dropdown/Primitive/DropdownLink.tsx
  packages/design-system/src/components/Dropdown/Primitive/DropdownShell.module.scss
  packages/design-system/src/components/Dropdown/Primitive/DropdownShell.tsx
  packages/design-system/src/components/Dropdown/Primitive/DropdownTitle.module.scss
  packages/design-system/src/components/Dropdown/Primitive/DropdownTitle.tsx
  packages/design-system/src/components/Dropdown/index.ts
  packages/design-system/src/components/Link/Link.module.scss
  packages/design-system/src/components/Linkable/Linkable.tsx
  packages/design-system/src/components/Linkable/LinkableStyles.module.scss
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.module.scss
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.tsx
Labels: need review

#3799 fix(design-system): dropdown fix in headerbar
  .changeset/purple-foxes-sing.md
  packages/design-system/MIGRATING.md
  packages/design-system/src/components/Form/Buttons/Buttons.style.ts
  packages/design-system/src/components/HeaderBar/docs/HeaderBar.js
  packages/design-system/src/components/HeaderBar/docs/HeaderBar.stories.jsx
  packages/design-system/src/components/HeaderBar/docs/HeaderBar.stories.mdx
  packages/design-system/src/pages/blocks/HeaderBar.js
Labels: need review

#3798 fix(Datalist): allow to open clicking on the caret
  .changeset/grumpy-monkeys-yawn.md
  packages/components/src/Typeahead/Typeahead.scss
Labels: need review

#3801 chore: update @talend/scripts
  yarn.lock
Labels: need review

#3802 fix(cmf): test in node 16
  .changeset/eight-mugs-obey.md
  packages/cmf/__tests__/middlewares/http.test.js
  packages/cmf/src/middlewares/http/middleware.js
Labels: need review

#3813 fix(design-system): prettier
  package.json
  yarn.lock
Labels: bug, need review, easy review

#3797 chore(ARCH-482): refactor datalist to remove deprecated lifecycle
  packages/components/package.json
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/src/Datalist/__snapshots__/Datalist.component.test.js.snap
  packages/forms/stories/json/fields/core-datalist.json
  yarn.lock
Labels: need review

#3815 test(ARCH-482): migrate AboutDialog to RTL
  packages/components/package.json
  packages/components/src/AboutDialog/AboutDialog.component.js
  packages/components/src/AboutDialog/AboutDialog.snapshot.test.js
  packages/components/src/AboutDialog/AboutDialog.test.js
  packages/components/src/AboutDialog/__snapshots__/AboutDialog.snapshot.test.js.snap
  yarn.lock
Labels: need review

#3819 chore(testing-library): fix user-event lib version and RTL tests
  .changeset/spotty-spies-cheat.md
  packages/components/package.json
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
  yarn.lock
Labels: need review

#3817 chore(ARCH-482/DateTimePickers): remove deprecated lifecycle
  .changeset/long-flies-fix.md
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Manager/Manager.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/DateTime/Manager/Manager.component.test.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/DateTimePicker/DateTimePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/YearPicker/YearPicker.component.js
  packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.component.js
  packages/components/src/DateTimePickers/pickers/YearPicker/YearPicker.component.js
Labels: need review
