Repository Talend/ui, pull requests merged in 2022-04, with the labels that each got.

#3829 chore(ARCH-482/ComponentForm): remove deprecated lifecycle
  .changeset/twelve-nails-exercise.md
  packages/containers/.storybook/preview.js
  packages/containers/src/ComponentForm/ComponentForm.component.js
  packages/containers/src/Form/Form.stories.js
Labels: need review

#3843 chore(ARCH-497): dynamic-cdn-webpack-plugin do not need build
  .changeset/nervous-days-chew.md
  .changeset/old-teachers-marry.md
  .github/workflows/design-system-component-testing.yml
  .github/workflows/design-system-deploy.yml
  .github/workflows/design-system-visual-testing.yml
  fork/dynamic-cdn-webpack-plugin/index.js
  fork/dynamic-cdn-webpack-plugin/package.json
  fork/dynamic-cdn-webpack-plugin/src/find.js
  fork/dynamic-cdn-webpack-plugin/src/find.test.js
  fork/dynamic-cdn-webpack-plugin/src/get-resolver.js
  fork/dynamic-cdn-webpack-plugin/src/index.js
  fork/dynamic-cdn-webpack-plugin/src/resolve-pkg.js
  fork/dynamic-cdn-webpack-plugin/test/core.test.js
  fork/dynamic-cdn-webpack-plugin/test/html-webpack-plugin.test.js
  fork/dynamic-cdn-webpack-plugin/test/optional-peer-dep.test.js
  fork/dynamic-cdn-webpack-plugin/test/webpack-manifest-plugin.test.js
  package.json
  packages/design-tokens/package.json
  packages/design-tokens/yarn.lock
  packages/playground/webpack.config.dev.js
  tools/scripts-config-cdn/cdn.js
Labels: need review

#3849 chore(cypress): github action
  .github/workflows/design-system-component-testing.yml
Labels: need review, easy review

#3844 fix: Bring back @talend libs in TALEND_APP_INFO
  .changeset/chilly-cows-drive.md
  tools/scripts-config-react-webpack/config/webpack.config.js
Labels: need review

#3855 fix: add missing src files to release
  .changeset/stupid-yaks-heal.md
  fork/dynamic-cdn-webpack-plugin/package.json
Labels: need review

#3859 fix: sentry browser
  .changeset/ninety-candles-push.md
  fork/module-to-cdn/modules.json
Labels: need review

#3861 fix(list): make hover work again with tc-list-item
  .changeset/young-frogs-walk.md
  packages/components/src/List/ListComposition/LazyLoadingList/__snapshots__/LazyLoadingList.component.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/VirtualizedList/ListTable/ListTable.component.js
  packages/components/src/VirtualizedList/ListTable/__snapshots__/ListTable.test.js.snap
Labels: need review

#3846 feat(faceted-search): replace faceted mode toggle by design system switch component
  .changeset/tiny-rocks-drive.md
  packages/faceted-search/.storybook/preview.js
  packages/faceted-search/package.json
  packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
Labels: need review, dependencies

#3858 fix(Datalist): focus management on inside element click
  .changeset/lucky-seas-flash.md
  packages/components/src/Typeahead/Typeahead.component.js
  packages/components/src/Typeahead/Typeahead.component.renderers.js
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
  yarn.lock
Labels: need review

#3865 fix(ComponentForm): infinite rendering because of new Map ref everytime
  .changeset/small-bugs-melt.md
  packages/containers/src/ComponentForm/ComponentForm.component.js
Labels: need review

#3869 chore(ARCH-497): remove ng tools
  packages/jsfc/package.json
  tools/scripts-config-karma/CHANGELOG.md
  tools/scripts-config-karma/README.md
  tools/scripts-config-karma/index.js
  tools/scripts-config-karma/karma.conf.js
  tools/scripts-config-karma/package.json
  tools/scripts-config-karma/webpack.config.js
  tools/scripts-config-karma/yarn.lock
  tools/scripts-preset-react-ng/CHANGELOG.md
  tools/scripts-preset-react-ng/README.md
  tools/scripts-preset-react-ng/index.js
  tools/scripts-preset-react-ng/package.json
  tools/scripts-preset-react-ng/yarn.lock
  yarn.lock
Labels: need review

#3845 chore(ARCH-482/EnumerationWidget): remove deprecated lifecycle and use RTL for tests
  .changeset/eighty-kings-sip.md
  packages/forms/src/deprecated/widgets/EnumerationWidget/EnumerationWidget.js
  packages/forms/src/deprecated/widgets/EnumerationWidget/EnumerationWidget.test.js
  packages/forms/src/deprecated/widgets/EnumerationWidget/__snapshots__/EnumerationWidget.test.js.snap
Labels: need review

#3867 chore(ARCH-482/ListViewWidget): remove deprecated lifecycle and use RTL for tests
  .changeset/young-bears-deny.md
  packages/forms/src/deprecated/widgets/ListViewWidget/ListViewWidget.js
  packages/forms/src/deprecated/widgets/ListViewWidget/ListViewWidget.test.js
Labels: need review

#3783 feat(cmf-cqrs): add use-websocket hook
  .changeset/dull-scissors-juggle.md
  packages/cmf-cqrs/README.md
  packages/cmf-cqrs/package.json
  packages/cmf-cqrs/src/constants/index.js
  packages/cmf-cqrs/src/constants/status.js
  packages/cmf-cqrs/src/hooks.test.ts
  packages/cmf-cqrs/src/hooks.ts
  packages/cmf-cqrs/src/index.ts
  packages/cmf-cqrs/src/middleware/smartWebsocket.js
  packages/cmf-cqrs/src/registry.js
  packages/cmf-cqrs/tsconfig.build.json
  packages/cmf-cqrs/tsconfig.json
  yarn.lock
Labels: need review

#3870 chore(ARCH-482/MultiSelectTagWidget): remove deprecated lifecycle and use RTL for tests
  .changeset/nice-guests-jog.md
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/MultiSelectTagWidget.js
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/MultiSelectTagWidget.test.js
  packages/forms/src/deprecated/widgets/MultiSelectTagWidget/__snapshots__/MultiSelectTagWidget.test.js.snap
Labels: need review

#3877 fix(AboutModal): rendering issue while empty table
  .changeset/violet-moles-roll.md
  packages/components/src/AboutDialog/AboutDialogTable.component.js
Labels: need review

#3889 fix(multiselect): add height when no option
  .changeset/wise-beers-wonder.md
  packages/components/src/MultiSelect/MultiSelect.container.js
  packages/components/src/MultiSelect/MultiSelect.stories.js
Labels: need review

#3891 chore(ci): Trigger visual NR on push
  .github/workflows/design-system-visual-testing.yml
Labels: need visual approval

#3893 qchore(ci): Broken github action
  .github/workflows/design-system-visual-testing.yml
Labels: need visual approval

#3894 chore(design-system): Action for visual testing on PR ready
  .github/workflows/design-system-visual-testing.yml
Labels: need visual approval

#3873 chore(ARCH-482/UIForm): remove deprecated lifecycle and use RTL for tests
  .changeset/gold-panthers-sleep.md
  packages/forms/__mocks__/data.js
  packages/forms/src/UIForm/UIForm.component.js
  packages/forms/src/UIForm/UIForm.component.test.js
  packages/forms/src/UIForm/UIForm.container.js
  packages/forms/src/UIForm/UIForm.container.test.js
  packages/forms/src/UIForm/__snapshots__/UIForm.component.test.js.snap
  packages/forms/src/UIForm/__snapshots__/UIForm.container.test.js.snap
Labels: need review

#3781 feat(design-system): Empty States
  .changeset/healthy-stingrays-design.md
  packages/design-system/.storybook/preview.js
  packages/design-system/package.json
  packages/design-system/src/components/EmptyState/EmptyState.stories.mdx
  packages/design-system/src/components/EmptyState/EmptyState.stories.tsx
  packages/design-system/src/components/EmptyState/EmptyState.tsx
  packages/design-system/src/components/EmptyState/illustrations/IconDefault.module.scss
  packages/design-system/src/components/EmptyState/illustrations/IconDefault.tsx
  packages/design-system/src/components/EmptyState/illustrations/SpotDefault.module.scss
  packages/design-system/src/components/EmptyState/illustrations/SpotDefault.tsx
  packages/design-system/src/components/EmptyState/index.ts
  packages/design-system/src/components/EmptyState/primitive/EmptyStatePrimitive.module.scss
  packages/design-system/src/components/EmptyState/primitive/EmptyStatePrimitive.tsx
  packages/design-system/src/components/EmptyState/variants/EmptyStateLarge.tsx
  packages/design-system/src/components/EmptyState/variants/EmptyStateMedium.tsx
  packages/design-system/src/components/EmptyState/variants/EmptyStateSmall.tsx
  packages/design-system/src/index.ts
Labels: need review, need visual approval

#3896 doc(design-system): Updating template and guidelines
  .github/workflows/design-system-visual-testing.yml
  packages/design-system/CONTRIBUTING.md
  packages/design-system/DOCTEMPLATE.md
Labels: need visual approval

#3898 chore(ARCH-482/FlowDesigner): remove deprecated lifecycle
  .changeset/great-masks-impress.md
  packages/flow-designer/src/components/FlowDesigner.container.tsx
  packages/flow-designer/src/components/ZoomHandler.component.tsx
  packages/flow-designer/src/components/node/AbstractNode.component.tsx
Labels: need review

#3908 fix(Datalist): keep suggestions when clicking inside the suggestion box
  .changeset/tall-bags-boil.md
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
Labels: need review

#3903 chore(ARCH-482/ListView): remove deprecated lifecycle and use RTL for test
  .changeset/loud-dingos-swim.md
  packages/components/src/Checkbox/Checkbox.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.js
  packages/forms/src/UIForm/fields/ListView/ListView.component.test.js
  packages/forms/src/UIForm/fields/ListView/__snapshots__/ListView.component.test.js.snap
  packages/forms/src/deprecated/widgets/ListViewWidget/ListViewWidget.test.js
Labels: need review

#3902 chore(ARCH-482/EnumerationWidget): remove deprecated lifecycle and use RTL for test
  .changeset/popular-suits-jog.md
  packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
  packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.test.js
  packages/forms/src/UIForm/fields/Enumeration/__snapshots__/EnumerationWidget.test.js.snap
  packages/forms/src/deprecated/widgets/EnumerationWidget/EnumerationWidget.test.js
Labels: need review

#3871 test(ARCH-497/module-to-cdn): fix tests and move them to cron
  .github/workflows/tests-cron.yml
  fork/module-to-cdn/index.test.js
  fork/module-to-cdn/modules.test.js
  fork/module-to-cdn/package.json
  package.json
Labels: need review

#3905 chore: remove deprecated tools
  codemodes/cmf/README.md
  codemodes/cmf/api_to_index.js
  codemodes/cmf/componentState_to_cmfConnect.js
  codemodes/cmf/omitCMFProps.js
  codemodes/cmf/package.json
  codemodes/cmf/yarn.lock
  codemodes/i18next/from_9_to_15.js
  codemodes/migrate_actions_settings_expressions.js
  codemodes/talend-ui-imports/codemod.js
  codemodes/talend-ui-imports/replace-imports.sh
Labels: need review

#3906 chore: upgrade dependencies
  fork/module-to-cdn/package.json
  package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/design-system/package.json
  packages/faceted-search/package.json
  packages/flow-designer/package.json
  packages/forms/package.json
  packages/playground/package.json
  packages/router-bridge/package.json
  packages/stepper/package.json
  tools/babel-plugin-assets-api/package.json
  tools/babel-plugin-import-from-index/package.json
  tools/eslint-plugin/package.json
  tools/scripts-build-cdn/package.json
  tools/scripts-config-cdn/package.json
  tools/scripts-config-eslint/package.json
  tools/scripts-config-jest/package.json
  tools/scripts-config-react-webpack/package.json
  tools/scripts-config-storybook-lib/package.json
  tools/scripts-preset-react-lib/package.json
  tools/scripts-preset-react/package.json
  tools/scripts-publish-local/package.json
  tools/upgrade-deps/package.json
  yarn.lock
Labels: need review

#3907 chore: remove DS warnings in tests
  .changeset/hot-wolves-drive.md
  packages/components/src/ActionIntercom/__snapshots__/Intercom.component.test.js.snap
  packages/components/src/Actions/ActionDropdown/__snapshots__/ActionDropdown.snapshot.test.js.snap
  packages/components/src/AppSwitcher/__snapshots__/AppSwitcher.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeDelete/__snapshots__/BadgeDelete.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeDropdown/__snapshots__/BadgeDropdown.component.test.js.snap
  packages/components/src/Badge/BadgeComposition/BadgeIcon/__snapshots__/BadgeIcon.component.test.js.snap
  packages/components/src/CollapsiblePanel/__snapshots__/CollapsiblePanel.snapshot.test.js.snap
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/__snapshots__/InputDateTimeRangePicker.component.test.js.snap
  packages/components/src/HttpError/__snapshots__/HttpError.snapshot.test.js.snap
  packages/components/src/InlineMessage/__snapshots__/InlineMessage.snapshot.test.js.snap
  packages/components/src/Layout/SkipLinks/__snapshots__/SkipLinks.test.js.snap
  packages/components/src/List/ListComposition/DisplayMode/__snapshots__/ListDisplayMode.component.test.js.snap
  packages/components/src/List/ListComposition/TextFilter/__snapshots__/TextFilter.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/ColumnChooserBody/__snapshots__/ColumnChooserBody.component.test.js.snap
  packages/components/src/List/Toolbar/ColumnChooserButton/ColumnChooser/__snapshots__/ColumnChooser.component.test.js.snap
  packages/components/src/List/Toolbar/Pagination/__snapshots__/Pagination.snapshot.test.js.snap
  packages/components/src/List/Toolbar/SelectSortBy/__snapshots__/SelectSortBy.test.js.snap
  packages/components/src/List/Toolbar/__snapshots__/Toolbar.snapshot.test.js.snap
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/Header.snapshot.test.js.snap
  packages/components/src/ListView/Header/__snapshots__/headerInput.snapshot.test.js.snap
  packages/components/src/ListView/Items/__snapshots__/items.test.js.snap
  packages/components/src/Status/__snapshots__/Status.snapshot.test.js.snap
  packages/components/src/Typeahead/__snapshots__/Typeahead.snapshot.test.js.snap
  packages/components/src/VirtualizedList/CellBoolean/__snapshots__/CellBoolean.test.js.snap
  packages/components/src/VirtualizedList/CellLabel/__snapshots__/CellLabel.test.js.snap
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopver.component.test.js
  packages/faceted-search/src/components/AddFacetPopover/__snapshots__/AddFacetPopver.component.test.js.snap
  packages/faceted-search/src/components/AdvancedSearch/__snapshots__/AdvancedSearch.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeCheckboxes/BadgeCheckboxesForm.component.test.js
  packages/faceted-search/src/components/Badges/BadgeFaceted/__snapshots__/BadgeFaceted.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeOperator/__snapshots__/BadgeOperatorPopover.component.test.js.snap
  packages/faceted-search/src/components/Badges/BadgeText/__snapshots__/BadgeText.component.test.js.snap
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
  packages/faceted-search/src/components/FacetedSearchIcon/__snapshots__/FacetedSearchIcon.component.test.js.snap
  packages/forms/src/UIForm/Widget/__snapshots__/Widget.component.test.js.snap
  packages/forms/src/deprecated/fields/__snapshots__/CollapsibleFieldset.test.js.snap
  packages/forms/src/widgets/templates/FieldTemplate/FieldTemplate.test.js
  packages/forms/src/widgets/templates/FieldTemplate/__snapshots__/FieldTemplate.test.js.snap
  tools/scripts-config-jest/test-setup.js
  yarn.lock
Labels: need review

#3912 fix(Fieldset): nested conditional fieldset are broken
  .changeset/twenty-bottles-kick.md
  packages/forms/src/UIForm/fieldsets/Fieldset/Fieldset.component.js
  packages/forms/src/UIForm/fieldsets/Fieldset/Fieldset.component.test.js
Labels: bug, need review

#3915 doc(design-system): Updating Copy story with static default value
  packages/design-system/src/components/Form/docs/Input.copy.stories.mdx
Labels: need review

#3909 chore(ARCH-482/MultiSelectTag): remove deprecated lifecycle and use RTL for test
  .changeset/sixty-deers-joke.md
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.js
  packages/forms/src/UIForm/fields/MultiSelectTag/MultiSelectTag.component.test.js
  packages/forms/src/UIForm/fields/MultiSelectTag/__snapshots__/MultiSelectTag.component.test.js.snap
Labels: need review

#3928 chore(Datalist): Allow reset to empty in restricted mode
  .changeset/cool-months-help.md
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
Labels: need review
