Repository Talend/ui, pull requests merged in 2022-11, with the labels that each got.

#4412 fix: missing fonts in exposed bundle
  .changeset/modern-rocks-arrive.md
  .changeset/purple-pugs-share.md
  packages/design-system/.storybook/preview-head.html
  packages/design-system/src/components/ThemeProvider/ThemeProvider.tsx
  tools/scripts-config-storybook-lib/.storybook-templates/preview-head.html
Labels: need visual approval

#4384 feat(dataviz): highlight line legend on hover
  .changeset/little-tips-draw.md
  .changeset/silver-waves-burn.md
  packages/dataviz/src/components/LineChart/LineChart.component.tsx
  packages/dataviz/src/components/LineChart/LineChart.module.scss
  packages/dataviz/src/components/LineChart/LineChart.stories.tsx
  packages/dataviz/src/components/LineChart/LineChartLegend.component.tsx
Labels: need review

#4419 fix(dataviz): render dot in LineChart when there is only one value
  .changeset/beige-kings-deliver.md
  packages/dataviz/src/components/LineChart/LineChart.component.tsx
  packages/dataviz/src/components/LineChart/LineChart.stories.tsx
Labels: need review

#4427 fix(SubHeaderBar): replace EditableText to InlineEditing
  .changeset/large-radios-pretend.md
  .changeset/large-radios-pretend2.md
  packages/components/src/SubHeaderBar/SubHeader.stories.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.component.js
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.module.scss
  packages/components/src/SubHeaderBar/TitleSubHeader/TitleSubHeader.test.js
  packages/design-system/src/components/InlineEditing/InlineEditing.stories.tsx
  packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx
Labels: need review

#4380 fix(List): separator alignment for persistent actions
  .changeset/big-papayas-wave.md
  packages/components/src/VirtualizedList/CellTitle/CellTitleActions.module.scss
Labels: bug, need review, easy review

#4430 fix(datagrid/TDC-6571): Use back DateCellRenderer
  .changeset/light-meals-hammer.md
  packages/datagrid/mocks/sample.json
  packages/datagrid/src/components/DataGrid/Datagrid.stories.tsx
  packages/datagrid/src/components/DefaultCellRenderer/AvroRenderer.component.tsx
  packages/datagrid/src/components/DefaultDateCellRenderer/date.js
  packages/datagrid/src/components/DefaultDateCellRenderer/date.test.js
  packages/datagrid/src/serializers/__snapshots__/datasetSerializer.test.ts.snap
Labels: need review

#4436 fix(ARCH-658): add missing dep
  .changeset/slimy-moles-move.md
  tools/scripts-config-storybook-lib/package.json
Labels: need review

#4437 chore(ARCH-658): simplify webpack from sb
  .changeset/loud-dolphins-drum.md
  tools/scripts-config-storybook-lib/.storybook-templates/main.js
Labels: need review

#4438 fix(ARCH-658): make the types optional
  .changeset/mighty-moose-float.md
  packages/components/.gitignore
  packages/components/package.json
  packages/datagrid/src/types/types.d.ts
Labels: need review

#4441 fix(ARCH-658): add postcss 8 dependency
  .changeset/breezy-bees-act.md
  .changeset/twenty-tomatoes-ring.md
  packages/theme/package.json
  tools/scripts-config-react-webpack/package.json
  yarn.lock
Labels: need review

#4451 chore(ARCH-658): remove uuid dependency on components
  .changeset/tender-cows-deliver.md
  .changeset/witty-apes-brake.md
  packages/components/__mocks__/uuid.js
  packages/components/package.json
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.component.js
  packages/components/src/Breadcrumbs/Breadcrumbs.component.js
  packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.js
  packages/components/src/List/ListComposition/SortBy/SortBy.component.js
  packages/components/src/List/Toolbar/Pagination/Pagination.component.js
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js
  packages/components/src/Toggle/LabelToggle/LabelToggle.component.js
  packages/components/src/TooltipTrigger/TooltipTrigger.component.js
  packages/components/src/Typeahead/Typeahead.component.js
  tools/scripts-config-jest/test-setup.js
Labels: need review, easy review

#4447 chore(theme): clean old theme files
  .changeset/blue-oranges-fry.md
  packages/components/src/Layout/AppLayout.stories.js
  packages/components/src/SidePanel/SidePanel.module.scss
  packages/components/src/SidePanel/SidePanel.stories.js
  packages/components/stories/config/themes.module.scss
  packages/containers/src/HomeListView/HomeListView.stories.js
  packages/containers/stories/config/themes.scss
  packages/theme/src/theme/_visual-helpers.scss
  packages/theme/src/theme/variations/_mdm.scss
  packages/theme/src/theme/variations/_portal.scss
  packages/theme/src/theme/variations/_tdc.scss
  packages/theme/src/theme/variations/_tdp.scss
  packages/theme/src/theme/variations/_tds.scss
  packages/theme/src/theme/variations/_tfd.scss
  packages/theme/src/theme/variations/_tic.scss
  packages/theme/src/theme/variations/_tmc.scss
Labels: need review, breaking change

#4457 chore(ARCH-658/security/xmldom): update
  .changeset/calm-otters-drum.md
  .changeset/new-turtles-raise.md
  packages/icons/package.json
  packages/icons/stories/IconsFont.stories.tsx
  tools/scripts-config-storybook-lib/.storybook-templates/msw/mockServiceWorker.js
  tools/scripts-config-storybook-lib/package.json
  yarn.lock
Labels: need review

#4460 chore(ARCH-658): remove uuid
  .changeset/famous-toys-look.md
  .changeset/giant-geckos-draw.md
  .changeset/sixty-fishes-smile.md
  packages/cmf/__tests__/cmfConnect.test.js
  packages/cmf/package.json
  packages/cmf/src/cmfConnect.js
  packages/cmf/src/components/Saga/CmfRegisteredSaga.component.js
  packages/cmf/src/components/Saga/CmfRegisteredSaga.component.test.js
  packages/cmf/src/components/Saga/Saga.component.js
  packages/cmf/src/components/Saga/Saga.component.test.js
  packages/components/src/Actions/ActionFile/ActionFile.component.js
  packages/components/src/Actions/ActionSplitDropdown/ActionSplitDropdown.component.js
  packages/components/src/Breadcrumbs/Breadcrumbs.component.js
  packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.component.js
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/InputDateTimePicker/InputDateTimePicker.component.js
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/TimePicker/TimePicker.component.js
  packages/components/src/List/ListComposition/DisplayMode/ListDisplayMode.component.js
  packages/components/src/List/ListComposition/SortBy/SortBy.component.js
  packages/components/src/List/Toolbar/Pagination/Pagination.component.js
  packages/components/src/List/Toolbar/SelectSortBy/SelectSortBy.component.js
  packages/components/src/List/__snapshots__/List.test.js.snap
  packages/components/src/Toggle/LabelToggle/LabelToggle.component.js
  packages/components/src/TooltipTrigger/TooltipTrigger.component.js
  packages/components/src/Typeahead/Typeahead.component.js
  packages/containers/__mocks__/uuid.js
  packages/containers/package.json
  packages/containers/src/Notification/Notification.sagas.js
  packages/containers/src/Notification/pushNotification.js
  packages/datagrid/__mocks__/uuid.js
  packages/faceted-search/__mocks__/uuid.js
  packages/faceted-search/package.json
  packages/faceted-search/src/components/types/badgeDefinition.type.js
  packages/forms/__mocks__/uuid.js
  packages/forms/package.json
  packages/forms/src/UIForm/Message/generateId.js
  packages/forms/src/widgets/templates/utils.js
  packages/forms/stories/json/FormStoryWithDisplayMode.js
  packages/utils/src/index.ts
  packages/utils/src/uuid.ts
  yarn.lock
Labels: need review

#4466 fix(datagrid): header cell width
  .changeset/ten-feet-tell.md
  packages/datagrid/src/components/HeaderCellRenderer/HeaderCellRenderer.module.scss
Labels: need review

#4467 fix(TFD-14833) InlineEditing : fix enter key always handled
  .changeset/long-days-vanish.md
  packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx
Labels: need review

#4471 fix(ARCH-658/InlineEditing): remove usekey
  .changeset/long-days-vanish.md
  package.json
  packages/design-system/package.json
  packages/design-system/src/components/InlineEditing/InlineEditing.spec.tsx
  packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx
  packages/storybook/src/design-system/InlineEditing/InlineEditing.stories.tsx
Labels: need review
