Repository Talend/ui, pull requests merged in 2022-09, with the labels that each got.

#4303 fix(ci): build storybook docs for visual testing github action
  .github/workflows/visual-testing.yml
Labels: bug, need review, need visual approval, github_actions

#4313 feat(design-system/NO-TICKET): Fixing Popover stories and styles
  .changeset/strong-teachers-drive.md
  packages/design-system/src/components/WIP/Popover/Popover.module.scss
  packages/design-system/src/components/WIP/Popover/Popover.stories.mdx
  packages/design-system/src/components/WIP/Popover/Popover.stories.tsx
  packages/design-system/src/components/WIP/Popover/Popover.tsx
  packages/faceted-search/src/components/BasicSearch/__snapshots__/BasicSearch.component.test.js.snap
Labels: easy review

#4268 fix(talend-scripts): webpack config for ng config compatibility
  .changeset/large-days-listen.md
  .changeset/old-starfishes-listen.md
  .changeset/silver-teachers-report.md
  packages/playground/src/app/index.js
  tools/scripts-config-react-webpack/config/webpack.config.js
  tools/scripts-config-react-webpack/package.json
  tools/scripts-config-storybook-lib/package.json
  tools/scripts-config-stylelint/package.json
  yarn.lock
Labels: dependencies

#4316 chore(presets): add breaking change for talend scripts presets
  .changeset/large-days-breaking.md
Labels: need review

#4317 fix(faceted-search): infinite loop with initialBadges
  .changeset/seven-chefs-design.md
  packages/faceted-search/src/components/BasicSearch/BasicSearch.component.js
Labels: need review

#4319 fix(talend-scripts-eslint): force trim bump for better security
  .changeset/ninety-clocks-drum.md
  package.json
  yarn.lock
Labels: need review, dependencies

#4325 feat(TDC-6381): QualityBar design rework
  .changeset/flat-masks-grow.md
  packages/components/src/QualityBar/QualityBar.component.js
  packages/components/src/QualityBar/QualityBar.component.test.js
  packages/components/src/QualityBar/QualityBar.stories.js
  packages/components/src/QualityBar/QualityRatioBar.component.js
  packages/components/src/QualityBar/QualityRatioBar.scss
  packages/components/src/VirtualizedList/CellQualityBar/__snapshots__/CellQualityBar.test.js.snap
Labels: need review

#4331 fix(playground): display playground icons
  .changeset/olive-taxis-joke.md
  packages/playground/package.json
Labels: bug, need review

#4332 fix(TDC-6514): Faceted Search - locators
  .changeset/new-mirrors-leave.md
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopover.component.js
  packages/faceted-search/src/components/AddFacetPopover/AddFacetPopoverRow/AddFacetPopoverRowItem/AddFacetPopoverRowItem.component.js
Labels: need review

#4333 chore(design-system): fix translations extraction
  packages/design-system/i18next-scanner.config.js
  packages/design-system/package.json
  packages/design-system/src/components/Form/Field/Input/Input.File.tsx
Labels: need review

#4321 chore(talend-scripts): disable storybook telemetry
  .changeset/wild-garlics-marry.md
  tools/scripts-config-storybook-lib/.storybook-templates/main.js
Labels: need review, easy review

#4344 fix(storybook config): msw setup update
  .changeset/afraid-ads-vanish.md
  tools/scripts-config-storybook-lib/.storybook-templates/msw/mockServiceWorker.js
  tools/scripts-config-storybook-lib/package.json
Labels: need review

#4348 fix(faceted-search): handle DS breaking changes (Switch to ToggleSwitch)
  .changeset/breezy-jars-argue.md
  packages/faceted-search/package.json
  packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
Labels: need review

#4347 fix(TFD-14580): Fix DataViewer click on icons
  .changeset/brown-mayflies-swim.md
  packages/components/src/DataViewer/Core/Tree/Tree.scss
  packages/components/src/DataViewer/Icons/TreeBranchIcon/TreeBranchIcon.component.js
  packages/components/src/DataViewer/Icons/TreeBranchIcon/TreeBranchIcon.scss
  packages/components/src/DataViewer/Icons/TreeBranchIcon/TreeBranchIcon.test.js
  packages/components/src/DataViewer/Icons/TreeBranchIcon/__snapshots__/TreeBranchIcon.test.js.snap
  packages/components/src/DataViewer/RecordsViewer/Branch/RecordsViewerBranch.component.js
  packages/components/src/DataViewer/RecordsViewer/RecordsViewer.scss
Labels: need review

#4357 fix: use flex-start
  .changeset/slow-swans-approve.md
  packages/components/src/SidePanel/SidePanel.scss
  packages/design-system/.storybook/docs/tokensDocHelpers/components/CompositionList/CompositionListItem.module.scss
  packages/design-system/.storybook/docs/tokensDocHelpers/components/DefinitionList/ColorScale/ColorScale.module.scss
  packages/design-system/.storybook/docs/tokensDocHelpers/components/DefinitionList/SizingScale/SizingScale.module.scss
  packages/design-system/src/components/Form/Primitives/Checkbox/Checkbox.module.scss
  packages/design-system/src/components/Form/Primitives/Radio/Radio.module.scss
  packages/design-system/src/components/InlineMessage/Primitive/InlineMessagePrimitive.module.scss
  packages/design-system/src/components/WIP/Tabs/Primitive/TabStyles.module.scss
Labels: need review

#4256 fix(security): glob-parent
  package.json
  yarn.lock
Labels: need review

#4362 feat(no ticket): Action in EmptyState size M
  .changeset/twelve-apricots-end.md
  packages/design-system/src/components/EmptyState/EmptyState.stories.mdx
  packages/design-system/src/components/EmptyState/EmptyState.stories.tsx
  packages/design-system/src/components/EmptyState/variants/EmptyStateMedium.tsx
Labels: need review, easy review, need visual approval

#4366 fix(ARCH-631/tools): remove sass data
  .changeset/cuddly-pants-suffer.md
  .changeset/dull-squids-press.md
  packages/theme/src/theme/variations/_mdm.scss
  packages/theme/src/theme/variations/_portal.scss
  packages/theme/src/theme/variations/_tdc.scss
  packages/theme/src/theme/variations/_tdp.scss
  packages/theme/src/theme/variations/_tds.scss
  packages/theme/src/theme/variations/_tfd.scss
  packages/theme/src/theme/variations/_tic.scss
  packages/theme/src/theme/variations/_tmc.scss
  tools/scripts-config-react-webpack/config/webpack.config.common.js
Labels: need review, breaking change
