Repository Talend/ui, pull requests merged in 2022-05, with the labels that each got.

#3943 chore(ci): Setup chromatic on datagrid & dataviz
  .github/workflows/visual-testing.yml
  packages/datagrid/.storybook/preview.js
  packages/datagrid/package.json
  packages/datagrid/src/components/datagrid.component.stories.js
  packages/dataviz/.storybook/preview.js
  packages/dataviz/package.json
  packages/dataviz/src/components/BoxPlot/BoxPlot.stories.tsx
  packages/dataviz/src/components/RangeFilter/RangeFilter.component.stories.tsx
Labels: need visual approval

#3692 feat(ARCH-349): add assets api
  .changeset/early-files-float.md
  .changeset/fifty-camels-call.md
  .changeset/rich-swans-lie.md
  .changeset/thirty-terms-return.md
  .changeset/tiny-carrots-clean.md
  .github/workflows/design-system-component-testing.yml
  .github/workflows/design-system-deploy.yml
  .github/workflows/visual-testing.yml
  .prettierignore
  packages/assets-api/README.md
  packages/assets-api/package.json
  packages/assets-api/src/index.test.ts
  packages/assets-api/src/index.ts
  packages/assets-api/talend-scripts.json
  packages/assets-api/tsconfig.json
  packages/components/src/FilterBar/FilterBar.test.js
  packages/datagrid/.babelrc.json
  packages/datagrid/package.json
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.test.js
  packages/datagrid/src/components/DataGrid/__snapshots__/DataGrid.test.js.snap
  packages/dataviz/assets/maps/CA.topo.json
  packages/dataviz/assets/maps/FR.topo.json
  packages/dataviz/assets/maps/MX.topo.json
  packages/dataviz/assets/maps/US.topo.json
  packages/dataviz/assets/maps/US_CA.topo.json
  packages/dataviz/assets/maps/continents.topo.json
  packages/dataviz/assets/maps/world.topo.json
  packages/dataviz/package.json
  packages/dataviz/src/components/GeoChart/GeoChart.test.js
  packages/dataviz/src/components/GeoChart/GeoChart.utils.ts
  packages/dataviz/talend-scripts.json
  packages/design-system/README.md
  packages/design-system/package.json
  packages/design-system/src/components/IconsProvider/IconsProvider.tsx
  packages/design-system/src/components/Stepper/docs/Stepper.stories.mdx
  packages/design-system/tsconfig.build.json
  packages/faceted-search/package.json
  packages/forms/package.json
  packages/forms/src/UIForm/fields/Code/Code.component.js
  packages/forms/src/UIForm/fields/Code/Code.component.test.js
  packages/forms/src/UIForm/fields/Code/__snapshots__/Code.component.test.js.snap
  packages/forms/src/deprecated/widgets/CodeWidget/CodeWidget.component.js
  packages/forms/src/deprecated/widgets/CodeWidget/CodeWidget.test.js
  packages/forms/src/deprecated/widgets/CodeWidget/__snapshots__/CodeWidget.test.js.snap
  packages/playground/src/app/components/DataGrid.js
  packages/playground/src/app/components/Dataviz.js
  packages/playground/src/app/i18n.js
  packages/playground/src/assets/inject.js
  packages/playground/webpack.config.dev.js
  packages/stepper/package.json
  packages/utils/package.json
  tools/scripts-config-react-webpack/src/inject.js
Labels: need review

#3897 feat(components/QualityBar): rework quality bar with design tokens
  .changeset/wise-chicken-divide.md
  .changeset/wise-chicken-plop.md
  packages/components/src/QualityBar/QualityBar.stories.js
  packages/components/src/QualityBar/QualityRatioBar.scss
  packages/components/src/RatioBar/RatioBar.scss
  packages/components/src/RatioBar/RatioBar.stories.js
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DefaultCellRenderer/QualityIndicator.scss
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.scss
  packages/datagrid/src/components/DefaultHeaderRenderer/DefaultHeaderRenderer.test.js
  packages/datagrid/src/components/DefaultHeaderRenderer/QualityBar.component.js
  packages/datagrid/src/components/DefaultHeaderRenderer/QualityBar.scss
  packages/datagrid/src/components/DefaultHeaderRenderer/QualityBar.test.js
  packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/DefaultHeaderRenderer.test.js.snap
  packages/datagrid/src/components/DefaultHeaderRenderer/__snapshots__/QualityBar.test.js.snap
  packages/datagrid/src/components/datagrid.component.stories.js
  packages/datagrid/src/containers/DataGrid/__snapshots__/DataGrid.container.test.js.snap
  packages/datagrid/src/index.js
Labels: enhancement, need review

#3956 chore(datagrid): Drop cmfModule
  .changeset/hip-crabs-eat.md
  packages/datagrid/.storybook/cmfModule/actionCreators.js
  packages/datagrid/.storybook/cmfModule/components.js
  packages/datagrid/.storybook/cmfModule/index.js
  packages/datagrid/.storybook/cmfModule/middlewares.js
  packages/datagrid/.storybook/cmfModule/preloadedState.js
  packages/datagrid/.storybook/cmfModule/settings.js
  packages/datagrid/.storybook/preview.js
  packages/datagrid/package.json
  packages/datagrid/src/cmfModule.js
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DataGrid/DataGrid.proptypes.js
  packages/datagrid/src/components/DatasetSerializer/__snapshots__/datasetSerializer.test.js.snap
  packages/datagrid/src/components/DatasetSerializer/datasetSerializer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/AvroRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/AvroRenderer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.test.js
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/AvroRenderer.test.js.snap
  packages/datagrid/src/components/DefaultCellRenderer/__snapshots__/DefaultCellRenderer.test.js.snap
  packages/datagrid/src/components/datagrid.component.stories.js
  packages/datagrid/src/containers/DataGrid/DataGrid.connect.js
  packages/datagrid/src/containers/DataGrid/DataGrid.connect.test.js
  packages/datagrid/src/containers/DataGrid/DataGrid.container.js
  packages/datagrid/src/containers/DataGrid/DataGrid.container.test.js
  packages/datagrid/src/containers/DataGrid/__snapshots__/DataGrid.container.test.js.snap
  packages/datagrid/src/containers/datagrid.container.stories.js
  packages/datagrid/src/containers/index.js
  packages/datagrid/src/index.js
  packages/datagrid/src/register.js
  packages/datagrid/src/register.test.js
  packages/datagrid/stories/DynamicDataGrid.component.js
  packages/datagrid/stories/FasterDatagrid.component.js
  packages/datagrid/stories/ImmutableDatagrid.component.js
  packages/datagrid/stories/getComponent.js
Labels: need review

#3969 fix(assetApi): prevent getCdnUrl to start with double slash
  .changeset/curvy-balloons-jog.md
  packages/assets-api/src/index.test.ts
  packages/assets-api/src/index.ts
Labels: bug, need review

#3974 chore: add missing changeset
  .changeset/fluffy-cups-push.md
Labels: need review

#3978 feat: distribute assets-api in UMD
  .changeset/healthy-maps-report.md
  .changeset/wicked-badgers-rest.md
  packages/assets-api/package.json
  packages/playground/webpack.config.dev.js
  tools/scripts-config-cdn/modules.json
Labels: need review

#3984 fix(Dropdown): Close on button or link click
  .changeset/gentle-beds-yawn.md
  packages/design-system/src/components/Dropdown/Dropdown.spec.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
Labels: need review, easy review

#3985 chore(ARCH-515/security): make scan always up to date
  .github/actions/sourceclear/Dockerfile
  .github/actions/sourceclear/entrypoint.sh
  packages/components/yarn.lock
  packages/containers/yarn.lock
  packages/design-system/yarn.lock
  packages/design-tokens/yarn.lock
  packages/faceted-search/yarn.lock
  packages/theme/yarn.lock
  tools/babel-plugin-import-d3/yarn.lock
  tools/babel-plugin-import-from-index/yarn.lock
  tools/babel-plugin-import-from-lib/yarn.lock
  tools/cypress-api-mock-plugin/yarn.lock
  tools/eslint-plugin/yarn.lock
  tools/scripts-build-cdn/yarn.lock
  tools/scripts-config-babel/yarn.lock
  tools/scripts-config-cdn/yarn.lock
  tools/scripts-config-eslint/yarn.lock
  tools/scripts-config-jest/yarn.lock
  tools/scripts-config-ng-webpack/yarn.lock
  tools/scripts-config-prettier/yarn.lock
  tools/scripts-config-react-webpack/yarn.lock
  tools/scripts-config-storybook-lib/yarn.lock
  tools/scripts-config-stylelint/yarn.lock
  tools/scripts-config-typescript/yarn.lock
  tools/scripts-core/yarn.lock
  tools/scripts-preset-react-lib/yarn.lock
  tools/scripts-preset-react/yarn.lock
  tools/scripts-teorem/yarn.lock
Labels: need review

#3988 chore(ci): use alpine node to have apk
  .github/actions/sourceclear/Dockerfile
Labels: need review

#3989 chore(ci): install curl for security scan action
  .github/actions/sourceclear/Dockerfile
Labels: need review

#3990 chore(ci): update apt-get to install jq in security scan action
  .github/actions/sourceclear/Dockerfile
Labels: need review

#3992 chore(ci): security scan fix
  .github/actions/sourceclear/entrypoint.sh
Labels: need review

#3996 chore(ci): secu scan cp yarn.lock instead of symlink
  .github/actions/sourceclear/entrypoint.sh
Labels: need review

#3991 fix(Components/Vlist): proptypes
  .changeset/fluffy-games-press.md
  packages/components/src/List/ListComposition/VList/VList.component.js
Labels: need review

#4010 chore(design-system): remark plugin into Storybook
  packages/design-system/.storybook/main.js
  packages/design-system/.storybook/mdx/groupBy.js
  packages/design-system/.storybook/mdx/groupByDetails.js
Labels: enhancement, easy review

#4012 chore(ARCH-515): fix order in workspace-run.js
  .changeset/five-kiwis-reply.md
  packages/cmf-webpack-plugin/package.json
  packages/cmf-webpack-plugin/talend-scripts.json
  workspace-run.js
Labels: need review

#4013 fix(Notification): remove this in functional component
  .changeset/eight-camels-notice.md
  packages/components/src/Notification/Notification.component.js
Labels: need review

#3924 feat(icons): map.svg
  .changeset/small-pans-pump.md
  packages/icons/src/svg/processors/map.svg
Labels: need review, easy review

#4014 feat(upgrade:deps): add --next support
  .changeset/gentle-spoons-build.md
  tools/upgrade-deps/README.md
  tools/upgrade-deps/src/index.js
  tools/upgrade-deps/src/npm.js
Labels: need review

#4028 fix(ARCH-515/cdn): use findPackage instead of require.resolve
  .changeset/short-chefs-drive.md
  fork/dynamic-cdn-webpack-plugin/src/find.js
  fork/dynamic-cdn-webpack-plugin/src/find.test.js
  fork/dynamic-cdn-webpack-plugin/src/index.js
  fork/dynamic-cdn-webpack-plugin/src/resolve-pkg.js
Labels: need review

#4038 fix(datagrid) int cell doesn't display text align right
  .changeset/small-tables-roll.md
  packages/datagrid/src/components/DefaultIntCellRenderer/DefaultIntCell.scss
Labels: need review, need visual approval

#4043 chore(datagrid): Cleanup internal renderer API
  .changeset/plenty-cobras-fix.md
  packages/datagrid/src/components/DataGrid/DataGrid.component.js
  packages/datagrid/src/components/DefaultCellRenderer/DefaultCellRenderer.component.js
  packages/datagrid/src/components/DefaultCellRenderer/index.js
  packages/datagrid/src/components/DefaultHeaderRenderer/index.ts
  packages/datagrid/src/components/PinHeaderRenderer/PinHeaderRenderer.component.tsx
  packages/datagrid/src/components/PinHeaderRenderer/index.ts
Labels: need visual approval

#4011 feat(design-system): Checkbox and Radio primitives
  packages/design-system/src/components/Form/Field/Input/hooks/useCheckboxState.tsx
  packages/design-system/src/components/Form/Field/Input/hooks/useReadOnly.tsx
  packages/design-system/src/components/Form/Primitives/Checkbox/Checkbox.module.scss
  packages/design-system/src/components/Form/Primitives/Checkbox/Checkbox.tsx
  packages/design-system/src/components/Form/Primitives/Label/Label.tsx
  packages/design-system/src/components/Form/Primitives/Primitives.stories.mdx
  packages/design-system/src/components/Form/Primitives/Primitives.stories.tsx
  packages/design-system/src/components/Form/Primitives/Radio/Radio.module.scss
  packages/design-system/src/components/Form/Primitives/Radio/Radio.tsx
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.module.scss
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.tsx
  packages/design-system/src/components/Stack/StackHorizontal.tsx
  packages/design-system/src/components/Stack/StackVertical.tsx
Labels: need visual approval

#4040 feat(codemod): react-boostrap to @talend/react-bootstrap
  tools/codemods/rb-to-talend-rb/README.md
  tools/codemods/rb-to-talend-rb/index.js
Labels: need review

#4049 fix(dynamic-cdn-webpack-plugin): findPackage follow symlink
  .changeset/twelve-masks-heal.md
  fork/dynamic-cdn-webpack-plugin/src/find.js
Labels: need review

#3524 feat(ARCH-395): upgrade react router v6
  .changeset/serious-starfishes-listen.md
  packages/cmf-router/package.json
  packages/cmf-router/src/UIRouter.js
  packages/cmf-router/src/history.js
  packages/cmf-router/src/index.js
  packages/cmf-router/src/index.test.js
  packages/cmf-router/src/middleware.js
  packages/cmf-router/src/route.js
  packages/cmf-router/src/route.md
  packages/cmf-router/src/route.test.js
  packages/cmf-router/src/sagaRouter.js
  packages/cmf-router/src/sagaRouter.test.js
  packages/cmf-router/talend-scripts.json
  packages/containers/src/Redirect/Redirect.test.js
  packages/playground/package.json
  packages/playground/src/app/actions/redirect.js
  packages/playground/src/app/components/FacetedSearch.js
  packages/playground/src/app/index.js
  packages/playground/talend-scripts.json
  packages/playground/webpack.config.dev.js
  packages/router-bridge/package.json
  packages/router-bridge/src/router/index.js
  yarn.lock
Labels: need review, breaking change

#4041 feat(icons): SVG sprites from figma
  .changeset/mean-parrots-pretend.md
  .github/workflows/before-surge.sh
  packages/icons/.babelrc.json
  packages/icons/.storybook/main.js
  packages/icons/.storybook/preview-head.html
  packages/icons/.storybook/preview.js
  packages/icons/package.json
  packages/icons/scripts/docs.js
  packages/icons/scripts/react.js
  packages/icons/scripts/typescript.js
  packages/icons/src/extract.js
  packages/icons/src/index.js
  packages/icons/src/info.js
  packages/icons/stories/DeprecatedIcon.stories.tsx
  packages/icons/stories/DeprecatedIcons.stories.mdx
  packages/icons/stories/Icon.stories.tsx
  packages/icons/stories/Icon.tsx
  packages/icons/stories/IconsByName.stories.mdx
  packages/icons/stories/IconsBySize.stories.mdx
  packages/icons/talend-scripts.json
  yarn.lock
Labels: enhancement, need review

#4054 chore(icons): Github Action to download icons from Figma
  .github/workflows/icons.yml
Labels: enhancement, need review, easy review
