Repository Talend/ui, pull requests merged in 2022-02, with the labels that each got.

#3666 fix(design-system): Divider uses CSS modules
  .changeset/dirty-pears-search.md
  packages/design-system/src/components/Divider/Divider.module.scss
  packages/design-system/src/components/Divider/Divider.stories.mdx
  packages/design-system/src/components/Divider/Divider.ts
  packages/design-system/src/components/Divider/Divider.tsx
  packages/design-system/src/components/Divider/docs/Divider.stories.mdx
Labels: enhancement, need review, easy review

#3673 chore(ARCH-432): apply updated upgrade:deps wf
  .changeset/ci-dependencies-0373c884.md
  .changeset/ci-dependencies-09d55ec1.md
  .changeset/ci-dependencies-827b1673.md
  .changeset/ci-dependencies-8633c3bc.md
  .changeset/ci-dependencies-87e05616.md
  .changeset/ci-dependencies-bd724c09.md
  .changeset/ci-dependencies-cd9168fd.md
  .changeset/ci-dependencies-d45aa0c5.md
  .changeset/ci-dependencies-f2777ef2.md
  .changeset/ci-dependencies-fb4f83b6.md
  .changeset/config.json
  .changeset/sharp-wombats-behave.md
  .changeset/sharp-wombats-gods.md
  .github/workflows/dependencies.yml
  packages/cmf-cqrs/package.json
  packages/cmf-router/package.json
  packages/cmf-webpack-plugin/package.json
  packages/cmf/package.json
  packages/components/package.json
  packages/containers/package.json
  packages/datagrid/package.json
  packages/dataviz/package.json
  packages/design-system/cypress/plugins/index.js
  packages/design-system/package.json
  packages/design-tokens/package.json
  packages/faceted-search/package.json
  packages/flow-designer/package.json
  packages/forms/package.json
  packages/http/package.json
  packages/jsfc/package.json
  packages/playground/package.json
  packages/router-bridge/package.json
  packages/sagas/package.json
  packages/stepper/package.json
  packages/storybook-cmf/package.json
  packages/theme/package.json
  packages/utils/package.json
  yarn.lock
Labels: need review

#3675 chore(design-system): browser matrix for Cypress
  .github/workflows/design-system-component-testing.yml
  packages/design-system/README.md
Labels: enhancement, need review, easy review

#3669 chore(design-system): Cypress instead of Jest
  packages/design-system/.eslintrc.js
  packages/design-system/.gitignore
  packages/design-system/cypress/plugins/index.js
  packages/design-system/cypress/support/index.d.ts
  packages/design-system/cypress/support/index.js
  packages/design-system/cypress/tsconfig.json
  packages/design-system/package.json
  packages/design-system/src/components/Button/Button.spec.tsx
  packages/design-system/src/components/Button/Button.stories.tsx
  packages/design-system/src/components/Button/Button.test.js
  packages/design-system/src/components/ButtonIcon/ButtonIcon.spec.tsx
  packages/design-system/src/components/Dropdown/Dropdown.spec.tsx
  packages/design-system/src/components/Form/Field/Input/Password/Password.spec.tsx
  packages/design-system/src/components/Form/Fieldset/Fieldset.spec.tsx
  packages/design-system/src/components/Icon/Icon.spec.tsx
  packages/design-system/src/components/Icon/Icon.stories.mdx
  packages/design-system/src/components/Icon/Icon.test.js
  packages/design-system/src/components/Icon/__snapshots__/Icon.test.js.snap
  packages/design-system/src/components/IconsProvider/IconsProvider.spec.tsx
  packages/design-system/src/components/IconsProvider/IconsProvider.test.tsx
  packages/design-system/src/components/IconsProvider/__snapshots__/IconsProvider.test.tsx.snap
  packages/design-system/src/components/InlineEditing/InlineEditing.spec.tsx
  packages/design-system/src/components/InlineMessage/variations/InlineMessage.information.tsx
  packages/design-system/src/components/InlineMessage/variations/InlineMessage.success.tsx
  packages/design-system/src/components/InlineMessage/variations/InlineMessage.warning.tsx
  packages/design-system/src/components/Link/Link.spec.tsx
  packages/design-system/src/components/Link/Link.stories.tsx
  packages/design-system/src/components/Link/Link.test.js
  packages/design-system/src/components/Link/Link.tsx
  packages/design-system/src/components/Tag/Tag.spec.tsx
  packages/design-system/src/components/Tag/Tag.stories.tsx
  packages/design-system/src/components/Toggle/Toggle.spec.tsx
  packages/design-system/src/components/Tooltip/Tooltip.stories.tsx
  packages/design-system/src/index.ts
  packages/design-system/test-utils.js
  packages/design-system/tsconfig.build.json
  packages/design-system/tsconfig.json
  yarn.lock
Labels: enhancement, need review

#3657 chore(design-system): deprecate Button.Icon and Toggle
  .changeset/poor-windows-fetch.md
  packages/design-system/.storybook/docs/Badge.tsx
  packages/design-system/.storybook/docs/BadgeStorybook.tsx
  packages/design-system/.storybook/docs/StatusTable.tsx
  packages/design-system/.storybook/main.js
  packages/design-system/src/components/Button/docs/Button.stories.mdx
  packages/design-system/src/components/Toggle/docs/Toggle.stories.mdx
Labels: enhancement, need review

#3679 chore(ARCH-432/CI): remove changeset from upgrade
  .github/workflows/dependencies.yml
Labels: need review

#3685 chore(design-system): visual testing on demand
  .github/workflows/design-system-visual-testing.yml
Labels: enhancement, need review, easy review

#3686 chore(design-system): migrate chromatic to talend account
  .github/workflows/design-system-visual-testing.yml
Labels: need review

#3687 chore(surge): teardown workflow without npm cache
  .github/workflows/surge-cleanup.yml
Labels: need review, easy review

#3684 chore(ARCH-392): move eslint config
  packages/eslint-config/.eslintrc.json
  packages/eslint-config/CHANGELOG.md
  packages/eslint-config/README.md
  packages/eslint-config/api-app-react.yaml
  packages/eslint-config/api-app.yaml
  packages/eslint-config/api-packaging.yaml
  packages/eslint-config/api-test-jasmine.yaml
  packages/eslint-config/api-test.yaml
  packages/eslint-config/api/eslintrc.base.yaml
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  yarn.lock
Labels: need review

#3697 test(ARCH-349): add datagrid playground
  packages/playground/package.json
  packages/playground/src/app/components/DataGrid.js
  packages/playground/src/app/index.js
  packages/playground/src/assets/settings.json
  packages/playground/webpack.config.dev.js
Labels: need review

#3698 test(ARCH-349): add faceted search playground
  packages/playground/package.json
  packages/playground/src/app/components/FacetedSearch.js
  packages/playground/src/app/index.js
  packages/playground/src/assets/settings.json
  packages/playground/webpack.config.dev.js
Labels: need review

#3699 chore(http): typings for error calls
  .changeset/chilled-goats-arrive.md
  packages/http/src/http.types.ts
Labels: need review

#3704 fix(utils/date): convertToTimeZone function with specific timezone and summer time
  .changeset/stale-hairs-give.md
  packages/utils/src/date/date.test.ts
  packages/utils/src/date/index.ts
Labels: enhancement, need review, easy review

#3715 chore(semgrep): remove sync with gh alert tab
  .github/workflows/semgrep.yml
Labels: need review, easy review

#3722 fix(ds): remove icons from config
  packages/design-system/talend-scripts.json
Labels: need review

#3729 fix(ARCH-432/router-bridge): set visibility to public
  .changeset/weak-mails-poke.md
  packages/router-bridge/package.json
Labels: need review
