Repository Talend/ui, pull requests merged in 2022-12, with the labels that each got.

#4481 fix(TDP-11600): allow to add new value in datalist
  .changeset/bright-apples-think.md
  packages/components/src/Datalist/Datalist.component.js
  packages/components/src/Datalist/Datalist.component.test.js
  packages/components/src/Datalist/Datalist.stories.js
Labels: need review, need visual approval

#4484 fix: playground
  packages/playground/src/settings/settings.json
Labels: need review

#4459 feat(ARCH-661/scripts): toggle dynamic-cdn-webpack-plugin
  .changeset/unlucky-spoons-obey.md
  packages/playground/talend-scripts.json
  tools/scripts-config-cdn/cdn.js
  tools/scripts-config-react-webpack/README.md
  tools/scripts-config-react-webpack/config/webpack.config.js
Labels: need review

#4490 fix(design-system): add data-testid to InlineEdit
  .changeset/light-numbers-tan.md
  packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.tsx
Labels: need review

#4238 chore(ARCH-658): remove static option from our devServer
  .changeset/curly-cars-crash.md
  tools/scripts-config-react-webpack/config/webpack.config.js
Labels: need review, easy review

#4503 fix(ARCH-669): storybook config without cmf
  .changeset/loud-suns-sip.md
  tools/scripts-config-storybook-lib/.storybook-templates/preview.js
  tools/scripts-config-storybook-lib/index.js
Labels: need review

#4248 feat(upgrade:deps): do not run scripts on install and updates
  .changeset/lazy-ties-attack.md
  .changeset/ninety-panthers-roll.md
  .github/workflows/dependencies.yml
  tools/upgrade-deps/README.md
  tools/upgrade-deps/bin/cli.js
  tools/upgrade-deps/src/index.js
  tools/upgrade-deps/src/npm.js
  tools/upgrade-deps/tests/cli.test.js
  tools/upgrade-deps/tests/fixture/basic/package-lock.json.tpl
  tools/upgrade-deps/tests/fixture/basic/package.json
  tools/upgrade-deps/tests/utils.js
Labels: need review

#4501 doc(components/AppLoader): simplify story using argTypes and remove all stories
  packages/components/src/AppLoader/AppLoader.stories.js
Labels: need review, easy review

#4493 feat(TFD-14774): Add Badge component
  .changeset/fast-boats-know.md
  package.json
  packages/design-system/package.json
  packages/design-system/src/components/Badge/Badge.spec.tsx
  packages/design-system/src/components/Badge/Badge.tsx
  packages/design-system/src/components/Badge/button/BadgeButton.module.scss
  packages/design-system/src/components/Badge/button/BadgeButton.tsx
  packages/design-system/src/components/Badge/index.ts
  packages/design-system/src/components/Badge/primitive/BadgePrimitive.module.scss
  packages/design-system/src/components/Badge/primitive/BadgePrimitive.tsx
  packages/design-system/src/components/Badge/variants/BadgeDropdown.module.scss
  packages/design-system/src/components/Badge/variants/BadgeDropdown.tsx
  packages/design-system/src/components/Badge/variants/BadgePopover.tsx
  packages/design-system/src/components/Badge/variants/BadgeTag.tsx
  packages/design-system/src/components/Badge/variants/BadgeValue.module.scss
  packages/design-system/src/components/Badge/variants/BadgeValue.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/index.ts
  packages/storybook/.storybook/preview.js
  packages/storybook/src/design-system/Badge/Badge.stories.mdx
  packages/storybook/src/design-system/Badge/Badge.stories.tsx
  yarn.lock
Labels: need review, need visual approval
