Repository Talend/ui, pull requests merged in 2023-01, with the labels that each got.

#4519 chore(ARCH-669): fix eslintrc config of the repository
  .eslintrc.js
  tools/scripts-config-eslint/package.json
  tsconfig.json
  yarn.lock
Labels: need review

#4514 fix(TDP-11750): WithDrawer content hidden on safari due to hidden overflow
  .changeset/khaki-worms-rest.md
  packages/components/src/WithDrawer/withDrawer.module.scss
Labels: need visual approval

#4524 chore: fix husky lint-staged config
  package.json
Labels: need review

#4556 fix(ARCH-662/scripts): win32 support
  .changeset/breezy-cats-dance.md
  package.json
  tools/scripts-core/src/config/webpack.config.js
  tools/scripts-utils/__tests__/path.test.js
  tools/scripts-utils/__tests__/pkg.test.js
  tools/scripts-utils/__tests__/utils.test.js
  tools/scripts-utils/src/path.js
Labels: need review

#4448 doc: update SECURITY.md
  SECURITY.md
Labels: need review, easy review

#4558 feat(ARCH-662/scripts): add talend-yarn-workspace
  package.json
  tools/scripts-yarn-workspace/.eslintrc.json
  tools/scripts-yarn-workspace/README.md
  tools/scripts-yarn-workspace/package.json
  tools/scripts-yarn-workspace/src/consume.js
  tools/scripts-yarn-workspace/src/index.js
  tools/scripts-yarn-workspace/src/run.js
  tools/scripts-yarn-workspace/src/workspace-run.js
  workspace-run.js
Labels: need review

#4560 feat(ARCH-662/cmf/settings): do not write settigns to disk
  .changeset/chilly-emus-sit.md
  tools/cmf-webpack-plugin/src/index.js
  tools/scripts-cmf/cmf-settings.i18n.js
  tools/scripts-cmf/cmf-settings.merge.js
Labels: need review

#4563 feat(Tabs&Dropdown): add new data-feature & data-testid capabilities
  .changeset/curly-squids-wave.md
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/WIP/Tabs/variants/Tabs.tsx
Labels: enhancement, need review, easy review

#4562 chore(ARCH-662): make storybook optional
  .changeset/great-oranges-jump.md
  tools/scripts-core/src/utils/storybook.js
Labels: need review

#4568 chore(CI): cancel previous GHA run if push again on the branch
  .github/workflows/changeset.yml
  .github/workflows/pr-demo.yml
  .github/workflows/pr-lint.yml
  .github/workflows/pr-playground.yml
  .github/workflows/pr-test.yml
  .github/workflows/visual-testing.yml
  .github/workflows/yarn-deduplicate.yml
Labels: need review

#4547 chore: apply code-style to components
  .changeset/fuzzy-pots-carry.md
  packages/components/src/ActionBar/ActionBar.module.scss
  packages/components/src/ActionIntercom/Intercom.module.scss
  packages/components/src/Actions/ActionDropdown/ActionDropdown.module.scss
  packages/components/src/CollapsiblePanel/CollapsiblePanel.module.scss
  packages/components/src/DataViewer/Core/Tree/Tree.module.scss
  packages/components/src/DataViewer/Headers/TreeHeader/TreeHeader.module.scss
  packages/components/src/DataViewer/Icons/TreeBranchIcon/TreeBranchIcon.module.scss
  packages/components/src/DataViewer/ModelViewer/ModelViewer.module.scss
  packages/components/src/Datalist/Datalist.module.scss
  packages/components/src/DateTimePickers/InputDatePicker/InputDatePicker.module.scss
  packages/components/src/DateTimePickers/InputDateRangePicker/InputDateRangePicker.module.scss
  packages/components/src/DateTimePickers/InputDateTimeRangePicker/InputDateTimeRangePicker.module.scss
  packages/components/src/DateTimePickers/InputTimePicker/InputTimePicker.module.scss
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/DatePicker/DatePicker.module.scss
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/DateTimePicker/DateTimePicker.module.scss
  packages/components/src/DateTimePickers/LegacyDateTimePickers/pickers/MonthPicker/MonthPicker.module.scss
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/HeaderTitle/HeaderTitle.module.scss
  packages/components/src/DateTimePickers/LegacyDateTimePickers/views/ViewLayout/ViewLayout.module.scss
  packages/components/src/DateTimePickers/pickers/CalendarPicker/CalendarPicker.module.scss
  packages/components/src/DateTimePickers/pickers/DatePicker/DatePicker.module.scss
  packages/components/src/DateTimePickers/pickers/MonthPicker/MonthPicker.module.scss
  packages/components/src/DateTimePickers/views/HeaderTitle/HeaderTitle.module.scss
  packages/components/src/DateTimePickers/views/ViewLayout/ViewLayout.module.scss
  packages/components/src/Dialog/Dialog.scss
  packages/components/src/Enumeration/Enumeration.module.scss
  packages/components/src/FormatValue/FormatValue.module.scss
  packages/components/src/GridLayout/Grid.module.scss
  packages/components/src/HttpError/HttpError.module.scss
  packages/components/src/Layout/TwoColumns/TwoColumns.module.scss
  packages/components/src/List/ListComposition/DisplayMode/DisplayModeToggle.scss
  packages/components/src/List/ListComposition/SortBy/SortBy.module.scss
  packages/components/src/List/ListComposition/Toolbar/ListToolbar.module.scss
  packages/components/src/List/Toolbar/SelectAll/SelectAll.module.scss
  packages/components/src/Notification/Notification.module.scss
  packages/components/src/PieChart/PieChart.module.scss
  packages/components/src/RadarChart/RadarChart.module.scss
  packages/components/src/ResourcePicker/ResourcePicker.module.scss
  packages/components/src/Rich/Layout/RichLayout.module.scss
  packages/components/src/Skeleton/Skeleton.module.scss
  packages/components/src/Slider/Slider.module.scss
  packages/components/src/Stepper/Stepper.component.module.scss
  packages/components/src/SubHeaderBar/SubHeaderBar.module.scss
  packages/components/src/TooltipTrigger/TooltipTrigger.module.scss
  packages/components/src/Typeahead/Typeahead.module.scss
  packages/components/src/VirtualizedList/ListTable/ListTable.module.scss
  packages/components/src/VirtualizedList/RowLarge/RowLarge.module.scss
  packages/components/src/VirtualizedList/RowSelection/RowSelection.module.scss
Labels: need review

#4548 chore: apply code style to bootstrap-theme
  .changeset/gold-cooks-drum.md
  .github/workflows/pr-lint.yml
  packages/theme/src/theme/_animation.scss
  packages/theme/src/theme/_breadcrumbs.scss
  packages/theme/src/theme/_labels.scss
  packages/theme/src/theme/_navbar.scss
  packages/theme/src/theme/_paddings.scss
  packages/theme/src/theme/_visual-helpers.scss
Labels: need review

#4549 chore: apply code style to design-system
  .changeset/metal-buttons-eat.md
  packages/design-system/src/components/ButtonIcon/Primitive/ButtonIcon.module.scss
  packages/design-system/src/components/Clickable/Clickable.module.scss
  packages/design-system/src/components/Dropdown/Primitive/DropdownEntry.module.scss
  packages/design-system/src/components/Dropdown/Primitive/DropdownShell.module.scss
  packages/design-system/src/components/Form/Affix/AffixStyles.module.scss
  packages/design-system/src/components/Form/Buttons/Buttons.module.scss
  packages/design-system/src/components/Form/Field/Input/Input.File.module.scss
  packages/design-system/src/components/Form/Field/Input/Input.ToggleSwitch.module.scss
  packages/design-system/src/components/Form/Field/Input/hooks/passwordButton.module.scss
  packages/design-system/src/components/Form/Fieldset/Fieldset.module.scss
  packages/design-system/src/components/Form/Form.module.scss
  packages/design-system/src/components/Form/Primitives/Checkbox/Checkbox.module.scss
  packages/design-system/src/components/Form/Primitives/Input/Input.module.scss
  packages/design-system/src/components/Form/Primitives/InputWrapper/InputWrapper.module.scss
  packages/design-system/src/components/Form/Primitives/Label/Label.module.scss
  packages/design-system/src/components/Form/Primitives/Radio/Radio.module.scss
  packages/design-system/src/components/Form/Primitives/Select/Select.module.scss
  packages/design-system/src/components/Form/Primitives/Textarea/Textarea.module.scss
  packages/design-system/src/components/Form/Primitives/_mixins.scss
  packages/design-system/src/components/Form/Row/Row.module.scss
  packages/design-system/src/components/Icon/Icon.module.scss
  packages/design-system/src/components/InlineEditing/Primitives/InlineEditingPrimitive.module.scss
  packages/design-system/src/components/InlineMessage/Primitive/InlineMessagePrimitive.module.scss
  packages/design-system/src/components/InlineMessage/variations/InlineMessageBeta.module.scss
  packages/design-system/src/components/InlineMessage/variations/InlineMessageDestructive.module.scss
  packages/design-system/src/components/InlineMessage/variations/InlineMessageInformation.module.scss
  packages/design-system/src/components/InlineMessage/variations/InlineMessageSuccess.module.scss
  packages/design-system/src/components/InlineMessage/variations/InlineMessageWarning.module.scss
  packages/design-system/src/components/Link/Link.module.scss
  packages/design-system/src/components/Linkable/LinkableStyles.module.scss
  packages/design-system/src/components/Modal/Modal.module.scss
  packages/design-system/src/components/Skeleton/variations/SkeletonInput.module.scss
  packages/design-system/src/components/Stack/Primitive/StackPrimitive.module.scss
  packages/design-system/src/components/Stack/StackItem.module.scss
  packages/design-system/src/components/Stepper/Step/Primitive/Step.module.scss
  packages/design-system/src/components/Switch/Switch.module.scss
  packages/design-system/src/components/ThemeProvider/ThemeProvider.module.scss
  packages/design-system/src/components/Tooltip/Tooltip.module.scss
  packages/design-system/src/components/WIP/Accordion/Primitive/CollapsiblePanel.module.scss
  packages/design-system/src/components/WIP/Combobox/Combobox.module.scss
  packages/design-system/src/components/WIP/Popover/Popover.module.scss
  packages/design-system/src/components/WIP/Tabs/Primitive/TabStyles.module.scss
  packages/design-system/src/components/WIP/Tabs/variants/TabsAsLinkList.module.scss
Labels: need review
